helics: helics::ValueFederate Class Reference
helics::ValueFederate Class Reference
#include <ValueFederate.hpp>
Public Member Functions
ValueFederate (const FederateInfo &fi)
ValueFederate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
ValueFederate (const std::string &jsonString)
ValueFederate (const std::string &name, const std::string &jsonString)
ValueFederate ()
ValueFederate (bool res)
ValueFederate (const ValueFederate &fed)=delete
ValueFederate (ValueFederate &&fed) noexcept
virtual ~ValueFederate ()
ValueFederate & operator= (ValueFederate &&fed) noexcept
publication_id_t registerPublication (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
publication_id_t registerPublication (const std::string &key, const std::string &units=std::string())
publication_id_t registerGlobalPublication (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
publication_id_t registerGlobalPublication (const std::string &key, const std::string &units=std::string())
template<typename X >
publication_id_t registerPublicationIndexed (const std::string &key, int index1, const std::string &units=std::string())
template<typename X >
publication_id_t registerPublicationIndexed (const std::string &key, int index1, int index2, const std::string &units=std::string())
subscription_id_t registerRequiredSubscription (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
subscription_id_t registerRequiredSubscription (const std::string &name, const std::string &units=std::string())
template<typename X >
subscription_id_t registerRequiredSubscriptionIndexed (const std::string &key, int index1, const std::string &units=std::string())
template<typename X >
subscription_id_t registerRequiredSubscriptionIndexed (const std::string &key, int index1, int index2, const std::string &units=std::string())
subscription_id_t registerOptionalSubscription (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
subscription_id_t registerOptionalSubscription (const std::string &key, const std::string &units=std::string())
template<typename X >
subscription_id_t registerOptionalSubscriptionIndexed (const std::string &key, int index1, const std::string &units=std::string())
template<typename X >
subscription_id_t registerOptionalSubscriptionIndexed (const std::string &key, int index1, int index2, const std::string &units=std::string())
void addSubscriptionShortcut (subscription_id_t subid, const std::string &shortcutName)
void setDefaultValue (subscription_id_t id, data_view block)
void setDefaultValue (subscription_id_t id, const data_block &block)
template<typename X >
void setDefaultValue (subscription_id_t id, const X &val)
virtual void registerInterfaces (const std::string &jsonString) override
void registerValueInterfaces (const std::string &jsonString)
data_view getValueRaw (subscription_id_t id)
template<typename X >
void getValue (subscription_id_t id, X &obj)
template<typename X >
X getValue (subscription_id_t id)
void publish (publication_id_t id, data_view block)
void publish (publication_id_t id, const data_block &block)
void publish (publication_id_t id, const char *data)
void publish (publication_id_t id, const char *data, size_t data_size)
template<typename X >
void publish (publication_id_t id, const X &value)
bool isUpdated (subscription_id_t sub_id) const
Time getLastUpdateTime (subscription_id_t sub_id) const
virtual void disconnect () override
std::vector< subscription_id_t > queryUpdates ()
std::string getSubscriptionKey (subscription_id_t) const
subscription_id_t getSubscriptionId (const std::string &key) const
subscription_id_t getSubscriptionId (const std::string &key, int index1) const
subscription_id_t getSubscriptionId (const std::string &key, int index1, int index2) const
std::string getPublicationKey (publication_id_t) const
publication_id_t getPublicationId (const std::string &key) const
publication_id_t getPublicationId (const std::string &key, int index1) const
publication_id_t getPublicationId (const std::string &key, int index1, int index2) const
std::string getSubscriptionUnits (subscription_id_t id) const
std::string getPublicationUnits (publication_id_t id) const
std::string getSubscriptionType (subscription_id_t id) const
std::string getPublicationType (publication_id_t id) const
std::string getPublicationType (subscription_id_t id) const
void registerSubscriptionNotificationCallback (std::function< void(subscription_id_t, Time)> callback)
void registerSubscriptionNotificationCallback (subscription_id_t id, std::function< void(subscription_id_t, Time)> callback)
void registerSubscriptionNotificationCallback (const std::vector< subscription_id_t > &ids, std::function< void(subscription_id_t, Time)> callback)
int getPublicationCount () const
int getSubscriptionCount () const
ValueFederate (FederateInfo &fi)
ValueFederate (const std::string &jsonString)
ValueFederate (const ValueFederate &vfed)
ValueFederate & operator= (const ValueFederate &fedObj)
Publication registerPublication (const std::string &name, const std::string &type, const std::string &units="")
Publication registerTypePublication (const std::string &name, int type, const std::string &units="")
Publication registerGlobalPublication (const std::string &name, const std::string &type, const std::string &units="")
Publication registerGlobalTypePublication (const std::string &name, int type, const std::string &units="")
Publication registerPublicationIndexed (const std::string &name, int index1, int type, const std::string &units="")
Publication registerPublicationIndexed (const std::string &name, int index1, int index2, int type, const std::string &units="")
Subscription registerSubscription (const std::string &name, const std::string &type, const std::string &units="")
Subscription registerOptionalSubscription (const std::string &name, const std::string &type, const std::string &units="")
Subscription registerTypeSubscription (const std::string &name, int type, const std::string &units="")
Subscription registerSubscriptionIndexed (const std::string &name, int index1, int type, const std::string &units="")
Subscription registerSubscriptionIndexed (const std::string &name, int index1, int index2, int type, const std::string &units="")
int getSubscriptionCount () const
int getPublicationCount () const
std::vector< helics_subscription > queryUpdates ()
Public Member Functions inherited from helics::Federate
Federate (const FederateInfo &fi)
Federate (const std::string &name, const FederateInfo &fi)
Federate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
Federate (const std::string &jsonString)
Federate (const std::string &name, const std::string &jsonString)
Federate () noexcept
Federate (Federate &&fed) noexcept
Federate (const Federate &fed)=delete
virtual ~Federate ()
Federate & operator= (Federate &&fed) noexcept
Federate & operator= (const Federate &fed)=delete
void enterInitializationState ()
void enterInitializationStateAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationStateComplete ()
iteration_result enterExecutionState (iteration_request iterate=iteration_request::no_iterations)
void enterExecutionStateAsync (iteration_request iterate=iteration_request::no_iterations)
iteration_result enterExecutionStateComplete ()
void finalize ()
void error (int errorcode)
void error (int errorcode, const std::string &message)
void setSeparator (char separator)
Time requestTime (Time nextInternalTimeStep)
iteration_time requestTimeIterative (Time nextInternalTimeStep, iteration_request iterate)
void requestTimeAsync (Time nextInternalTimeStep)
void requestTimeIterativeAsync (Time nextInternalTimeStep, iteration_request iterate)
Time requestTimeComplete ()
iteration_time requestTimeIterativeComplete ()
void setTimeDelta (Time tdelta)
void setOutputDelay (Time outputDelay)
void setInputDelay (Time inputDelay)
void setPeriod (Time period, Time offset=timeZero)
virtual void setFlag (int flag, bool flagValue=true)
void setLoggingLevel (int loggingLevel)
void setMaxIterations (int maxIterations)
void setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> &logFunction)
std::string query (const std::string &target, const std::string &queryStr)
std::string query (const std::string &queryStr)
query_id_t queryAsync (const std::string &target, const std::string &queryStr)
query_id_t queryAsync (const std::string &queryStr)
std::string queryComplete (query_id_t queryIndex)
bool isQueryCompleted (query_id_t queryIndex) const
filter_id_t registerSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerDestinationFilter (const std::string &destEndpoint)
filter_id_t registerCloningSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerCloningDestinationFilter (const std::string &destEndpoint)
std::string getFilterName (filter_id_t id) const
std::string getFilterEndpoint (filter_id_t id) const
std::string getFilterInputType (filter_id_t id) const
std::string getFilterOutputType (filter_id_t id) const
filter_id_t getFilterId (const std::string &filterName) const
filter_id_t getSourceFilterId (const std::string &filterName) const
filter_id_t getDestFilterId (const std::string &filterName) const
void setFilterOperator (filter_id_t filter, std::shared_ptr< FilterOperator > op)
register a operator for the specified filter
void setFilterOperator (const std::vector< filter_id_t > &filters, std::shared_ptr< FilterOperator > op)
register a operator for the specified filters
void registerFilterInterfaces (const std::string &jsonString)
auto getID () const noexcept
op_states getCurrentState () const
Time getCurrentTime () const
const std::string & getName () const
std::shared_ptr< Core > getCorePointer ()
std::shared_ptr< Filter > getFilterObject (int index)
void addFilterObject (std::shared_ptr< Filter > obj)
int filterObjectCount () const
Federate (const Federate &fedObj)
Federate & operator= (const Federate &fedObj)
operator helics_federate () const
helics_federate baseObject () const
void setFlag (int flag, int value)
void setOutputDelay (helics_time_t outputDelay)
void setTimeDelta (helics_time_t timeDelta)
void setInputDelay (helics_time_t inputDelay)
void setPeriod (helics_time_t period, helics_time_t offset)
void setMaxIterations (int max_iterations)
void setLoggingLevel (int logLevel)
federate_state getState () const
void enterInitializationMode ()
void enterInitializationModeAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationModeComplete ()
helics_iteration_status enterExecutionMode (helics_iteration_request iterate=no_iteration)
void enterExecutionModeAsync (helics_iteration_request iterate=no_iteration)
helics_iteration_status enterExecutionModeComplete ()
void finalize ()
helics_time_t requestTime (helics_time_t time)
helics_iteration_time requestTimeIterative (helics_time_t time, helics_iteration_request iterate)
void requestTimeAsync (helics_time_t time)
void requestTimeIterativeAsync (helics_time_t time, helics_iteration_request iterate)
helics_time_t requestTimeComplete ()
helics_iteration_time requestTimeIterativeComplete ()
std::string getName () const
std::string query (const std::string &target, const std::string &queryStr)
Filter registerSourceFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
Filter registerDestinationFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
CloningFilter registerCloningFilter (const std::string &deliveryEndpoint)
Protected Member Functions
virtual void updateTime (Time newTime, Time oldTime) override
virtual void startupToInitializeStateTransition () override
virtual void initializeToExecuteStateTransition () override
Friends
class helics::FederateInfo
Additional Inherited Members
Public Types inherited from helics::Federate
enum op_states : char {
op_states::startup = 0, op_states::initialization = 1, op_states::execution = 2, op_states::finalize = 3,
op_states::error = 4, op_states::pending_init = 5, op_states::pending_exec = 6, op_states::pending_time = 7,
op_states::pending_iterative_time = 8
}
Protected Attributes inherited from helics::Federate
std::atomic< op_states > state {op_states::startup}
the current state of the simulation
char separator_ = '/'
the separator between automatically prependend names
std::shared_ptr< Core > coreObject
reference to the core simulation API
Time currentTime
the current simulation time
FederateInfo FedInfo
the information structure that contains the data on the federate
helics_federate fed
bool exec_async_iterate
Detailed Description
class defining the value based interface
Constructor & Destructor Documentation
ValueFederate() [1/8]
helics::ValueFederate::ValueFederate (const FederateInfo & fi) explicit
constructor taking a federate information structure and using the default core
Parameters
[in] fi a federate information structure
constructor taking a core engine and federate info structure
References helics::Federate::coreObject, and helics::Federate::getID().
ValueFederate() [2/8]
helics::ValueFederate::ValueFederate (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a core and a federate information structure, sore information in fi is ignored
Parameters
[in] core a shared ptr to a core to join
[in] fi a federate information structure
References helics::Federate::coreObject, and helics::Federate::getID().
ValueFederate() [3/8]
helics::ValueFederate::ValueFederate (const std::string & jsonString) explicit
constructor taking a string with the required information
Parameters
[in] jsonString can be either a json file or a string containing json code
References helics::Federate::coreObject, helics::Federate::getID(), and registerInterfaces().
ValueFederate() [4/8]
helics::ValueFederate::ValueFederate (const std::string & name, const std::string & jsonString)
constructor taking a string with the required information
Parameters
[in] jsonString can be either a json file or a string containing json code
References helics::Federate::coreObject, helics::Federate::getID(), and registerInterfaces().
ValueFederate() [5/8]
helics::ValueFederate::ValueFederate () explicit default
default constructor
ValueFederate() [6/8]
helics::ValueFederate::ValueFederate (bool res) explicit
special constructor called by child class to initialize the class vs the default constructor
References helics::Federate::coreObject, and helics::Federate::getID().
ValueFederate() [7/8]
helics::ValueFederate::ValueFederate (const ValueFederate & fed) delete
federate is not copyable
ValueFederate() [8/8]
helics::ValueFederate::ValueFederate (ValueFederate && fed) default noexcept
default move constructor
~ValueFederate()
helics::ValueFederate::~ValueFederate () virtual default
destructor
Member Function Documentation
addSubscriptionShortcut()
void helics::ValueFederate::addSubscriptionShortcut (subscription_id_t subid, const std::string & shortcutName)
add a shortcut for locating a subscription
primarily for use in looking up an id from a different location creates a local shortcut for referring to a subscription which may have a long actual name
Parameters
[in] the subscription identifier
[in] shortcutName the name of the shortcut
disconnect()
void helics::ValueFederate::disconnect () override virtual
disconnect a simulation from the core (will also call finalize before disconnecting if necessary)
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
References helics::Federate::disconnect().
Referenced by helics::CombinationFederate::disconnect().
getLastUpdateTime()
Time helics::ValueFederate::getLastUpdateTime (subscription_id_t sub_id) const
get the time of the last update
Referenced by helics::SubscriptionBase::getLastUpdate().
getPublicationCount()
int helics::ValueFederate::getPublicationCount () const
get a count of the number publications registered
Referenced by helics::PublicationBase::PublicationBase().
getPublicationId() [1/3]
publication_id_t helics::ValueFederate::getPublicationId (const std::string & key) const
get the id of a registered publication from its id
Parameters
[in] name the name of the publication
Returns
ivalid_publication_id if name is not recognized otherwise returns the publication_id
References helics::Federate::getName(), helics::invalid_id_value, and helics::Federate::separator_.
Referenced by helics::publish().
getPublicationId() [2/3]
publication_id_t helics::ValueFederate::getPublicationId (const std::string & key, int index1) const
get the id of a registered publication from its id
Parameters
[in] name the name of the publication
Returns
ivalid_publication_id if name is not recognized otherwise returns the publication_id
getPublicationId() [3/3]
publication_id_t helics::ValueFederate::getPublicationId (const std::string & key, int index1, int index2) const
get the id of a registered publication from its id
Parameters
[in] name the name of the publication
Returns
ivalid_publication_id if name is not recognized otherwise returns the publication_id
getPublicationKey()
std::string helics::ValueFederate::getPublicationKey (publication_id_t pub_id) const
get the name of a publication from its id
Returns
empty string if an invalid id is passed
Referenced by helics::PublicationBase::getKey(), and helics::PublicationBase::PublicationBase().
getPublicationType() [1/2]
std::string helics::ValueFederate::getPublicationType (publication_id_t id) const
get the type of a publication from its id
Parameters
[in] id the publication id to query
Returns
the type or empty string on unrecognized id
Referenced by helics::SubscriptionBase::getType(), and helics::PublicationBase::PublicationBase().
getPublicationType() [2/2]
std::string helics::ValueFederate::getPublicationType (subscription_id_t id) const
get the type of the publication of a particular subscription
Parameters
[in] id the subscription id to query
Returns
the type or empty string on unrecognized id
getPublicationUnits()
std::string helics::ValueFederate::getPublicationUnits (publication_id_t id) const
get the units of a publication from its id
Parameters
[in] id the publication id to query
Returns
the units or empty string on unrecognized id
Referenced by helics::PublicationBase::PublicationBase().
getSubscriptionCount()
int helics::ValueFederate::getSubscriptionCount () const
get a count of the number subscriptions registered
getSubscriptionId() [1/3]
subscription_id_t helics::ValueFederate::getSubscriptionId (const std::string & key) const
get the id of a subscription
Returns
ivalid_subscription_id if name is not a recognized
Referenced by helics::getValue().
getSubscriptionId() [2/3]
subscription_id_t helics::ValueFederate::getSubscriptionId (const std::string & key, int index1) const
get the id of a subscription from a vector of subscriptions
Returns
ivalid_subscription_id if name is not a recognized
getSubscriptionId() [3/3]
subscription_id_t helics::ValueFederate::getSubscriptionId (const std::string & key, int index1, int index2) const
get the id of a subscription from a 2-d vector of subscriptions
Returns
ivalid_subscription_id if name is not a recognized
getSubscriptionKey()
std::string helics::ValueFederate::getSubscriptionKey (subscription_id_t sub_id) const
get the key or the string identifier of a subscription from its id
Returns
empty string if an invalid id is passed
getSubscriptionType()
std::string helics::ValueFederate::getSubscriptionType (subscription_id_t id) const
get the type of a subscription from its id
Parameters
[in] id the subscription id to query
Returns
the type or empty string on unrecognized id
getSubscriptionUnits()
std::string helics::ValueFederate::getSubscriptionUnits (subscription_id_t id) const
get the units of a subscriptions from its id
Parameters
[in] id the subscription id to query
Returns
the name or empty string on unrecognized id
getValue() [1/2]
template<typename X > void helics::ValueFederate::getValue (subscription_id_t id, X & obj) inline
get a value as raw data block from the system
Parameters
[in] id the identifier for the subscription
[out] the value translated to a specific object
Returns
a constant data block
Exceptions
std::invalid_argument if id is invalid
References getValueRaw(), and helics::ValueConverter< X >::interpret().
Referenced by helics::SubscriptionT< X >::getValue(), and helics::getValue().
getValue() [2/2]
template<typename X > X helics::ValueFederate::getValue (subscription_id_t id) inline
get a value as raw data block from the system
Parameters
[in] id the identifier for the subscription
[out] the value translated to a specific object
Returns
a constant data block
Exceptions
std::invalid_argument if id is invalid
References getValueRaw(), and helics::ValueConverter< X >::interpret().
getValueRaw()
data_view helics::ValueFederate::getValueRaw (subscription_id_t id)
get a value as raw data block from the system
Parameters
[in] id the identifier for the subscription
Returns
a constant data block
Exceptions
std::invalid_argument if id is invalid
Referenced by getValue().
initializeToExecuteStateTransition()
void helics::ValueFederate::initializeToExecuteStateTransition () override protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
Referenced by helics::CombinationFederate::initializeToExecuteStateTransition().
isUpdated()
bool helics::ValueFederate::isUpdated (subscription_id_t sub_id) const
check if a given subscription has an update
Returns
true if the subscription id is valid and has an update
Referenced by helics::SubscriptionBase::isUpdated().
operator=()
ValueFederate & helics::ValueFederate::operator= (ValueFederate && fed) noexcept
default move assignment
References helics::Federate::operator=().
publish() [1/5]
void helics::ValueFederate::publish (publication_id_t id, data_view block)
publish a value
Parameters
[in] id the publication identifier
[in] a data block containing the data
Exceptions
invalid_argument if the publication id is invalid
References helics::Federate::execution, helics::Federate::initialization, and helics::Federate::state.
Referenced by helics::Publication::publish(), helics::PublicationT< X >::publish(), publish(), and helics::publish().
publish() [2/5]
void helics::ValueFederate::publish (publication_id_t id, const data_block & block) inline
publish a data block
this function is primarily to prevent data blocks from falling through to the template
Parameters
[in] id the publication identifier
[in] a data block containing the data
Exceptions
invalid_argument if the publication id is invalid
References publish().
Referenced by publish().
publish() [3/5]
void helics::ValueFederate::publish (publication_id_t id, const char * data) inline
publish a string
Parameters
[in] id the publication identifier
[in] data a const char pointer to a string
Exceptions
invalid_argument if the publication id is invalid
References publish().
Referenced by publish().
publish() [4/5]
void helics::ValueFederate::publish (publication_id_t id, const char * data, size_t data_size) inline
publish data
Parameters
[in] id the publication identifier
[in] data a const char pointer to raw data
[in] data_size the length of the data
Exceptions
invalid_argument if the publication id is invalid
References publish().
publish() [5/5]
template<typename X > void helics::ValueFederate::publish (publication_id_t id, const X & value) inline
publish a value
Template Parameters
X the type of the value to publish
Parameters
[in] id the publication identifier
[in] value a reference to a value holding the data
Exceptions
invalid_argument if the publication id is invalid
References publish().
queryUpdates() [1/2]
std::vector<helics_subscription> helics::ValueFederate::queryUpdates () inline
Get a list of all subscriptions with updates since the last call
queryUpdates() [2/2]
std::vector< subscription_id_t > helics::ValueFederate::queryUpdates ()
get a list of all the values that have been updated since the last call
Returns
a vector of subscription_ids with all the values that have not been retrieved since updated
registerGlobalPublication() [1/2]
publication_id_t helics::ValueFederate::registerGlobalPublication (const std::string & key, const std::string & type, const std::string & units = std::string ())
register a publication
call is only valid in startup mode
Parameters
[in] key the name of the publication
[in] type a string defining the type of the publication
[in] units a string defining the units of the publication [optional]
Returns
a publication id object for use as an identifier
References helics::Federate::startup, and helics::Federate::state.
Referenced by registerGlobalPublication().
registerGlobalPublication() [2/2]
template<typename X > publication_id_t helics::ValueFederate::registerGlobalPublication (const std::string & key, const std::string & units = std::string ()) inline
register a publication
call is only valid in startup mode by default prepends the name with the federate name
Parameters
[in] key the name of the publication
[in] units the optional units of the publication
Returns
an identifier for use with this publication
References registerGlobalPublication().
registerInterfaces()
void helics::ValueFederate::registerInterfaces (const std::string & jsonString) override virtual
register a set of interfaces defined in a file
call is only valid in startup mode
Parameters
[in] jsonString the location of the file to load to generate the interfaces
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
References helics::Federate::registerInterfaces(), and registerValueInterfaces().
Referenced by ValueFederate().
registerOptionalSubscription() [1/3]
Subscription helics::ValueFederate::registerOptionalSubscription (const std::string & name, const std::string & type, const std::string & units = "") inline
Methods to register subscriptions
References helicsFederateRegisterOptionalSubscription(), and helics::FederateInfo::name.
registerOptionalSubscription() [2/3]
subscription_id_t helics::ValueFederate::registerOptionalSubscription (const std::string & key, const std::string & type, const std::string & units = std::string ())
register a subscription
call is only valid in startup mode
Parameters
[in] key the name of the publication to subscribe to
[in] type the type of the subscription
[in] units the units associated with the desired output
Referenced by registerOptionalSubscription().
registerOptionalSubscription() [3/3]
template<typename X > subscription_id_t helics::ValueFederate::registerOptionalSubscription (const std::string & key, const std::string & units = std::string ()) inline
register a subscription
call is only valid in startup mode
Parameters
[in] key the name of the subscription
[in] units the optional units on the subscription
References registerOptionalSubscription().
registerOptionalSubscriptionIndexed() [1/2]
template<typename X > subscription_id_t helics::ValueFederate::registerOptionalSubscriptionIndexed (const std::string & key, int index1, const std::string & units = std::string ()) inline
register an optional subscription
call is only valid in startup mode, register an optional subscription for a 1D array of values
Parameters
[in] key the name of the subscription
[in] index1 the index into a 1 dimensional array of values
[in] units the optional units on the subscription
registerOptionalSubscriptionIndexed() [2/2]
template<typename X > subscription_id_t helics::ValueFederate::registerOptionalSubscriptionIndexed (const std::string & key, int index1, int index2, const std::string & units = std::string ()) inline
register an optional subscription for a 2-D array of values
call is only valid in startup mode
Parameters
[in] key the name of the subscription
[in] index1 the first index of a 2-D value structure
[in] index2 the 2nd index of a 2-D value structure
[in] units the optional units on the subscription
registerPublication() [1/3]
publication_id_t helics::ValueFederate::registerPublication (const std::string & key, const std::string & type, const std::string & units = std::string ())
register a publication
call is only valid in startup mode
Parameters
[in] key the name of the publication
[in] type a string defining the type of the publication
[in] units a string defining the units of the publication [optional]
Returns
a publication id object for use as an identifier
References helics::Federate::getName(), helics::Federate::separator_, helics::Federate::startup, and helics::Federate::state.
Referenced by registerPublication().
registerPublication() [2/3]
template<typename X > publication_id_t helics::ValueFederate::registerPublication (const std::string & key, const std::string & units = std::string ()) inline
register a publication
call is only valid in startup mode by default prepends the name with the federate name
Parameters
[in] key the name of the publication
[in] units the optional units of the publication
Returns
an identifier for use with this publication
References registerPublication().
registerPublication() [3/3]
Publication helics::ValueFederate::registerPublication (const std::string & name, const std::string & type, const std::string & units = "") inline
Methods to register publications
References helicsFederateRegisterPublication(), and helics::FederateInfo::name.
registerPublicationIndexed() [1/2]
template<typename X > publication_id_t helics::ValueFederate::registerPublicationIndexed (const std::string & key, int index1, const std::string & units = std::string ()) inline
register a publication as part of an indexed structure
call is only valid in startup mode by default prepends the name with the federate name the name is registered as a global structure with the index appended
Parameters
[in] key the name of the publication
[in] index1 an index associated with the publication
[in] units the optional units of the publication
Returns
an identifier for use with this publication
registerPublicationIndexed() [2/2]
template<typename X > publication_id_t helics::ValueFederate::registerPublicationIndexed (const std::string & key, int index1, int index2, const std::string & units = std::string ()) inline
register a publication as part of a 2 dimensional indexed structure
call is only valid in startup mode by default prepends the name with the federate name the name is registered as a global structure with the indices appended
Parameters
[in] key the name of the publication
[in] index1 an index associated with the publication
[in] index2 a second index
[in] units the optional units of the publication
Returns
an identifier for use with this publication
registerRequiredSubscription() [1/2]
subscription_id_t helics::ValueFederate::registerRequiredSubscription (const std::string & key, const std::string & type, const std::string & units = std::string ())
register a subscription
call is only valid in startup mode register a subscription with name type and units
Parameters
[in] key the name of the publication to subscribe to
[in] type a string describing the type of the publication
[in] units a string describing the units on the publication
Referenced by registerRequiredSubscription().
registerRequiredSubscription() [2/2]
template<typename X > subscription_id_t helics::ValueFederate::registerRequiredSubscription (const std::string & name, const std::string & units = std::string ()) inline
register a subscription
call is only valid in startup mode
References registerRequiredSubscription().
registerRequiredSubscriptionIndexed() [1/2]
template<typename X > subscription_id_t helics::ValueFederate::registerRequiredSubscriptionIndexed (const std::string & key, int index1, const std::string & units = std::string ()) inline
register a required subscription
call is only valid in startup mode, register an optional subscription for a 1D array of values
Parameters
[in] key the name of the subscription
[in] index1 the index into a 1 dimensional array of values
[in] units the optional units on the subscription
registerRequiredSubscriptionIndexed() [2/2]
template<typename X > subscription_id_t helics::ValueFederate::registerRequiredSubscriptionIndexed (const std::string & key, int index1, int index2, const std::string & units = std::string ()) inline
register a required subscription for a 2-D array of values
call is only valid in startup mode
Parameters
[in] key the name of the subscription
[in] index1 the first index of a 2-D value structure
[in] index2 the 2nd index of a 2-D value structure
[in] units the optional units on the subscription
registerSubscription()
Subscription helics::ValueFederate::registerSubscription (const std::string & name, const std::string & type, const std::string & units = "") inline
Methods to register subscriptions
References helicsFederateRegisterSubscription(), and helics::FederateInfo::name.
registerSubscriptionNotificationCallback() [1/3]
void helics::ValueFederate::registerSubscriptionNotificationCallback (std::function< void(subscription_id_t, Time)> callback)
register a callback function to call when any subscribed value is updated
there can only be one generic callback
Parameters
[in] callback the function to call signature void(subscription_id_t, Time)
Referenced by helics::VectorSubscription< X >::operator=(), helics::VectorSubscription2d< X >::operator=(), helics::SubscriptionBase::registerCallback(), helics::Subscription::registerCallback(), helics::SubscriptionT< X >::registerCallback(), helics::VectorSubscription< X >::VectorSubscription(), and helics::VectorSubscription2d< X >::VectorSubscription2d().
registerSubscriptionNotificationCallback() [2/3]
void helics::ValueFederate::registerSubscriptionNotificationCallback (subscription_id_t id, std::function< void(subscription_id_t, Time)> callback)
register a callback function to call when the specified subscription is updated
Parameters
[in] id the id to register the callback for
[in] callback the function to call
registerSubscriptionNotificationCallback() [3/3]
void helics::ValueFederate::registerSubscriptionNotificationCallback (const std::vector< subscription_id_t > & ids, std::function< void(subscription_id_t, Time)> callback)
register a callback function to call when the specified subscription is updated
Parameters
[in] ids the set of ids to register the callback for
[in] callback the function to call
registerValueInterfaces()
void helics::ValueFederate::registerValueInterfaces (const std::string & jsonString)
register a set of value interfaces (publications and subscriptions)
call is only valid in startup mode it is a protected call to add an
Parameters
[in] jsonString the location of the file or json String to load to generate the interfaces
References getKey(), helics::invalid_id_value, loadJsonString(), helics::Federate::startup, and helics::Federate::state.
Referenced by helics::CombinationFederate::registerInterfaces(), and registerInterfaces().
setDefaultValue() [1/3]
void helics::ValueFederate::setDefaultValue (subscription_id_t id, data_view block)
set the default value for a subscription
this is the value returned prior to any publications
Parameters
[in] id the subscription identifier
[in] block the data view representing the default value
Exceptions
std::invalid_argument if id is invalid
Referenced by helics::SubscriptionT< X >::setDefault(), and setDefaultValue().
setDefaultValue() [2/3]
void helics::ValueFederate::setDefaultValue (subscription_id_t id, const data_block & block) inline
set the default value for a subscription
this is the value returned prior to any publications
Parameters
[in] id the subscription identifier
[in] block the data block representing the default value
Exceptions
std::invalid_argument if id is invalid
References setDefaultValue().
setDefaultValue() [3/3]
template<typename X > void helics::ValueFederate::setDefaultValue (subscription_id_t id, const X & val) inline
set a default value for a subscription
Parameters
[in] id the identifier for the subscription
[in] val the default value
Exceptions
std::invalid_argument if id is invalid
References setDefaultValue().
startupToInitializeStateTransition()
void helics::ValueFederate::startupToInitializeStateTransition () override protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
Referenced by helics::CombinationFederate::startupToInitializeStateTransition().
updateTime()
void helics::ValueFederate::updateTime (Time newTime, Time oldTime) override protected virtual
function to deal with any operations that need to occur on a time update
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
Referenced by helics::CombinationFederate::updateTime().
The documentation for this class was generated from the following files:
application_api/ValueFederate.hpp
ValueFederate.cpp