helics: AsioServiceManager Class Reference
AsioServiceManager Class Reference
#include <AsioServiceManager.h>
Public Types
using LoopHandle = std::unique_ptr< servicer >
Public Member Functions
const std::string & getName () const
boost::asio::io_service & getBaseService () const
Static Public Member Functions
static std::shared_ptr< AsioServiceManager > getServicePointer (const std::string &serviceName=std::string())
static std::shared_ptr< AsioServiceManager > getExistingServicePointer (const std::string &serviceName=std::string())
static boost::asio::io_service & getService (const std::string &serviceName=std::string())
static boost::asio::io_service & getExistingService (const std::string &serviceName=std::string())
static void closeService (const std::string &serviceName=std::string())
static void setServiceToLeakOnDelete (const std::string &serviceName=std::string())
static LoopHandle runServiceLoop (const std::string &serviceName=std::string())
Friends
void serviceProcessingLoop (std::shared_ptr< AsioServiceManager > ptr)
Detailed Description
class defining a (potential) singleton ASIO io_service manager for all boost::asio usage
Member Function Documentation
getBaseService()
boost::asio::io_service& AsioServiceManager::getBaseService () const inline
get the underlying boost::io_service reference
getExistingService()
boost::asio::io_service & AsioServiceManager::getExistingService (const std::string & serviceName = std::string()) static
get the boost io_service associated with the service manager but only if the service exists if it doesn't this will throw and invalid_argument exception
References getExistingServicePointer().
getExistingServicePointer()
std::shared_ptr< AsioServiceManager > AsioServiceManager::getExistingServicePointer (const std::string & serviceName = std::string()) static
return a pointer to a service manager
the function will search for an existing service manager for the name if it doesn't find one it will return nullptr
Parameters
serviceName the name of the service to find
Referenced by getExistingService().
getName()
const std::string& AsioServiceManager::getName () const inline
get the name of the current service manager
getService()
boost::asio::io_service & AsioServiceManager::getService (const std::string & serviceName = std::string()) static
get the boost io_service associated with the service manager
References getServicePointer().
getServicePointer()
std::shared_ptr< AsioServiceManager > AsioServiceManager::getServicePointer (const std::string & serviceName = std::string()) static
return a pointer to a service manager
the function will search for an existing service manager for the name if it doesn't find one it will create a new one
Parameters
serviceName the name of the service to find or create
Referenced by getService().
runServiceLoop()
AsioServiceManager::LoopHandle AsioServiceManager::runServiceLoop (const std::string & serviceName = std::string()) static
run a single thread for the service manager to execute asynchronous services in
will run a single thread for the io_service, it will not stop the thread until either the service manager is closed or the haltServiceLoop function is called and there is no more work
Parameters
in the name of the service
setServiceToLeakOnDelete()
void AsioServiceManager::setServiceToLeakOnDelete (const std::string & serviceName = std::string()) static
tell the service to free the pointer and leak the memory on delete
You may ask why, well in windows systems when operating in a DLL if this context is closed after certain other operations that happen when the DLL is unlinked bad things can happen, and since in nearly all cases this happens at Shutdown leaking really doesn't matter that much and if you don't the service could terminate before some other parts of the program which cause all sorts of odd errors and issues
The documentation for this class was generated from the following files:
AsioServiceManager.h
AsioServiceManager.cpp