helics: helics::Endpoint Class Reference
helics::Endpoint Class Reference
#include <Endpoints.hpp>
Public Member Functions
Endpoint ()=default
template<class FedPtr >
Endpoint (FedPtr mFed, const std::string &name, const std::string &type=std::string())
template<class FedPtr >
Endpoint (interface_visibility locality, FedPtr mFed, const std::string &name, const std::string &type=std::string())
Endpoint (MessageFederate *mFed, int endpointIndex)
void send (const std::string &dest, const char *data, size_t data_size) const
void subscribe (const std::string &key, const std::string &type)
void send (const std::string &dest, const char *data, size_t data_size, Time sendTime) const
void send (const char *data, size_t data_size, Time sendTime) const
void send (const std::string &dest, data_view data) const
void send (const std::string &dest, data_view data, Time sendTime) const
void send (const char *data, size_t data_size) const
void send (data_view data) const
void send (data_view data, Time sendTime) const
void send (const Message &mess) const
auto getMessage () const
bool hasMessage () const
auto receiveCount () const
void setCallback (const std::function< void(endpoint_id_t, Time)> &callback)
void setCallback (std::function< void(const Endpoint *, Time)> callback)
void setTargetDestination (const std::string &target)
const std::string & getName () const
std::string getType () const
endpoint_id_t getID () const
Detailed Description
class to manage an endpoint
Constructor & Destructor Documentation
Endpoint() [1/4]
helics::Endpoint::Endpoint () default
default constructor
Endpoint() [2/4]
template<class FedPtr > helics::Endpoint::Endpoint (FedPtr mFed, const std::string & name, const std::string & type = std::string ()) inline
constructor to build an endpoint object
Parameters
[in] mFed the MessageFederate to use
[in] name the name of the endpoint
[in] type a named type associated with the endpoint
References helics::MessageFederate::getEndpointName(), and helics::MessageFederate::registerEndpoint().
Endpoint() [3/4]
template<class FedPtr > helics::Endpoint::Endpoint (interface_visibility locality, FedPtr mFed, const std::string & name, const std::string & type = std::string ()) inline
constructor to build an endpoint object
Parameters
[in] mFed the MessageFederate to use
[in] name the name of the endpoint
[in] type a named type associated with the endpoint
References helics::MessageFederate::getEndpointName(), helics::MessageFederate::registerEndpoint(), and helics::MessageFederate::registerGlobalEndpoint().
Endpoint() [4/4]
Endpoint::Endpoint (MessageFederate * mFed, int endpointIndex)
generate an endpoint from a MessageFederate pointer and an endpoint index
References helics::MessageFederate::getEndpointCount(), and helics::MessageFederate::getEndpointName().
Member Function Documentation
getID()
endpoint_id_t helics::Endpoint::getID () const inline
get the actual endpoint id for the fed
getMessage()
auto helics::Endpoint::getMessage () const inline
get an available message if there is no message the returned object is empty
References helics::MessageFederate::getMessage().
getName()
const std::string& helics::Endpoint::getName () const inline
get the name of the endpoint
getType()
std::string helics::Endpoint::getType () const inline
get the specified type of the endpoint
References helics::MessageFederate::getEndpointType().
hasMessage()
bool helics::Endpoint::hasMessage () const inline
check if there is a message available
References helics::MessageFederate::hasMessage().
receiveCount()
auto helics::Endpoint::receiveCount () const inline
check if there is a message available
References helics::MessageFederate::receiveCount().
send() [1/9]
void helics::Endpoint::send (const std::string & dest, const char * data, size_t data_size) const inline
send a data block and length
Parameters
[in] dest string name of the destination
[in] data pointer to data location
[in] data_size the length of the data
send() [2/9]
void helics::Endpoint::send (const std::string & dest, const char * data, size_t data_size, Time sendTime) const inline
send a data block and length
Parameters
[in] dest string name of the destination
[in] data pointer to data location
[in] data_size the length of the data
send() [3/9]
void helics::Endpoint::send (const char * data, size_t data_size, Time sendTime) const inline
send a data block and length
Parameters
[in] data pointer to data location
[in] data_size the length of the data
sendTime the time to send the message
References helics::MessageFederate::sendMessage().
send() [4/9]
void helics::Endpoint::send (const std::string & dest, data_view data) const inline
send a data_view
a data view can convert from many different formats so this function should be catching many of the common use cases
Parameters
[in] dest string name of the destination
[in] data the information to send
send() [5/9]
void helics::Endpoint::send (const std::string & dest, data_view data, Time sendTime) const inline
send a data_view
a data view can convert from many different formats so this function should be catching many of the common use cases
Parameters
[in] dest string name of the destination
[in] data data representation to send
[in] sendTime the time the message should be sent
send() [6/9]
void helics::Endpoint::send (const char * data, size_t data_size) const inline
send a data block and length to the target destination
Parameters
[in] data pointer to data location
[in] data_size the length of the data
References helics::MessageFederate::sendMessage().
send() [7/9]
void helics::Endpoint::send (data_view data) const inline
send a data_view to the target destination
a data view can convert from many different formats so this function should be catching many of the common use cases
Parameters
[in] data the information to send
References helics::MessageFederate::sendMessage().
send() [8/9]
void helics::Endpoint::send (data_view data, Time sendTime) const inline
send a data_view to the specified target destination
a data view can convert from many different formats so this function should be catching many of the common use cases
Parameters
[in] data a representation to send
[in] sendTime the time the message should be sent
References helics::MessageFederate::sendMessage().
send() [9/9]
void helics::Endpoint::send (const Message & mess) const inline
send a message object
this is to send a pre-built message
Parameters
[in] mess a reference to an actual message object
References helics::MessageFederate::sendMessage().
setCallback() [1/2]
void helics::Endpoint::setCallback (const std::function< void(endpoint_id_t, Time)> & callback) inline
register a callback for an update notification
the callback is called in the just before the time request function returns
Parameters
[in] callback a function with signature void(endpoint_id_t, Time) time is the time the value was updated This callback is a notification callback and doesn't return the value
References helics::MessageFederate::registerEndpointCallback().
setCallback() [2/2]
void Endpoint::setCallback (std::function< void(const Endpoint *, Time)> callback)
register a callback for an update notification
the callback is called in the just before the time request function returns
Parameters
[in] callback a function with signature void(endpoint_id_t, Time) time is the time the value was updated This callback is a notification callback and doesn't return the value
setTargetDestination()
void helics::Endpoint::setTargetDestination (const std::string & target) inline
set a target destination for unspecified messages
subscribe()
void helics::Endpoint::subscribe (const std::string & key, const std::string & type) inline
subscribe the endpoint to a particular publication
References helics::MessageFederate::subscribe().
The documentation for this class was generated from the following files:
Endpoints.hpp
Endpoints.cpp