helics: helics::ValueFederateManager Class Reference
helics::ValueFederateManager Class Reference
#include <ValueFederateManager.hpp>
Public Member Functions
ValueFederateManager (Core *coreOb, Core::federate_id_t id)
publication_id_t registerPublication (const std::string &key, const std::string &type, const std::string &units)
subscription_id_t registerRequiredSubscription (const std::string &key, const std::string &type, const std::string &units)
subscription_id_t registerOptionalSubscription (const std::string &key, const std::string &type, const std::string &units)
void addSubscriptionShortcut (subscription_id_t subid, const std::string &shortcutName)
void setDefaultValue (subscription_id_t id, const data_view &block)
data_view getValue (subscription_id_t id)
void publish (publication_id_t id, const data_view &block)
bool queryUpdate (subscription_id_t sub_id) const
Time queryLastUpdate (subscription_id_t sub_id) const
void updateTime (Time newTime, Time oldTime)
void startupToInitializeStateTransition ()
void initializeToExecuteStateTransition ()
std::vector< subscription_id_t > queryUpdates ()
std::string getSubscriptionKey (subscription_id_t id) const
subscription_id_t getSubscriptionId (const std::string &name) const
std::string getPublicationKey (publication_id_t id) const
publication_id_t getPublicationId (const std::string &key) const
std::string getSubscriptionUnits (subscription_id_t id) const
std::string getPublicationUnits (publication_id_t id) const
std::string getSubscriptionType (subscription_id_t id) const
std::string getPublicationType (publication_id_t id) const
std::string getPublicationType (subscription_id_t id) const
void registerCallback (std::function< void(subscription_id_t, Time)> callback)
void registerCallback (subscription_id_t id, std::function< void(subscription_id_t, Time)> callback)
void registerCallback (const std::vector< subscription_id_t > &ids, std::function< void(subscription_id_t, Time)> callback)
void disconnect ()
int getPublicationCount () const
int getSubscriptionCount () const
Detailed Description
class handling the implementation details of a value Federate
Member Function Documentation
addSubscriptionShortcut()
void helics::ValueFederateManager::addSubscriptionShortcut (subscription_id_t subid, const std::string & shortcutName)
add a shortcut for locating a subscription
primarily for use in looking up an id from a different location creates a local shortcut for referring to a subscription which may have a long actual name
Parameters
[in] the subscription identifier
[in] shortcutName the name of the shortcut
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
disconnect()
void helics::ValueFederateManager::disconnect ()
disconnect from the coreObject
getPublicationCount()
int helics::ValueFederateManager::getPublicationCount () const
get a count of the number publications registered
getPublicationId()
publication_id_t helics::ValueFederateManager::getPublicationId (const std::string & key) const
get the id of a registered publication from its id
Parameters
[in] name the publication id
Returns
ivalid_publication_id if name is not recognized otherwise returns the publication_id
References helics::invalid_id_value.
getPublicationKey()
std::string helics::ValueFederateManager::getPublicationKey (publication_id_t id) const
get the key of a publication from its id
Returns
empty string if an invalid id is passed
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
getPublicationType() [1/2]
std::string helics::ValueFederateManager::getPublicationType (publication_id_t id) const
get the type of a publication from its id
Parameters
[in] id the publication id to query
Returns
the type or empty string on unrecognized id
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
getPublicationType() [2/2]
std::string helics::ValueFederateManager::getPublicationType (subscription_id_t id) const
get the type of a publication from its subscription
Parameters
[in] id the subscription id to query
Returns
the type or empty string on unrecognized id
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
getPublicationUnits()
std::string helics::ValueFederateManager::getPublicationUnits (publication_id_t id) const
get the units of a publication from its id
Parameters
[in] id the publication id to query
Returns
the units or empty string on unrecognized id
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
getSubscriptionCount()
int helics::ValueFederateManager::getSubscriptionCount () const
get a count of the number subscriptions registered
getSubscriptionId()
subscription_id_t helics::ValueFederateManager::getSubscriptionId (const std::string & name) const
get the id of a subscription
Returns
ivalid_subscription_id if name is not a recognized
References helics::invalid_id_value.
getSubscriptionKey()
std::string helics::ValueFederateManager::getSubscriptionKey (subscription_id_t id) const
get the key of a subscription from its id
Returns
empty string if an invalid id is passed
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
getSubscriptionType()
std::string helics::ValueFederateManager::getSubscriptionType (subscription_id_t id) const
get the type of a subscription from its id
Parameters
[in] id the subscription id to query
Returns
the type or empty string on unrecognized id
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
getSubscriptionUnits()
std::string helics::ValueFederateManager::getSubscriptionUnits (subscription_id_t id) const
get the units of a subscriptions from its id
Parameters
[in] id the subscription id to query
Returns
the name or empty string on unrecognized id
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
getValue()
data_view helics::ValueFederateManager::getValue (subscription_id_t id)
get a value as raw data block from the system
Parameters
[in] id the identifier for the subscription
Returns
a constant data block
initializeToExecuteStateTransition()
void helics::ValueFederateManager::initializeToExecuteStateTransition ()
transition from initialize to execution State
publish()
void helics::ValueFederateManager::publish (publication_id_t id, const data_view & block)
publish a value
References helics::data_view::data(), helics::isBlockSizeValid(), and helics::data_view::size().
queryLastUpdate()
Time helics::ValueFederateManager::queryLastUpdate (subscription_id_t sub_id) const
get the time of the last update
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
queryUpdate()
bool helics::ValueFederateManager::queryUpdate (subscription_id_t sub_id) const
check if a given subscription has and update
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
queryUpdates()
std::vector< subscription_id_t > helics::ValueFederateManager::queryUpdates ()
get a list of all the values that have been updated since the last call
Returns
a vector of subscription_ids with all the values that have not been retrieved since updated
registerCallback() [1/3]
void helics::ValueFederateManager::registerCallback (std::function< void(subscription_id_t, Time)> callback)
register a callback function to call when any subscribed value is updated
there can only be one generic callback
Parameters
[in] callback the function to call
registerCallback() [2/3]
void helics::ValueFederateManager::registerCallback (subscription_id_t id, std::function< void(subscription_id_t, Time)> callback)
register a callback function to call when the specified subscription is updated
Parameters
[in] id the id to register the callback for
[in] callback the function to call
registerCallback() [3/3]
void helics::ValueFederateManager::registerCallback (const std::vector< subscription_id_t > & ids, std::function< void(subscription_id_t, Time)> callback)
register a callback function to call when the specified subscription is updated
Parameters
[in] ids the set of ids to register the callback for
[in] callback the function to call
registerOptionalSubscription()
subscription_id_t helics::ValueFederateManager::registerOptionalSubscription (const std::string & key, const std::string & type, const std::string & units)
register a subscription
call is only valid in startup mode
registerRequiredSubscription()
subscription_id_t helics::ValueFederateManager::registerRequiredSubscription (const std::string & key, const std::string & type, const std::string & units)
register a subscription
call is only valid in startup mode
setDefaultValue()
void helics::ValueFederateManager::setDefaultValue (subscription_id_t id, const data_view & block)
set the default value for a subscription
this is the value returned prior to any publications
Parameters
[in] id the subscription identifier
[in] block the data block representing the default value
copy the data first since we are not entirely sure of the lifetime of the data_view
References helics::data_view::data(), and helics::data_view::size().
startupToInitializeStateTransition()
void helics::ValueFederateManager::startupToInitializeStateTransition ()
transition from Startup To the Initialize State
updateTime()
void helics::ValueFederateManager::updateTime (Time newTime, Time oldTime)
update the time from oldTime to newTime
Parameters
[in] newTime the newTime of the federate
[in] oldTime the oldTime of the federate
find the id
The documentation for this class was generated from the following files:
ValueFederateManager.hpp
ValueFederateManager.cpp