helics: helics::PublicationT< X > Class Template Reference
helics::PublicationT< X > Class Template Reference
#include <Publications.hpp>
Public Member Functions
template<class FedPtr >
PublicationT (FedPtr valueFed, const std::string &key, const std::string &units=std::string())
template<class FedPtr >
PublicationT (interface_visibility locality, FedPtr valueFed, const std::string &key, const std::string &units=std::string())
virtual void publish (const X &val) const
virtual void publish (const X &val, const std::string &) const
Public Member Functions inherited from helics::PublicationBase
template<class FedPtr >
PublicationBase (FedPtr valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
template<class FedPtr >
PublicationBase (interface_visibility locality, FedPtr valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
PublicationBase (ValueFederate *valueFed, int pubIndex)
virtual ~PublicationBase ()=default
publication_id_t getID () const
std::string getKey () const
const std::string & getName () const
const std::string & getType () const
const std::string & getUnits () const
Additional Inherited Members
Protected Attributes inherited from helics::PublicationBase
ValueFederate * fed = nullptr
the federate construct to interact with
publication_id_t id
the internal id of the publication
Detailed Description
template<class X>
class helics::PublicationT< X >
class to handle a publication of an arbitrary type
Constructor & Destructor Documentation
PublicationT() [1/2]
template<class X > template<class FedPtr > helics::PublicationT< X >::PublicationT (FedPtr valueFed, const std::string & key, const std::string & units = std::string ()) inline
constructor to build a publication object
Parameters
[in] valueFed the ValueFederate to use
[in] key the identifier for the publication
[in] units the units associated with a Federate
PublicationT() [2/2]
template<class X > template<class FedPtr > helics::PublicationT< X >::PublicationT (interface_visibility locality, FedPtr valueFed, const std::string & key, const std::string & units = std::string ()) inline
constructor to build a publication object
Parameters
[in] valueFed the ValueFederate to use
[in] key the identifier for the publication
[in] units the units associated with a Federate
Member Function Documentation
publish() [1/2]
template<class X > virtual void helics::PublicationT< X >::publish (const X & val) const inline virtual
send a value for publication
Parameters
[in] val the value to publish
Reimplemented in helics::PublicationOnChange< X >.
References helics::PublicationBase::fed, and helics::ValueFederate::publish().
Referenced by helics::PublicationT< X >::publish(), and helics::PublicationOnChange< X >::publish().
publish() [2/2]
template<class X > virtual void helics::PublicationT< X >::publish (const X & val, const std::string &) const inline virtual
secondary publish function to allow unit conversion before publication
Parameters
[in] val the value to publish
[in] units the units association with the publication
References helics::PublicationT< X >::publish().
The documentation for this class was generated from the following file:
Publications.hpp