helics: helics::MessageFederate Class Reference
helics::MessageFederate Class Reference
#include <MessageFederate.hpp>
Public Member Functions
MessageFederate (const FederateInfo &fi)
MessageFederate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
MessageFederate (const std::string &jsonString)
MessageFederate (const std::string &name, const std::string &jsonString)
MessageFederate (MessageFederate &&mFed) noexcept
MessageFederate ()
MessageFederate (bool res)
~MessageFederate ()
MessageFederate & operator= (MessageFederate &&mFed) noexcept
endpoint_id_t registerEndpoint (const std::string &name, const std::string &type="")
endpoint_id_t registerGlobalEndpoint (const std::string &name, const std::string &type="")
virtual void registerInterfaces (const std::string &jsonString) override
void registerMessageInterfaces (const std::string &jsonString)
void registerKnownCommunicationPath (endpoint_id_t localEndpoint, const std::string &remoteEndpoint)
void subscribe (endpoint_id_t endpoint, const std::string &name, const std::string &type)
bool hasMessage () const
bool hasMessage (endpoint_id_t id) const
uint64_t receiveCount (endpoint_id_t id) const
uint64_t receiveCount () const
std::unique_ptr< Message > getMessage (endpoint_id_t endpoint)
std::unique_ptr< Message > getMessage ()
void sendMessage (endpoint_id_t source, const std::string &dest, const char *data, size_t len)
void sendMessage (endpoint_id_t source, const std::string &dest, const data_view &message)
void sendMessage (endpoint_id_t source, const std::string &dest, const char *data, size_t len, Time sendTime)
void sendMessage (endpoint_id_t source, const std::string &dest, const data_view &message, Time sendTime)
void sendMessage (endpoint_id_t source, std::unique_ptr< Message > message)
void sendMessage (endpoint_id_t source, const Message &message)
std::string getEndpointName (endpoint_id_t id) const
endpoint_id_t getEndpointId (const std::string &name) const
std::string getEndpointType (endpoint_id_t ep)
void registerEndpointCallback (const std::function< void(endpoint_id_t, Time)> &callback)
void registerEndpointCallback (endpoint_id_t ep, const std::function< void(endpoint_id_t, Time)> &callback)
void registerEndpointCallback (const std::vector< endpoint_id_t > &ep, const std::function< void(endpoint_id_t, Time)> &callback)
virtual void disconnect () override
int getEndpointCount () const
MessageFederate (FederateInfo &fi)
MessageFederate (const std::string &jsonString)
Endpoint registerEndpoint (const std::string &name, const std::string &type="")
Endpoint registerGlobalEndpoint (const std::string &name, const std::string &type="")
bool hasMessage () const
uint64_t receiveCount () const
message_t getMessage ()
Public Member Functions inherited from helics::Federate
Federate (const FederateInfo &fi)
Federate (const std::string &name, const FederateInfo &fi)
Federate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
Federate (const std::string &jsonString)
Federate (const std::string &name, const std::string &jsonString)
Federate () noexcept
Federate (Federate &&fed) noexcept
Federate (const Federate &fed)=delete
virtual ~Federate ()
Federate & operator= (Federate &&fed) noexcept
Federate & operator= (const Federate &fed)=delete
void enterInitializationState ()
void enterInitializationStateAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationStateComplete ()
iteration_result enterExecutionState (iteration_request iterate=iteration_request::no_iterations)
void enterExecutionStateAsync (iteration_request iterate=iteration_request::no_iterations)
iteration_result enterExecutionStateComplete ()
void finalize ()
void error (int errorcode)
void error (int errorcode, const std::string &message)
void setSeparator (char separator)
Time requestTime (Time nextInternalTimeStep)
iteration_time requestTimeIterative (Time nextInternalTimeStep, iteration_request iterate)
void requestTimeAsync (Time nextInternalTimeStep)
void requestTimeIterativeAsync (Time nextInternalTimeStep, iteration_request iterate)
Time requestTimeComplete ()
iteration_time requestTimeIterativeComplete ()
void setTimeDelta (Time tdelta)
void setOutputDelay (Time outputDelay)
void setInputDelay (Time inputDelay)
void setPeriod (Time period, Time offset=timeZero)
virtual void setFlag (int flag, bool flagValue=true)
void setLoggingLevel (int loggingLevel)
void setMaxIterations (int maxIterations)
void setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> &logFunction)
std::string query (const std::string &target, const std::string &queryStr)
std::string query (const std::string &queryStr)
query_id_t queryAsync (const std::string &target, const std::string &queryStr)
query_id_t queryAsync (const std::string &queryStr)
std::string queryComplete (query_id_t queryIndex)
bool isQueryCompleted (query_id_t queryIndex) const
filter_id_t registerSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerDestinationFilter (const std::string &destEndpoint)
filter_id_t registerCloningSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerCloningDestinationFilter (const std::string &destEndpoint)
std::string getFilterName (filter_id_t id) const
std::string getFilterEndpoint (filter_id_t id) const
std::string getFilterInputType (filter_id_t id) const
std::string getFilterOutputType (filter_id_t id) const
filter_id_t getFilterId (const std::string &filterName) const
filter_id_t getSourceFilterId (const std::string &filterName) const
filter_id_t getDestFilterId (const std::string &filterName) const
void setFilterOperator (filter_id_t filter, std::shared_ptr< FilterOperator > op)
register a operator for the specified filter
void setFilterOperator (const std::vector< filter_id_t > &filters, std::shared_ptr< FilterOperator > op)
register a operator for the specified filters
void registerFilterInterfaces (const std::string &jsonString)
auto getID () const noexcept
op_states getCurrentState () const
Time getCurrentTime () const
const std::string & getName () const
std::shared_ptr< Core > getCorePointer ()
std::shared_ptr< Filter > getFilterObject (int index)
void addFilterObject (std::shared_ptr< Filter > obj)
int filterObjectCount () const
Federate (const Federate &fedObj)
Federate & operator= (const Federate &fedObj)
operator helics_federate () const
helics_federate baseObject () const
void setFlag (int flag, int value)
void setOutputDelay (helics_time_t outputDelay)
void setTimeDelta (helics_time_t timeDelta)
void setInputDelay (helics_time_t inputDelay)
void setPeriod (helics_time_t period, helics_time_t offset)
void setMaxIterations (int max_iterations)
void setLoggingLevel (int logLevel)
federate_state getState () const
void enterInitializationMode ()
void enterInitializationModeAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationModeComplete ()
helics_iteration_status enterExecutionMode (helics_iteration_request iterate=no_iteration)
void enterExecutionModeAsync (helics_iteration_request iterate=no_iteration)
helics_iteration_status enterExecutionModeComplete ()
void finalize ()
helics_time_t requestTime (helics_time_t time)
helics_iteration_time requestTimeIterative (helics_time_t time, helics_iteration_request iterate)
void requestTimeAsync (helics_time_t time)
void requestTimeIterativeAsync (helics_time_t time, helics_iteration_request iterate)
helics_time_t requestTimeComplete ()
helics_iteration_time requestTimeIterativeComplete ()
std::string getName () const
std::string query (const std::string &target, const std::string &queryStr)
Filter registerSourceFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
Filter registerDestinationFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
CloningFilter registerCloningFilter (const std::string &deliveryEndpoint)
Protected Member Functions
virtual void startupToInitializeStateTransition () override
virtual void initializeToExecuteStateTransition () override
virtual void updateTime (Time newTime, Time oldTime) override
Additional Inherited Members
Public Types inherited from helics::Federate
enum op_states : char {
op_states::startup = 0, op_states::initialization = 1, op_states::execution = 2, op_states::finalize = 3,
op_states::error = 4, op_states::pending_init = 5, op_states::pending_exec = 6, op_states::pending_time = 7,
op_states::pending_iterative_time = 8
}
Protected Attributes inherited from helics::Federate
std::atomic< op_states > state {op_states::startup}
the current state of the simulation
char separator_ = '/'
the separator between automatically prependend names
std::shared_ptr< Core > coreObject
reference to the core simulation API
Time currentTime
the current simulation time
FederateInfo FedInfo
the information structure that contains the data on the federate
helics_federate fed
bool exec_async_iterate
Detailed Description
class defining the block communication based interface
Constructor & Destructor Documentation
MessageFederate() [1/7]
helics::MessageFederate::MessageFederate (const FederateInfo & fi) explicit
constructor taking a federate information structure and using the default core
Parameters
[in] fi a federate information structure
References helics::Federate::coreObject, and helics::Federate::getID().
MessageFederate() [2/7]
helics::MessageFederate::MessageFederate (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a core and a federate information structure, sore information in fi is ignored
Parameters
[in] core a shared ptr to a core to join
[in] fi a federate information structure
References helics::Federate::coreObject, and helics::Federate::getID().
MessageFederate() [3/7]
helics::MessageFederate::MessageFederate (const std::string & jsonString) explicit
constructor taking a string with the required information
Parameters
[in] jsonString can be either a json file or a string containing json code
References helics::Federate::coreObject, helics::Federate::getID(), and registerInterfaces().
MessageFederate() [4/7]
helics::MessageFederate::MessageFederate (const std::string & name, const std::string & jsonString)
constructor taking a string with the required information
Parameters
[in] name the name of the federate
[in] jsonString can be either a json file or a string containing json code
References helics::Federate::coreObject, helics::Federate::getID(), and registerInterfaces().
MessageFederate() [5/7]
helics::MessageFederate::MessageFederate (MessageFederate && mFed) default noexcept
move constructor
MessageFederate() [6/7]
helics::MessageFederate::MessageFederate ()
default constructor
MessageFederate() [7/7]
helics::MessageFederate::MessageFederate (bool res) explicit
special constructor should only be used by child classes in constructor due to virtual inheritance
References helics::Federate::coreObject, and helics::Federate::getID().
~MessageFederate()
helics::MessageFederate::~MessageFederate () default
destructor
Member Function Documentation
disconnect()
void helics::MessageFederate::disconnect () override virtual
disconnect a simulation from the core (will also call finalize before disconnecting if necessary)
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
References helics::Federate::disconnect().
Referenced by helics::CombinationFederate::disconnect().
getEndpointCount()
int helics::MessageFederate::getEndpointCount () const
get the number of registered endpoints
get a count of the number endpoints registered
Referenced by helics::Endpoint::Endpoint().
getEndpointId()
endpoint_id_t helics::MessageFederate::getEndpointId (const std::string & name) const
get the id of a registered publication from its id
Parameters
[in] name the publication id
Returns
ivalid_publication_id if name is not recognized otherwise returns the publication_id
References helics::Federate::getName(), and helics::invalid_id_value.
getEndpointName()
std::string helics::MessageFederate::getEndpointName (endpoint_id_t id) const
get the name of an endpoint from its id
Parameters
[in] id the endpoint to query
Returns
empty string if an invalid id is passed
Referenced by helics::Endpoint::Endpoint().
getEndpointType()
std::string helics::MessageFederate::getEndpointType (endpoint_id_t ep)
get the type associated with an endpoint
Parameters
[in] ep the endpoint identifier
Returns
a string containing the endpoint type
Referenced by helics::Endpoint::getType().
getMessage() [1/3]
message_t helics::MessageFederate::getMessage () inline
Get a packet for any endpoints in the federate
References helicsFederateGetMessage().
getMessage() [2/3]
std::unique_ptr< Message > helics::MessageFederate::getMessage (endpoint_id_t endpoint)
receive a packet from a particular endpoint
Parameters
[in] endpoint the identifier for the endpoint
Returns
a message object
References helics::Federate::execution, and helics::Federate::state.
Referenced by helics::Endpoint::getMessage().
getMessage() [3/3]
std::unique_ptr< Message > helics::MessageFederate::getMessage ()
receive a communication message for any endpoint in the federate
the return order will be in order of endpoint creation then order of arrival all messages for the first endpoint, then all for the second, and so on
Returns
a unique_ptr to a Message object containing the message data
References helics::Federate::execution, and helics::Federate::state.
hasMessage() [1/2]
bool helics::MessageFederate::hasMessage () const inline
Checks if federate has any messages
References helicsFederateHasMessage().
hasMessage() [2/2]
bool helics::MessageFederate::hasMessage () const
check if the federate has any outstanding messages
References helics::Federate::execution, and helics::Federate::state.
Referenced by helics::Endpoint::hasMessage().
initializeToExecuteStateTransition()
void helics::MessageFederate::initializeToExecuteStateTransition () override protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
Referenced by helics::CombinationFederate::initializeToExecuteStateTransition().
operator=()
MessageFederate & helics::MessageFederate::operator= (MessageFederate && mFed) noexcept
move assignment
References helics::Federate::operator=().
receiveCount() [1/3]
uint64_t helics::MessageFederate::receiveCount () const inline
Returns the number of pending receives for all endpoints.
References helicsFederateReceiveCount().
receiveCount() [2/3]
uint64_t helics::MessageFederate::receiveCount (endpoint_id_t id) const
Returns the number of pending receives for the specified destination endpoint.
References helics::Federate::execution, and helics::Federate::state.
Referenced by helics::Endpoint::receiveCount().
receiveCount() [3/3]
uint64_t helics::MessageFederate::receiveCount () const
Returns the number of pending receives for all endpoints.
Returns the number of pending receives for the specified destination endpoint.
this function is not preferred in multithreaded contexts due to the required locking prefer to just use getMessage until it returns an invalid Message.
References helics::Federate::execution, and helics::Federate::state.
registerEndpoint() [1/2]
Endpoint helics::MessageFederate::registerEndpoint (const std::string & name, const std::string & type = "") inline
Methods for registering endpoints
References helicsFederateRegisterEndpoint().
registerEndpoint() [2/2]
endpoint_id_t helics::MessageFederate::registerEndpoint (const std::string & name, const std::string & type = "")
register an endpoint
call is only valid in startup mode
Parameters
[in] name the name of the endpoint
[in] type the defined type of the interface for endpoint checking if requested
References helics::Federate::getName(), helics::Federate::separator_, helics::Federate::startup, and helics::Federate::state.
Referenced by helics::Endpoint::Endpoint().
registerEndpointCallback() [1/3]
void helics::MessageFederate::registerEndpointCallback (const std::function< void(endpoint_id_t, Time)> & callback)
register a callback for all endpoints
Parameters
[in] callback the function to execute upon receipt of a message for any endpoint
Referenced by helics::Endpoint::setCallback().
registerEndpointCallback() [2/3]
void helics::MessageFederate::registerEndpointCallback (endpoint_id_t ep, const std::function< void(endpoint_id_t, Time)> & callback)
register a callback for a specific endpoint
Parameters
[in] ep the endpoint to associate with the specified callback
[in] callback the function to execute upon receipt of a message for the given endpoint
registerEndpointCallback() [3/3]
void helics::MessageFederate::registerEndpointCallback (const std::vector< endpoint_id_t > & ep, const std::function< void(endpoint_id_t, Time)> & callback)
register a callback for a set of specific endpoint
Parameters
[in] ep a vector of endpoints to associate with the specified callback
[in] callback the function to execute upon receipt of a message for the given endpoint
registerGlobalEndpoint()
endpoint_id_t helics::MessageFederate::registerGlobalEndpoint (const std::string & name, const std::string & type = "")
register an endpoint directly without prepending the federate name
call is only valid in startup mode
Parameters
[in] name the name of the endpoint
[in] type the defined type of the interface for endpoint checking if requested
References helics::Federate::startup, and helics::Federate::state.
Referenced by helics::Endpoint::Endpoint().
registerInterfaces()
void helics::MessageFederate::registerInterfaces (const std::string & jsonString) override virtual
register a set of interfaces defined in a file
call is only valid in startup mode
Parameters
[in] jsonString the location of the file or json String to load to generate the interfaces
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
References helics::Federate::registerFilterInterfaces(), and registerMessageInterfaces().
Referenced by MessageFederate().
registerKnownCommunicationPath()
void helics::MessageFederate::registerKnownCommunicationPath (endpoint_id_t localEndpoint, const std::string & remoteEndpoint)
give the core a hint for known communication paths
the function will generate an error in the core if a communication path is not present once the simulation is initialized
Parameters
[in] localEndpoint the local endpoint of a known communication pair
[in] remoteEndpoint of a communication pair
References helics::Federate::startup, and helics::Federate::state.
registerMessageInterfaces()
void helics::MessageFederate::registerMessageInterfaces (const std::string & jsonString)
register a set Message interfaces
call is only valid in startup mode it is a protected call to add an
Parameters
[in] jsonString the location of the file or json String to load to generate the interfaces
References getKey(), loadJsonString(), helics::Federate::startup, and helics::Federate::state.
Referenced by helics::CombinationFederate::registerInterfaces(), and registerInterfaces().
sendMessage() [1/6]
void helics::MessageFederate::sendMessage (endpoint_id_t source, const std::string & dest, const char * data, size_t len) inline
send a message
send a message to a specific destination
Parameters
[in] source the source endpoint
[in] dest a string naming the destination
[in] data a buffer containing the data
[in] len the length of the data buffer
Referenced by helics::Endpoint::send().
sendMessage() [2/6]
void helics::MessageFederate::sendMessage (endpoint_id_t source, const std::string & dest, const data_view & message)
send a message
send a message to a specific destination
Parameters
[in] source the source endpoint
[in] dest a string naming the destination
[in] message a data_view of the message
References helics::Federate::execution, and helics::Federate::state.
sendMessage() [3/6]
void helics::MessageFederate::sendMessage (endpoint_id_t source, const std::string & dest, const char * data, size_t len, Time sendTime) inline
send an event message at a particular time
send a message to a specific destination
Parameters
[in] source the source endpoint
[in] dest a string naming the destination
[in] data a buffer containing the data
[in] len the length of the data buffer
[in] Time the time the message should be sent
sendMessage() [4/6]
void helics::MessageFederate::sendMessage (endpoint_id_t source, const std::string & dest, const data_view & message, Time sendTime)
send an event message at a particular time
send a message to a specific destination
Parameters
[in] source the source endpoint
[in] dest a string naming the destination
[in] message a data_view of the message data to send
[in] Time the time the message should be sent
References helics::Federate::execution, and helics::Federate::state.
sendMessage() [5/6]
void helics::MessageFederate::sendMessage (endpoint_id_t source, std::unique_ptr< Message > message)
send an event message at a particular time
send a message to a specific destination
Parameters
[in] source the source endpoint
[in] message a pointer to the message
References helics::Federate::execution, and helics::Federate::state.
sendMessage() [6/6]
void helics::MessageFederate::sendMessage (endpoint_id_t source, const Message & message)
send an event message at a particular time
send a message to a specific destination
Parameters
[in] source the source endpoint
[in] message a message object
References helics::Federate::execution, and helics::Federate::state.
startupToInitializeStateTransition()
void helics::MessageFederate::startupToInitializeStateTransition () override protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
Referenced by helics::CombinationFederate::startupToInitializeStateTransition().
subscribe()
void helics::MessageFederate::subscribe (endpoint_id_t endpoint, const std::string & name, const std::string & type)
subscribe to valueFederate publication to be delivered as Messages to the given endpoint
Parameters
[in] endpoint the specified endpoint to deliver the values
[in] name the name of the publication to subscribe
[in] type the type of publication
References helics::Federate::startup, and helics::Federate::state.
Referenced by helics::Endpoint::subscribe().
updateTime()
void helics::MessageFederate::updateTime (Time newTime, Time oldTime) override protected virtual
function to deal with any operations that need to occur on a time update
Reimplemented from helics::Federate.
Reimplemented in helics::CombinationFederate.
Referenced by helics::CombinationFederate::updateTime().
The documentation for this class was generated from the following files:
application_api/MessageFederate.hpp
MessageFederate.cpp