helics: helics::FederateInfo Class Reference
helics::FederateInfo Class Reference
#include <Federate.hpp>
Public Member Functions
FederateInfo ()=default
FederateInfo (std::string fedname)
FederateInfo (std::string fedname, core_type cType)
FederateInfo (int argc, const char *const *argv)
void loadInfoFromArgs (int argc, const char *const *argv)
FederateInfo (const std::string &fedname)
FederateInfo (const std::string &fedname, const std::string &coretype)
void setFederateName (const std::string &name)
void setCoreName (const std::string &corename)
void setCoreInitString (const std::string &coreInit)
void setCoreTypeFromString (const std::string &coretype)
void setCoreType (int coretype)
void setFlag (int flag, int value)
void setOutputDelay (helics_time_t outputDelay)
void setTimeDelta (helics_time_t timeDelta)
void setInputDelay (helics_time_t inputDelay)
void setTimeOffset (helics_time_t timeOffset)
void setPeriod (helics_time_t period)
void setMaxIterations (int max_iterations)
void setLoggingLevel (int logLevel)
helics_federate_info_t getInfo ()
Public Attributes
std::string name
federate name
bool rollback = false
indicator that the federate has rollback features
bool forwardCompute = false
char separator = '/'
separator for global name of localFederates
core_type coreType
the type of the core
std::string coreName
the name of the core
std::string coreInitString
an initialization string for the core API object
Public Attributes inherited from helics::CoreFederateInfo
Time timeDelta = timeEpsilon
Time outputDelay
Time inputDelay
the time it takes values and messages to propagate to be accessible to the Federate
Time period = timeZero
a period value, all granted times must be on this period n*Period+offset
Time offset = timeZero
offset to the time period
bool observer = false
flag indicating that the federate is an observer
bool uninterruptible
flag indicating that the federate should never return a time other than requested
bool source_only
flag indicating that the federate does not receive or do anything with received information.
bool only_transmit_on_change
flag indicating that values should only updated if the number has actually changes
bool only_update_on_change
flag indicating values should be discarded if they are not changed from previous values
bool wait_for_current_time_updates = false
int16_t maxIterations = 50
the maximum number of iterations allowed for the federate
int32_t logLevel = 1
the logging level above which not to log to file
Detailed Description
data class defining federate properties and information
Constructor & Destructor Documentation
FederateInfo() [1/4]
helics::FederateInfo::FederateInfo () default
default constructor
FederateInfo() [2/4]
helics::FederateInfo::FederateInfo (std::string fedname) inline
construct from the federate name
FederateInfo() [3/4]
helics::FederateInfo::FederateInfo (std::string fedname, core_type cType) inline
construct from the name and type
FederateInfo() [4/4]
helics::FederateInfo::FederateInfo (int argc, const char *const * argv)
load a federateInfo object from command line arguments
Parameters
argc the number of arguments
argv an array of char * pointers to the arguments
Member Function Documentation
loadInfoFromArgs()
void helics::FederateInfo::loadInfoFromArgs (int argc, const char *const * argv)
load a federateInfo object from command line arguments
Parameters
argc the number of arguments
argv an array of char * pointers to the arguments
References helics::argumentParser(), helics::coreTypeFromString(), helics::versionReturn(), and helics::versionString.
Referenced by helics::apps::App::App(), and helicsFederateInfoLoadFromArgs().
Member Data Documentation
forwardCompute
bool helics::FederateInfo::forwardCompute = false
indicator that the federate does computation ahead of the timing call[must support rollback at least in a limited sense if set to true]
Referenced by helics::loadFederateInfo(), and helics::Federate::setFlag().
The documentation for this class was generated from the following files:
application_api/Federate.hpp
FederateInfo.cpp