helics: helics::CommonCore Class Reference
helics::CommonCore Class Reference abstract
#include <CommonCore.hpp>
Public Member Functions
CommonCore () noexcept
CommonCore (bool arg) noexcept
CommonCore (const std::string &core_name)
virtual ~CommonCore () override
virtual void initialize (const std::string &initializationString) override final
virtual void initializeFromArgs (int argc, const char *const *argv) override
virtual bool isInitialized () const override final
virtual bool isOpenToNewFederates () const override final
virtual void error (federate_id_t federateID, int errorCode=-1) override final
virtual void finalize (federate_id_t federateID) override final
virtual void enterInitializingState (federate_id_t federateID) override final
virtual void setCoreReadyToInit () override final
virtual iteration_result enterExecutingState (federate_id_t federateID, iteration_request iterate=NO_ITERATION) override final
virtual federate_id_t registerFederate (const std::string &name, const CoreFederateInfo &info) override final
virtual const std::string & getFederateName (federate_id_t federateID) const override final
virtual federate_id_t getFederateId (const std::string &name) override final
virtual int32_t getFederationSize () override final
virtual Time timeRequest (federate_id_t federateID, Time next) override final
virtual iteration_time requestTimeIterative (federate_id_t federateID, Time next, iteration_request iterate) override final
virtual Time getCurrentTime (federate_id_t federateID) const override final
virtual uint64_t getCurrentReiteration (federate_id_t federateID) const override final
virtual void setMaximumIterations (federate_id_t federateID, int32_t iterations) override final
virtual void setTimeDelta (federate_id_t federateID, Time time) override final
virtual void setOutputDelay (federate_id_t federateID, Time outputDelayTime) override final
virtual void setPeriod (federate_id_t federateID, Time timePeriod) override final
virtual void setTimeOffset (federate_id_t federateID, Time timeOffset) override final
virtual void setInputDelay (federate_id_t federateID, Time inputDelayTime) override final
virtual void setLoggingLevel (federate_id_t federateID, int loggingLevel) override final
virtual void setFlag (federate_id_t federateID, int flag, bool flagValue=true) override final
virtual handle_id_t registerSubscription (federate_id_t federateID, const std::string &key, const std::string &type, const std::string &units, handle_check_mode check_mode) override final
virtual handle_id_t getSubscription (federate_id_t federateID, const std::string &key) const override final
virtual handle_id_t registerPublication (federate_id_t federateID, const std::string &key, const std::string &type, const std::string &units) override final
virtual handle_id_t getPublication (federate_id_t federateID, const std::string &key) const override final
virtual const std::string & getHandleName (handle_id_t handle) const override final
virtual const std::string & getTarget (handle_id_t handle) const override final
virtual const std::string & getUnits (handle_id_t handle) const override final
virtual const std::string & getType (handle_id_t handle) const override final
virtual const std::string & getOutputType (handle_id_t handle) const override final
virtual void setValue (handle_id_t handle, const char *data, uint64_t len) override final
virtual std::shared_ptr< const data_block > getValue (handle_id_t handle) override final
virtual const std::vector< handle_id_t > & getValueUpdates (federate_id_t federateID) override final
virtual handle_id_t registerEndpoint (federate_id_t federateID, const std::string &name, const std::string &type) override final
virtual handle_id_t getEndpoint (federate_id_t federateID, const std::string &name) const override final
virtual handle_id_t registerSourceFilter (const std::string &filterName, const std::string &source, const std::string &type_in, const std::string &type_out) override final
virtual handle_id_t registerDestinationFilter (const std::string &filterName, const std::string &dest, const std::string &type_in, const std::string &type_out) override final
virtual handle_id_t registerCloningSourceFilter (const std::string &filterName, const std::string &source, const std::string &type_in, const std::string &type_out) override final
virtual handle_id_t registerCloningDestinationFilter (const std::string &filterName, const std::string &dest, const std::string &type_in, const std::string &type_out) override final
virtual handle_id_t getSourceFilter (const std::string &name) const override final
virtual handle_id_t getDestinationFilter (const std::string &name) const override final
virtual void addDependency (federate_id_t federateID, const std::string &federateName) override final
virtual void registerFrequentCommunicationsPair (const std::string &source, const std::string &dest) override final
virtual void send (handle_id_t sourceHandle, const std::string &destination, const char *data, uint64_t length) override final
virtual void sendEvent (Time time, handle_id_t sourceHandle, const std::string &destination, const char *data, uint64_t length) override final
virtual void sendMessage (handle_id_t sourceHandle, std::unique_ptr< Message > message) override final
virtual uint64_t receiveCount (handle_id_t destination) override final
virtual std::unique_ptr< Message > receive (handle_id_t destination) override final
virtual std::unique_ptr< Message > receiveAny (federate_id_t federateID, handle_id_t &endpoint_id) override final
virtual uint64_t receiveCountAny (federate_id_t federateID) override final
virtual void logMessage (federate_id_t federateID, int logLevel, const std::string &messageToLog) override final
virtual void setFilterOperator (handle_id_t filter, std::shared_ptr< FilterOperator > callback) override final
void setIdentifier (const std::string &name)
const std::string & getIdentifier () const override final
const std::string & getFederateNameNoThrow (federate_id_t federateID) const noexcept
virtual void setLoggingCallback (federate_id_t federateID, std::function< void(int, const std::string &, const std::string &)> logFunction) override final
virtual std::string query (const std::string &target, const std::string &queryStr) override
virtual void setQueryCallback (federate_id_t federateID, std::function< std::string(const std::string &)> queryFunction) override
virtual std::string getAddress () const =0
virtual bool connect () override final
virtual bool isConnected () const override final
virtual void disconnect () override final
void unregister ()
virtual void processDisconnect (bool skipUnregister=false) override final
Public Member Functions inherited from helics::Core
Core ()=default
virtual ~Core ()=default
virtual handle_id_t registerSubscription (federate_id_t federateID, const std::string &key, const std::string &(type), const std::string &units, handle_check_mode check_mode)=0
Core (const std::string &type, const std::string &name, const std::string &initString)
Core (const std::string &type, const std::string &name, int argc, const char **argv)
operator helics_core ()
helics_core baseObject () const
bool isConnected () const
Core (const Core &cr)
Core & operator= (const Core &cr)
void setReadyToInit ()
void disconnect ()
std::string getIdentifier () const
Filter registerSourceFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
Filter registerDestinationFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
CloningFilter registerCloningFilter (const std::string &deliveryEndpoint)
Public Member Functions inherited from helics::BrokerBase
BrokerBase (const std::string &broker_name)
virtual void initializeFromCmdArgs (int argc, const char *const *argv)
void addActionMessage (const ActionMessage &m)
void addActionMessage (ActionMessage &&m)
void setLoggerFunction (std::function< void(int, const std::string &, const std::string &)> logFunction)
bool isRunning () const
void setLogLevel (int32_t level)
void setLogLevels (int32_t consoleLevel, int32_t fileLevel)
void joinAllThreads ()
Protected Member Functions
virtual void processCommand (ActionMessage &&cmd) override final
virtual void processPriorityCommand (ActionMessage &&command) override final
virtual void transmit (int route_id, const ActionMessage &cmd)=0
virtual void addRoute (int route_id, const std::string &routeInfo)=0
FederateState * getFederateAt (federate_id_t federateID) const
FederateState * getFederate (const std::string &federateName) const
FederateState * getHandleFederate (handle_id_t id_)
BasicHandleInfo * getHandleInfo (handle_id_t id_) const
BasicHandleInfo * getLocalEndpoint (const std::string &name)
FilterCoordinator * getFilterCoordinator (handle_id_t id_)
bool allInitReady () const
bool allDisconnected () const
virtual bool sendToLogger (federate_id_t federateID, int logLevel, const std::string &name, const std::string &message) const override
void deliverMessage (ActionMessage &message)
ActionMessage & processMessage (ActionMessage &m)
BasicHandleInfo * createBasicHandle (federate_id_t global_federateId, federate_id_t local_federateId, handle_type_t HandleType, const std::string &key, const std::string &type, const std::string &units, bool required)
BasicHandleInfo * createBasicHandle (federate_id_t global_federateId, federate_id_t local_federateId, handle_type_t HandleType, const std::string &key, const std::string &target, const std::string &type_in, const std::string &type_out)
bool isLocal (Core::federate_id_t global_id) const
int32_t getRoute (Core::federate_id_t global_id) const
void processFilterInfo (ActionMessage &command)
void organizeFilterOperations ()
std::string federateQuery (Core::federate_id_t federateID, const std::string &queryStr) const
void sendErrorToFederates (int error_code)
Protected Member Functions inherited from helics::BrokerBase
virtual bool tryReconnect ()=0
void generateNewIdentifier ()
Additional Inherited Members
Public Types inherited from helics::Core
using federate_id_t = int32_t
using handle_id_t = int32_t
Static Public Member Functions inherited from helics::BrokerBase
static void displayHelp ()
Protected Types inherited from helics::BrokerBase
enum broker_state_t : int16_t {
created = -5, initialized = -4, connecting = -3, connected = -2,
initializing = -1, operating = 0, terminating = 1, terminated = 3,
errored = 7
}
Protected Attributes inherited from helics::Core
helics_core core
Protected Attributes inherited from helics::BrokerBase
std::atomic< Core::federate_id_t > global_broker_id
the unique identifier for the broker(core or broker)
Core::federate_id_t higher_broker_id = 0
the id code of the broker 1 level about this broker
std::atomic< int32_t > maxLogLevel {1}
the logging level to use levels >=this will be logged
int32_t consoleLogLevel = 1
the logging level for console display
int32_t fileLogLevel = 1
the logging level for logging to a file
int32_t minFederateCount = 1
the minimum number of federates that must connect before entering init mode
int32_t minBrokerCount = 0
the minimum number of brokers that must connect before entering init mode
int32_t maxIterationCount = 10000
the maximum number of iterative loops that are allowed
int32_t tickTimer = 4000
counter for the length of a keep alive tick in milliseconds
int32_t timeout
timeout to wait to establish a broker connection before giving up in milliseconds
std::string identifier
an identifier for the broker
std::unique_ptr< Logger > loggingObj
default logging object to use if the logging callback is not specified
std::thread _queue_processing_thread
thread for running the broker
std::function< void(int, const std::string &, const std::string &)> loggerFunction
std::atomic< bool > haltOperations {false}
flag indicating that no further message should be processed
std::string logFile
std::unique_ptr< ForwardingTimeCoordinator > timeCoord
object managing the time control
BlockingPriorityQueue< ActionMessage > actionQueue
primary routing queue
std::atomic< broker_state_t > brokerState {created}
bool noAutomaticID = false
bool hasTimeDependency = false
set to true if the broker has Time dependencies
bool enteredExecutionMode = false
flag indicating that the broker has entered execution mode
bool waitingForServerPingReply = false
flag indicating we are waiting for a ping reply
bool hasFilters = false
flag indicating filters come through the broker
Detailed Description
base class implementing a standard interaction strategy between federates
the CommonCore is virtual class that manages local federates and handles most of the interaction between federate it is meant to be instantiated for specific inter-federate communication strategies
Constructor & Destructor Documentation
CommonCore() [1/3]
helics::CommonCore::CommonCore () noexcept
default constructor
CommonCore() [2/3]
helics::CommonCore::CommonCore (bool arg) explicit noexcept
function mainly to match some other object constructors does the same thing as the default constructor
CommonCore() [3/3]
helics::CommonCore::CommonCore (const std::string & core_name) explicit
construct from a core name
~CommonCore()
helics::CommonCore::~CommonCore () override virtual
virtual destructor
References helics::BrokerBase::joinAllThreads().
Member Function Documentation
addDependency()
void helics::CommonCore::addDependency (federate_id_t federateID, const std::string & federateName) final override virtual
add a time dependency between federates
this function is primarily useful for Message federates which do not otherwise restrict the dependencies adding a dependency gives additional information to the core that the specified federate(given by id) will be sending Messages to the named Federate(by federateName)
Parameters
[in] federateID the identifier for the federate
[in] federateName the name of the dependent federate
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), getFederateAt(), helics::ActionMessage::name, and helics::ActionMessage::source_id.
addRoute()
virtual void helics::CommonCore::addRoute (int route_id, const std::string & routeInfo) protected pure virtual
add a route to whatever internal structure manages the routes
Parameters
route_id the identification of the route
routeInfo a string containing the information necessary to connect
Implemented in helics::testcore::TestCore.
allDisconnected()
bool helics::CommonCore::allDisconnected () const protected
check if all federates have said good-bye
References helics::HELICS_ERROR, and helics::HELICS_FINISHED.
allInitReady()
bool helics::CommonCore::allInitReady () const protected
check if all federates managed by the core are ready to enter initialization state
References helics::BrokerBase::minFederateCount.
Referenced by query().
connect()
bool helics::CommonCore::connect () final override virtual
connect the core to a broker if needed
Returns
true if the connection was successful
Implements helics::Core.
References helics::BrokerBase::brokerState, getAddress(), getIdentifier(), helics::ActionMessage::info(), isConnected(), helics::ActionMessage::name, helics::ActionMessage::AdditionalInfo::target, and transmit().
createBasicHandle() [1/2]
BasicHandleInfo * helics::CommonCore::createBasicHandle (federate_id_t global_federateId, federate_id_t local_federateId, handle_type_t HandleType, const std::string & key, const std::string & type, const std::string & units, bool required) protected
add a new handle to the generic structure and return a pointer to it, the pointer is non-owning
References helics::HandlePointerManager::addHandle(), helics::BasicHandleInfo::local_fed_id, and helics::required.
Referenced by registerCloningDestinationFilter(), registerCloningSourceFilter(), registerDestinationFilter(), registerEndpoint(), and registerSourceFilter().
createBasicHandle() [2/2]
BasicHandleInfo * helics::CommonCore::createBasicHandle (federate_id_t global_federateId, federate_id_t local_federateId, handle_type_t HandleType, const std::string & key, const std::string & target, const std::string & type_in, const std::string & type_out) protected
add a new handle to the generic structure and return a pointer to it the pointer is non owning variation targeted at filters
References helics::HandlePointerManager::addHandle(), and helics::BasicHandleInfo::local_fed_id.
deliverMessage()
void helics::CommonCore::deliverMessage (ActionMessage & message) protected
deliver a message to the appropriate location
References helics::ActionMessage::action(), helics::createMessageFromCommand(), helics::ActionMessage::dest_handle, helics::ActionMessage::dest_id, getFilterCoordinator(), getLocalEndpoint(), getRoute(), helics::BrokerBase::global_broker_id, helics::ActionMessage::index, helics::ActionMessage::info(), helics::ActionMessage::moveInfo(), helics::ActionMessage::setAction(), helics::ActionMessage::source_handle, helics::ActionMessage::source_id, helics::ActionMessage::AdditionalInfo::target, and transmit().
disconnect()
void helics::CommonCore::disconnect () final override virtual
disconnect the core from its broker
Implements helics::Core.
References processDisconnect().
enterExecutingState()
iteration_result helics::CommonCore::enterExecutingState (federate_id_t federateID, iteration_request iterate = NO_ITERATION) final override virtual
Change the federate state to the Executing state.
May only be invoked in Initializing state.
Parameters
[in] federateID the identifier of the federate
[in] iterationCompleted if true no more iterations on this federate are requested if nonconverged the federate requests an iterative update
Returns
nonconverged if the executing state has not been entered and there are updates, complete if the simulation is ready to move on to the executing state
Implements helics::Core.
References getFederateAt(), helics::HELICS_EXECUTING, helics::HELICS_INITIALIZING, and helics::next_step.
enterInitializingState()
void helics::CommonCore::enterInitializingState (federate_id_t federateID) final override virtual
Federates may be in three states.
Federates are in three states.
Startup Configuration of the federate. State begins when registerFederate() is invoked and ends when enterInitializingState() is invoked.
Initializing Configure of the simulation state prior to the start of time stepping. State begins when enterInitializingState() is invoked and ends when enterExecutingState(true) is invoked.
Executing State begins when enterExecutingState() is invoked and ends when Finalize() is invoked. Change the federate state to the Initializing state.
May only be invoked in Created state otherwise an error is thrown
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), getFederateAt(), helics::HELICS_INITIALIZING, helics::next_step, and helics::ActionMessage::source_id.
error()
void helics::CommonCore::error (federate_id_t federateID, int errorCode = -1) final override virtual
Federate has encountered an unrecoverable error.
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), helics::error, getFederateAt(), helics::halted, helics::next_step, helics::ActionMessage::source_handle, and helics::ActionMessage::source_id.
federateQuery()
std::string helics::CommonCore::federateQuery (Core::federate_id_t federateID, const std::string & queryStr) const protected
generate a query response of a federate if possible
Parameters
federateID the identifier for the federate to query
queryStr the string containing the actual query
References getFederateAt().
Referenced by query().
finalize()
void helics::CommonCore::finalize (federate_id_t federateID) final override virtual
Federate has completed.
Should be invoked a single time to complete the simulation.
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), helics::ActionMessage::dest_id, helics::error, getFederateAt(), helics::halted, helics::next_step, and helics::ActionMessage::source_id.
getAddress()
virtual std::string helics::CommonCore::getAddress () const pure virtual
get a string representing the connection info to send data to this object
Implemented in helics::testcore::TestCore, helics::zeromq::ZmqCore, helics::ipc::IpcCore, helics::mpi::MpiCore, helics::tcp::TcpCore, and helics::udp::UdpCore.
Referenced by connect().
getCurrentReiteration()
uint64_t helics::CommonCore::getCurrentReiteration (federate_id_t federateID) const final override virtual
Returns the current reiteration count for the specified federate.
Implements helics::Core.
References getFederateAt().
getCurrentTime()
Time helics::CommonCore::getCurrentTime (federate_id_t federateID) const final override virtual
get the most recent granted Time
Parameters
federateID,the id of the federate to get the time
Returns
the most recent granted time or the startup time
Implements helics::Core.
References getFederateAt().
getDestinationFilter()
handle_id_t helics::CommonCore::getDestinationFilter (const std::string & name) const final override virtual
get a destination filter Handle from its name or target(this may not be unique so it will only find the first one)
Parameters
name the name of the filter or its target
Returns
a handle to identify the filter
Implements helics::Core.
getEndpoint()
handle_id_t helics::CommonCore::getEndpoint (federate_id_t federateID, const std::string & name) const final override virtual
get a endpoint Handle from its name or target(this may not be unique so it will only find the first one)
Parameters
federateID the identifier for the federate
name the name of the endpoint
Returns
a handle to identify the endpoint
Implements helics::Core.
References getFederateAt().
getFederate()
FederateState * helics::CommonCore::getFederate (const std::string & federateName) const protected
get the federate Information from the federateID
getFederateAt()
FederateState * helics::CommonCore::getFederateAt (federate_id_t federateID) const protected
get the federate Information from the federateID
Referenced by addDependency(), enterExecutingState(), enterInitializingState(), error(), federateQuery(), finalize(), getCurrentReiteration(), getCurrentTime(), getEndpoint(), getFederateName(), getPublication(), getSubscription(), getValueUpdates(), logMessage(), receiveAny(), receiveCountAny(), registerEndpoint(), registerPublication(), requestTimeIterative(), sendToLogger(), setFlag(), setInputDelay(), setLoggingCallback(), setLoggingLevel(), setMaximumIterations(), setOutputDelay(), setPeriod(), setQueryCallback(), setTimeDelta(), setTimeOffset(), and timeRequest().
getFederateId()
federate_id_t helics::CommonCore::getFederateId (const std::string & name) final override virtual
Returns the federate Id.
Implements helics::Core.
Referenced by query().
getFederateName()
const std::string & helics::CommonCore::getFederateName (federate_id_t federateID) const final override virtual
Returns the federate name.
Implements helics::Core.
References getFederateAt().
getFederationSize()
int32_t helics::CommonCore::getFederationSize () final override virtual
Returns the global number of federates that are registered only return accurately after the initialization state has been entered
Implements helics::Core.
References helics::BrokerBase::brokerState, and helics::BrokerBase::operating.
getFilterCoordinator()
FilterCoordinator * helics::CommonCore::getFilterCoordinator (handle_id_t id_) protected
get a filtering function object
References helics::BrokerBase::brokerState, and helics::BrokerBase::operating.
Referenced by deliverMessage(), processFilterInfo(), and processMessage().
getHandleFederate()
FederateState * helics::CommonCore::getHandleFederate (handle_id_t id_) protected
get the federate Information from a handle
Parameters
id a handle identifier as generated by the one of the functions
References helics::BrokerBase::brokerState, and helics::BrokerBase::operating.
Referenced by receive(), and receiveCount().
getHandleInfo()
BasicHandleInfo * helics::CommonCore::getHandleInfo (handle_id_t id_) const protected
get the basic handle information
References helics::BrokerBase::brokerState, and helics::BrokerBase::operating.
Referenced by getHandleName(), getOutputType(), getTarget(), getType(), getUnits(), getValue(), organizeFilterOperations(), processFilterInfo(), processMessage(), send(), sendEvent(), sendMessage(), setFilterOperator(), and setValue().
getHandleName()
const std::string & helics::CommonCore::getHandleName (handle_id_t handle) const final override virtual
Returns the name or identifier for a specified handle
Implements helics::Core.
References getHandleInfo().
getIdentifier()
const std::string& helics::CommonCore::getIdentifier () const inline final override virtual
get the local identifier for the core
Implements helics::Core.
Referenced by connect(), logMessage(), processDisconnect(), and query().
getLocalEndpoint()
BasicHandleInfo * helics::CommonCore::getLocalEndpoint (const std::string & name) protected
get a localEndpoint from the name
References helics::BrokerBase::brokerState, and helics::BrokerBase::operating.
Referenced by deliverMessage().
getOutputType()
const std::string & helics::CommonCore::getOutputType (handle_id_t handle) const final override virtual
Returns output type for specified handle.
for filters this is the outputType, for Subscriptions this is the expected type for endpoints and publications this is the same as getType();
Parameters
handle the handle from the publication, subscription, endpoint or filter
Implements helics::Core.
References getHandleInfo().
getPublication()
handle_id_t helics::CommonCore::getPublication (federate_id_t federateID, const std::string & key) const final override virtual
get a publication Handle from its key
Parameters
federateID the identifier for the federate the name of the publication
Returns
a handle to identify the publication
Implements helics::Core.
References getFederateAt().
getRoute()
int32_t helics::CommonCore::getRoute (Core::federate_id_t global_id) const protected
get a route id for a non-local federate
Parameters
[in] global_id the federate global id
Returns
0 if unknown, otherwise returns the route_id
Referenced by deliverMessage().
getSourceFilter()
handle_id_t helics::CommonCore::getSourceFilter (const std::string & name) const final override virtual
get a source filter Handle from its name or target(this may not be unique so it will only find the first one)
Parameters
name the name of the filter or its target
Returns
a handle to identify the filter
Implements helics::Core.
getSubscription()
handle_id_t helics::CommonCore::getSubscription (federate_id_t federateID, const std::string & key) const final override virtual
get a subscription Handle from its key
Parameters
federateID the identifier for the federate the tag of the subscription
Returns
a handle to identify the subscription
Implements helics::Core.
References getFederateAt().
getTarget()
const std::string & helics::CommonCore::getTarget (handle_id_t handle) const final override virtual
Returns the target of a specified handle
for publications and subscriptions this is the key for filters this is the target and for endpoints this will return an empty string
Implements helics::Core.
References getHandleInfo().
getType()
const std::string & helics::CommonCore::getType (handle_id_t handle) const final override virtual
Returns type for specified handle.
for endpoints, publications, and filters, this is the input type for subscriptions this is the type of the publication(if available)
Parameters
handle the handle from the publication, subscription, endpoint or filter
Implements helics::Core.
References getHandleInfo().
getUnits()
const std::string & helics::CommonCore::getUnits (handle_id_t handle) const final override virtual
Returns units for specified handle.
Implements helics::Core.
References getHandleInfo().
getValue()
std::shared_ptr< const data_block > helics::CommonCore::getValue (handle_id_t handle) final override virtual
Return the data for the specified handle.
Implements helics::Core.
References getHandleInfo().
getValueUpdates()
const std::vector< handle_id_t > & helics::CommonCore::getValueUpdates (federate_id_t federateID) final override virtual
Returns vector of subscription handles that received an update during the last time request. The data remains valid until the next call to getValueUpdates for the given federateID
Parameters
federateID the identification code of the federate to query
Returns
a reference to the location of an array of handles that have been updated
Implements helics::Core.
References getFederateAt().
initialize()
void helics::CommonCore::initialize (const std::string & initializationString) final override virtual
Simulator control. Initialize the core.
Should be invoked a single time to initialize the co-simulation core.
Implements helics::Core.
References helics::BrokerBase::brokerState, helics::BrokerBase::created, StringToCmdLine::getArgCount(), StringToCmdLine::getArgV(), and initializeFromArgs().
initializeFromArgs()
void helics::CommonCore::initializeFromArgs (int argc, const char *const * argv) override virtual
initialize the core manager with command line arguments
Parameters
[in] argc the number of arguments
[in] argv char pointers to the arguments
Implements helics::Core.
Reimplemented in helics::testcore::TestCore, helics::zeromq::ZmqCore, helics::ipc::IpcCore, helics::mpi::MpiCore, helics::tcp::TcpCore, and helics::udp::UdpCore.
References helics::BrokerBase::brokerState, helics::BrokerBase::created, and helics::BrokerBase::initializeFromCmdArgs().
Referenced by initialize(), helics::udp::UdpCore::initializeFromArgs(), helics::tcp::TcpCore::initializeFromArgs(), helics::mpi::MpiCore::initializeFromArgs(), helics::ipc::IpcCore::initializeFromArgs(), helics::zeromq::ZmqCore::initializeFromArgs(), and helics::testcore::TestCore::initializeFromArgs().
isConnected()
bool helics::CommonCore::isConnected () const final override virtual
check if the core is connected properly
Implements helics::Core.
References helics::BrokerBase::brokerState, helics::BrokerBase::connected, and helics::BrokerBase::operating.
Referenced by connect().
isInitialized()
bool helics::CommonCore::isInitialized () const final override virtual
Returns true if the core has been initialized.
Implements helics::Core.
References helics::BrokerBase::brokerState, and helics::BrokerBase::initialized.
isLocal()
bool helics::CommonCore::isLocal (Core::federate_id_t global_id) const protected
check if a global id represents a local federate
Parameters
[in] global_id the federate global id
Returns
true if it is a local federate
isOpenToNewFederates()
bool helics::CommonCore::isOpenToNewFederates () const final override virtual
check if the core is ready to accept new federates
Implements helics::Core.
References helics::BrokerBase::brokerState, helics::BrokerBase::created, and helics::BrokerBase::operating.
logMessage()
void helics::CommonCore::logMessage (federate_id_t federateID, int logLevel, const std::string & messageToLog) final override virtual
send a log message to the Core for logging
Parameters
[in] federateID the federate that is sending the log message
[in] logLevel an integer for the log level (0- error, 1- warning, 2-status, 3-debug)
[in] messageToLog
Implements helics::Core.
References helics::BrokerBase::actionQueue, getFederateAt(), getIdentifier(), helics::ActionMessage::index, helics::ActionMessage::payload, sendToLogger(), and helics::ActionMessage::source_id.
organizeFilterOperations()
void helics::CommonCore::organizeFilterOperations () protected
organize filters organize the filter and report and potential warnings and errors
References getHandleInfo().
processCommand()
void helics::CommonCore::processCommand (ActionMessage && cmd) final override protected virtual
process a single command action
cmd may be modified by this function
Implements helics::BrokerBase.
processDisconnect()
void helics::CommonCore::processDisconnect (bool skipUnregister = false) final override virtual
process a disconnect signal
Implements helics::BrokerBase.
References helics::BrokerBase::addActionMessage(), helics::BrokerBase::brokerState, getIdentifier(), helics::BrokerBase::global_broker_id, helics::ActionMessage::payload, helics::ActionMessage::source_id, helics::BrokerBase::terminated, transmit(), and unregister().
Referenced by disconnect().
processFilterInfo()
void helics::CommonCore::processFilterInfo (ActionMessage & command) protected
process a message for potential additions to the filter ordering
Parameters
command the message to process
References helics::ActionMessage::action(), helics::checkActionFlag(), helics::clone_flag, helics::ActionMessage::dest_handle, helics::ActionMessage::dest_id, getFilterCoordinator(), getHandleInfo(), helics::ActionMessage::payload, helics::ActionMessage::source_handle, and helics::ActionMessage::source_id.
processMessage()
ActionMessage & helics::CommonCore::processMessage (ActionMessage & m) protected
function to deal with a source filters
References helics::clone_flag, helics::ActionMessage::counter, helics::createMessageFromCommand(), helics::ActionMessage::dest_handle, helics::ActionMessage::dest_id, getFilterCoordinator(), getHandleInfo(), helics::BrokerBase::global_broker_id, helics::ActionMessage::info(), helics::ActionMessage::setAction(), helics::setActionFlag(), and helics::ActionMessage::source_handle.
processPriorityCommand()
void helics::CommonCore::processPriorityCommand (ActionMessage && command) final override protected virtual
function to process a priority command independent of the main queue called when processing a priority command. The priority command has a response message which gets sent this mainly deals with some of the registration functions
Parameters
[in] command the command to process
Returns
a action message response to the priority command
Implements helics::BrokerBase.
query()
std::string helics::CommonCore::query (const std::string & target, const std::string & queryStr) override virtual
make a query for information from the co-simulation
the format is somewhat unspecified target is the name of an object typically one of "federation", "broker", "core", or the name of a specific object query is a broken
Parameters
target the specific target of the query
queryStr the actual query
Returns
a string containing the response to the query. Query is a blocking call and will not return until the query is answered so use with caution
Implements helics::Core.
References allInitReady(), federateQuery(), getFederateId(), getIdentifier(), helics::BrokerBase::global_broker_id, helics::ActionMessage::index, helics::ActionMessage::info(), helics::ActionMessage::payload, helics::ActionMessage::source_id, helics::ActionMessage::AdditionalInfo::target, and transmit().
receive()
std::unique_ptr< Message > helics::CommonCore::receive (handle_id_t destination) final override virtual
Returns the next buffered message the specified destination endpoint or filter.
this is a non-blocking call and will return a nullptr if no message are available
Implements helics::Core.
References getHandleFederate(), and helics::HELICS_EXECUTING.
receiveAny()
std::unique_ptr< Message > helics::CommonCore::receiveAny (federate_id_t federateID, handle_id_t & enpoint_id) final override virtual
Receives a message for any destination.
this is a non-blocking call and will return a nullptr if no messages are available
Parameters
federateID the identifier for the federate
[out] endpoint_id the endpoint handle related to the message gets stored here
Implements helics::Core.
References getFederateAt(), and helics::HELICS_EXECUTING.
receiveCount()
uint64_t helics::CommonCore::receiveCount (handle_id_t destination) final override virtual
Returns the number of pending receives for the specified destination endpoint or filter.
Implements helics::Core.
References getHandleFederate().
receiveCountAny()
uint64_t helics::CommonCore::receiveCountAny (federate_id_t federateID) final override virtual
Returns number of messages for all destinations.
Implements helics::Core.
References getFederateAt(), and helics::HELICS_EXECUTING.
registerCloningDestinationFilter()
handle_id_t helics::CommonCore::registerCloningDestinationFilter (const std::string & filterName, const std::string & dest, const std::string & type_in, const std::string & type_out) final override virtual
Register a cloning destination filter.
a destination filter will create an additional processing step of messages before they get to a destination endpoint, a destination may have multiple cloning filters but only one non-cloning filter
May only be invoked in the Initialization state.
Parameters
filterName the name of the filter (may be left blank)
dest the target endpoint for the filter
type_in the input type of the filter (may be left blank, this is for error checking and will produce a warning if it doesn't match with the input type of the target endpoint
Returns
the handle for the new filter
Implements helics::Core.
References helics::BrokerBase::brokerState, createBasicHandle(), helics::destination_filter, helics::BrokerBase::global_broker_id, and helics::BrokerBase::operating.
registerCloningSourceFilter()
handle_id_t helics::CommonCore::registerCloningSourceFilter (const std::string & filterName, const std::string & source, const std::string & type_in, const std::string & type_out) final override virtual
Register a cloning source filter, a cloning filter operates on a copy of the message vs the actual message
Parameters
filterName the name of the filter (may be left blank and one will be automatically assigned)
source the target endpoint for the filter
type_in the input type of the filter
type_out the output type of the filter (may be left blank if the filter doesn't change type)
Returns
the handle for the new filter
Implements helics::Core.
References helics::BrokerBase::brokerState, createBasicHandle(), helics::BrokerBase::global_broker_id, helics::BrokerBase::operating, and helics::source_filter.
registerDestinationFilter()
handle_id_t helics::CommonCore::registerDestinationFilter (const std::string & filterName, const std::string & dest, const std::string & type_in, const std::string & type_out) final override virtual
Register destination filter.
a destination filter will create an additional processing step of messages before they get to a destination endpoint
May only be invoked in the Initialization state.
Parameters
filterName the name of the filter (may be left blank)
dest the target endpoint for the filter
type_in the input type of the filter (may be left blank, this is for error checking and will produce a warning if it doesn't match with the input type of the target endpoint
Returns
the handle for the new filter
Implements helics::Core.
References helics::BrokerBase::brokerState, createBasicHandle(), helics::destination_filter, helics::BrokerBase::global_broker_id, and helics::BrokerBase::operating.
registerEndpoint()
handle_id_t helics::CommonCore::registerEndpoint (federate_id_t federateID, const std::string & name, const std::string & type) final override virtual
Message interface. Designed for point-to-point communication patterns. Register an endpoint.
May only be invoked in the Initialization state.
Implements helics::Core.
References createBasicHandle(), and getFederateAt().
registerFederate()
federate_id_t helics::CommonCore::registerFederate (const std::string & name, const CoreFederateInfo & info) final override virtual
Register a federate.
The returned FederateId is local to invoking process, FederateId's should not be used as a global identifier.
May only be invoked in initialize state otherwise throws an error
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), helics::BrokerBase::brokerState, helics::BrokerBase::created, helics::FederateState::lastErrorString(), helics::FederateState::local_id, helics::ActionMessage::name, helics::next_step, helics::BrokerBase::operating, sendToLogger(), helics::FederateState::setLogger(), helics::FederateState::setParent(), and helics::FederateState::waitSetup().
registerFrequentCommunicationsPair()
void helics::CommonCore::registerFrequentCommunicationsPair (const std::string & source, const std::string & dest) final override virtual
Register known frequently communicating source/destination end points.
May be used for error checking for compatible types and possible optimization by pre-registering the intent for these endpoints to communicate.
Implements helics::Core.
registerPublication()
handle_id_t helics::CommonCore::registerPublication (federate_id_t federateID, const std::string & key, const std::string & type, const std::string & units) final override virtual
Register a publication.
May only be invoked in the initialize state.
Parameters
federateID the identifier for the federate
key the tag for the publication
type the type of data the publication produces
units the units associated with the publication
Returns
a handle to identify the publication
Implements helics::Core.
References getFederateAt().
registerSourceFilter()
handle_id_t helics::CommonCore::registerSourceFilter (const std::string & filterName, const std::string & source, const std::string & type_in, const std::string & type_out) final override virtual
Register source filter.
May only be invoked in the Initialization state.
Parameters
filterName the name of the filter (may be left blank and one will be automatically assigned)
source the target endpoint for the filter
type_in the input type of the filter
type_out the output type of the filter (may be left blank if the filter doesn't change type) this is important for ordering in filters with operators
Returns
the handle for the new filter
Implements helics::Core.
References helics::BrokerBase::brokerState, createBasicHandle(), helics::BrokerBase::global_broker_id, helics::BrokerBase::operating, and helics::source_filter.
requestTimeIterative()
iteration_time helics::CommonCore::requestTimeIterative (federate_id_t federateID, Time next, iteration_request iterate) final override virtual
Request a new time advancement window for reiterative federates.
Reiterative federates block on requestTimeIterative() until all reiterative federates have invoked requestTimeIterative(). The bool returned a global AND of all localConverged values. If globalConverged is false, time returned is the previous granted time. Time should not advance and another iteration attempted. Federates should recompute state based on newly published values. Time is advanced only when all reiterative federates have converged. If globalConverged is True, grantedTime is the minimum of over all next times in both reiterative and non-reiterative federates.
If a federate determines it cannot converge it should invoke the error() method.
Federates only participate it in reiterations for times that are evenly divisible by the federates time delta.
May only be invoked in Executing state.
Non-reiterative federates may not invoke this method.
Parameters
federateID the identifier for the federate to process
next the requested time
localConverged has the local federate converged
Returns
an iteration_time object with two field grantedTime and a enumeration indicating the state of the iteration
Implements helics::Core.
References getFederateAt(), helics::HELICS_EXECUTING, helics::iterate_if_needed, helics::BrokerBase::maxIterationCount, and helics::no_iterations.
send()
void helics::CommonCore::send (handle_id_t sourceHandle, const std::string & destination, const char * data, uint64_t length) final override virtual
Send data from source to destination.
Time is implicitly defined as the end of the current time advancement window (value returned by last call to nextTime().
This send version was designed to enable communication of data between federates with the possible introduction of source and destination filters to represent properties of a communication network. This enables simulations to be run with/without a communications model present.
Implements helics::Core.
References getHandleInfo().
sendErrorToFederates()
void helics::CommonCore::sendErrorToFederates (int error_code) protected
send an error code to all the federates
References helics::ActionMessage::index.
sendEvent()
void helics::CommonCore::sendEvent (Time time, handle_id_t sourceHandle, const std::string & destination, const char * data, uint64_t length) final override virtual
Send data from source to destination with explicit expected delivery time.
Time supplied is the time that will be reported in the message in the receiving federate.
This send version was designed to enable communication of events between discrete event federates. For this use case the receiving federate can deserialize the data and schedule an event for the specified time.
Parameters
time the time the event is scheduled for
sourceHandle the source of the event
destination the target of the event
data the raw data for the event
length the record length of the event
Implements helics::Core.
References getHandleInfo().
sendMessage()
void helics::CommonCore::sendMessage (handle_id_t sourceHandle, std::unique_ptr< Message > message) final override virtual
Send for filters.
Continues sending the message to the next filter or to final destination.
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), helics::direct_send_handle, getHandleInfo(), helics::BrokerBase::global_broker_id, helics::ActionMessage::source_handle, and helics::ActionMessage::source_id.
sendToLogger()
bool helics::CommonCore::sendToLogger (federate_id_t federateID, int logLevel, const std::string & name, const std::string & message) const override protected virtual
send a Message to the logging system
Returns
true if the message was actually logged
Reimplemented from helics::BrokerBase.
References getFederateAt(), and helics::BrokerBase::sendToLogger().
Referenced by logMessage(), and registerFederate().
setCoreReadyToInit()
void helics::CommonCore::setCoreReadyToInit () final override virtual
set the core to ready to enter init
this function only needs to be called for cores that don't have any federates but may have filters for cores with federates it won't do anything
Implements helics::Core.
References ENABLE_INIT_ENTRY, and setFlag().
setFilterOperator()
void helics::CommonCore::setFilterOperator (handle_id_t filter, std::shared_ptr< FilterOperator > callback) final override virtual
set the filter callback operator
Parameters
[in] filter the handle of the filter
[in] operator pointer to the operator class executing the filter
Implements helics::Core.
References getHandleInfo().
setFlag()
void helics::CommonCore::setFlag (federate_id_t federateID, int flag, bool flagValue = true) final override virtual
Set a flag in a a federate
Parameters
federateID the identifier for the federate
flag an index code for the flag to set
flagValue the value to set the flag to
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), DELAY_INIT_ENTRY, helics::ActionMessage::dest_id, ENABLE_INIT_ENTRY, getFederateAt(), helics::ActionMessage::index, helics::indicator_flag, and helics::setActionFlag().
Referenced by setCoreReadyToInit().
setIdentifier()
void helics::CommonCore::setIdentifier (const std::string & name)
set the local identification for the core
References helics::BrokerBase::brokerState, helics::BrokerBase::created, and helics::BrokerBase::identifier.
setInputDelay()
void helics::CommonCore::setInputDelay (federate_id_t federateID, Time timeImpact) final override virtual
Set the inputDelay time.
The value is used to determine the interaction amongst various federates as to when a specific federate can influence another
Parameters
federateID the identifier for the federate
timeImpact the length of time it take outside message to propagate into a federate
Implements helics::Core.
References helics::ActionMessage::actionTime, getFederateAt(), and helics::ActionMessage::index.
setLoggingCallback()
void helics::CommonCore::setLoggingCallback (federate_id_t federateID, std::function< void(int, const std::string &, const std::string &)> logFunction) final override virtual
define a logging function to use for logging message and notices from the federation and individual federate
Parameters
federateID the identifier for the individual federate or 0 for the Core Logger
logFunction the callback function for doing something with a log message it takes 3 inputs an integer for logLevel 0-4+ 0 -error, 1- warning 2-status, 3-debug 44trace A string indicating the source of the message and another string with the actual message
Implements helics::Core.
References getFederateAt(), and helics::BrokerBase::setLoggerFunction().
setLoggingLevel()
void helics::CommonCore::setLoggingLevel (federate_id_t federateID, int loggingLevel) final override virtual
Set the logging level
set the logging level for an individual federate set federateID to 0 for the core logging level
Parameters
federateID the identifier for the federate
loggingLevel the level of logging to enable <0-no logging, 0 -error only, 1- warnings, 2-normal, 3-debug, 4-trace
Implements helics::Core.
References helics::BrokerBase::addActionMessage(), helics::ActionMessage::dest_id, getFederateAt(), and helics::ActionMessage::index.
setMaximumIterations()
void helics::CommonCore::setMaximumIterations (federate_id_t federateID, int32_t iterations) final override virtual
Set the maximum number of iterations allowed.
The minimum value set in any federate is used.
Default value is the maximum allowed value for uint64_t.
May only be invoked in the initialize state.
Implements helics::Core.
References helics::ActionMessage::dest_id, getFederateAt(), and helics::ActionMessage::index.
setOutputDelay()
void helics::CommonCore::setOutputDelay (federate_id_t federateID, Time timeoutputDelay) final override virtual
Set the outputDelay time for the specified federate.
The value is used to determine the interaction amongst various federates as to when a specific federate can influence another
Parameters
federateID the identifier for the federate
timeoutputDelay
Implements helics::Core.
References helics::ActionMessage::actionTime, getFederateAt(), and helics::ActionMessage::index.
setPeriod()
void helics::CommonCore::setPeriod (federate_id_t federateID, Time timePeriod) final override virtual
Set the period for a specified federate.
The value is used to determine the interaction amongst various federates as to when a specific federate can influence another
Parameters
federateID the identifier for the federate
timeoutputDelay
Implements helics::Core.
References helics::ActionMessage::actionTime, getFederateAt(), and helics::ActionMessage::index.
setQueryCallback()
void helics::CommonCore::setQueryCallback (federate_id_t federateID, std::function< std::string(const std::string &)> queryFunction) override virtual
supply a query callback function
the intention of the query callback is to allow federates to answer particular requests through the query interface this allows other federates to make requests or queries of other federates in an asynchronous fashion.
Parameters
federateID the identifier for the federate
queryFunction a function object that returns a string as a result of a query in the form of const string ref. This callback will be called when a federate received a query that cannot be answered that directed at a particular federate
Implements helics::Core.
References getFederateAt().
setTimeDelta()
void helics::CommonCore::setTimeDelta (federate_id_t federateID, Time time) final override virtual
Set the minimum time resolution for the specified federate.
The value is used to constrain when the timeRequest methods return to values that are multiples of the specified delta. This is useful for federates that are time-stepped and making sub-time-step updates is not meaningful.
Parameters
time
Implements helics::Core.
References helics::ActionMessage::actionTime, getFederateAt(), and helics::ActionMessage::index.
setTimeOffset()
void helics::CommonCore::setTimeOffset (federate_id_t federateID, Time timeOffset) final override virtual
Set the periodic offset for a specified federate.
The value is used as a time shift for calculating the allowable time in a federate the granted time must one of N*period+offset
Parameters
federateID the identifier for the federate
timeOffset the periodic phase shift
Implements helics::Core.
References helics::ActionMessage::actionTime, getFederateAt(), and helics::ActionMessage::index.
setValue()
void helics::CommonCore::setValue (handle_id_t handle, const char * data, uint64_t len) final override virtual
Publish specified data to the specified key.
Parameters
handle a handle to a publication to use for the value
[in] data the raw data to send
len the size of the data
Implements helics::Core.
References getHandleInfo().
timeRequest()
Time helics::CommonCore::timeRequest (federate_id_t federateID, Time next) final override virtual
Time management. Request a new time advancement window for non-reiterative federates.
RequestTime() blocks until all non-reiterative federates have invoked requestTime() and all reiterative federates have converged (called requestTimeIterative() with localConverged value of true). Return time is the minimum of all supplied times.
May only be invoked in Executing state.
Iterative federates may not invoke this method.
Parameters
next
Implements helics::Core.
References helics::error, getFederateAt(), helics::HELICS_EXECUTING, and helics::no_iterations.
transmit()
virtual void helics::CommonCore::transmit (int route_id, const ActionMessage & cmd) protected pure virtual
transit an ActionMessage to another core or broker
Parameters
route_id the identifier for the route information to send the message to
[in] cmd the actionMessage to send
Implemented in helics::testcore::TestCore.
Referenced by connect(), deliverMessage(), processDisconnect(), and query().
unregister()
void helics::CommonCore::unregister ()
unregister the core from any process find functions
References helics::CoreFactory::findCore(), helics::BrokerBase::identifier, and helics::CoreFactory::unregisterCore().
Referenced by processDisconnect().
The documentation for this class was generated from the following files:
CommonCore.hpp
CommonCore.cpp