helics: helics::BrokerBase Class Reference
helics::BrokerBase Class Reference abstract
#include <BrokerBase.hpp>
Public Member Functions
BrokerBase (const std::string &broker_name)
virtual void initializeFromCmdArgs (int argc, const char *const *argv)
void addActionMessage (const ActionMessage &m)
void addActionMessage (ActionMessage &&m)
void setLoggerFunction (std::function< void(int, const std::string &, const std::string &)> logFunction)
virtual void processDisconnect (bool skipUnregister=false)=0
bool isRunning () const
void setLogLevel (int32_t level)
void setLogLevels (int32_t consoleLevel, int32_t fileLevel)
void joinAllThreads ()
Static Public Member Functions
static void displayHelp ()
Protected Types
enum broker_state_t : int16_t {
created = -5, initialized = -4, connecting = -3, connected = -2,
initializing = -1, operating = 0, terminating = 1, terminated = 3,
errored = 7
}
Protected Member Functions
virtual bool tryReconnect ()=0
virtual void processCommand (ActionMessage &&cmd)=0
virtual void processPriorityCommand (ActionMessage &&command)=0
virtual bool sendToLogger (Core::federate_id_t federateID, int logLevel, const std::string &name, const std::string &message) const
void generateNewIdentifier ()
Protected Attributes
std::atomic< Core::federate_id_t > global_broker_id
the unique identifier for the broker(core or broker)
Core::federate_id_t higher_broker_id = 0
the id code of the broker 1 level about this broker
std::atomic< int32_t > maxLogLevel {1}
the logging level to use levels >=this will be logged
int32_t consoleLogLevel = 1
the logging level for console display
int32_t fileLogLevel = 1
the logging level for logging to a file
int32_t minFederateCount = 1
the minimum number of federates that must connect before entering init mode
int32_t minBrokerCount = 0
the minimum number of brokers that must connect before entering init mode
int32_t maxIterationCount = 10000
the maximum number of iterative loops that are allowed
int32_t tickTimer = 4000
counter for the length of a keep alive tick in milliseconds
int32_t timeout
timeout to wait to establish a broker connection before giving up in milliseconds
std::string identifier
an identifier for the broker
std::unique_ptr< Logger > loggingObj
default logging object to use if the logging callback is not specified
std::thread _queue_processing_thread
thread for running the broker
std::function< void(int, const std::string &, const std::string &)> loggerFunction
std::atomic< bool > haltOperations {false}
flag indicating that no further message should be processed
std::string logFile
std::unique_ptr< ForwardingTimeCoordinator > timeCoord
object managing the time control
BlockingPriorityQueue< ActionMessage > actionQueue
primary routing queue
std::atomic< broker_state_t > brokerState {created}
bool noAutomaticID = false
bool hasTimeDependency = false
set to true if the broker has Time dependencies
bool enteredExecutionMode = false
flag indicating that the broker has entered execution mode
bool waitingForServerPingReply = false
flag indicating we are waiting for a ping reply
bool hasFilters = false
flag indicating filters come through the broker
Detailed Description
base class for broker like objects
Member Enumeration Documentation
broker_state_t
enum helics::BrokerBase::broker_state_t : int16_t protected
enumeration of the possible core states
Enumerator
created
the broker has been created
initialized
the broker itself has been initialized and is ready to connect
connecting
the connection process has started
connected
the connection process has completed
initializing
the enter initialization process has started
operating
normal operating conditions
terminating
the termination process has started
terminated
the termination process has started
errored
an error was encountered
Member Function Documentation
addActionMessage() [1/2]
void helics::BrokerBase::addActionMessage (const ActionMessage & m)
add an action Message to the process queue
References actionQueue, and helics::isPriorityCommand().
Referenced by helics::CommonCore::addDependency(), helics::CommonCore::enterInitializingState(), helics::CommonCore::error(), helics::CommonCore::finalize(), helics::CommonCore::processDisconnect(), helics::CommonCore::registerFederate(), helics::FederateState::routeMessage(), helics::CommonCore::sendMessage(), helics::CommonCore::setFlag(), and helics::CommonCore::setLoggingLevel().
addActionMessage() [2/2]
void helics::BrokerBase::addActionMessage (ActionMessage && m)
move a action Message into the commandQueue
References actionQueue, and helics::isPriorityCommand().
displayHelp()
void helics::BrokerBase::displayHelp () static
display help messages for the broker
References helics::argumentParser().
Referenced by helics::CoreBroker::displayHelp().
generateNewIdentifier()
void helics::BrokerBase::generateNewIdentifier () protected
generate a new random id based on a uuid
References identifier.
initializeFromCmdArgs()
void helics::BrokerBase::initializeFromCmdArgs (int argc, const char *const * argv) virtual
initialize the core manager with command line arguments
Parameters
[in] argc the number of arguments
[in] argv char pointers to the arguments
References helics::argumentParser(), identifier, maxIterationCount, maxLogLevel, minBrokerCount, and minFederateCount.
Referenced by helics::CommonCore::initializeFromArgs(), and helics::CoreBroker::initializeFromArgs().
isRunning()
bool helics::BrokerBase::isRunning () const inline
check if the main processing loop of a broker is running
joinAllThreads()
void helics::BrokerBase::joinAllThreads ()
close all the threads
References _queue_processing_thread, and actionQueue.
Referenced by helics::CommonCore::~CommonCore().
processCommand()
virtual void helics::BrokerBase::processCommand (ActionMessage && cmd) protected pure virtual
process a single command action
cmd may be modified by this function
Implemented in helics::CommonCore.
processDisconnect()
virtual void helics::BrokerBase::processDisconnect (bool skipUnregister = false) pure virtual
process a disconnect signal
Implemented in helics::CommonCore, and helics::CoreBroker.
processPriorityCommand()
virtual void helics::BrokerBase::processPriorityCommand (ActionMessage && command) protected pure virtual
function to process a priority command independent of the main queue called when processing a priority command. The priority command has a response message which gets sent this mainly deals with some of the registration functions
Parameters
[in] command the command to process
Returns
a action message response to the priority command
Implemented in helics::CommonCore.
sendToLogger()
bool helics::BrokerBase::sendToLogger (Core::federate_id_t federateID, int logLevel, const std::string & name, const std::string & message) const protected virtual
send a Message to the logging system
Returns
true if the message was actually logged
Reimplemented in helics::CommonCore.
References global_broker_id, loggerFunction, loggingObj, and maxLogLevel.
Referenced by helics::CommonCore::sendToLogger().
setLoggerFunction()
void helics::BrokerBase::setLoggerFunction (std::function< void(int, const std::string &, const std::string &)> logFunction)
set the logging callback function
Parameters
logFunction a function with a signature of void(int level, const std::string &source, const std::string &message) the function takes a level indicating the logging level string with the source name and a string with the message
References loggerFunction, and loggingObj.
Referenced by helics::CoreBroker::setLoggingCallback(), and helics::CommonCore::setLoggingCallback().
setLogLevel()
void helics::BrokerBase::setLogLevel (int32_t level)
set the logging level
References setLogLevels().
setLogLevels()
void helics::BrokerBase::setLogLevels (int32_t consoleLevel, int32_t fileLevel)
set the logging levels
Parameters
consoleLevel the logging level for the console display
fileLevel the logging level for the log file
References consoleLogLevel, fileLogLevel, loggingObj, and maxLogLevel.
Referenced by setLogLevel().
tryReconnect()
bool helics::BrokerBase::tryReconnect () protected pure virtual
in the case of connection failure with a broker this function will try a reconnect procedure
Implemented in helics::testcore::TestBroker.
Member Data Documentation
brokerState
std::atomic<broker_state_t> helics::BrokerBase::brokerState {created} protected
flag indicating that the structure is past the initialization stage indicating that no more changes can be made to the number of federates or handles
Referenced by helics::CoreBroker::connect(), helics::CommonCore::connect(), helics::CommonCore::getFederationSize(), helics::CommonCore::getFilterCoordinator(), helics::CommonCore::getHandleFederate(), helics::CommonCore::getHandleInfo(), helics::CommonCore::getLocalEndpoint(), helics::CommonCore::initialize(), helics::CoreBroker::initialize(), helics::udp::UdpCore::initializeFromArgs(), helics::tcp::TcpCore::initializeFromArgs(), helics::ipc::IpcBroker::initializeFromArgs(), helics::ipc::IpcCore::initializeFromArgs(), helics::udp::UdpBroker::initializeFromArgs(), helics::tcp::TcpBroker::initializeFromArgs(), helics::zeromq::ZmqCore::initializeFromArgs(), helics::zeromq::ZmqBroker::initializeFromArgs(), helics::CommonCore::initializeFromArgs(), helics::CoreBroker::initializeFromArgs(), helics::CoreBroker::isConnected(), helics::CommonCore::isConnected(), helics::CommonCore::isInitialized(), helics::CommonCore::isOpenToNewFederates(), helics::CommonCore::processDisconnect(), helics::CommonCore::registerCloningDestinationFilter(), helics::CommonCore::registerCloningSourceFilter(), helics::CommonCore::registerDestinationFilter(), helics::CommonCore::registerFederate(), helics::CommonCore::registerSourceFilter(), helics::CoreBroker::setAsRoot(), and helics::CommonCore::setIdentifier().
global_broker_id
std::atomic<Core::federate_id_t> helics::BrokerBase::global_broker_id protected
Initial value:
{
      0}
the unique identifier for the broker(core or broker)
Referenced by helics::CommonCore::deliverMessage(), helics::CommonCore::processDisconnect(), helics::CommonCore::processMessage(), helics::CommonCore::query(), helics::CommonCore::registerCloningDestinationFilter(), helics::CommonCore::registerCloningSourceFilter(), helics::CommonCore::registerDestinationFilter(), helics::CommonCore::registerSourceFilter(), helics::CommonCore::sendMessage(), sendToLogger(), and helics::CoreBroker::setAsRoot().
loggerFunction
std::function<void(int, const std::string &, const std::string &)> helics::BrokerBase::loggerFunction protected
a logging function for logging or printing messages
Referenced by sendToLogger(), and setLoggerFunction().
timeout
int32_t helics::BrokerBase::timeout protected
Initial value:
=
      30000
timeout to wait to establish a broker connection before giving up in milliseconds
The documentation for this class was generated from the following files:
BrokerBase.hpp
BrokerBase.cpp