helics: helics::apps::SignalGenerator Class Reference
helics::apps::SignalGenerator Class Reference abstract
Public Member Functions
virtual void set (const std::string &parameter, double val)
virtual void setString (const std::string &parameter, const std::string &val)
virtual defV generate (Time signalTime)=0
void setTime (Time indexTime)
Protected Attributes
Time lastTime = timeZero
Time keyTime = timeZero
Member Function Documentation
generate()
virtual defV helics::apps::SignalGenerator::generate (Time signalTime) pure virtual
generate a new value at time signalTime
Returns
a value and a defV object
Implemented in helics::apps::PhasorGenerator, helics::apps::SineGenerator, and helics::apps::RampGenerator.
set()
void helics::apps::SignalGenerator::set (const std::string & parameter, double val) virtual
set a numerical parameter
Reimplemented in helics::apps::PhasorGenerator, helics::apps::SineGenerator, and helics::apps::RampGenerator.
Referenced by helics::apps::RampGenerator::set(), helics::apps::SineGenerator::set(), and helics::apps::PhasorGenerator::set().
setString()
void helics::apps::SignalGenerator::setString (const std::string & parameter, const std::string & val) virtual
set a string parameter
Reimplemented in helics::apps::PhasorGenerator.
Referenced by helics::apps::PhasorGenerator::setString().
setTime()
void helics::apps::SignalGenerator::setTime (Time indexTime) inline
set the key time
The documentation for this class was generated from the following files:
Source.hpp
Source.cpp