helics: helics::data_view Class Reference
helics::data_view Class Reference
#include <data_view.hpp>
Public Member Functions
data_view () noexcept
data_view (std::shared_ptr< const data_block > dt)
data_view (const data_block &dt) noexcept
data_view (const data_view &dt) noexcept=default
data_view (data_view &&dv) noexcept
data_view (const char *dt) noexcept
data_view (const char *dt, size_t len) noexcept
data_view (const std::string &str) noexcept
data_view (std::string &&str)
data_view (const std::vector< char > &dvec) noexcept
data_view (const stx::string_view &sview) noexcept
data_view & operator= (const data_view &dv) noexcept
data_view & operator= (data_view &&dv) noexcept
data_view & operator= (std::shared_ptr< const data_block > dt) noexcept
data_view & operator= (const data_block &dt) noexcept
data_view & operator= (const stx::string_view &str) noexcept
data_view & operator= (const char *s) noexcept
data_block to_data_block () const
void swap (data_view &dv2) noexcept
const char * data () const noexcept
size_t size () const noexcept
bool empty () const noexcept
std::string string () const
char operator[] (int index) const
auto begin ()
auto end ()
auto cbegin () const
auto cend () const
Detailed Description
class containing a constant view of data block
Constructor & Destructor Documentation
data_view() [1/11]
helics::data_view::data_view () inline noexcept
default constructor
data_view() [2/11]
helics::data_view::data_view (std::shared_ptr< const data_block > dt) inline
construct from a shared_ptr to a data_block
data_view() [3/11]
helics::data_view::data_view (const data_block & dt) inline noexcept
construct from a regular data_block
data_view() [4/11]
helics::data_view::data_view (const data_view & dt) default noexcept
copy constructor
data_view() [5/11]
helics::data_view::data_view (data_view && dv) inline noexcept
move constructor
data_view() [6/11]
helics::data_view::data_view (const char * dt) inline noexcept
construct from a string
data_view() [7/11]
helics::data_view::data_view (const char * dt, size_t len) inline noexcept
construct from a char Pointer and length
data_view() [8/11]
helics::data_view::data_view (const std::string & str) inline noexcept
construct from a string
data_view() [9/11]
helics::data_view::data_view (std::string && str) inline
construct from a rValue to a string
data_view() [10/11]
helics::data_view::data_view (const std::vector< char > & dvec) inline noexcept
construct from a char vector
data_view() [11/11]
helics::data_view::data_view (const stx::string_view & sview) inline noexcept
construct from a string_view
Member Function Documentation
begin()
auto helics::data_view::begin () inline
begin iterator
cbegin()
auto helics::data_view::cbegin () const inline
begin const iterator
cend()
auto helics::data_view::cend () const inline
end const iterator
data()
const char* helics::data_view::data () const inline noexcept
get the data block
Referenced by helics::ValueConverter< X >::interpret(), helics::ValueFederateManager::publish(), and helics::ValueFederateManager::setDefaultValue().
empty()
bool helics::data_view::empty () const inline noexcept
check if the view is empty
end()
auto helics::data_view::end () inline
end iterator
operator=() [1/5]
data_view& helics::data_view::operator= (const data_view & dv) inline noexcept
assignment operator from another ata_view
operator=() [2/5]
data_view& helics::data_view::operator= (std::shared_ptr< const data_block > dt) inline noexcept
assignment from a data_block shared_ptr
operator=() [3/5]
data_view& helics::data_view::operator= (const data_block & dt) inline noexcept
assignment from a data_block
operator=() [4/5]
data_view& helics::data_view::operator= (const stx::string_view & str) inline noexcept
assignment from a string_view
operator=() [5/5]
data_view& helics::data_view::operator= (const char * s) inline noexcept
assignment from a const char *
operator[]()
char helics::data_view::operator[] (int index) const inline
random access operator
size()
size_t helics::data_view::size () const inline noexcept
get the length
Referenced by helics::ValueConverter< X >::interpret(), helics::ValueFederateManager::publish(), and helics::ValueFederateManager::setDefaultValue().
string()
std::string helics::data_view::string () const inline
return a string of the data
this actually does a copy to a new string
swap()
void helics::data_view::swap (data_view & dv2) inline noexcept
swap function
to_data_block()
data_block helics::data_view::to_data_block () const inline
create a new data_block from the data
The documentation for this class was generated from the following file:
data_view.hpp