helics: helics::Filter Class Reference
helics::Filter Class Reference
#include <Filters.hpp>
Public Member Functions
Filter ()=default
Filter (Federate *fed)
Filter (Core *cr)
virtual ~Filter ()=default
void setOperator (std::shared_ptr< FilterOperator > mo)
filter_id_t getID () const
Core::handle_id_t getCoreHandle () const
const std::string & getTarget () const
const std::string & getName () const
const std::string & getInputType () const
const std::string & getOutputType () const
virtual void set (const std::string &property, double val)
virtual void setString (const std::string &property, const std::string &val)
Filter (helics_filter hfilt)
Filter (const Filter &filter)
Filter & operator= (const Filter &filter)
operator helics_filter () const
helics_filter baseObject () const
std::string getTarget () const
std::string getName () const
void set (const std::string &property, double val)
void setString (const std::string &property, const std::string &val)
Protected Member Functions
void setFilterOperations (std::shared_ptr< FilterOperations > filterOps)
Protected Attributes
Core * corePtr = nullptr
the Core to use
Core::handle_id_t id = invalid_handle
the id as generated by the Federate
filter_id_t fid = invalid_id_value
id for interacting with a federate
std::shared_ptr< FilterOperations > filtOp
a class running any specific operation of the Filter
helics_filter filt
the reference to the underlying publication
Friends
void addOperations (Filter *filt, defined_filter_types type, Core *cptr)
Detailed Description
class for managing a particular filter
Constructor & Destructor Documentation
Filter() [1/3]
helics::Filter::Filter () default
default constructor
Filter() [2/3]
helics::Filter::Filter (Federate * fed) explicit
construct through a federate
References corePtr, and helics::Federate::getCorePointer().
Filter() [3/3]
helics::Filter::Filter (Core * cr) explicit
construct through a core object
~Filter()
virtual helics::Filter::~Filter () virtual default
virtual destructor
Member Function Documentation
getCoreHandle()
Core::handle_id_t helics::Filter::getCoreHandle () const inline
get the underlying core handle for use with a core
References id.
getID()
filter_id_t helics::Filter::getID () const inline
get the underlying filter id for use with a federate
References fid.
getInputType()
const std::string & helics::Filter::getInputType () const
get the specified input type of the filter
References corePtr, and helics::Core::getType().
getName()
const std::string & helics::Filter::getName () const
get the name for the filter
References corePtr, and helics::Core::getHandleName().
Referenced by helics::CloningFilter::addDestinationTarget(), and helics::CloningFilter::addSourceTarget().
getOutputType()
const std::string & helics::Filter::getOutputType () const
get the specified output type of the filter
References corePtr, and helics::Core::getOutputType().
getTarget()
const std::string & helics::Filter::getTarget () const
get the target of the filter
References corePtr, and helics::Core::getTarget().
set()
void helics::Filter::set (const std::string & property, double val) virtual
set a property on a filter
Parameters
property the name of the property of the filter to change
val the numerical value of the property
References filtOp.
setFilterOperations()
void helics::Filter::setFilterOperations (std::shared_ptr< FilterOperations > filterOps) protected
set a filter operations object
References corePtr, filtOp, and helics::Core::setFilterOperator().
setOperator()
void helics::Filter::setOperator (std::shared_ptr< FilterOperator > mo)
set a message operator to process the message
References corePtr, and helics::Core::setFilterOperator().
setString()
void helics::Filter::setString (const std::string & property, const std::string & val) virtual
set a string property on a filter
Parameters
property the name of the property of the filter to change
val the numerical value of the property
Reimplemented in helics::CloningFilter.
References filtOp.
Referenced by helics::CloningFilter::addDeliveryEndpoint(), helics::CloningFilter::removeDeliveryEndpoint(), and helics::CloningFilter::setString().
The documentation for this class was generated from the following files:
Filters.hpp
Filter.hpp
Filters.cpp