helics: helics::TimeDependencies Class Reference
helics::TimeDependencies Class Reference
#include <TimeDependencies.hpp>
Public Member Functions
TimeDependencies ()=default
bool isDependency (Core::federate_id_t ofed) const
bool addDependency (Core::federate_id_t id)
void removeDependency (Core::federate_id_t id)
bool updateTime (const ActionMessage &m)
auto size () const
auto begin ()
auto end ()
auto begin () const
auto end () const
auto cbegin () const
auto cend () const
const DependencyInfo * getDependencyInfo (Core::federate_id_t id) const
DependencyInfo * getDependencyInfo (Core::federate_id_t id)
bool checkIfReadyForExecEntry (bool iterating) const
bool checkIfReadyForTimeGrant (bool iterating, Time desiredGrantTime) const
void resetIteratingExecRequests ()
void resetIteratingTimeRequests (Time requestTime)
bool hasActiveTimeDependencies () const
Detailed Description
class for managing a set of dependencies
Constructor & Destructor Documentation
TimeDependencies()
helics::TimeDependencies::TimeDependencies () default
default constructor
Member Function Documentation
addDependency()
bool helics::TimeDependencies::addDependency (Core::federate_id_t id)
insert a dependency into the structure
Returns
true if the dependency was added, false if it existed already
Referenced by helics::TimeCoordinator::addDependency().
begin() [1/2]
auto helics::TimeDependencies::begin () inline
iterator to first dependency
begin() [2/2]
auto helics::TimeDependencies::begin () const inline
const iterator to first dependency
cbegin()
auto helics::TimeDependencies::cbegin () const inline
const iterator to first dependency
cend()
auto helics::TimeDependencies::cend () const inline
const iterator to first dependency
checkIfReadyForExecEntry()
bool helics::TimeDependencies::checkIfReadyForExecEntry (bool iterating) const
check if the dependencies would allow entry to exec mode
References helics::iterating.
Referenced by helics::TimeCoordinator::checkExecEntry().
checkIfReadyForTimeGrant()
bool helics::TimeDependencies::checkIfReadyForTimeGrant (bool iterating, Time desiredGrantTime) const
check if the dependencies would allow a grant of the time
Parameters
iterating true if the object is iterating
desiredGrantTime the time to check for granting
Returns
true if the object is ready
References helics::iterating.
Referenced by helics::TimeCoordinator::checkTimeGrant().
end() [1/2]
auto helics::TimeDependencies::end () inline
iterator to end point
end() [2/2]
auto helics::TimeDependencies::end () const inline
const iterator to end point
getDependencyInfo() [1/2]
const DependencyInfo * helics::TimeDependencies::getDependencyInfo (Core::federate_id_t id) const
get a pointer to the dependency information for a particular object
Referenced by helics::TimeCoordinator::getDependencyInfo(), helics::TimeCoordinator::processTimeMessage(), and updateTime().
getDependencyInfo() [2/2]
DependencyInfo * helics::TimeDependencies::getDependencyInfo (Core::federate_id_t id)
get a pointer to the dependency information for a particular object
hasActiveTimeDependencies()
bool helics::TimeDependencies::hasActiveTimeDependencies () const
check if there are active dependencies
References helics::global_broker_id_shift, helics::global_federate_id_shift, and TimeRepresentation< Tconv >::maxVal().
Referenced by helics::TimeCoordinator::hasActiveTimeDependencies().
isDependency()
bool helics::TimeDependencies::isDependency (Core::federate_id_t ofed) const
return true if the given federate is already a member
Referenced by helics::TimeCoordinator::isDependency().
removeDependency()
void helics::TimeDependencies::removeDependency (Core::federate_id_t id)
remove dependency from consideration
Referenced by helics::TimeCoordinator::removeDependency().
resetIteratingExecRequests()
void helics::TimeDependencies::resetIteratingExecRequests ()
reset the iterative exec requests to prepare for the next iteration
Referenced by helics::TimeCoordinator::checkExecEntry().
resetIteratingTimeRequests()
void helics::TimeDependencies::resetIteratingTimeRequests (helics::Time requestTime)
reset iterative time requests to prepare for next iteration
Parameters
requestTime the time that is being iterated
size()
auto helics::TimeDependencies::size () const inline
get the number of dependencies
Referenced by helics::TimeCoordinator::getDependencies().
updateTime()
bool helics::TimeDependencies::updateTime (const ActionMessage & m)
update the info about a dependency based on a message
References helics::ActionMessage::action(), helics::ActionMessage::dest_id, getDependencyInfo(), helics::DependencyInfo::ProcessMessage(), and helics::ActionMessage::source_id.
Referenced by helics::TimeCoordinator::processTimeMessage().
The documentation for this class was generated from the following files:
TimeDependencies.hpp
TimeDependencies.cpp