helics: TimeRepresentation< Tconv > Class Template Reference
TimeRepresentation< Tconv > Class Template Reference
#include <timeRepresentation.hpp>
Public Types
using baseType = typename Tconv::baseType
Public Member Functions
TimeRepresentation () noexcept
constexpr TimeRepresentation (double t) noexcept
CHRONO_CONSTEXPR TimeRepresentation (std::chrono::nanoseconds nsTime) noexcept
constexpr TimeRepresentation (std::int64_t count, timeUnits units) noexcept
constexpr TimeRepresentation (const TimeRepresentation &x) noexcept=default
constexpr std::int64_t seconds () const noexcept
std::int64_t toCount (timeUnits units) const noexcept
TimeRepresentation & operator= (const TimeRepresentation &x) noexcept=default
TimeRepresentation & operator= (double t) noexcept
operator std::chrono::nanoseconds ()
constexpr operator double () const noexcept
TimeRepresentation & operator+= (const TimeRepresentation &rhs) noexcept
TimeRepresentation & operator-= (const TimeRepresentation &rhs) noexcept
TimeRepresentation & operator*= (int multiplier) noexcept
TimeRepresentation & operator*= (double multiplier) noexcept
TimeRepresentation & operator/= (int divisor) noexcept
TimeRepresentation & operator/= (double divisor) noexcept
TimeRepresentation operator% (const TimeRepresentation &other) const noexcept
TimeRepresentation & operator%= (const TimeRepresentation &other) noexcept
constexpr TimeRepresentation operator- () const noexcept
constexpr TimeRepresentation operator+ (const TimeRepresentation &other) const noexcept
constexpr TimeRepresentation operator- (const TimeRepresentation &other) const noexcept
constexpr TimeRepresentation operator* (int multiplier) const noexcept
constexpr TimeRepresentation operator/ (int divisor) const noexcept
constexpr TimeRepresentation operator* (double multiplier) const noexcept
constexpr TimeRepresentation operator/ (double divisor) const noexcept
bool operator== (const TimeRepresentation &rhs) const noexcept
bool operator!= (const TimeRepresentation &rhs) const noexcept
bool operator> (const TimeRepresentation &rhs) const noexcept
bool operator< (const TimeRepresentation &rhs) const noexcept
bool operator>= (const TimeRepresentation &rhs) const noexcept
bool operator<= (const TimeRepresentation &rhs) const noexcept
constexpr baseType getBaseTimeCode () const noexcept
void setBaseTimeCode (baseType timecodeval) noexcept
Static Public Member Functions
static constexpr TimeRepresentation maxVal () noexcept
static constexpr TimeRepresentation minVal () noexcept
static constexpr TimeRepresentation zeroVal () noexcept
static constexpr TimeRepresentation epsilon () noexcept
Detailed Description
template<class Tconv>
class TimeRepresentation< Tconv >
prototype class for representing time
time representation class that has as a template argument a class that can define time as a number and has some required features The debug version has a double included for debugging assistance and human readability, the release version removes the double calculations
Constructor & Destructor Documentation
TimeRepresentation() [1/2]
template<class Tconv> TimeRepresentation< Tconv >::TimeRepresentation () inline noexcept
default constructor
Referenced by TimeRepresentation< count_time< 9 > >::epsilon(), TimeRepresentation< count_time< 9 > >::maxVal(), TimeRepresentation< count_time< 9 > >::minVal(), and TimeRepresentation< count_time< 9 > >::zeroVal().
TimeRepresentation() [2/2]
template<class Tconv> constexpr TimeRepresentation< Tconv >::TimeRepresentation (double t) inline noexcept
normal time constructor from a double representation of seconds
Member Function Documentation
epsilon()
template<class Tconv> static constexpr TimeRepresentation TimeRepresentation< Tconv >::epsilon () inline static noexcept
generate a TimeRepresentation of 0
Referenced by helics::apps::Player::runTo().
getBaseTimeCode()
template<class Tconv> constexpr baseType TimeRepresentation< Tconv >::getBaseTimeCode () const inline noexcept
get the underlying time code value
maxVal()
template<class Tconv> static constexpr TimeRepresentation TimeRepresentation< Tconv >::maxVal () inline static noexcept
generate a TimeRepresentation of the maximum representative value
Referenced by helics::TimeCoordinator::checkTimeGrant(), helics::EndpointInfo::firstMessageTime(), helics::TimeDependencies::hasActiveTimeDependencies(), helics::apps::Source::initialize(), helics::SubscriptionInfo::nextValueTime(), helics::DependencyInfo::ProcessMessage(), helics::FederateState::receiveAny(), helics::apps::Player::runTo(), helics::apps::Source::runTo(), and helics::TimeCoordinator::updateTimeFactors().
minVal()
template<class Tconv> static constexpr TimeRepresentation TimeRepresentation< Tconv >::minVal () inline static noexcept
generate a TimeRepresentation of the minimum representative value
Referenced by loadJsonTime().
operator double()
template<class Tconv> constexpr TimeRepresentation< Tconv >::operator double () const inline noexcept
direct conversion to double static cast overload
operator std::chrono::nanoseconds()
template<class Tconv> TimeRepresentation< Tconv >::operator std::chrono::nanoseconds () inline
direct conversion to chrono nanoseconds
operator=() [1/2]
template<class Tconv> TimeRepresentation& TimeRepresentation< Tconv >::operator= (const TimeRepresentation< Tconv > & x) default noexcept
default copy operation
operator=() [2/2]
template<class Tconv> TimeRepresentation& TimeRepresentation< Tconv >::operator= (double t) inline noexcept
assignment operator from a double representation as seconds
seconds()
template<class Tconv> constexpr std::int64_t TimeRepresentation< Tconv >::seconds () const inline noexcept
generate the time in seconds
setBaseTimeCode()
template<class Tconv> void TimeRepresentation< Tconv >::setBaseTimeCode (baseType timecodeval) inline noexcept
set the underlying base representation of a time directly
this is not recommended for normal use
toCount()
template<class Tconv> std::int64_t TimeRepresentation< Tconv >::toCount (timeUnits units) const inline noexcept
convert to an integer 64 value
zeroVal()
template<class Tconv> static constexpr TimeRepresentation TimeRepresentation< Tconv >::zeroVal () inline static noexcept
generate a TimeRepresentation of 0
The documentation for this class was generated from the following file:
timeRepresentation.hpp