helics: helics::CoreBroker Class Reference
helics::CoreBroker Class Reference abstract
#include <CoreBroker.hpp>
Public Member Functions
virtual bool connect () override final
virtual void disconnect () override final
void unregister ()
virtual void processDisconnect (bool skipUnregister=false) override final
virtual bool isConnected () const override final
virtual void setAsRoot () override final
virtual bool isRoot () const override final
virtual bool isOpenToNewFederates () const override
virtual void setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> &logFunction) override final
CoreBroker (bool setAsRootBroker=false) noexcept
CoreBroker (const std::string &broker_name)
virtual ~CoreBroker ()
virtual void initialize (const std::string &initializationString) override final
virtual void initializeFromArgs (int argc, const char *const *argv) override
bool allInitReady () const
bool allDisconnected () const
void setIdentifier (const std::string &name)
virtual const std::string & getIdentifier () const override final
Public Member Functions inherited from helics::Broker
Broker ()=default
virtual ~Broker ()=default
virtual std::string getAddress () const =0
Broker (std::string type, std::string name, std::string initString)
Broker (std::string type, std::string name, int argc, const char **argv)
Broker (const Broker &brk)
Broker & operator= (const Broker &brk)
operator helics_broker ()
helics_broker baseObject () const
bool isConnected () const
void disconnect ()
std::string getIdentifier () const
std::string getAddress () const
Public Member Functions inherited from helics::BrokerBase
BrokerBase (const std::string &broker_name)
virtual void initializeFromCmdArgs (int argc, const char *const *argv)
void addActionMessage (const ActionMessage &m)
void addActionMessage (ActionMessage &&m)
void setLoggerFunction (std::function< void(int, const std::string &, const std::string &)> logFunction)
bool isRunning () const
void setLogLevel (int32_t level)
void setLogLevels (int32_t consoleLevel, int32_t fileLevel)
void joinAllThreads ()
Static Public Member Functions
static void displayHelp ()
Static Public Member Functions inherited from helics::BrokerBase
static void displayHelp ()
Protected Member Functions
virtual void transmit (int32_t route, const ActionMessage &command)=0
virtual void addRoute (int route_id, const std::string &routeInfo)=0
Protected Member Functions inherited from helics::BrokerBase
virtual bool tryReconnect ()=0
virtual bool sendToLogger (Core::federate_id_t federateID, int logLevel, const std::string &name, const std::string &message) const
void generateNewIdentifier ()
Protected Attributes
bool _gateway = false
set to true if this broker should act as a gateway.
Protected Attributes inherited from helics::Broker
helics_broker broker
Protected Attributes inherited from helics::BrokerBase
std::atomic< Core::federate_id_t > global_broker_id
the unique identifier for the broker(core or broker)
Core::federate_id_t higher_broker_id = 0
the id code of the broker 1 level about this broker
std::atomic< int32_t > maxLogLevel {1}
the logging level to use levels >=this will be logged
int32_t consoleLogLevel = 1
the logging level for console display
int32_t fileLogLevel = 1
the logging level for logging to a file
int32_t minFederateCount = 1
the minimum number of federates that must connect before entering init mode
int32_t minBrokerCount = 0
the minimum number of brokers that must connect before entering init mode
int32_t maxIterationCount = 10000
the maximum number of iterative loops that are allowed
int32_t tickTimer = 4000
counter for the length of a keep alive tick in milliseconds
int32_t timeout
timeout to wait to establish a broker connection before giving up in milliseconds
std::string identifier
an identifier for the broker
std::unique_ptr< Logger > loggingObj
default logging object to use if the logging callback is not specified
std::thread _queue_processing_thread
thread for running the broker
std::function< void(int, const std::string &, const std::string &)> loggerFunction
std::atomic< bool > haltOperations {false}
flag indicating that no further message should be processed
std::string logFile
std::unique_ptr< ForwardingTimeCoordinator > timeCoord
object managing the time control
BlockingPriorityQueue< ActionMessage > actionQueue
primary routing queue
std::atomic< broker_state_t > brokerState {created}
bool noAutomaticID = false
bool hasTimeDependency = false
set to true if the broker has Time dependencies
bool enteredExecutionMode = false
flag indicating that the broker has entered execution mode
bool waitingForServerPingReply = false
flag indicating we are waiting for a ping reply
bool hasFilters = false
flag indicating filters come through the broker
Additional Inherited Members
Protected Types inherited from helics::BrokerBase
enum broker_state_t : int16_t {
created = -5, initialized = -4, connecting = -3, connected = -2,
initializing = -1, operating = 0, terminating = 1, terminated = 3,
errored = 7
}
Detailed Description
class implementing most of the functionality of a generic broker Basically acts as a router for information, deals with stuff internally if it can and sends higher up if it can't or does something else if it is the root of the tree
Constructor & Destructor Documentation
CoreBroker() [1/2]
helics::CoreBroker::CoreBroker (bool setAsRootBroker = false) noexcept
default constructor
Parameters
setAsRootBroker set to true to indicate this object is a root broker
CoreBroker() [2/2]
helics::CoreBroker::CoreBroker (const std::string & broker_name)
constructor to set the name of the broker
~CoreBroker()
helics::CoreBroker::~CoreBroker () virtual
destructor
Member Function Documentation
addRoute()
virtual void helics::CoreBroker::addRoute (int route_id, const std::string & routeInfo) protected pure virtual
add a route to the type specific routing information and establish the connection
add a route to a table, the connection information is contained in the string with the described identifier
Parameters
[in] route_id the identifier for the route
[in] routeInfo a string describing the connection info
Implemented in helics::testcore::TestBroker.
allInitReady()
bool helics::CoreBroker::allInitReady () const
check if all the local federates are ready to be initialized
Returns
true if everyone is ready, false otherwise
References helics::BrokerBase::minBrokerCount, and helics::BrokerBase::minFederateCount.
connect()
bool helics::CoreBroker::connect () final override virtual
connect the core to its broker
should be done after initialization has complete
Implements helics::Broker.
References helics::BrokerBase::brokerState.
Referenced by helics::testcore::TestBroker::brokerConnect().
disconnect()
void helics::CoreBroker::disconnect () final override virtual
disconnect the broker from any other brokers and communications
Implements helics::Broker.
References processDisconnect().
displayHelp()
void helics::CoreBroker::displayHelp () static
display the help for command line arguments on the broker
References helics::argumentParser(), and helics::BrokerBase::displayHelp().
Referenced by helics::testcore::TestBroker::displayHelp(), and helics::BrokerFactory::displayHelp().
getIdentifier()
virtual const std::string& helics::CoreBroker::getIdentifier () const inline final override virtual
get the local identification for the broker
Implements helics::Broker.
References helics::BrokerBase::identifier.
Referenced by helics::ipc::IpcBroker::initializeFromArgs().
initialize()
void helics::CoreBroker::initialize (const std::string & initializationString) final override virtual
start up the broker with an initialization string containing commands and parameters
Implements helics::Broker.
References helics::BrokerBase::brokerState, StringToCmdLine::getArgCount(), StringToCmdLine::getArgV(), and initializeFromArgs().
initializeFromArgs()
void helics::CoreBroker::initializeFromArgs (int argc, const char *const * argv) override virtual
initialize from command line arguments
Implements helics::Broker.
Reimplemented in helics::zeromq::ZmqBroker, helics::tcp::TcpBroker, helics::udp::UdpBroker, helics::ipc::IpcBroker, helics::testcore::TestBroker, and helics::mpi::MpiBroker.
References helics::argumentParser(), helics::BrokerBase::brokerState, helics::BrokerBase::initializeFromCmdArgs(), and setAsRoot().
Referenced by initialize(), helics::mpi::MpiBroker::initializeFromArgs(), helics::ipc::IpcBroker::initializeFromArgs(), helics::testcore::TestBroker::initializeFromArgs(), helics::tcp::TcpBroker::initializeFromArgs(), helics::udp::UdpBroker::initializeFromArgs(), and helics::zeromq::ZmqBroker::initializeFromArgs().
isConnected()
bool helics::CoreBroker::isConnected () const final override virtual
check if the broker is connected
Implements helics::Broker.
References helics::BrokerBase::brokerState, helics::BrokerBase::connected, and helics::BrokerBase::operating.
isOpenToNewFederates()
bool helics::CoreBroker::isOpenToNewFederates () const override virtual
check if the broker is ready to accept new federates or cores
Implements helics::Broker.
isRoot()
virtual bool helics::CoreBroker::isRoot () const inline final override virtual
return true if the broker is a root broker
Implements helics::Broker.
processDisconnect()
void helics::CoreBroker::processDisconnect (bool skipUnregister = false) final override virtual
disconnect the broker from any other brokers and communications if the flag is set it should not do the unregister step of the disconnection, if this is set it is presumed the unregistration has already happened or it will be taken care of manually
Implements helics::BrokerBase.
Referenced by disconnect().
setAsRoot()
void helics::CoreBroker::setAsRoot () final override virtual
set the broker to be a root broker
only valid before the initialization function is called
Implements helics::Broker.
References helics::BrokerBase::brokerState, and helics::BrokerBase::global_broker_id.
Referenced by initializeFromArgs().
setIdentifier()
void helics::CoreBroker::setIdentifier (const std::string & name)
set the local identification string for the broker
Referenced by helics::ipc::IpcBroker::initializeFromArgs().
setLoggingCallback()
void helics::CoreBroker::setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> & logFunction) final override virtual
set the logging callback function
Parameters
logFunction a function with a signature of void(int level, const std::string &source, const std::string &message) the function takes a level indicating the logging level string with the source name and a string with the message
Implements helics::Broker.
References helics::BrokerBase::setLoggerFunction().
transmit()
virtual void helics::CoreBroker::transmit (int32_t route, const ActionMessage & command) protected pure virtual
this function is the one that will change for various flavors of broker communication
it takes a route info- a code of where to send the data and an action message and proceeds to transmit it to the appropriate location
Parameters
[in] route -the identifier for the routing information
[in] command the actionMessage to transmit
Implemented in helics::testcore::TestBroker.
unregister()
void helics::CoreBroker::unregister ()
unregister the broker from the factory find methods
References helics::BrokerFactory::findBroker(), helics::BrokerBase::identifier, and helics::BrokerFactory::unregisterBroker().
The documentation for this class was generated from the following files:
CoreBroker.hpp
CoreBroker.cpp