helics: helics::PublicationBase Class Reference
helics::PublicationBase Class Reference
Public Member Functions
template<class FedPtr >
PublicationBase (FedPtr valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
template<class FedPtr >
PublicationBase (interface_visibility locality, FedPtr valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
PublicationBase (ValueFederate *valueFed, int pubIndex)
virtual ~PublicationBase ()=default
publication_id_t getID () const
std::string getKey () const
const std::string & getName () const
const std::string & getType () const
const std::string & getUnits () const
Protected Attributes
ValueFederate * fed = nullptr
the federate construct to interact with
publication_id_t id
the internal id of the publication
Constructor & Destructor Documentation
PublicationBase() [1/3]
template<class FedPtr > helics::PublicationBase::PublicationBase (FedPtr valueFed, const std::string & key, const std::string & type, const std::string & units = std::string ()) inline
base constructor for a publication
Template Parameters
a valueFed a pointer of some kind to a value federate (any dereferencable type with * and -> operator that results in a valueFederate object
Parameters
key the identifier for the publication
type the type of the publication
units,an optional string defining the units
PublicationBase() [2/3]
template<class FedPtr > helics::PublicationBase::PublicationBase (interface_visibility locality, FedPtr valueFed, const std::string & key, const std::string & type, const std::string & units = std::string ()) inline
base constructor for a publication
Parameters
locality either GLOBAL or LOCAL, LOCAL prepends the federate name to create a global identifier
Template Parameters
valueFed a pointer of some kind to a value federate (any dereferencable type with * and -> operator that results in a valueFederate object
Parameters
key the identifier for the publication
type the type of the publication
units,an optional string defining the units
PublicationBase() [3/3]
helics::PublicationBase::PublicationBase (ValueFederate * valueFed, int pubIndex)
generate a publication object from an existing publication in a federate useful for creating publication objects from publications generated by a configuration script
References fed, helics::ValueFederate::getPublicationCount(), helics::ValueFederate::getPublicationKey(), helics::ValueFederate::getPublicationType(), and helics::ValueFederate::getPublicationUnits().
~PublicationBase()
virtual helics::PublicationBase::~PublicationBase () virtual default
default destructor
Member Function Documentation
getID()
publication_id_t helics::PublicationBase::getID () const inline
get the publication id that can be used to make the function calls from a Value Federate
References id.
getKey()
std::string helics::PublicationBase::getKey () const inline
get the key for the subscription
References fed, and helics::ValueFederate::getPublicationKey().
getName()
const std::string& helics::PublicationBase::getName () const inline
get the key for the subscription
getType()
const std::string& helics::PublicationBase::getType () const inline
get the key for the subscription
getUnits()
const std::string& helics::PublicationBase::getUnits () const inline
get the units of the Publication
The documentation for this class was generated from the following files:
Publications.hpp
Publications.cpp