helics: helics::apps::App Class Reference
helics::apps::App Class Reference abstract
#include <helicsApp.hpp>
Public Member Functions
App ()=default
App (const std::string &appName, int argc, char *argv[])
App (const FederateInfo &fi)
App (const std::shared_ptr< Core > &core, const FederateInfo &fi)
App (const std::string &appName, const std::string &jsonString)
App (App &&other_app)=default
App (const App &other_app)=delete
App & operator= (App &&fed)=default
App & operator= (const App &fed)=delete
void loadFile (const std::string &filename)
virtual void initialize ()
virtual void run ()
virtual void runTo (Time stopTime_input)=0
virtual void finalize ()
bool isActive () const
Protected Member Functions
int loadArguments (boost::program_options::variables_map &vm_map)
virtual void loadJsonFile (const std::string &jsonString)
void loadJsonFileConfiguration (const std::string &appName, const std::string &jsonString)
virtual void loadTextFile (const std::string &textFile)
Protected Attributes
std::shared_ptr< CombinationFederate > fed
the federate created for the Player
Time stopTime = Time::maxVal ()
the time the Player should stop
std::string masterFileName
the name of the master file used to do the construction
bool useLocal = false
bool fileLoaded = false
bool deactivated = false
bool quietMode = false
Detailed Description
class defining a basic helics App
the App class is not thread-safe in non-const methods, don't try to use it from multiple threads without external protection, that will result in undefined behavior
Constructor & Destructor Documentation
App() [1/7]
helics::apps::App::App () default
default constructor
App() [2/7]
helics::apps::App::App (const std::string & appName, int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
References helics::argumentParser(), fed, helics::helpReturn(), helics::FederateInfo::loadInfoFromArgs(), helics::versionReturn(), and helics::versionString.
App() [3/7]
helics::apps::App::App (const FederateInfo & fi) explicit
construct from a federate info object
Parameters
fi a pointer info object containing information on the desired federate configuration
App() [4/7]
helics::apps::App::App (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
App() [5/7]
helics::apps::App::App (const std::string & appName, const std::string & jsonString) explicit
constructor taking a file with the required information
Parameters
[in] jsonString file or JSON string defining the federate information and other configuration
References masterFileName.
App() [6/7]
helics::apps::App::App (App && other_app) default
move construction
App() [7/7]
helics::apps::App::App (const App & other_app) delete
don't allow the copy constructor
Member Function Documentation
finalize()
void helics::apps::App::finalize () virtual
finalize the Player federate
References fed.
initialize()
void helics::apps::App::initialize () virtual
initialize the Player federate
generate all the publications and organize the points, the final publication count will be available after this time and the Player will enter the initialization mode, which means it will not be possible to add more publications calling run will automatically do this if necessary
Reimplemented in helics::apps::Source, and helics::apps::Player.
References fed, and helics::Federate::startup.
Referenced by helics::apps::Echo::runTo().
isActive()
bool helics::apps::App::isActive () const inline
check if the Player is ready to run
loadFile()
void helics::apps::App::loadFile (const std::string & filename)
load a file containing publication information
Parameters
filename the file containing the configuration and Player data accepted format are JSON, xml, and a Player format which is tab delimited or comma delimited
References loadJsonFile(), and loadTextFile().
Referenced by helics::apps::Echo::Echo(), helics::apps::Player::Player(), helics::apps::Recorder::Recorder(), helics::apps::Source::Source(), and helics::apps::Tracer::Tracer().
loadJsonFile()
void helics::apps::App::loadJsonFile (const std::string & jsonString) protected virtual
load from a jsonString
Parameters
jsonString either a JSON filename or a string containing JSON
References loadJsonFileConfiguration().
Referenced by loadFile().
loadJsonFileConfiguration()
void helics::apps::App::loadJsonFileConfiguration (const std::string & appName, const std::string & jsonString) protected
load from a jsonString and check a field named appName for configuration options
Parameters
jsonString either a JSON filename or a string containing JSON
References fed, and loadJsonString().
Referenced by loadJsonFile().
loadTextFile()
void helics::apps::App::loadTextFile (const std::string & textFile) protected virtual
load a text file
Referenced by loadFile().
operator=() [1/2]
App& helics::apps::App::operator= (App && fed) default
move assignment
operator=() [2/2]
App& helics::apps::App::operator= (const App & fed) delete
don't allow the copy assignment, the default would fail anyway since federates are not copyable either
runTo()
virtual void helics::apps::App::runTo (Time stopTime_input) pure virtual
run the Player until the specified time
Parameters
stopTime_input the desired stop time
Implemented in helics::apps::Source, helics::apps::Player, helics::apps::Recorder, helics::apps::Tracer, and helics::apps::Echo.
The documentation for this class was generated from the following files:
helicsApp.hpp
helicsApp.cpp