helics: helics::DependencyInfo Class Reference
helics::DependencyInfo Class Reference
#include <TimeDependencies.hpp>
Public Types
enum time_state_t : int16_t {
initialized = 0, exec_requested_iterative = 1, exec_requested = 2, time_granted = 3,
time_requested_iterative = 4, time_requested = 5
}
Public Member Functions
DependencyInfo ()=default
DependencyInfo (Core::federate_id_t id)
bool ProcessMessage (const ActionMessage &m)
Public Attributes
Core::federate_id_t fedID = invalid_fed_id
identifier for the dependency
Core::federate_id_t minFed = invalid_fed_id
identifier for the min dependency
time_state_t time_state = time_state_t::initialized
the current state of the dependency
Time Tnext = negEpsilon
next possible message or value
Time Te = timeZero
the next currently scheduled event
Time Tdemin = timeZero
min dependency event time
Time forwardEvent = Time::maxVal ()
a predicted event
Detailed Description
data class containing information about inter-federate dependencies
Member Enumeration Documentation
time_state_t
enum helics::DependencyInfo::time_state_t : int16_t strong
enumeration of possible states for a federate to be in regards to time request
Constructor & Destructor Documentation
DependencyInfo() [1/2]
helics::DependencyInfo::DependencyInfo () default
default constructor
DependencyInfo() [2/2]
helics::DependencyInfo::DependencyInfo (Core::federate_id_t id) inline explicit
construct from a federate id
Member Function Documentation
ProcessMessage()
bool helics::DependencyInfo::ProcessMessage (const ActionMessage & m)
process a dependency related message
Parameters
m a reference to an action message that contains some instructions for modifying dependencies
Returns
the results of processing the message
References helics::ActionMessage::action(), helics::ActionMessage::actionTime, helics::checkActionFlag(), forwardEvent, helics::iteration_requested_flag, TimeRepresentation< Tconv >::maxVal(), minFed, helics::ActionMessage::source_handle, Tdemin, helics::ActionMessage::Tdemin, Te, helics::ActionMessage::Te, time_state, and Tnext.
Referenced by helics::TimeDependencies::updateTime().
The documentation for this class was generated from the following files:
TimeDependencies.hpp
TimeDependencies.cpp