helics: helics::CloningFilter Class Reference
helics::CloningFilter Class Reference
#include <Filters.hpp>
Public Member Functions
CloningFilter (Core *cr)
CloningFilter (Federate *fed)
void addSourceTarget (const std::string &sourceName)
void addDestinationTarget (const std::string &destinationName)
void addDeliveryEndpoint (const std::string &endpoint)
void removeSourceTarget (const std::string &sourceName)
void removeDestinationTarget (const std::string &destinationName)
void removeDeliveryEndpoint (const std::string &endpoint)
virtual void setString (const std::string &property, const std::string &val) override
CloningFilter (helics_filter hfilt)
CloningFilter (const CloningFilter &filter)
CloningFilter & operator= (const CloningFilter &filter)
void addDestinationTarget (const std::string &dest)
void addSourceTarget (const std::string &source)
void addDeliveryEndpoint (const std::string &deliveryEndpoint)
void removeDestinationTarget (const std::string &dest)
void removeSourceTarget (const std::string &source)
void removeDeliveryEndpoint (const std::string &deliveryEndpoint)
Public Member Functions inherited from helics::Filter
Filter ()=default
Filter (Federate *fed)
Filter (Core *cr)
virtual ~Filter ()=default
void setOperator (std::shared_ptr< FilterOperator > mo)
filter_id_t getID () const
Core::handle_id_t getCoreHandle () const
const std::string & getTarget () const
const std::string & getName () const
const std::string & getInputType () const
const std::string & getOutputType () const
virtual void set (const std::string &property, double val)
Filter (helics_filter hfilt)
Filter (const Filter &filter)
Filter & operator= (const Filter &filter)
operator helics_filter () const
helics_filter baseObject () const
std::string getTarget () const
std::string getName () const
void set (const std::string &property, double val)
void setString (const std::string &property, const std::string &val)
Additional Inherited Members
Protected Member Functions inherited from helics::Filter
void setFilterOperations (std::shared_ptr< FilterOperations > filterOps)
Protected Attributes inherited from helics::Filter
Core * corePtr = nullptr
the Core to use
Core::handle_id_t id = invalid_handle
the id as generated by the Federate
filter_id_t fid = invalid_id_value
id for interacting with a federate
std::shared_ptr< FilterOperations > filtOp
a class running any specific operation of the Filter
helics_filter filt
the reference to the underlying publication
Detailed Description
class used to clone message for delivery to other endpoints
Constructor & Destructor Documentation
CloningFilter() [1/2]
helics::CloningFilter::CloningFilter (Core * cr) explicit
construct from a core object
References helics::Filter::filtOp.
CloningFilter() [2/2]
helics::CloningFilter::CloningFilter (Federate * fed) explicit
construct from a Federate
References helics::Filter::filtOp, and helics::Federate::getCorePointer().
Member Function Documentation
addDeliveryEndpoint() [1/2]
void helics::CloningFilter::addDeliveryEndpoint (const std::string & deliveryEndpoint) inline
add a delivery endpoint to a cloning filter
all cloned messages are sent to the delivery address(es)
References helics::Filter::filt, and helicsFilterAddDeliveryEndpoint().
addDeliveryEndpoint() [2/2]
void helics::CloningFilter::addDeliveryEndpoint (const std::string & endpoint)
add a delivery address this is the name of an endpoint to deliver the message to
References helics::Filter::setString().
addDestinationTarget() [1/2]
void helics::CloningFilter::addDestinationTarget (const std::string & dest) inline
add a destination target to a cloning filter
all messages going to a destination are copied to the delivery address(es)
addDestinationTarget() [2/2]
void helics::CloningFilter::addDestinationTarget (const std::string & destinationName)
add a destination endpoint to the list of endpoints to clone
References helics::Filter::corePtr, helics::Filter::filtOp, helics::Filter::getName(), helics::Core::registerCloningDestinationFilter(), and helics::Core::setFilterOperator().
Referenced by setString().
addSourceTarget() [1/2]
void helics::CloningFilter::addSourceTarget (const std::string & source) inline
add a source target to a cloning filter
all messages coming from a source are copied to the delivery address(es)
addSourceTarget() [2/2]
void helics::CloningFilter::addSourceTarget (const std::string & sourceName)
add a sourceEndpoint to the list of endpoint to clone
References helics::Filter::corePtr, helics::Filter::filtOp, helics::Filter::getName(), helics::Core::registerCloningSourceFilter(), and helics::Core::setFilterOperator().
Referenced by setString().
removeDeliveryEndpoint() [1/2]
void helics::CloningFilter::removeDeliveryEndpoint (const std::string & deliveryEndpoint) inline
remove a delivery destination from a cloning filter
References helics::Filter::filt, and helicsFilterRemoveDeliveryEndpoint().
removeDeliveryEndpoint() [2/2]
void helics::CloningFilter::removeDeliveryEndpoint (const std::string & endpoint)
remove a delivery address this is the name of an endpoint to deliver the message to
References helics::Filter::setString().
removeDestinationTarget() [1/2]
void helics::CloningFilter::removeDestinationTarget (const std::string & dest) inline
remove a destination target from a cloning filter
removeDestinationTarget() [2/2]
void helics::CloningFilter::removeDestinationTarget (const std::string & destinationName)
remove a destination endpoint to the list of endpoints to clone
References helics::Filter::corePtr, and helics::Core::setFilterOperator().
Referenced by setString().
removeSourceTarget() [1/2]
void helics::CloningFilter::removeSourceTarget (const std::string & source) inline
remove a source target from a cloning filter
removeSourceTarget() [2/2]
void helics::CloningFilter::removeSourceTarget (const std::string & sourceName)
remove a sourceEndpoint to the list of endpoint to clone
References helics::Filter::corePtr, and helics::Core::setFilterOperator().
Referenced by setString().
setString()
void helics::CloningFilter::setString (const std::string & property, const std::string & val) override virtual
set a string property on a filter
Parameters
property the name of the property of the filter to change
val the numerical value of the property
Reimplemented from helics::Filter.
References addDestinationTarget(), addSourceTarget(), removeDestinationTarget(), removeSourceTarget(), and helics::Filter::setString().
The documentation for this class was generated from the following files:
Filters.hpp
Filter.hpp
Filters.cpp