helics: helics::apps::Source Class Reference
helics::apps::Source Class Reference
#include <Source.hpp>
Public Member Functions
Source ()=default
Source (int argc, char *argv[])
Source (const FederateInfo &fi)
Source (const std::shared_ptr< Core > &core, const FederateInfo &fi)
Source (const std::string &jsonString)
Source (Source &&other_source)=default
Source & operator= (Source &&fed)=default
virtual void initialize () override
virtual void runTo (Time stopTime_input) override
void addPublication (const std::string &key, const std::string &generator, helics_type_t type, Time period, const std::string &units=std::string())
void addPublication (const std::string &key, helics_type_t type, Time period, const std::string &units=std::string())
int addSignalGenerator (const std::string &name, const std::string &type)
void setStartTime (const std::string &key, Time startTime)
void setPeriod (const std::string &key, Time period)
void linkPublicationToGenerator (const std::string &key, const std::string &generator)
void linkPublicationToGenerator (const std::string &key, int genIndex)
std::shared_ptr< SignalGenerator > getGenerator (int index)
Public Member Functions inherited from helics::apps::App
App ()=default
App (const std::string &appName, int argc, char *argv[])
App (const FederateInfo &fi)
App (const std::shared_ptr< Core > &core, const FederateInfo &fi)
App (const std::string &appName, const std::string &jsonString)
App (App &&other_app)=default
App (const App &other_app)=delete
App & operator= (App &&fed)=default
App & operator= (const App &fed)=delete
void loadFile (const std::string &filename)
virtual void run ()
virtual void finalize ()
bool isActive () const
Additional Inherited Members
Protected Member Functions inherited from helics::apps::App
int loadArguments (boost::program_options::variables_map &vm_map)
void loadJsonFileConfiguration (const std::string &appName, const std::string &jsonString)
virtual void loadTextFile (const std::string &textFile)
Protected Attributes inherited from helics::apps::App
std::shared_ptr< CombinationFederate > fed
the federate created for the Player
Time stopTime = Time::maxVal ()
the time the Player should stop
std::string masterFileName
the name of the master file used to do the construction
bool useLocal = false
bool fileLoaded = false
bool deactivated = false
bool quietMode = false
Detailed Description
class implementing a source federate, which is capable of generating signals of various kinds and sending signals at the appropriate times
the source class is not threadsafe, don't try to use it from multiple threads without external protection, that will result in undefined behavior
Constructor & Destructor Documentation
Source() [1/6]
helics::apps::Source::Source () default
default constructor
Source() [2/6]
helics::apps::Source::Source (int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
References helics::argumentParser(), helics::apps::App::fed, helics::apps::App::loadFile(), helics::apps::App::masterFileName, and SOURCE_ONLY_FLAG.
Source() [3/6]
helics::apps::Source::Source (const FederateInfo & fi) explicit
construct from a federate info object
Parameters
fi a pointer info object containing information on the desired federate configuration
References helics::apps::App::fed, and SOURCE_ONLY_FLAG.
Source() [4/6]
helics::apps::Source::Source (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
References helics::apps::App::fed, and SOURCE_ONLY_FLAG.
Source() [5/6]
helics::apps::Source::Source (const std::string & jsonString) explicit
constructor taking a file with the required information
Parameters
[in] jsonString file or JSON string defining the federate information and other configuration
References helics::apps::App::fed, and SOURCE_ONLY_FLAG.
Source() [6/6]
helics::apps::Source::Source (Source && other_source) default
move construction
Member Function Documentation
addPublication() [1/2]
void helics::apps::Source::addPublication (const std::string & key, const std::string & generator, helics_type_t type, Time period, const std::string & units = std::string())
add a publication to a source
Parameters
key the key of the publication to add
generator the name of the generator to link with
type the type of the publication
period the period of the publication
units the units associated with the publication
References helics::apps::App::fed.
Referenced by addPublication().
addPublication() [2/2]
void helics::apps::Source::addPublication (const std::string & key, helics_type_t type, Time period, const std::string & units = std::string()) inline
add a publication to a source
Parameters
key the key of the publication to add
type the type of the publication
period the period of the publication
units the units associated with the publication
References addPublication().
addSignalGenerator()
int helics::apps::Source::addSignalGenerator (const std::string & name, const std::string & type)
add a signal generator to the source object
Returns
an index for later reference of the signal generator
getGenerator()
std::shared_ptr< SignalGenerator > helics::apps::Source::getGenerator (int index)
get a pointer to the signal generator
initialize()
void helics::apps::Source::initialize () override virtual
initialize the source federate
connect all sources with a generator
Reimplemented from helics::apps::App.
References helics::apps::App::fed, TimeRepresentation< Tconv >::maxVal(), and helics::Federate::startup.
Referenced by runTo().
linkPublicationToGenerator() [1/2]
void helics::apps::Source::linkPublicationToGenerator (const std::string & key, const std::string & generator)
tie a publication to a signal generator
linkPublicationToGenerator() [2/2]
void helics::apps::Source::linkPublicationToGenerator (const std::string & key, int genIndex)
tie a publication to a signal generator
operator=()
Source& helics::apps::Source::operator= (Source && fed) default
move assignment
runTo()
void helics::apps::Source::runTo (Time stopTime_input) override virtual
run the source until the specified time
Parameters
stopTime_input the desired stop time
Implements helics::apps::App.
References helics::Federate::execution, helics::apps::App::fed, initialize(), TimeRepresentation< Tconv >::maxVal(), and helics::Federate::startup.
setPeriod()
void helics::apps::Source::setPeriod (const std::string & key, Time period)
set the start time for a publication
setStartTime()
void helics::apps::Source::setStartTime (const std::string & key, Time startTime)
set the start time for a publication
The documentation for this class was generated from the following files:
Source.hpp
Source.cpp