helics: helics::NetworkBrokerData Class Reference
helics::NetworkBrokerData Class Reference
#include <NetworkBrokerData.hpp>
Public Types
enum interface_type { interface_type::tcp, interface_type::udp, interface_type::both }
Public Member Functions
NetworkBrokerData (interface_type type)
void initializeFromArgs (int argc, const char *const *argv, const std::string &localAddress)
void setInterfaceType (interface_type type)
Static Public Member Functions
static void displayHelp ()
Public Attributes
std::string brokerName
the identifier for the broker
std::string brokerAddress
the address or domain name of the broker
std::string localInterface
the interface to use for the local receive ports
int portNumber = -1
the port number for the local interface
int brokerPort = -1
the port number to use for the main broker interface
int portStart = -1
the starting port for automatic port definitions
Detailed Description
helper class designed to contain the common elements between networking brokers and cores
Member Enumeration Documentation
interface_type
enum helics::NetworkBrokerData::interface_type strong
define keys for particular interfaces
Enumerator
tcp
using tcp ports for communication
udp
using udp ports for communication
both
using both types of ports for communication
Constructor & Destructor Documentation
NetworkBrokerData()
helics::NetworkBrokerData::NetworkBrokerData (interface_type type) inline explicit
constructor from the allowed type
Member Function Documentation
displayHelp()
void helics::NetworkBrokerData::displayHelp () static
display the help line for the network information
References helics::argumentParser().
initializeFromArgs()
void helics::NetworkBrokerData::initializeFromArgs (int argc, const char *const * argv, const std::string & localAddress)
initialize the properties from input arguments
Parameters
argc the number of arguments
argv the strings as they may have come from the command line
localAddress a predefined string containing the desired local only address
References helics::argumentParser(), and helics::extractInterfaceandPort().
Referenced by helics::udp::UdpCore::initializeFromArgs(), helics::tcp::TcpCore::initializeFromArgs(), helics::zeromq::ZmqCore::initializeFromArgs(), helics::tcp::TcpBroker::initializeFromArgs(), helics::udp::UdpBroker::initializeFromArgs(), and helics::zeromq::ZmqBroker::initializeFromArgs().
setInterfaceType()
void helics::NetworkBrokerData::setInterfaceType (interface_type type) inline
set the desired interface type
The documentation for this class was generated from the following files:
NetworkBrokerData.hpp
NetworkBrokerData.cpp