helics: helics::ActionMessage Class Reference
helics::ActionMessage Class Reference
#include <ActionMessage.hpp>
Classes
class AdditionalInfo
Public Member Functions
ActionMessage () noexcept
ActionMessage (action_message_def::action_t startingAction)
ActionMessage (action_message_def::action_t startingAction, int32_t sourceId, int32_t destId)
ActionMessage (ActionMessage &&act) noexcept
ActionMessage (std::unique_ptr< Message > message)
ActionMessage (const std::string &bytes)
ActionMessage (const std::vector< char > &bytes)
ActionMessage (const char *data, size_t size)
~ActionMessage ()
ActionMessage (const ActionMessage &act)
ActionMessage & operator= (const ActionMessage &)
ActionMessage & operator= (ActionMessage &&act) noexcept
action_message_def::action_t action () const noexcept
void setAction (action_message_def::action_t newAction)
AdditionalInfo & info ()
const AdditionalInfo & info () const
void moveInfo (std::unique_ptr< Message > message)
template<class Archive >
void save (Archive &ar) const
template<class Archive >
void load (Archive &ar)
int toByteArray (char *data, size_t buffer_size) const
void to_string (std::string &data) const
std::string to_string () const
std::string packetize () const
void to_vector (std::vector< char > &data) const
std::vector< char > to_vector () const
void fromByteArray (const char *data, size_t buffer_size)
size_t depacketize (const char *data, size_t buffer_size)
void from_string (const std::string &data)
void from_vector (const std::vector< char > &data)
Public Attributes
int32_t source_id = 0
8 – for federate_id or route_id
int32_t source_handle = 0
12 – for local handle or local code
int32_t dest_id = 0
16 fed_id for a targeted message
int32_t dest_handle = 0
20 local handle for a targeted message
int32_t & index
alias to dest_handle
uint16_t counter = 0
22 counter for filter tracking or message counter
uint16_t flags = 0
24 set of messageFlags
Time actionTime = timeZero
32 the time an action took place or will take place //32
Time Te = timeZero
40 event time
Time Tdemin = timeZero
48 min dependent event time;
std::string payload
string containing the data //64 std::string is 32 bytes on most platforms (except libc++)
std::string & name
alias payload to a name reference for registration functions
Detailed Description
class defining the primary message object used in Helics
Constructor & Destructor Documentation
ActionMessage() [1/9]
helics::ActionMessage::ActionMessage () inline noexcept
default constructor
ActionMessage() [2/9]
helics::ActionMessage::ActionMessage (action_message_def::action_t startingAction)
construct from an action type
this is intended to be an implicit constructor
Parameters
startingAction from an action message definition
References helics::hasInfo().
ActionMessage() [3/9]
helics::ActionMessage::ActionMessage (action_message_def::action_t startingAction, int32_t sourceId, int32_t destId)
construct from action, source and destination id's
References dest_id, and source_id.
ActionMessage() [4/9]
helics::ActionMessage::ActionMessage (ActionMessage && act) noexcept
move constructor
ActionMessage() [5/9]
helics::ActionMessage::ActionMessage (std::unique_ptr< Message > message) explicit
build an action message from a message
ActionMessage() [6/9]
helics::ActionMessage::ActionMessage (const std::string & bytes) explicit
construct from a string
References from_string().
ActionMessage() [7/9]
helics::ActionMessage::ActionMessage (const std::vector< char > & bytes) explicit
construct from a data vector
References from_vector().
ActionMessage() [8/9]
helics::ActionMessage::ActionMessage (const char * data, size_t size) explicit
construct from a data pointer and size
References fromByteArray().
~ActionMessage()
helics::ActionMessage::~ActionMessage () default
destructor
ActionMessage() [9/9]
helics::ActionMessage::ActionMessage (const ActionMessage & act)
copy constructor
Member Function Documentation
action()
action_message_def::action_t helics::ActionMessage::action () const inline noexcept
get the action of the message
Referenced by helics::FederateState::addAction(), helics::CommonCore::deliverMessage(), helics::prettyPrintString(), helics::ForwardingTimeCoordinator::processDependencyUpdateMessage(), helics::TimeCoordinator::processDependencyUpdateMessage(), helics::CommonCore::processFilterInfo(), helics::DependencyInfo::ProcessMessage(), helics::TimeCoordinator::processTimeMessage(), helics::FederateState::updateFederateInfo(), and helics::TimeDependencies::updateTime().
depacketize()
size_t helics::ActionMessage::depacketize (const char * data, size_t buffer_size)
load a command from a packetized stream /ref packetize
Returns
the number of bytes used
Referenced by fromByteArray().
from_string()
void helics::ActionMessage::from_string (const std::string & data)
read a command from a string
References fromByteArray().
Referenced by ActionMessage().
from_vector()
void helics::ActionMessage::from_vector (const std::vector< char > & data)
read a command from a char vector
References fromByteArray().
Referenced by ActionMessage().
fromByteArray()
void helics::ActionMessage::fromByteArray (const char * data, size_t buffer_size)
generate a command from a raw data stream
References depacketize().
Referenced by ActionMessage(), from_string(), and from_vector().
info() [1/2]
ActionMessage::AdditionalInfo & helics::ActionMessage::info ()
get a reference to the additional info structure
Referenced by helics::CommonCore::connect(), helics::createMessageFromCommand(), helics::CommonCore::deliverMessage(), helics::prettyPrintString(), helics::CommonCore::processMessage(), and helics::CommonCore::query().
info() [2/2]
const ActionMessage::AdditionalInfo & helics::ActionMessage::info () const
get a const ref to the info structure
moveInfo()
void helics::ActionMessage::moveInfo (std::unique_ptr< Message > message)
move a message data into the actionMessage
take ownership of the message and move the contents out then destroy the message shell
Parameters
message the message to move.
References actionTime, and payload.
Referenced by helics::CommonCore::deliverMessage().
operator=() [1/2]
ActionMessage & helics::ActionMessage::operator= (const ActionMessage & act)
copy operator
References actionTime, counter, dest_handle, dest_id, flags, index, payload, source_handle, source_id, Tdemin, and Te.
operator=() [2/2]
ActionMessage & helics::ActionMessage::operator= (ActionMessage && act) noexcept
move assignment
packetize()
std::string helics::ActionMessage::packetize () const
packetize the message with a simple header and tail sequence
setAction()
void helics::ActionMessage::setAction (action_message_def::action_t newAction)
set the action
References helics::hasInfo().
Referenced by helics::CommonCore::deliverMessage(), and helics::CommonCore::processMessage().
to_string() [1/2]
void helics::ActionMessage::to_string (std::string & data) const
convert to a string using a reference
Referenced by helics::zeromq::ZmqRequestSets::transmit().
to_string() [2/2]
std::string helics::ActionMessage::to_string () const
convert to a byte string
to_vector() [1/2]
void helics::ActionMessage::to_vector (std::vector< char > & data) const
covert to a byte vector using a reference
to_vector() [2/2]
std::vector< char > helics::ActionMessage::to_vector () const
convert a command to a byte vector
toByteArray()
int helics::ActionMessage::toByteArray (char * data, size_t buffer_size) const
convert a command to a raw data bytes
Parameters
[out] data pointer to memory to store the command
[in] buffer_size&ndash; the size of the buffer
Returns
the size of the buffer actually used
The documentation for this class was generated from the following files:
ActionMessage.hpp
ActionMessage.cpp