helics: StringToCmdLine Class Reference
StringToCmdLine Class Reference
#include <stringToCmdLine.h>
Public Member Functions
StringToCmdLine (const std::string &cmdString)
void load (const std::string &cmdString)
int getArgCount () const
auto getArgV ()
Detailed Description
class used to convert a string into command line arguments
Constructor & Destructor Documentation
StringToCmdLine()
StringToCmdLine::StringToCmdLine (const std::string & cmdString)
construct from a string
References load().
Member Function Documentation
getArgCount()
int StringToCmdLine::getArgCount () const inline
get the number of separate arguments corresponding to argc
Referenced by helics::CommonCore::initialize(), and helics::CoreBroker::initialize().
getArgV()
auto StringToCmdLine::getArgV () inline
get the argument values corresponding to char *argv[]
Referenced by helics::CommonCore::initialize(), and helics::CoreBroker::initialize().
load()
void StringToCmdLine::load (const std::string & cmdString)
load a string
Parameters
cmdString a single string containing command line arguments
Referenced by StringToCmdLine().
The documentation for this class was generated from the following files:
stringToCmdLine.h
stringToCmdLine.cpp