helics: helics::Core Class Reference
helics::Core Class Reference abstract
#include <Core.hpp>
Public Types
using federate_id_t = int32_t
using handle_id_t = int32_t
Public Member Functions
Core ()=default
virtual ~Core ()=default
virtual void initialize (const std::string &initializationString)=0
virtual void initializeFromArgs (int argc, const char *const *argv)=0
virtual bool isInitialized () const =0
virtual bool connect ()=0
virtual bool isConnected () const =0
virtual void disconnect ()=0
virtual bool isOpenToNewFederates () const =0
virtual const std::string & getIdentifier () const =0
virtual void error (federate_id_t federateID, int errorCode=-1)=0
virtual void finalize (federate_id_t federateID)=0
virtual void enterInitializingState (federate_id_t federateID)=0
virtual void setCoreReadyToInit ()=0
virtual iteration_result enterExecutingState (federate_id_t federateID, iteration_request iterate=NO_ITERATION)=0
virtual federate_id_t registerFederate (const std::string &name, const CoreFederateInfo &info)=0
virtual const std::string & getFederateName (federate_id_t federateID) const =0
virtual federate_id_t getFederateId (const std::string &name)=0
virtual int32_t getFederationSize ()=0
virtual Time timeRequest (federate_id_t federateID, Time next)=0
virtual iteration_time requestTimeIterative (federate_id_t federateID, Time next, iteration_request iterate)=0
virtual uint64_t getCurrentReiteration (federate_id_t federateID) const =0
virtual Time getCurrentTime (federate_id_t federateID) const =0
virtual void setMaximumIterations (federate_id_t federateID, int32_t iterations)=0
virtual void setTimeDelta (federate_id_t federateID, Time time)=0
virtual void setOutputDelay (federate_id_t federateID, Time timeoutputDelay)=0
virtual void setPeriod (federate_id_t federateID, Time timePeriod)=0
virtual void setTimeOffset (federate_id_t federateID, Time timeOffset)=0
virtual void setInputDelay (federate_id_t federateID, Time timeImpact)=0
virtual void setLoggingLevel (federate_id_t federateID, int loggingLevel)=0
virtual void setFlag (federate_id_t federateID, int flag, bool flagValue=true)=0
virtual handle_id_t registerSubscription (federate_id_t federateID, const std::string &key, const std::string &(type), const std::string &units, handle_check_mode check_mode)=0
virtual handle_id_t getSubscription (federate_id_t federateID, const std::string &key) const =0
virtual handle_id_t registerPublication (federate_id_t federateID, const std::string &key, const std::string &type, const std::string &units)=0
virtual handle_id_t getPublication (federate_id_t federateID, const std::string &key) const =0
virtual const std::string & getHandleName (handle_id_t handle) const =0
virtual const std::string & getTarget (handle_id_t handle) const =0
virtual const std::string & getUnits (handle_id_t handle) const =0
virtual const std::string & getType (handle_id_t handle) const =0
virtual const std::string & getOutputType (handle_id_t handle) const =0
virtual void setValue (handle_id_t handle, const char *data, uint64_t len)=0
virtual std::shared_ptr< const data_block > getValue (handle_id_t handle)=0
virtual const std::vector< handle_id_t > & getValueUpdates (federate_id_t federateID)=0
virtual handle_id_t registerEndpoint (federate_id_t federateID, const std::string &name, const std::string &type)=0
virtual handle_id_t getEndpoint (federate_id_t federateID, const std::string &name) const =0
virtual handle_id_t registerCloningSourceFilter (const std::string &filterName, const std::string &source, const std::string &type_in, const std::string &type_out)=0
virtual handle_id_t registerCloningDestinationFilter (const std::string &filterName, const std::string &dest, const std::string &type_in, const std::string &type_out)=0
virtual handle_id_t registerSourceFilter (const std::string &filterName, const std::string &source, const std::string &type_in, const std::string &type_out)=0
virtual handle_id_t registerDestinationFilter (const std::string &filterName, const std::string &dest, const std::string &type_in, const std::string &type_out)=0
virtual handle_id_t getSourceFilter (const std::string &name) const =0
virtual handle_id_t getDestinationFilter (const std::string &name) const =0
virtual void addDependency (federate_id_t federateID, const std::string &federateName)=0
virtual void registerFrequentCommunicationsPair (const std::string &source, const std::string &dest)=0
virtual void send (handle_id_t sourceHandle, const std::string &destination, const char *data, uint64_t length)=0
virtual void sendEvent (Time time, handle_id_t sourceHandle, const std::string &destination, const char *data, uint64_t length)=0
virtual void sendMessage (handle_id_t sourceHandle, std::unique_ptr< Message > message)=0
virtual uint64_t receiveCount (handle_id_t destination)=0
virtual std::unique_ptr< Message > receive (handle_id_t destination)=0
virtual std::unique_ptr< Message > receiveAny (federate_id_t federateID, handle_id_t &enpoint_id)=0
virtual uint64_t receiveCountAny (federate_id_t federateID)=0
virtual void logMessage (federate_id_t federateID, int logLevel, const std::string &messageToLog)=0
virtual void setFilterOperator (handle_id_t filter, std::shared_ptr< FilterOperator > callback)=0
virtual void setLoggingCallback (federate_id_t federateID, std::function< void(int, const std::string &, const std::string &)> logFunction)=0
virtual std::string query (const std::string &target, const std::string &queryStr)=0
virtual void setQueryCallback (federate_id_t federateID, std::function< std::string(const std::string &)> queryFunction)=0
Core (const std::string &type, const std::string &name, const std::string &initString)
Core (const std::string &type, const std::string &name, int argc, const char **argv)
operator helics_core ()
helics_core baseObject () const
bool isConnected () const
Core (const Core &cr)
Core & operator= (const Core &cr)
void setReadyToInit ()
void disconnect ()
std::string getIdentifier () const
Filter registerSourceFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
Filter registerDestinationFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
CloningFilter registerCloningFilter (const std::string &deliveryEndpoint)
Protected Attributes
helics_core core
Detailed Description
the class defining the core interface through an abstract class
Member Typedef Documentation
federate_id_t
using helics::Core::federate_id_t = int32_t
FederateID uniquely identifies a federate.
handle_id_t
using helics::Core::handle_id_t = int32_t
HandleID uniquely identifies a handle.
Constructor & Destructor Documentation
Core()
helics::Core::Core () default
default constructor
~Core()
virtual helics::Core::~Core () virtual default
virtual destructor
Member Function Documentation
addDependency()
virtual void helics::Core::addDependency (federate_id_t federateID, const std::string & federateName) pure virtual
add a time dependency between federates
this function is primarily useful for Message federates which do not otherwise restrict the dependencies adding a dependency gives additional information to the core that the specified federate(given by id) will be sending Messages to the named Federate(by federateName)
Parameters
[in] federateID the identifier for the federate
[in] federateName the name of the dependent federate
Implemented in helics::CommonCore.
connect()
virtual bool helics::Core::connect () pure virtual
connect the core to a broker if needed
Returns
true if the connection was successful
Implemented in helics::CommonCore.
disconnect()
virtual void helics::Core::disconnect () pure virtual
disconnect the core from its broker
Implemented in helics::CommonCore.
enterExecutingState()
virtual iteration_result helics::Core::enterExecutingState (federate_id_t federateID, iteration_request iterate = NO_ITERATION) pure virtual
Change the federate state to the Executing state.
May only be invoked in Initializing state.
Parameters
[in] federateID the identifier of the federate
[in] iterationCompleted if true no more iterations on this federate are requested if nonconverged the federate requests an iterative update
Returns
nonconverged if the executing state has not been entered and there are updates, complete if the simulation is ready to move on to the executing state
Implemented in helics::CommonCore.
enterInitializingState()
virtual void helics::Core::enterInitializingState (federate_id_t federateID) pure virtual
Federates may be in three states.
Federates are in three states.
Startup Configuration of the federate. State begins when registerFederate() is invoked and ends when enterInitializingState() is invoked.
Initializing Configure of the simulation state prior to the start of time stepping. State begins when enterInitializingState() is invoked and ends when enterExecutingState(true) is invoked.
Executing State begins when enterExecutingState() is invoked and ends when Finalize() is invoked. Change the federate state to the Initializing state.
May only be invoked in Created state otherwise an error is thrown
Implemented in helics::CommonCore.
error()
virtual void helics::Core::error (federate_id_t federateID, int errorCode = -1) pure virtual
Federate has encountered an unrecoverable error.
Implemented in helics::CommonCore.
finalize()
virtual void helics::Core::finalize (federate_id_t federateID) pure virtual
Federate has completed.
Should be invoked a single time to complete the simulation.
Implemented in helics::CommonCore.
getCurrentReiteration()
virtual uint64_t helics::Core::getCurrentReiteration (federate_id_t federateID) const pure virtual
Returns the current reiteration count for the specified federate.
Implemented in helics::CommonCore.
getCurrentTime()
virtual Time helics::Core::getCurrentTime (federate_id_t federateID) const pure virtual
get the most recent granted Time
Parameters
federateID,the id of the federate to get the time
Returns
the most recent granted time or the startup time
Implemented in helics::CommonCore.
getDestinationFilter()
virtual handle_id_t helics::Core::getDestinationFilter (const std::string & name) const pure virtual
get a destination filter Handle from its name or target(this may not be unique so it will only find the first one)
Parameters
name the name of the filter or its target
Returns
a handle to identify the filter
Implemented in helics::CommonCore.
getEndpoint()
virtual handle_id_t helics::Core::getEndpoint (federate_id_t federateID, const std::string & name) const pure virtual
get a endpoint Handle from its name or target(this may not be unique so it will only find the first one)
Parameters
federateID the identifier for the federate
name the name of the endpoint
Returns
a handle to identify the endpoint
Implemented in helics::CommonCore.
getFederateId()
virtual federate_id_t helics::Core::getFederateId (const std::string & name) pure virtual
Returns the federate Id.
Implemented in helics::CommonCore.
getFederateName()
virtual const std::string& helics::Core::getFederateName (federate_id_t federateID) const pure virtual
Returns the federate name.
Implemented in helics::CommonCore.
getFederationSize()
virtual int32_t helics::Core::getFederationSize () pure virtual
Returns the global number of federates that are registered only return accurately after the initialization state has been entered
Implemented in helics::CommonCore.
getHandleName()
virtual const std::string& helics::Core::getHandleName (handle_id_t handle) const pure virtual
Returns the name or identifier for a specified handle
Implemented in helics::CommonCore.
Referenced by helics::Filter::getName().
getIdentifier()
virtual const std::string& helics::Core::getIdentifier () const pure virtual
get and identifier string for the core
Implemented in helics::CommonCore.
getOutputType()
virtual const std::string& helics::Core::getOutputType (handle_id_t handle) const pure virtual
Returns output type for specified handle.
for filters this is the outputType, for Subscriptions this is the expected type for endpoints and publications this is the same as getType();
Parameters
handle the handle from the publication, subscription, endpoint or filter
Implemented in helics::CommonCore.
Referenced by helics::Filter::getOutputType().
getPublication()
virtual handle_id_t helics::Core::getPublication (federate_id_t federateID, const std::string & key) const pure virtual
get a publication Handle from its key
Parameters
federateID the identifier for the federate the name of the publication
Returns
a handle to identify the publication
Implemented in helics::CommonCore.
getSourceFilter()
virtual handle_id_t helics::Core::getSourceFilter (const std::string & name) const pure virtual
get a source filter Handle from its name or target(this may not be unique so it will only find the first one)
Parameters
name the name of the filter or its target
Returns
a handle to identify the filter
Implemented in helics::CommonCore.
getSubscription()
virtual handle_id_t helics::Core::getSubscription (federate_id_t federateID, const std::string & key) const pure virtual
get a subscription Handle from its key
Parameters
federateID the identifier for the federate the tag of the subscription
Returns
a handle to identify the subscription
Implemented in helics::CommonCore.
getTarget()
virtual const std::string& helics::Core::getTarget (handle_id_t handle) const pure virtual
Returns the target of a specified handle
for publications and subscriptions this is the key for filters this is the target and for endpoints this will return an empty string
Implemented in helics::CommonCore.
Referenced by helics::Filter::getTarget().
getType()
virtual const std::string& helics::Core::getType (handle_id_t handle) const pure virtual
Returns type for specified handle.
for endpoints, publications, and filters, this is the input type for subscriptions this is the type of the publication(if available)
Parameters
handle the handle from the publication, subscription, endpoint or filter
Implemented in helics::CommonCore.
Referenced by helics::Filter::getInputType().
getUnits()
virtual const std::string& helics::Core::getUnits (handle_id_t handle) const pure virtual
Returns units for specified handle.
Implemented in helics::CommonCore.
getValue()
virtual std::shared_ptr<const data_block> helics::Core::getValue (handle_id_t handle) pure virtual
Return the data for the specified handle.
Implemented in helics::CommonCore.
Referenced by helics::MessageFederateManager::updateTime().
getValueUpdates()
virtual const std::vector<handle_id_t>& helics::Core::getValueUpdates (federate_id_t federateID) pure virtual
Returns vector of subscription handles that received an update during the last time request. The data remains valid until the next call to getValueUpdates for the given federateID
Parameters
federateID the identification code of the federate to query
Returns
a reference to the location of an array of handles that have been updated
Implemented in helics::CommonCore.
Referenced by helics::MessageFederateManager::updateTime().
initialize()
virtual void helics::Core::initialize (const std::string & initializationString) pure virtual
Simulator control. Initialize the core.
Should be invoked a single time to initialize the co-simulation core.
Implemented in helics::CommonCore.
initializeFromArgs()
virtual void helics::Core::initializeFromArgs (int argc, const char *const * argv) pure virtual
Initialize the core from command line arguments.
Should be invoked a single time to initialize the co-simulation core.
Implemented in helics::CommonCore, helics::testcore::TestCore, helics::zeromq::ZmqCore, helics::ipc::IpcCore, helics::mpi::MpiCore, helics::tcp::TcpCore, and helics::udp::UdpCore.
isConnected()
virtual bool helics::Core::isConnected () const pure virtual
check if the core is connected properly
Implemented in helics::CommonCore.
isInitialized()
virtual bool helics::Core::isInitialized () const pure virtual
Returns true if the core has been initialized.
Implemented in helics::CommonCore.
isOpenToNewFederates()
virtual bool helics::Core::isOpenToNewFederates () const pure virtual
check if the core is ready to accept new federates
Implemented in helics::CommonCore.
logMessage()
virtual void helics::Core::logMessage (federate_id_t federateID, int logLevel, const std::string & messageToLog) pure virtual
send a log message to the Core for logging
Parameters
[in] federateID the federate that is sending the log message
[in] logLevel an integer for the log level (0- error, 1- warning, 2-status, 3-debug)
[in] messageToLog
Implemented in helics::CommonCore.
query()
virtual std::string helics::Core::query (const std::string & target, const std::string & queryStr) pure virtual
make a query for information from the co-simulation
the format is somewhat unspecified target is the name of an object typically one of "federation", "broker", "core", or the name of a specific object query is a broken
Parameters
target the specific target of the query
queryStr the actual query
Returns
a string containing the response to the query. Query is a blocking call and will not return until the query is answered so use with caution
Implemented in helics::CommonCore.
receive()
virtual std::unique_ptr<Message> helics::Core::receive (handle_id_t destination) pure virtual
Returns the next buffered message the specified destination endpoint or filter.
this is a non-blocking call and will return a nullptr if no message are available
Implemented in helics::CommonCore.
receiveAny()
virtual std::unique_ptr<Message> helics::Core::receiveAny (federate_id_t federateID, handle_id_t & enpoint_id) pure virtual
Receives a message for any destination.
this is a non-blocking call and will return a nullptr if no messages are available
Parameters
federateID the identifier for the federate
[out] endpoint_id the endpoint handle related to the message gets stored here
Implemented in helics::CommonCore.
Referenced by helics::MessageFederateManager::updateTime().
receiveCount()
virtual uint64_t helics::Core::receiveCount (handle_id_t destination) pure virtual
Returns the number of pending receives for the specified destination endpoint or filter.
Implemented in helics::CommonCore.
receiveCountAny()
virtual uint64_t helics::Core::receiveCountAny (federate_id_t federateID) pure virtual
Returns number of messages for all destinations.
Implemented in helics::CommonCore.
Referenced by helics::MessageFederateManager::updateTime().
registerCloningDestinationFilter()
virtual handle_id_t helics::Core::registerCloningDestinationFilter (const std::string & filterName, const std::string & dest, const std::string & type_in, const std::string & type_out) pure virtual
Register a cloning destination filter.
a destination filter will create an additional processing step of messages before they get to a destination endpoint, a destination may have multiple cloning filters but only one non-cloning filter
May only be invoked in the Initialization state.
Parameters
filterName the name of the filter (may be left blank)
dest the target endpoint for the filter
type_in the input type of the filter (may be left blank, this is for error checking and will produce a warning if it doesn't match with the input type of the target endpoint
Returns
the handle for the new filter
Implemented in helics::CommonCore.
Referenced by helics::CloningFilter::addDestinationTarget().
registerCloningFilter()
CloningFilter helics::Core::registerCloningFilter (const std::string & deliveryEndpoint) inline
create a cloning Filter on the specified federate
cloning filters copy a message and send it to multiple locations source and destination can be added through other functions
Parameters
fed the fed to register through
deliveryEndpoint the specified endpoint to deliver the message
Returns
a helics_filter object
References helicsCoreRegisterCloningFilter().
registerCloningSourceFilter()
virtual handle_id_t helics::Core::registerCloningSourceFilter (const std::string & filterName, const std::string & source, const std::string & type_in, const std::string & type_out) pure virtual
Register a cloning source filter, a cloning filter operates on a copy of the message vs the actual message
Parameters
filterName the name of the filter (may be left blank and one will be automatically assigned)
source the target endpoint for the filter
type_in the input type of the filter
type_out the output type of the filter (may be left blank if the filter doesn't change type)
Returns
the handle for the new filter
Implemented in helics::CommonCore.
Referenced by helics::CloningFilter::addSourceTarget().
registerDestinationFilter() [1/2]
Filter helics::Core::registerDestinationFilter (helics_filter_type_t type, const std::string & target, const std::string & name = std::string()) inline
create a destination Filter on the specified federate
filters can be created through a federate or a core , linking through a federate allows a few extra features of name matching to function on the federate interface but otherwise equivalent behavior
Parameters
fed the fed to register through
type the type of filter to create
target the name of endpoint to target
name the name of the filter (can be NULL)
Returns
a helics_filter object
References helicsCoreRegisterDestinationFilter().
registerDestinationFilter() [2/2]
virtual handle_id_t helics::Core::registerDestinationFilter (const std::string & filterName, const std::string & dest, const std::string & type_in, const std::string & type_out) pure virtual
Register destination filter.
a destination filter will create an additional processing step of messages before they get to a destination endpoint
May only be invoked in the Initialization state.
Parameters
filterName the name of the filter (may be left blank)
dest the target endpoint for the filter
type_in the input type of the filter (may be left blank, this is for error checking and will produce a warning if it doesn't match with the input type of the target endpoint
Returns
the handle for the new filter
Implemented in helics::CommonCore.
Referenced by helics::DestinationFilter::DestinationFilter().
registerEndpoint()
virtual handle_id_t helics::Core::registerEndpoint (federate_id_t federateID, const std::string & name, const std::string & type) pure virtual
Message interface. Designed for point-to-point communication patterns. Register an endpoint.
May only be invoked in the Initialization state.
Implemented in helics::CommonCore.
Referenced by helics::MessageFederateManager::registerEndpoint().
registerFederate()
virtual federate_id_t helics::Core::registerFederate (const std::string & name, const CoreFederateInfo & info) pure virtual
Register a federate.
The returned FederateId is local to invoking process, FederateId's should not be used as a global identifier.
May only be invoked in initialize state otherwise throws an error
Implemented in helics::CommonCore.
registerFrequentCommunicationsPair()
virtual void helics::Core::registerFrequentCommunicationsPair (const std::string & source, const std::string & dest) pure virtual
Register known frequently communicating source/destination end points.
May be used for error checking for compatible types and possible optimization by pre-registering the intent for these endpoints to communicate.
Implemented in helics::CommonCore.
Referenced by helics::MessageFederateManager::registerKnownCommunicationPath().
registerPublication()
virtual handle_id_t helics::Core::registerPublication (federate_id_t federateID, const std::string & key, const std::string & type, const std::string & units) pure virtual
Register a publication.
May only be invoked in the initialize state.
Parameters
federateID the identifier for the federate
key the tag for the publication
type the type of data the publication produces
units the units associated with the publication
Returns
a handle to identify the publication
Implemented in helics::CommonCore.
registerSourceFilter()
virtual handle_id_t helics::Core::registerSourceFilter (const std::string & filterName, const std::string & source, const std::string & type_in, const std::string & type_out) pure virtual
Register source filter.
May only be invoked in the Initialization state.
Parameters
filterName the name of the filter (may be left blank and one will be automatically assigned)
source the target endpoint for the filter
type_in the input type of the filter
type_out the output type of the filter (may be left blank if the filter doesn't change type) this is important for ordering in filters with operators
Returns
the handle for the new filter
Implemented in helics::CommonCore.
Referenced by helics::SourceFilter::SourceFilter().
registerSubscription()
virtual handle_id_t helics::Core::registerSubscription (federate_id_t federateID, const std::string & key, const std::string & type, const std::string & units, handle_check_mode check_mode) pure virtual
Value interface. Register a subscription for the specified federate.
May only be invoked in the initialize state.
Parameters
[in] federateID
[in] key the name of the subscription
[in] type a string describing the type of the federate
[in] units a string naming the units of the federate
[in] check_mode if set to required the core will error if the subscription does not have a corresponding publication when converting to init mode
requestTimeIterative()
virtual iteration_time helics::Core::requestTimeIterative (federate_id_t federateID, Time next, iteration_request iterate) pure virtual
Request a new time advancement window for reiterative federates.
Reiterative federates block on requestTimeIterative() until all reiterative federates have invoked requestTimeIterative(). The bool returned a global AND of all localConverged values. If globalConverged is false, time returned is the previous granted time. Time should not advance and another iteration attempted. Federates should recompute state based on newly published values. Time is advanced only when all reiterative federates have converged. If globalConverged is True, grantedTime is the minimum of over all next times in both reiterative and non-reiterative federates.
If a federate determines it cannot converge it should invoke the error() method.
Federates only participate it in reiterations for times that are evenly divisible by the federates time delta.
May only be invoked in Executing state.
Non-reiterative federates may not invoke this method.
Parameters
federateID the identifier for the federate to process
next the requested time
localConverged has the local federate converged
Returns
an iteration_time object with two field grantedTime and a enumeration indicating the state of the iteration
Implemented in helics::CommonCore.
send()
virtual void helics::Core::send (handle_id_t sourceHandle, const std::string & destination, const char * data, uint64_t length) pure virtual
Send data from source to destination.
Time is implicitly defined as the end of the current time advancement window (value returned by last call to nextTime().
This send version was designed to enable communication of data between federates with the possible introduction of source and destination filters to represent properties of a communication network. This enables simulations to be run with/without a communications model present.
Implemented in helics::CommonCore.
sendEvent()
virtual void helics::Core::sendEvent (Time time, handle_id_t sourceHandle, const std::string & destination, const char * data, uint64_t length) pure virtual
Send data from source to destination with explicit expected delivery time.
Time supplied is the time that will be reported in the message in the receiving federate.
This send version was designed to enable communication of events between discrete event federates. For this use case the receiving federate can deserialize the data and schedule an event for the specified time.
Parameters
time the time the event is scheduled for
sourceHandle the source of the event
destination the target of the event
data the raw data for the event
length the record length of the event
Implemented in helics::CommonCore.
sendMessage()
virtual void helics::Core::sendMessage (handle_id_t sourceHandle, std::unique_ptr< Message > message) pure virtual
Send for filters.
Continues sending the message to the next filter or to final destination.
Implemented in helics::CommonCore.
setCoreReadyToInit()
virtual void helics::Core::setCoreReadyToInit () pure virtual
set the core to ready to enter init
this function only needs to be called for cores that don't have any federates but may have filters for cores with federates it won't do anything
Implemented in helics::CommonCore.
setFilterOperator()
virtual void helics::Core::setFilterOperator (handle_id_t filter, std::shared_ptr< FilterOperator > callback) pure virtual
set the filter callback operator
Parameters
[in] filter the handle of the filter
[in] operator pointer to the operator class executing the filter
Implemented in helics::CommonCore.
Referenced by helics::CloningFilter::addDestinationTarget(), helics::CloningFilter::addSourceTarget(), helics::CloningFilter::removeDestinationTarget(), helics::CloningFilter::removeSourceTarget(), helics::Filter::setFilterOperations(), and helics::Filter::setOperator().
setFlag()
virtual void helics::Core::setFlag (federate_id_t federateID, int flag, bool flagValue = true) pure virtual
Set a flag in a a federate
Parameters
federateID the identifier for the federate
flag an index code for the flag to set
flagValue the value to set the flag to
Implemented in helics::CommonCore.
setInputDelay()
virtual void helics::Core::setInputDelay (federate_id_t federateID, Time timeImpact) pure virtual
Set the inputDelay time.
The value is used to determine the interaction amongst various federates as to when a specific federate can influence another
Parameters
federateID the identifier for the federate
timeImpact the length of time it take outside message to propagate into a federate
Implemented in helics::CommonCore.
setLoggingCallback()
virtual void helics::Core::setLoggingCallback (federate_id_t federateID, std::function< void(int, const std::string &, const std::string &)> logFunction) pure virtual
define a logging function to use for logging message and notices from the federation and individual federate
Parameters
federateID the identifier for the individual federate or 0 for the Core Logger
logFunction the callback function for doing something with a log message it takes 3 inputs an integer for logLevel 0-4+ 0 -error, 1- warning 2-status, 3-debug 44trace A string indicating the source of the message and another string with the actual message
Implemented in helics::CommonCore.
setLoggingLevel()
virtual void helics::Core::setLoggingLevel (federate_id_t federateID, int loggingLevel) pure virtual
Set the logging level
set the logging level for an individual federate set federateID to 0 for the core logging level
Parameters
federateID the identifier for the federate
loggingLevel the level of logging to enable <0-no logging, 0 -error only, 1- warnings, 2-normal, 3-debug, 4-trace
Implemented in helics::CommonCore.
setMaximumIterations()
virtual void helics::Core::setMaximumIterations (federate_id_t federateID, int32_t iterations) pure virtual
Set the maximum number of iterations allowed.
The minimum value set in any federate is used.
Default value is the maximum allowed value for uint64_t.
May only be invoked in the initialize state.
Implemented in helics::CommonCore.
setOutputDelay()
virtual void helics::Core::setOutputDelay (federate_id_t federateID, Time timeoutputDelay) pure virtual
Set the outputDelay time for the specified federate.
The value is used to determine the interaction amongst various federates as to when a specific federate can influence another
Parameters
federateID the identifier for the federate
timeoutputDelay
Implemented in helics::CommonCore.
setPeriod()
virtual void helics::Core::setPeriod (federate_id_t federateID, Time timePeriod) pure virtual
Set the period for a specified federate.
The value is used to determine the interaction amongst various federates as to when a specific federate can influence another
Parameters
federateID the identifier for the federate
timeoutputDelay
Implemented in helics::CommonCore.
setQueryCallback()
virtual void helics::Core::setQueryCallback (federate_id_t federateID, std::function< std::string(const std::string &)> queryFunction) pure virtual
supply a query callback function
the intention of the query callback is to allow federates to answer particular requests through the query interface this allows other federates to make requests or queries of other federates in an asynchronous fashion.
Parameters
federateID the identifier for the federate
queryFunction a function object that returns a string as a result of a query in the form of const string ref. This callback will be called when a federate received a query that cannot be answered that directed at a particular federate
Implemented in helics::CommonCore.
setTimeDelta()
virtual void helics::Core::setTimeDelta (federate_id_t federateID, Time time) pure virtual
Set the minimum time resolution for the specified federate.
The value is used to constrain when the timeRequest methods return to values that are multiples of the specified delta. This is useful for federates that are time-stepped and making sub-time-step updates is not meaningful.
Parameters
time
Implemented in helics::CommonCore.
setTimeOffset()
virtual void helics::Core::setTimeOffset (federate_id_t federateID, Time timeOffset) pure virtual
Set the periodic offset for a specified federate.
The value is used as a time shift for calculating the allowable time in a federate the granted time must one of N*period+offset
Parameters
federateID the identifier for the federate
timeOffset the periodic phase shift
Implemented in helics::CommonCore.
setValue()
virtual void helics::Core::setValue (handle_id_t handle, const char * data, uint64_t len) pure virtual
Publish specified data to the specified key.
Parameters
handle a handle to a publication to use for the value
[in] data the raw data to send
len the size of the data
Implemented in helics::CommonCore.
timeRequest()
virtual Time helics::Core::timeRequest (federate_id_t federateID, Time next) pure virtual
Time management. Request a new time advancement window for non-reiterative federates.
RequestTime() blocks until all non-reiterative federates have invoked requestTime() and all reiterative federates have converged (called requestTimeIterative() with localConverged value of true). Return time is the minimum of all supplied times.
May only be invoked in Executing state.
Iterative federates may not invoke this method.
Parameters
next
Implemented in helics::CommonCore.
The documentation for this class was generated from the following file:
core/Core.hpp