helics: helics::TimeCoordinator Class Reference
helics::TimeCoordinator Class Reference
#include <TimeCoordinator.hpp>
Public Member Functions
TimeCoordinator ()
TimeCoordinator (const CoreFederateInfo &info_)
TimeCoordinator (const CoreFederateInfo &info_, std::function< void(const ActionMessage &)> sendMessageFunction_)
CoreFederateInfo & getFedInfo ()
const CoreFederateInfo & getFedInfo () const
void setInfo (const CoreFederateInfo &info_)
void setMessageSender (std::function< void(const ActionMessage &)> sendMessageFunction_)
Time getGrantedTime () const
Time allowedSendTime () const
std::vector< Core::federate_id_t > getDependencies () const
const std::vector< Core::federate_id_t > & getDependents () const
int32_t getCurrentIteration () const
bool updateTimeFactors ()
void updateValueTime (Time valueUpdateTime)
void updateMessageTime (Time messageUpdateTime)
DependencyInfo * getDependencyInfo (Core::federate_id_t ofed)
bool isDependency (Core::federate_id_t ofed) const
message_process_result processTimeMessage (const ActionMessage &cmd)
void processConfigUpdateMessage (const ActionMessage &cmd, bool initMode=false)
void processDependencyUpdateMessage (const ActionMessage &cmd)
bool addDependency (Core::federate_id_t fedID)
bool addDependent (Core::federate_id_t fedID)
void removeDependency (Core::federate_id_t fedID)
void removeDependent (Core::federate_id_t fedID)
iteration_state checkExecEntry ()
void timeRequest (Time nextTime, iteration_request iterate, Time newValueTime, Time newMessageTime)
void enteringExecMode (iteration_request mode)
iteration_state checkTimeGrant ()
void disconnect ()
std::string printTimeStatus () const
bool hasActiveTimeDependencies () const
Public Attributes
Core::federate_id_t source_id
the identifier for inserting into the source id field of any generated messages;
bool iterating = false
indicator that the coordinator should be iterating if need be
bool checkingExec = false
flag indicating that the coordinator is trying to enter the exec mode
bool executionMode = false
flag that the coordinator has entered the execution Mode
bool hasInitUpdates
flag indicating that a value or message was received during initialization stage
bool forwarding = false
Detailed Description
class managing the coordination of time in HELICS the time coordinator manages dependencies and computes whether time can advance or enter execution mode
Constructor & Destructor Documentation
TimeCoordinator() [1/3]
helics::TimeCoordinator::TimeCoordinator ()
default constructor
TimeCoordinator() [2/3]
helics::TimeCoordinator::TimeCoordinator (const CoreFederateInfo & info_) explicit
construct from a federate info
TimeCoordinator() [3/3]
helics::TimeCoordinator::TimeCoordinator (const CoreFederateInfo & info_, std::function< void(const ActionMessage &)> sendMessageFunction_)
construct from a federate info and message send function
Member Function Documentation
addDependency()
bool helics::TimeCoordinator::addDependency (Core::federate_id_t fedID)
add a federate dependency
Returns
true if it was actually added, false if the federate was already present
References helics::TimeDependencies::addDependency().
Referenced by processDependencyUpdateMessage().
addDependent()
bool helics::TimeCoordinator::addDependent (Core::federate_id_t fedID)
add a dependent federate
Returns
true if it was actually added, false if the federate was already present
Referenced by processDependencyUpdateMessage().
allowedSendTime()
Time helics::TimeCoordinator::allowedSendTime () const inline
get the current granted time
References helics::CoreFederateInfo::outputDelay.
checkExecEntry()
iteration_state helics::TimeCoordinator::checkExecEntry ()
check if entry to the executing state can be granted
References helics::TimeDependencies::checkIfReadyForExecEntry(), helics::continue_processing, helics::ActionMessage::counter, executionMode, hasInitUpdates, helics::iterating, iterating, helics::iteration_requested_flag, helics::CoreFederateInfo::maxIterations, helics::next_step, helics::TimeDependencies::resetIteratingExecRequests(), helics::setActionFlag(), source_id, and helics::ActionMessage::source_id.
checkTimeGrant()
iteration_state helics::TimeCoordinator::checkTimeGrant ()
check if it is valid to grant a time
References helics::TimeDependencies::checkIfReadyForTimeGrant(), helics::continue_processing, helics::halted, helics::iterating, iterating, TimeRepresentation< Tconv >::maxVal(), helics::next_step, source_id, helics::ActionMessage::source_id, and updateTimeFactors().
disconnect()
void helics::TimeCoordinator::disconnect ()
disconnect
References source_id, and helics::ActionMessage::source_id.
enteringExecMode()
void helics::TimeCoordinator::enteringExecMode (iteration_request mode)
function to enter the exec Mode
Parameters
mode the mode of iteration_request (no_iteration, force_iteration, iterate_if_needed)
References checkingExec, executionMode, iterating, helics::iteration_requested_flag, helics::no_iterations, helics::setActionFlag(), source_id, and helics::ActionMessage::source_id.
getCurrentIteration()
int32_t helics::TimeCoordinator::getCurrentIteration () const inline
get the current iteration counter for an iterative call
this will work properly even when a federate is processing
getDependencies()
std::vector< Core::federate_id_t > helics::TimeCoordinator::getDependencies () const
get a list of actual dependencies
References helics::TimeDependencies::size().
getDependencyInfo()
DependencyInfo * helics::TimeCoordinator::getDependencyInfo (Core::federate_id_t ofed)
take a global id and get a pointer to the dependencyInfo for the other fed will be nullptr if it doesn't exist
References helics::TimeDependencies::getDependencyInfo().
getDependents()
const std::vector<Core::federate_id_t>& helics::TimeCoordinator::getDependents () const inline
get a reference to the dependents vector
getFedInfo()
const CoreFederateInfo& helics::TimeCoordinator::getFedInfo () const inline
get the core federate info in const setting
getGrantedTime()
Time helics::TimeCoordinator::getGrantedTime () const inline
get the current granted time
hasActiveTimeDependencies()
bool helics::TimeCoordinator::hasActiveTimeDependencies () const
return true if there are active dependencies
References helics::TimeDependencies::hasActiveTimeDependencies().
isDependency()
bool helics::TimeCoordinator::isDependency (Core::federate_id_t ofed) const
check whether a federate is a dependency
References helics::TimeDependencies::isDependency().
printTimeStatus()
std::string helics::TimeCoordinator::printTimeStatus () const
generate a string with the current time status
processConfigUpdateMessage()
void helics::TimeCoordinator::processConfigUpdateMessage (const ActionMessage & cmd, bool initMode = false)
process a message related to configuration
Parameters
cmd the update command
initMode set to true to allow initialization mode only updates
References helics::ActionMessage::actionTime, helics::checkActionFlag(), helics::ActionMessage::dest_id, helics::ActionMessage::index, helics::indicator_flag, helics::CoreFederateInfo::inputDelay, helics::CoreFederateInfo::logLevel, helics::CoreFederateInfo::maxIterations, helics::CoreFederateInfo::observer, OBSERVER_FLAG, helics::CoreFederateInfo::offset, helics::CoreFederateInfo::only_transmit_on_change, ONLY_TRANSMIT_ON_CHANGE_FLAG, helics::CoreFederateInfo::only_update_on_change, ONLY_UPDATE_ON_CHANGE_FLAG, helics::CoreFederateInfo::outputDelay, helics::CoreFederateInfo::period, helics::CoreFederateInfo::source_only, SOURCE_ONLY_FLAG, helics::CoreFederateInfo::uninterruptible, UNINTERRUPTIBLE_FLAG, WAIT_FOR_CURRENT_TIME_UPDATE_FLAG, and helics::CoreFederateInfo::wait_for_current_time_updates.
processDependencyUpdateMessage()
void helics::TimeCoordinator::processDependencyUpdateMessage (const ActionMessage & cmd)
process a dependency update message
References helics::ActionMessage::action(), addDependency(), addDependent(), removeDependency(), removeDependent(), and helics::ActionMessage::source_id.
processTimeMessage()
message_process_result helics::TimeCoordinator::processTimeMessage (const ActionMessage & cmd)
process a message related to time
Returns
the result of processing the message
References helics::ActionMessage::action(), checkingExec, helics::delay_processing, helics::TimeDependencies::getDependencyInfo(), iterating, helics::no_effect, helics::processed, source_id, helics::ActionMessage::source_id, and helics::TimeDependencies::updateTime().
removeDependency()
void helics::TimeCoordinator::removeDependency (Core::federate_id_t fedID)
remove a dependency
Parameters
fedID the identifier of the federate to remove
References helics::TimeDependencies::removeDependency().
Referenced by processDependencyUpdateMessage().
removeDependent()
void helics::TimeCoordinator::removeDependent (Core::federate_id_t fedID)
remove a dependent
Parameters
fedID the identifier of the federate to remove
Referenced by processDependencyUpdateMessage().
setInfo()
void helics::TimeCoordinator::setInfo (const CoreFederateInfo & info_) inline
set the core information using for timing as a block
setMessageSender()
void helics::TimeCoordinator::setMessageSender (std::function< void(const ActionMessage &)> sendMessageFunction_)
set the callback function used for the sending messages
timeRequest()
void helics::TimeCoordinator::timeRequest (Time nextTime, iteration_request iterate, Time newValueTime, Time newMessageTime)
request a time
Parameters
nextTime the new requested time
iterate the mode of iteration to use (no_iteration, force_iteration, iterate_if_needed)
newValueTime the time of the next value
newMessageTime the time of the next message
References iterating, helics::no_iterations, and updateTimeFactors().
updateMessageTime()
void helics::TimeCoordinator::updateMessageTime (Time messageUpdateTime)
update the time_message variable with a new value if needed
References executionMode, hasInitUpdates, and iterating.
updateTimeFactors()
bool helics::TimeCoordinator::updateTimeFactors ()
compute updates to time values
Returns
true if they have been modified
References helics::CoreFederateInfo::inputDelay, TimeRepresentation< Tconv >::maxVal(), and helics::CoreFederateInfo::outputDelay.
Referenced by checkTimeGrant(), and timeRequest().
updateValueTime()
void helics::TimeCoordinator::updateValueTime (Time valueUpdateTime)
update the time_value variable with a new value if needed
References executionMode, hasInitUpdates, and iterating.
Member Data Documentation
hasInitUpdates
bool helics::TimeCoordinator::hasInitUpdates
Initial value:
=
      false
flag indicating that a value or message was received during initialization stage
Referenced by checkExecEntry(), updateMessageTime(), and updateValueTime().
The documentation for this class was generated from the following files:
TimeCoordinator.hpp
TimeCoordinator.cpp