helics: helics::FederateState Class Reference
helics::FederateState Class Reference
#include <FederateState.hpp>
Public Member Functions
FederateState (const std::string &name_, const CoreFederateInfo &info_)
~FederateState ()
void reset ()
void reInit ()
const std::string & getIdentifier () const
federate_state_t getState () const
const SubscriptionInfo * getSubscription (const std::string &subName) const
const SubscriptionInfo * getSubscription (Core::handle_id_t handle_) const
SubscriptionInfo * getSubscription (const std::string &subName)
SubscriptionInfo * getSubscription (Core::handle_id_t handle_)
const PublicationInfo * getPublication (const std::string &pubName) const
const PublicationInfo * getPublication (Core::handle_id_t handle_) const
PublicationInfo * getPublication (const std::string &pubName)
PublicationInfo * getPublication (Core::handle_id_t handle_)
const EndpointInfo * getEndpoint (const std::string &endpointName) const
const EndpointInfo * getEndpoint (Core::handle_id_t handle_) const
EndpointInfo * getEndpoint (const std::string &endpointName)
EndpointInfo * getEndpoint (Core::handle_id_t handle_)
void createSubscription (Core::handle_id_t handle, const std::string &key, const std::string &type, const std::string &units, handle_check_mode check_mode)
void createPublication (Core::handle_id_t handle, const std::string &key, const std::string &type, const std::string &units)
void createEndpoint (Core::handle_id_t handle, const std::string &key, const std::string &type)
uint64_t getQueueSize (Core::handle_id_t id) const
uint64_t getQueueSize () const
int32_t getCurrentIteration () const
std::unique_ptr< Message > receive (Core::handle_id_t id)
std::unique_ptr< Message > receiveAny (Core::handle_id_t &id)
void setParent (CommonCore *coreObject)
CoreFederateInfo getInfo () const
void updateFederateInfo (const ActionMessage &cmd)
Time grantedTime () const
Time nextAllowedSendTime () const
const std::vector< Core::handle_id_t > & getEvents () const
const std::vector< Core::federate_id_t > & getDependents () const
const std::string & lastErrorString () const
void setCoreObject (CommonCore *parent)
iteration_result waitSetup ()
iteration_result enterInitializationState ()
iteration_result enterExecutingState (iteration_request iterate)
iteration_time requestTime (Time nextTime, iteration_request iterate)
iteration_result genericUnspecifiedQueueProcess ()
void addAction (const ActionMessage &action)
void addAction (ActionMessage &&action)
void logMessage (int level, const std::string &logMessageSource, const std::string &message) const
void setLogger (std::function< void(int, const std::string &, const std::string &)> logFunction)
void setQueryCallback (std::function< std::string(const std::string &)> queryCallbackFunction)
std::string processQuery (const std::string &query) const
bool checkAndSetValue (Core::handle_id_t pub_id, const char *data, uint64_t len)
void routeMessage (const ActionMessage &msg)
Public Attributes
Core::federate_id_t local_id = invalid_fed_id
id code, default to something invalid
std::atomic< Core::federate_id_t > global_id {invalid_fed_id}
global id code, default to invalid
std::atomic< bool > init_transmitted {false}
the initialization request has been transmitted
std::atomic< bool > init_requested {false}
this federate has requested entry to initialization
bool iterating = false
the federate is iterating at a time step
bool hasEndpoints = false
the federate has endpoints
bool timeGranted_mode
indicator if the federate is in a granted state or a requested state waiting to grant
int logLevel = 1
the level of logging used in the federate
Detailed Description
class managing the information about a single federate
Constructor & Destructor Documentation
FederateState()
helics::FederateState::FederateState (const std::string & name_, const CoreFederateInfo & info_)
constructor from name and information structure
References helics::CoreFederateInfo::logLevel, logLevel, helics::CoreFederateInfo::only_transmit_on_change, helics::CoreFederateInfo::only_update_on_change, and routeMessage().
~FederateState()
helics::FederateState::~FederateState () default
destructor
Member Function Documentation
addAction() [1/2]
void helics::FederateState::addAction (const ActionMessage & action)
add an action message to the queue
References helics::ActionMessage::action().
Referenced by enterExecutingState(), and updateFederateInfo().
addAction() [2/2]
void helics::FederateState::addAction (ActionMessage && action)
move a message to the queue
checkAndSetValue()
bool helics::FederateState::checkAndSetValue (Core::handle_id_t pub_id, const char * data, uint64_t len)
check if a value should be published or not
Parameters
pub_id the handle of the publication
data the raw data to check
len the length of the data
Returns
true if it should be published, false if not
enterExecutingState()
iteration_result helics::FederateState::enterExecutingState (iteration_request iterate)
function to call when entering execution state
Parameters
converged indicator of whether the fed should iterate if need be or not returns either converged or nonconverged depending on whether an iteration is needed
References addAction(), helics::error, helics::force_iteration, global_id, helics::halted, helics::HELICS_ERROR, helics::HELICS_EXECUTING, helics::HELICS_FINISHED, helics::HELICS_INITIALIZING, helics::iterate_if_needed, helics::iterating, helics::iteration_requested_flag, helics::next_step, helics::no_iterations, helics::required_flag, helics::setActionFlag(), and helics::ActionMessage::source_id.
enterInitializationState()
iteration_result helics::FederateState::enterInitializationState ()
process until the initialization state has been entered or there is a failure
References helics::error, helics::halted, helics::HELICS_ERROR, helics::HELICS_FINISHED, helics::iterating, and helics::next_step.
genericUnspecifiedQueueProcess()
iteration_result helics::FederateState::genericUnspecifiedQueueProcess ()
function to process the queue in a generic fashion used to just process messages with no specific end in mind
References helics::next_step.
getCurrentIteration()
int32_t helics::FederateState::getCurrentIteration () const
get the current iteration counter for an iterative call
this will work properly even when a federate is processing
getDependents()
const std::vector< Core::federate_id_t > & helics::FederateState::getDependents () const
get a reference to the global ids of dependent federates
getEvents()
const std::vector< Core::handle_id_t > & helics::FederateState::getEvents () const
get a reference to the handles of subscriptions with value updates
< if we are processing this vector is in an undefined state
getIdentifier()
const std::string& helics::FederateState::getIdentifier () const inline
get the name of the federate
getInfo()
CoreFederateInfo helics::FederateState::getInfo () const
specify the core object that manages this federate get the info structure for the federate
getQueueSize() [1/2]
uint64_t helics::FederateState::getQueueSize (Core::handle_id_t id) const
get the size of a message queue for a specific endpoint or filter handle
getQueueSize() [2/2]
uint64_t helics::FederateState::getQueueSize () const
get the sum of all message queue sizes i.e. the total number of messages available in all endpoints
grantedTime()
Time helics::FederateState::grantedTime () const inline
get the granted time of a federate
lastErrorString()
const std::string& helics::FederateState::lastErrorString () const inline
get the last error string
Referenced by helics::CommonCore::registerFederate().
logMessage()
void helics::FederateState::logMessage (int level, const std::string & logMessageSource, const std::string & message) const
log a message to the federate Logger
Parameters
level the logging level of the message
logMessageSource- the name of the object that sent the message
message the message to log
References global_id, and logLevel.
nextAllowedSendTime()
Time helics::FederateState::nextAllowedSendTime () const inline
get allowable message time
processQuery()
std::string helics::FederateState::processQuery (const std::string & query) const
generate the result of a query string
Parameters
query a query string
Returns
the resulting string from the query
receive()
std::unique_ptr< Message > helics::FederateState::receive (Core::handle_id_t id)
get the next available message for an endpoint
Parameters
id the handle of an endpoint or filter
Returns
a pointer to a message -the ownership of the message is transfered to the caller
receiveAny()
std::unique_ptr< Message > helics::FederateState::receiveAny (Core::handle_id_t & id)
get any message ready for reception
Parameters
[out] id the endpoint related to the message
References helics::EndpointInfo::getMessage(), helics::EndpointInfo::id, and TimeRepresentation< Tconv >::maxVal().
reInit()
void helics::FederateState::reInit ()
reset the federate to the initializing state
References helics::HELICS_INITIALIZING.
requestTime()
iteration_time helics::FederateState::requestTime (Time nextTime, iteration_request iterate)
request a time advancement
Parameters
nextTime the time of the requested advancement
converged set to complete to end dense time step iteration, nonconverged to continue iterating if need be
Returns
an iteration time with two elements the granted time and the convergence state
reset()
void helics::FederateState::reset ()
reset the federate to created state
References global_id, and local_id.
routeMessage()
void helics::FederateState::routeMessage (const ActionMessage & msg)
route a message either forward to parent or add to queue
References helics::BrokerBase::addActionMessage().
Referenced by FederateState().
setLogger()
void helics::FederateState::setLogger (std::function< void(int, const std::string &, const std::string &)> logFunction) inline
set the logging function
function must have signature void(int level, const std::string &sourceName, const std::string &message)
Referenced by helics::CommonCore::registerFederate().
setParent()
void helics::FederateState::setParent (CommonCore * coreObject) inline
set the CommonCore object that is managing this Federate
Referenced by helics::CommonCore::registerFederate().
setQueryCallback()
void helics::FederateState::setQueryCallback (std::function< std::string(const std::string &)> queryCallbackFunction) inline
set the query callback function
function must have signature std::string(const std::string &query)
updateFederateInfo()
void helics::FederateState::updateFederateInfo (const ActionMessage & cmd)
update the info structure
public call so it also calls the federate lock before calling private update function the action Message should be CMD_FED_CONFIGURE
References helics::ActionMessage::action(), and addAction().
waitSetup()
iteration_result helics::FederateState::waitSetup ()
process until the federate has verified its membership and assigned a global id number
References helics::error, helics::halted, helics::HELICS_ERROR, helics::HELICS_FINISHED, and helics::next_step.
Referenced by helics::CommonCore::registerFederate().
Member Data Documentation
timeGranted_mode
bool helics::FederateState::timeGranted_mode
Initial value:
=
      false
indicator if the federate is in a granted state or a requested state waiting to grant
The documentation for this class was generated from the following files:
FederateState.hpp
FederateState.cpp