helics: helics::CombinationFederate Class Reference
helics::CombinationFederate Class Reference
#include <CombinationFederate.hpp>
Public Member Functions
CombinationFederate ()
CombinationFederate (const FederateInfo &fi)
CombinationFederate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
CombinationFederate (const std::string &jsonString)
CombinationFederate (const std::string &name, const std::string &jsonString)
CombinationFederate (CombinationFederate &&fed) noexcept
virtual ~CombinationFederate ()
CombinationFederate & operator= (CombinationFederate &&fed) noexcept
virtual void disconnect () override
virtual void registerInterfaces (const std::string &jsonString) override
CombinationFederate (FederateInfo &fi)
CombinationFederate (const std::string &jsonString)
Public Member Functions inherited from helics::ValueFederate
ValueFederate (const FederateInfo &fi)
ValueFederate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
ValueFederate (const std::string &jsonString)
ValueFederate (const std::string &name, const std::string &jsonString)
ValueFederate ()
ValueFederate (bool res)
ValueFederate (const ValueFederate &fed)=delete
ValueFederate (ValueFederate &&fed) noexcept
virtual ~ValueFederate ()
ValueFederate & operator= (ValueFederate &&fed) noexcept
publication_id_t registerPublication (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
publication_id_t registerPublication (const std::string &key, const std::string &units=std::string())
publication_id_t registerGlobalPublication (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
publication_id_t registerGlobalPublication (const std::string &key, const std::string &units=std::string())
template<typename X >
publication_id_t registerPublicationIndexed (const std::string &key, int index1, const std::string &units=std::string())
template<typename X >
publication_id_t registerPublicationIndexed (const std::string &key, int index1, int index2, const std::string &units=std::string())
subscription_id_t registerRequiredSubscription (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
subscription_id_t registerRequiredSubscription (const std::string &name, const std::string &units=std::string())
template<typename X >
subscription_id_t registerRequiredSubscriptionIndexed (const std::string &key, int index1, const std::string &units=std::string())
template<typename X >
subscription_id_t registerRequiredSubscriptionIndexed (const std::string &key, int index1, int index2, const std::string &units=std::string())
subscription_id_t registerOptionalSubscription (const std::string &key, const std::string &type, const std::string &units=std::string())
template<typename X >
subscription_id_t registerOptionalSubscription (const std::string &key, const std::string &units=std::string())
template<typename X >
subscription_id_t registerOptionalSubscriptionIndexed (const std::string &key, int index1, const std::string &units=std::string())
template<typename X >
subscription_id_t registerOptionalSubscriptionIndexed (const std::string &key, int index1, int index2, const std::string &units=std::string())
void addSubscriptionShortcut (subscription_id_t subid, const std::string &shortcutName)
void setDefaultValue (subscription_id_t id, data_view block)
void setDefaultValue (subscription_id_t id, const data_block &block)
template<typename X >
void setDefaultValue (subscription_id_t id, const X &val)
void registerValueInterfaces (const std::string &jsonString)
data_view getValueRaw (subscription_id_t id)
template<typename X >
void getValue (subscription_id_t id, X &obj)
template<typename X >
X getValue (subscription_id_t id)
void publish (publication_id_t id, data_view block)
void publish (publication_id_t id, const data_block &block)
void publish (publication_id_t id, const char *data)
void publish (publication_id_t id, const char *data, size_t data_size)
template<typename X >
void publish (publication_id_t id, const X &value)
bool isUpdated (subscription_id_t sub_id) const
Time getLastUpdateTime (subscription_id_t sub_id) const
std::vector< subscription_id_t > queryUpdates ()
std::string getSubscriptionKey (subscription_id_t) const
subscription_id_t getSubscriptionId (const std::string &key) const
subscription_id_t getSubscriptionId (const std::string &key, int index1) const
subscription_id_t getSubscriptionId (const std::string &key, int index1, int index2) const
std::string getPublicationKey (publication_id_t) const
publication_id_t getPublicationId (const std::string &key) const
publication_id_t getPublicationId (const std::string &key, int index1) const
publication_id_t getPublicationId (const std::string &key, int index1, int index2) const
std::string getSubscriptionUnits (subscription_id_t id) const
std::string getPublicationUnits (publication_id_t id) const
std::string getSubscriptionType (subscription_id_t id) const
std::string getPublicationType (publication_id_t id) const
std::string getPublicationType (subscription_id_t id) const
void registerSubscriptionNotificationCallback (std::function< void(subscription_id_t, Time)> callback)
void registerSubscriptionNotificationCallback (subscription_id_t id, std::function< void(subscription_id_t, Time)> callback)
void registerSubscriptionNotificationCallback (const std::vector< subscription_id_t > &ids, std::function< void(subscription_id_t, Time)> callback)
int getPublicationCount () const
int getSubscriptionCount () const
ValueFederate (FederateInfo &fi)
ValueFederate (const std::string &jsonString)
ValueFederate (const ValueFederate &vfed)
ValueFederate & operator= (const ValueFederate &fedObj)
Publication registerPublication (const std::string &name, const std::string &type, const std::string &units="")
Publication registerTypePublication (const std::string &name, int type, const std::string &units="")
Publication registerGlobalPublication (const std::string &name, const std::string &type, const std::string &units="")
Publication registerGlobalTypePublication (const std::string &name, int type, const std::string &units="")
Publication registerPublicationIndexed (const std::string &name, int index1, int type, const std::string &units="")
Publication registerPublicationIndexed (const std::string &name, int index1, int index2, int type, const std::string &units="")
Subscription registerSubscription (const std::string &name, const std::string &type, const std::string &units="")
Subscription registerOptionalSubscription (const std::string &name, const std::string &type, const std::string &units="")
Subscription registerTypeSubscription (const std::string &name, int type, const std::string &units="")
Subscription registerSubscriptionIndexed (const std::string &name, int index1, int type, const std::string &units="")
Subscription registerSubscriptionIndexed (const std::string &name, int index1, int index2, int type, const std::string &units="")
int getSubscriptionCount () const
int getPublicationCount () const
std::vector< helics_subscription > queryUpdates ()
Public Member Functions inherited from helics::Federate
Federate (const FederateInfo &fi)
Federate (const std::string &name, const FederateInfo &fi)
Federate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
Federate (const std::string &jsonString)
Federate (const std::string &name, const std::string &jsonString)
Federate () noexcept
Federate (Federate &&fed) noexcept
Federate (const Federate &fed)=delete
virtual ~Federate ()
Federate & operator= (Federate &&fed) noexcept
Federate & operator= (const Federate &fed)=delete
void enterInitializationState ()
void enterInitializationStateAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationStateComplete ()
iteration_result enterExecutionState (iteration_request iterate=iteration_request::no_iterations)
void enterExecutionStateAsync (iteration_request iterate=iteration_request::no_iterations)
iteration_result enterExecutionStateComplete ()
void finalize ()
void error (int errorcode)
void error (int errorcode, const std::string &message)
void setSeparator (char separator)
Time requestTime (Time nextInternalTimeStep)
iteration_time requestTimeIterative (Time nextInternalTimeStep, iteration_request iterate)
void requestTimeAsync (Time nextInternalTimeStep)
void requestTimeIterativeAsync (Time nextInternalTimeStep, iteration_request iterate)
Time requestTimeComplete ()
iteration_time requestTimeIterativeComplete ()
void setTimeDelta (Time tdelta)
void setOutputDelay (Time outputDelay)
void setInputDelay (Time inputDelay)
void setPeriod (Time period, Time offset=timeZero)
virtual void setFlag (int flag, bool flagValue=true)
void setLoggingLevel (int loggingLevel)
void setMaxIterations (int maxIterations)
void setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> &logFunction)
std::string query (const std::string &target, const std::string &queryStr)
std::string query (const std::string &queryStr)
query_id_t queryAsync (const std::string &target, const std::string &queryStr)
query_id_t queryAsync (const std::string &queryStr)
std::string queryComplete (query_id_t queryIndex)
bool isQueryCompleted (query_id_t queryIndex) const
filter_id_t registerSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerDestinationFilter (const std::string &destEndpoint)
filter_id_t registerCloningSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerCloningDestinationFilter (const std::string &destEndpoint)
std::string getFilterName (filter_id_t id) const
std::string getFilterEndpoint (filter_id_t id) const
std::string getFilterInputType (filter_id_t id) const
std::string getFilterOutputType (filter_id_t id) const
filter_id_t getFilterId (const std::string &filterName) const
filter_id_t getSourceFilterId (const std::string &filterName) const
filter_id_t getDestFilterId (const std::string &filterName) const
void setFilterOperator (filter_id_t filter, std::shared_ptr< FilterOperator > op)
register a operator for the specified filter
void setFilterOperator (const std::vector< filter_id_t > &filters, std::shared_ptr< FilterOperator > op)
register a operator for the specified filters
void registerFilterInterfaces (const std::string &jsonString)
auto getID () const noexcept
op_states getCurrentState () const
Time getCurrentTime () const
const std::string & getName () const
std::shared_ptr< Core > getCorePointer ()
std::shared_ptr< Filter > getFilterObject (int index)
void addFilterObject (std::shared_ptr< Filter > obj)
int filterObjectCount () const
Federate (const Federate &fedObj)
Federate & operator= (const Federate &fedObj)
operator helics_federate () const
helics_federate baseObject () const
void setFlag (int flag, int value)
void setOutputDelay (helics_time_t outputDelay)
void setTimeDelta (helics_time_t timeDelta)
void setInputDelay (helics_time_t inputDelay)
void setPeriod (helics_time_t period, helics_time_t offset)
void setMaxIterations (int max_iterations)
void setLoggingLevel (int logLevel)
federate_state getState () const
void enterInitializationMode ()
void enterInitializationModeAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationModeComplete ()
helics_iteration_status enterExecutionMode (helics_iteration_request iterate=no_iteration)
void enterExecutionModeAsync (helics_iteration_request iterate=no_iteration)
helics_iteration_status enterExecutionModeComplete ()
void finalize ()
helics_time_t requestTime (helics_time_t time)
helics_iteration_time requestTimeIterative (helics_time_t time, helics_iteration_request iterate)
void requestTimeAsync (helics_time_t time)
void requestTimeIterativeAsync (helics_time_t time, helics_iteration_request iterate)
helics_time_t requestTimeComplete ()
helics_iteration_time requestTimeIterativeComplete ()
std::string getName () const
std::string query (const std::string &target, const std::string &queryStr)
Filter registerSourceFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
Filter registerDestinationFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
CloningFilter registerCloningFilter (const std::string &deliveryEndpoint)
Public Member Functions inherited from helics::MessageFederate
MessageFederate (const FederateInfo &fi)
MessageFederate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
MessageFederate (const std::string &jsonString)
MessageFederate (const std::string &name, const std::string &jsonString)
MessageFederate (MessageFederate &&mFed) noexcept
MessageFederate ()
MessageFederate (bool res)
~MessageFederate ()
MessageFederate & operator= (MessageFederate &&mFed) noexcept
endpoint_id_t registerEndpoint (const std::string &name, const std::string &type="")
endpoint_id_t registerGlobalEndpoint (const std::string &name, const std::string &type="")
void registerMessageInterfaces (const std::string &jsonString)
void registerKnownCommunicationPath (endpoint_id_t localEndpoint, const std::string &remoteEndpoint)
void subscribe (endpoint_id_t endpoint, const std::string &name, const std::string &type)
bool hasMessage () const
bool hasMessage (endpoint_id_t id) const
uint64_t receiveCount (endpoint_id_t id) const
uint64_t receiveCount () const
std::unique_ptr< Message > getMessage (endpoint_id_t endpoint)
std::unique_ptr< Message > getMessage ()
void sendMessage (endpoint_id_t source, const std::string &dest, const char *data, size_t len)
void sendMessage (endpoint_id_t source, const std::string &dest, const data_view &message)
void sendMessage (endpoint_id_t source, const std::string &dest, const char *data, size_t len, Time sendTime)
void sendMessage (endpoint_id_t source, const std::string &dest, const data_view &message, Time sendTime)
void sendMessage (endpoint_id_t source, std::unique_ptr< Message > message)
void sendMessage (endpoint_id_t source, const Message &message)
std::string getEndpointName (endpoint_id_t id) const
endpoint_id_t getEndpointId (const std::string &name) const
std::string getEndpointType (endpoint_id_t ep)
void registerEndpointCallback (const std::function< void(endpoint_id_t, Time)> &callback)
void registerEndpointCallback (endpoint_id_t ep, const std::function< void(endpoint_id_t, Time)> &callback)
void registerEndpointCallback (const std::vector< endpoint_id_t > &ep, const std::function< void(endpoint_id_t, Time)> &callback)
int getEndpointCount () const
MessageFederate (FederateInfo &fi)
MessageFederate (const std::string &jsonString)
Endpoint registerEndpoint (const std::string &name, const std::string &type="")
Endpoint registerGlobalEndpoint (const std::string &name, const std::string &type="")
bool hasMessage () const
uint64_t receiveCount () const
message_t getMessage ()
Protected Member Functions
virtual void updateTime (Time newTime, Time oldTime) override
virtual void startupToInitializeStateTransition () override
virtual void initializeToExecuteStateTransition () override
Additional Inherited Members
Public Types inherited from helics::Federate
enum op_states : char {
op_states::startup = 0, op_states::initialization = 1, op_states::execution = 2, op_states::finalize = 3,
op_states::error = 4, op_states::pending_init = 5, op_states::pending_exec = 6, op_states::pending_time = 7,
op_states::pending_iterative_time = 8
}
Protected Attributes inherited from helics::Federate
std::atomic< op_states > state {op_states::startup}
the current state of the simulation
char separator_ = '/'
the separator between automatically prependend names
std::shared_ptr< Core > coreObject
reference to the core simulation API
Time currentTime
the current simulation time
FederateInfo FedInfo
the information structure that contains the data on the federate
helics_federate fed
bool exec_async_iterate
Detailed Description
class defining a federate that can use both the value and message interfaces
Constructor & Destructor Documentation
CombinationFederate() [1/6]
helics::CombinationFederate::CombinationFederate () default
default constructor
CombinationFederate() [2/6]
helics::CombinationFederate::CombinationFederate (const FederateInfo & fi) explicit
constructor taking a federate information structure and using the default core
Parameters
fi a federate information structure
CombinationFederate() [3/6]
helics::CombinationFederate::CombinationFederate (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
CombinationFederate() [4/6]
helics::CombinationFederate::CombinationFederate (const std::string & jsonString) explicit
constructor taking a file with the required information
Parameters
[in] file a file defining the federate information
References registerInterfaces().
CombinationFederate() [5/6]
helics::CombinationFederate::CombinationFederate (const std::string & name, const std::string & jsonString)
constructor taking a federate name and a file with the required information
Parameters
[in] file a file defining the federate information
References registerInterfaces().
CombinationFederate() [6/6]
helics::CombinationFederate::CombinationFederate (CombinationFederate && fed) default noexcept
move construction
~CombinationFederate()
helics::CombinationFederate::~CombinationFederate () virtual default
destructor
Member Function Documentation
disconnect()
void helics::CombinationFederate::disconnect () override virtual
disconnect a simulation from the core (will also call finalize before disconnecting if necessary)
Reimplemented from helics::MessageFederate.
References helics::MessageFederate::disconnect(), and helics::ValueFederate::disconnect().
initializeToExecuteStateTransition()
void helics::CombinationFederate::initializeToExecuteStateTransition () override protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented from helics::MessageFederate.
References helics::MessageFederate::initializeToExecuteStateTransition(), and helics::ValueFederate::initializeToExecuteStateTransition().
operator=()
CombinationFederate & helics::CombinationFederate::operator= (CombinationFederate && fed) default noexcept
move assignment
registerInterfaces()
void helics::CombinationFederate::registerInterfaces (const std::string & jsonString) override virtual
register a set of interfaces defined in a file
call is only valid in startup mode
Parameters
[in] jsonString the location of the file or json String to load to generate the interfaces
Reimplemented from helics::MessageFederate.
References helics::Federate::registerFilterInterfaces(), helics::MessageFederate::registerMessageInterfaces(), and helics::ValueFederate::registerValueInterfaces().
Referenced by CombinationFederate().
startupToInitializeStateTransition()
void helics::CombinationFederate::startupToInitializeStateTransition () override protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented from helics::MessageFederate.
References helics::MessageFederate::startupToInitializeStateTransition(), and helics::ValueFederate::startupToInitializeStateTransition().
updateTime()
void helics::CombinationFederate::updateTime (Time newTime, Time oldTime) override protected virtual
function to deal with any operations that need to occur on a time update
Reimplemented from helics::MessageFederate.
References helics::MessageFederate::updateTime(), and helics::ValueFederate::updateTime().
The documentation for this class was generated from the following files:
application_api/CombinationFederate.hpp
CombinationFederate.cpp