helics: Endpoint Class Reference
Endpoint Class Reference
Public Member Functions
Endpoint (helics_endpoint hep)
Endpoint (const Endpoint &endpoint)
Endpoint & operator= (const Endpoint &endpoint)
operator helics_endpoint ()
helics_endpoint baseObject () const
bool hasMessage () const
uint64_t receiveCount () const
message_t getMessage ()
void sendMessage (const std::string &dest, const char *data, size_t len)
void sendMessage (const std::string &dest, const char *data, size_t len, helics_time_t time)
void sendMessage (const std::string &dest, const std::string &data)
void sendMessage (const std::string &dest, const std::string &data, helics_time_t time)
void sendMessage (const std::string &dest, const std::vector< char > &data)
void sendMessage (const std::string &dest, const std::vector< char > &data, helics_time_t time)
void sendMessage (message_t &message)
std::string getName () const
std::string getType ()
Member Function Documentation
getMessage()
message_t Endpoint::getMessage () inline
Get a packet from an endpoint
References helicsEndpointGetMessage().
receiveCount()
uint64_t Endpoint::receiveCount () const inline
Returns the number of pending receives for endpoint
References helicsEndpointReceiveCount().
sendMessage() [1/3]
void Endpoint::sendMessage (const std::string & dest, const char * data, size_t len) inline
Methods for sending a message
References helicsEndpointSendMessageRaw().
sendMessage() [2/3]
void Endpoint::sendMessage (const std::string & dest, const std::string & data) inline
Methods for sending a message
References helicsEndpointSendMessageRaw().
sendMessage() [3/3]
void Endpoint::sendMessage (const std::string & dest, const std::vector< char > & data) inline
Methods for sending a message
References helicsEndpointSendMessageRaw().
The documentation for this class was generated from the following file:
Endpoint.hpp