helics: helics::apps::Recorder Class Reference
helics::apps::Recorder Class Reference
#include <Recorder.hpp>
Public Member Functions
Recorder (FederateInfo &fi)
Recorder (int argc, char *argv[])
Recorder (const std::shared_ptr< Core > &core, const FederateInfo &fi)
Recorder (const std::string &jsonString)
Recorder (Recorder &&other_recorder)=default
Recorder & operator= (Recorder &&record)=default
~Recorder ()
virtual void runTo (Time stopTime) override
void addSubscription (const std::string &key)
void addEndpoint (const std::string &endpoint)
void addSourceEndpointClone (const std::string &sourceEndpoint)
void addDestEndpointClone (const std::string &destEndpoint)
void addCapture (const std::string &captureDesc)
void saveFile (const std::string &filename)
auto pointCount () const
auto messageCount () const
std::pair< std::string, std::string > getValue (int index) const
std::unique_ptr< Message > getMessage (int index) const
Public Member Functions inherited from helics::apps::App
App ()=default
App (const std::string &appName, int argc, char *argv[])
App (const FederateInfo &fi)
App (const std::shared_ptr< Core > &core, const FederateInfo &fi)
App (const std::string &appName, const std::string &jsonString)
App (App &&other_app)=default
App (const App &other_app)=delete
App & operator= (App &&fed)=default
App & operator= (const App &fed)=delete
void loadFile (const std::string &filename)
virtual void run ()
virtual void finalize ()
bool isActive () const
Protected Attributes
bool allow_iteration = false
trigger to allow Iteration
std::unique_ptr< CloningFilter > cFilt
a pointer to a clone filter
std::vector< ValueCapture > points
lists of points that were captured
std::vector< Subscription > subscriptions
the actual subscription objects
std::vector< Endpoint > endpoints
the actual endpoint objects
std::unique_ptr< Endpoint > cloneEndpoint
the endpoint for cloned message delivery
std::vector< std::unique_ptr< Message > > messages
list of messages
std::map< helics::subscription_id_t, int > subids
map of the subscription ids
std::map< std::string, int > subkeys
translate subscription names to an index
std::map< helics::endpoint_id_t, int > eptids
std::map< std::string, int > eptNames
translate endpoint name to index
std::vector< ValueStats > vStat
storage for statistics capture
std::vector< std::string > captureInterfaces
storage for the interfaces to capture
std::string mapfile
file name for the on-line file updater
std::string outFileName
the final output file
Protected Attributes inherited from helics::apps::App
std::shared_ptr< CombinationFederate > fed
the federate created for the Player
Time stopTime = Time::maxVal ()
the time the Player should stop
std::string masterFileName
the name of the master file used to do the construction
bool useLocal = false
bool fileLoaded = false
bool deactivated = false
bool quietMode = false
Additional Inherited Members
Protected Member Functions inherited from helics::apps::App
int loadArguments (boost::program_options::variables_map &vm_map)
void loadJsonFileConfiguration (const std::string &appName, const std::string &jsonString)
Detailed Description
class designed to capture data points from a set of subscriptions or endpoints
Constructor & Destructor Documentation
Recorder() [1/5]
helics::apps::Recorder::Recorder (FederateInfo & fi) explicit
construct from a FederateInfo structure
References helics::apps::App::fed, and OBSERVER_FLAG.
Recorder() [2/5]
helics::apps::Recorder::Recorder (int argc, char * argv[])
construct from command line arguments
References helics::argumentParser(), helics::apps::App::fed, helics::apps::App::loadFile(), helics::apps::App::masterFileName, and OBSERVER_FLAG.
Recorder() [3/5]
helics::apps::Recorder::Recorder (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
References helics::apps::App::fed, and OBSERVER_FLAG.
Recorder() [4/5]
helics::apps::Recorder::Recorder (const std::string & jsonString) explicit
constructor taking a file with the required information
Parameters
[in] file a file defining the federate information
References helics::apps::App::fed, and OBSERVER_FLAG.
Recorder() [5/5]
helics::apps::Recorder::Recorder (Recorder && other_recorder) default
move construction
~Recorder()
helics::apps::Recorder::~Recorder ()
destructor
References outFileName, and saveFile().
Member Function Documentation
addCapture()
void helics::apps::Recorder::addCapture (const std::string & captureDesc)
add a capture interface
Parameters
captureDesc describes a federate to capture all the interfaces for
References captureInterfaces.
addDestEndpointClone()
void helics::apps::Recorder::addDestEndpointClone (const std::string & destEndpoint)
copy all messages that are going to a specific endpoint
References cFilt, cloneEndpoint, and helics::apps::App::fed.
addEndpoint()
void helics::apps::Recorder::addEndpoint (const std::string & endpoint)
add an endpoint
addSourceEndpointClone()
void helics::apps::Recorder::addSourceEndpointClone (const std::string & sourceEndpoint)
copy all messages that come from a specified endpoint
References cFilt, cloneEndpoint, and helics::apps::App::fed.
addSubscription()
void helics::apps::Recorder::addSubscription (const std::string & key)
add a subscription to capture
add a subscription to record
References helics::apps::App::fed, subids, subkeys, and subscriptions.
getMessage()
std::unique_ptr< Message > helics::apps::Recorder::getMessage (int index) const
get a message
makes a copy of a message and returns it in a unique_ptr
Parameters
index the number of the message to retrieve
References helics::isValidIndex(), and messages.
getValue()
std::pair< std::string, std::string > helics::apps::Recorder::getValue (int index) const
get a string with the value of point index
Parameters
index the number of the point to retrieve
Returns
a pair with the tag as the first element and the value as the second
References helics::isValidIndex(), points, and subscriptions.
messageCount()
auto helics::apps::Recorder::messageCount () const inline
get the number of captured messages
References messages.
operator=()
Recorder& helics::apps::Recorder::operator= (Recorder && record) default
move assignment
pointCount()
auto helics::apps::Recorder::pointCount () const inline
get the number of captured points
References points.
runTo()
void helics::apps::Recorder::runTo (Time runToTime) override virtual
run the Player until the specified time
Implements helics::apps::App.
References allow_iteration, helics::apps::App::fed, helics::iterate_if_needed, mapfile, helics::next_step, and vStat.
saveFile()
void helics::apps::Recorder::saveFile (const std::string & filename)
save the data to a file
Referenced by ~Recorder().
The documentation for this class was generated from the following files:
Recorder.hpp
Recorder.cpp