helics: helics::Publication Class Reference
helics::Publication Class Reference
#include <Publications.hpp>
Public Member Functions
Publication ()=default
template<class FedPtr >
Publication (FedPtr valueFed, const std::string &key, helics_type_t type, const std::string &units=std::string())
template<class FedPtr >
Publication (interface_visibility locality, FedPtr valueFed, const std::string &key, helics_type_t type, const std::string &units=std::string())
Publication (ValueFederate *valueFed, int pubIndex)
void publish (double val) const
void publish (int64_t val) const
void publish (const char *val) const
void publish (const std::string &val) const
void publish (const std::vector< double > &val) const
void publish (const std::vector< std::complex< double >> &val) const
void publish (const double *vals, int size) const
void publish (std::complex< double > val) const
void publish (const defV &val) const
void publish (bool val) const
template<class X >
void publish (const X &val, const std::string &) const
void setMinimumChange (double deltaV)
void enableChangeDetection (bool enabled=true)
Publication (helics_publication hpub)
Publication (const Publication &publication)
Publication & operator= (const Publication &publication)
operator helics_publication () const
helics_publication baseObject () const
void publish (const char *data, int len)
void publish (std::string str)
void publish (int64_t val)
void publish (double val)
void publish (std::complex< double > cmplx)
void publish (std::vector< double > data)
std::string getKey () const
std::string getUnits () const
std::string getType () const
Public Member Functions inherited from helics::PublicationBase
template<class FedPtr >
PublicationBase (FedPtr valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
template<class FedPtr >
PublicationBase (interface_visibility locality, FedPtr valueFed, const std::string &key, const std::string &type, const std::string &units=std::string())
PublicationBase (ValueFederate *valueFed, int pubIndex)
virtual ~PublicationBase ()=default
publication_id_t getID () const
std::string getKey () const
const std::string & getName () const
const std::string & getType () const
const std::string & getUnits () const
Additional Inherited Members
Protected Attributes inherited from helics::PublicationBase
ValueFederate * fed = nullptr
the federate construct to interact with
publication_id_t id
the internal id of the publication
Detailed Description
class wrapping the calls for a publication in an object so identifiers and pointers do not need to be used for every call
Constructor & Destructor Documentation
Publication() [1/4]
helics::Publication::Publication () default
default constructor
Publication() [2/4]
template<class FedPtr > helics::Publication::Publication (FedPtr valueFed, const std::string & key, helics_type_t type, const std::string & units = std::string ()) inline
constructor to build a publication object
Parameters
[in] valueFed the ValueFederate to use
[in] key the identifier for the publication
type_ the defined type of the publication
[in] units the units associated with a Federate
Publication() [3/4]
template<class FedPtr > helics::Publication::Publication (interface_visibility locality, FedPtr valueFed, const std::string & key, helics_type_t type, const std::string & units = std::string ()) inline
constructor to build a publication object
Parameters
locality set to global for a global publication or local for a local one
[in] valueFed the ValueFederate to use
[in] key the identifier for the publication
type_ the defined type of the publication
[in] units the units associated with a Federate
Publication() [4/4]
helics::Publication::Publication (ValueFederate * valueFed, int pubIndex) inline
generate a publication object from a preexisting publication
Parameters
valueFed a pointer to the appropriate value Federate
pubIndex the index of the subscription
Member Function Documentation
enableChangeDetection()
void helics::Publication::enableChangeDetection (bool enabled = true) inline
if set to false, the change detection mechanisms are not enabled if set to true the values will be published if there is sufficient change as specified in the call to setMinimumChange
publish() [1/3]
void helics::Publication::publish (const char * data, int len) inline
Methods to publish values
References helicsPublicationPublishRaw().
publish() [2/3]
void helics::Publication::publish (double val) const
send a value for publication
Parameters
[in] val the value to publish
References helics::changeDetected(), helics::PublicationBase::fed, helics::ValueFederate::publish(), and helics::typeConvert().
Referenced by publish().
publish() [3/3]
template<class X > void helics::Publication::publish (const X & val, const std::string &) const inline
secondary publish function to allow unit conversion before publication
Parameters
[in] val the value to publish
[in] units the units association with the publication
References publish().
setMinimumChange()
void helics::Publication::setMinimumChange (double deltaV) inline
set the level by which a value must have changed to actually publish the value
The documentation for this class was generated from the following files:
Publications.hpp
Publication.hpp
Publications.cpp