helics: helics::LoggingCore Class Reference
helics::LoggingCore Class Reference
#include <logger.h>
Public Member Functions
LoggingCore ()
~LoggingCore ()
void addMessage (const std::string &message)
void addMessage (std::string &&message)
void addMessage (int index, const std::string &message)
void addMessage (int index, std::string &&message)
int addFileProcessor (std::function< void(std::string &&message)> newFunction)
void haltOperations (int)
void updateProcessingFunction (int index, std::function< void(std::string &&message)> newFunction)
Static Public Member Functions
static void setFastShutdown ()
Detailed Description
class to manage a single thread for all logging
Constructor & Destructor Documentation
LoggingCore()
helics::LoggingCore::LoggingCore ()
default constructor
~LoggingCore()
helics::LoggingCore::~LoggingCore ()
destructor
References BlockingQueue< T >::emplace(), and tripwire::TripWireDetector::isTripped().
Member Function Documentation
addFileProcessor()
int helics::LoggingCore::addFileProcessor (std::function< void(std::string &&message)> newFunction)
add a file processing callback (not just files)
Parameters
newFunction the callback to call on receipt of a message
addMessage() [1/4]
void helics::LoggingCore::addMessage (const std::string & message)
add a message for the LoggingCore or just general console print
References BlockingQueue< T >::emplace().
addMessage() [2/4]
void helics::LoggingCore::addMessage (std::string && message)
move a message for the LoggingCore or just general console print
References BlockingQueue< T >::emplace().
addMessage() [3/4]
void helics::LoggingCore::addMessage (int index, const std::string & message)
add a message for a specific Logger
Parameters
index the index of the function callback to use
message the message to send
References BlockingQueue< T >::emplace().
addMessage() [4/4]
void helics::LoggingCore::addMessage (int index, std::string && message)
add a message for a specific Logger
Parameters
index the index of the function callback to use
message the message to send
References BlockingQueue< T >::emplace().
haltOperations()
void helics::LoggingCore::haltOperations (int loggerIndex)
remove a function callback
setFastShutdown()
void helics::LoggingCore::setFastShutdown () static
enable a fast shutdown in situations where a thread may be force-ably terminated
updateProcessingFunction()
void helics::LoggingCore::updateProcessingFunction (int index, std::function< void(std::string &&message)> newFunction)
update a callback for a particular instance
The documentation for this class was generated from the following files:
logger.h
logger.cpp