helics: helics::Federate Class Reference
helics::Federate Class Reference
#include <Federate.hpp>
Public Types
enum op_states : char {
op_states::startup = 0, op_states::initialization = 1, op_states::execution = 2, op_states::finalize = 3,
op_states::error = 4, op_states::pending_init = 5, op_states::pending_exec = 6, op_states::pending_time = 7,
op_states::pending_iterative_time = 8
}
Public Member Functions
Federate (const FederateInfo &fi)
Federate (const std::string &name, const FederateInfo &fi)
Federate (const std::shared_ptr< Core > &core, const FederateInfo &fi)
Federate (const std::string &jsonString)
Federate (const std::string &name, const std::string &jsonString)
Federate () noexcept
Federate (Federate &&fed) noexcept
Federate (const Federate &fed)=delete
virtual ~Federate ()
Federate & operator= (Federate &&fed) noexcept
Federate & operator= (const Federate &fed)=delete
void enterInitializationState ()
void enterInitializationStateAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationStateComplete ()
iteration_result enterExecutionState (iteration_request iterate=iteration_request::no_iterations)
void enterExecutionStateAsync (iteration_request iterate=iteration_request::no_iterations)
iteration_result enterExecutionStateComplete ()
void finalize ()
virtual void disconnect ()
void error (int errorcode)
void error (int errorcode, const std::string &message)
void setSeparator (char separator)
Time requestTime (Time nextInternalTimeStep)
iteration_time requestTimeIterative (Time nextInternalTimeStep, iteration_request iterate)
void requestTimeAsync (Time nextInternalTimeStep)
void requestTimeIterativeAsync (Time nextInternalTimeStep, iteration_request iterate)
Time requestTimeComplete ()
iteration_time requestTimeIterativeComplete ()
void setTimeDelta (Time tdelta)
void setOutputDelay (Time outputDelay)
void setInputDelay (Time inputDelay)
void setPeriod (Time period, Time offset=timeZero)
virtual void setFlag (int flag, bool flagValue=true)
void setLoggingLevel (int loggingLevel)
void setMaxIterations (int maxIterations)
void setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> &logFunction)
std::string query (const std::string &target, const std::string &queryStr)
std::string query (const std::string &queryStr)
query_id_t queryAsync (const std::string &target, const std::string &queryStr)
query_id_t queryAsync (const std::string &queryStr)
std::string queryComplete (query_id_t queryIndex)
bool isQueryCompleted (query_id_t queryIndex) const
filter_id_t registerSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningSourceFilter (const std::string &filterName, const std::string &sourceEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerCloningDestinationFilter (const std::string &filterName, const std::string &destEndpoint, const std::string &inputType=std::string(), const std::string &outputType=std::string())
filter_id_t registerSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerDestinationFilter (const std::string &destEndpoint)
filter_id_t registerCloningSourceFilter (const std::string &sourceEndpoint)
filter_id_t registerCloningDestinationFilter (const std::string &destEndpoint)
std::string getFilterName (filter_id_t id) const
std::string getFilterEndpoint (filter_id_t id) const
std::string getFilterInputType (filter_id_t id) const
std::string getFilterOutputType (filter_id_t id) const
filter_id_t getFilterId (const std::string &filterName) const
filter_id_t getSourceFilterId (const std::string &filterName) const
filter_id_t getDestFilterId (const std::string &filterName) const
void setFilterOperator (filter_id_t filter, std::shared_ptr< FilterOperator > op)
register a operator for the specified filter
void setFilterOperator (const std::vector< filter_id_t > &filters, std::shared_ptr< FilterOperator > op)
register a operator for the specified filters
virtual void registerInterfaces (const std::string &jsonString)
void registerFilterInterfaces (const std::string &jsonString)
auto getID () const noexcept
op_states getCurrentState () const
Time getCurrentTime () const
const std::string & getName () const
std::shared_ptr< Core > getCorePointer ()
std::shared_ptr< Filter > getFilterObject (int index)
void addFilterObject (std::shared_ptr< Filter > obj)
int filterObjectCount () const
Federate (const Federate &fedObj)
Federate & operator= (const Federate &fedObj)
operator helics_federate () const
helics_federate baseObject () const
void setFlag (int flag, int value)
void setOutputDelay (helics_time_t outputDelay)
void setTimeDelta (helics_time_t timeDelta)
void setInputDelay (helics_time_t inputDelay)
void setPeriod (helics_time_t period, helics_time_t offset)
void setMaxIterations (int max_iterations)
void setLoggingLevel (int logLevel)
federate_state getState () const
void enterInitializationMode ()
void enterInitializationModeAsync ()
bool isAsyncOperationCompleted () const
void enterInitializationModeComplete ()
helics_iteration_status enterExecutionMode (helics_iteration_request iterate=no_iteration)
void enterExecutionModeAsync (helics_iteration_request iterate=no_iteration)
helics_iteration_status enterExecutionModeComplete ()
void finalize ()
helics_time_t requestTime (helics_time_t time)
helics_iteration_time requestTimeIterative (helics_time_t time, helics_iteration_request iterate)
void requestTimeAsync (helics_time_t time)
void requestTimeIterativeAsync (helics_time_t time, helics_iteration_request iterate)
helics_time_t requestTimeComplete ()
helics_iteration_time requestTimeIterativeComplete ()
std::string getName () const
std::string query (const std::string &target, const std::string &queryStr)
Filter registerSourceFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
Filter registerDestinationFilter (helics_filter_type_t type, const std::string &target, const std::string &name=std::string())
CloningFilter registerCloningFilter (const std::string &deliveryEndpoint)
Protected Member Functions
virtual void updateTime (Time newTime, Time oldTime)
virtual void startupToInitializeStateTransition ()
virtual void initializeToExecuteStateTransition ()
Protected Attributes
std::atomic< op_states > state {op_states::startup}
the current state of the simulation
char separator_ = '/'
the separator between automatically prependend names
std::shared_ptr< Core > coreObject
reference to the core simulation API
Time currentTime
the current simulation time
FederateInfo FedInfo
the information structure that contains the data on the federate
helics_federate fed
bool exec_async_iterate
Detailed Description
base class for a federate in the application API
Member Enumeration Documentation
op_states
enum helics::Federate::op_states : char strong
the allowable states of the federate
Enumerator
startup
when created the federate is in startup state
initialization
entered after the enterInitializationState call has returned
execution
entered after the enterExectuationState call has returned
finalize
the federate has finished executing normally final values may be retrieved
error
error state no core communication is possible but values can be retrieved
pending_init
indicator that the federate is pending entry to initialization state
pending_exec
state pending EnterExecution State
pending_time
state that the federate is pending a timeRequest
pending_iterative_time
state that the federate is pending an iterative time request
Constructor & Destructor Documentation
Federate() [1/6]
helics::Federate::Federate (const FederateInfo & fi) explicit
constructor taking a federate information structure
Parameters
[in] fi a federate information structure
Federate() [2/6]
helics::Federate::Federate (const std::string & name, const FederateInfo & fi)
constructor taking a federate information structure
Parameters
[in] fi a federate information structure
make sure the core is connected
References helics::CoreFactory::cleanUpCores(), helics::FederateInfo::coreInitString, helics::FederateInfo::coreName, coreObject, helics::FederateInfo::coreType, helics::CoreFactory::create(), currentTime, helics::CoreFactory::findJoinableCoreOfType(), helics::CoreFactory::FindOrCreate(), helics::FederateInfo::separator, and separator_.
Federate() [3/6]
helics::Federate::Federate (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a core and a federate information structure
Parameters
core a shared pointer to a core object, the pointer will be copied
[in] fi a federate information structure
make sure the core is connected
References helics::FederateInfo::coreInitString, helics::FederateInfo::coreName, coreObject, helics::FederateInfo::coreType, helics::CoreFactory::create(), currentTime, error, helics::CoreFactory::findJoinableCoreOfType(), helics::CoreFactory::FindOrCreate(), helics::FederateInfo::name, helics::FederateInfo::separator, separator_, and state.
Federate() [4/6]
helics::Federate::Federate (const std::string & jsonString) explicit
constructor taking a file with the required information
Parameters
[in] jsonString can be either a JSON file or a string containing JSON code
References registerFilterInterfaces().
Federate() [5/6]
helics::Federate::Federate (const std::string & name, const std::string & jsonString)
constructor taking a file with the required information and the name of the federate
Parameters
[in] name the name of the federate
[in] jsonString can be either a JSON file or a string containing JSON code
References registerFilterInterfaces().
Federate() [6/6]
helics::Federate::Federate () noexcept
default constructor
~Federate()
helics::Federate::~Federate () virtual
virtual destructor function
References coreObject, and finalize().
Member Function Documentation
addFilterObject()
void helics::Federate::addFilterObject (std::shared_ptr< Filter > obj)
add a shared pointer object to the Federate
disconnect()
void helics::Federate::disconnect () virtual
disconnect a simulation from the core (will also call finalize before disconnecting if necessary)
Reimplemented in helics::ValueFederate, helics::MessageFederate, and helics::CombinationFederate.
References coreObject, finalize, and state.
Referenced by helics::MessageFederate::disconnect(), and helics::ValueFederate::disconnect().
enterExecutionState()
iteration_result helics::Federate::enterExecutionState (iteration_request iterate = iteration_request::no_iterations)
enter the normal execution mode
call will block until all federates have entered this mode
Parameters
iterate an optional flag indicating the desired iteration mode
References coreObject, currentTime, enterExecutionStateComplete(), enterInitializationState(), helics::error, error, execution, finalize, getCurrentTime(), helics::halted, initialization, initializeToExecuteStateTransition(), helics::iterating, helics::next_step, pending_exec, pending_init, pending_iterative_time, pending_time, requestTimeComplete(), startup, state, and updateTime().
enterExecutionStateAsync()
void helics::Federate::enterExecutionStateAsync (iteration_request iterate = iteration_request::no_iterations)
enter the normal execution mode
call will block until all federates have entered this mode
References coreObject, enterInitializationStateComplete(), execution, initialization, pending_exec, pending_init, startup, startupToInitializeStateTransition(), and state.
enterExecutionStateComplete()
iteration_result helics::Federate::enterExecutionStateComplete ()
complete the async call for entering Execution state
call will not block but will return quickly. The enterInitializationStateFinalize must be called before doing other operations
References currentTime, helics::error, error, execution, finalize, getCurrentTime(), helics::halted, initialization, initializeToExecuteStateTransition(), helics::iterating, helics::next_step, pending_exec, state, and updateTime().
Referenced by enterExecutionState(), and finalize().
enterInitializationState()
void helics::Federate::enterInitializationState ()
enter the initialization mode after all interfaces have been defined
the call will block until all federates have entered initialization mode
References coreObject, currentTime, enterInitializationStateComplete(), initialization, pending_init, startup, startupToInitializeStateTransition(), and state.
Referenced by enterExecutionState(), and enterInitializationStateComplete().
enterInitializationStateAsync()
void helics::Federate::enterInitializationStateAsync ()
enter the initialization mode after all interfaces have been defined
the call will not block
References coreObject, initialization, pending_init, startup, and state.
enterInitializationStateComplete()
void helics::Federate::enterInitializationStateComplete ()
second part of the async process for entering initializationState call after a call to enterInitializationStateAsync if call any other time it will throw an InvalidFunctionCall exception
References coreObject, currentTime, enterInitializationState(), initialization, pending_init, startup, startupToInitializeStateTransition(), and state.
Referenced by enterExecutionStateAsync(), enterInitializationState(), and finalize().
error() [1/2]
void helics::Federate::error (int errorcode)
specify the simulator had an unrecoverable error
References coreObject, error, FedInfo, helics::FederateInfo::name, and state.
error() [2/2]
void helics::Federate::error (int errorcode, const std::string & message)
specify the simulator had an error with error code and message
References coreObject, error, and state.
filterObjectCount()
int helics::Federate::filterObjectCount () const
get a count of the number of filter objects stored in the federate
finalize()
void helics::Federate::finalize ()
terminate the simulation
call is normally non-blocking, but may block if called in the midst of an asynchronous call sequence, no core calling commands may be called after completion of this function
References coreObject, enterExecutionStateComplete(), enterInitializationStateComplete(), error, execution, finalize, initialization, pending_exec, pending_init, pending_iterative_time, pending_time, requestTimeComplete(), requestTimeIterativeComplete(), startup, and state.
Referenced by ~Federate().
getCorePointer()
std::shared_ptr<Core> helics::Federate::getCorePointer () inline
get a pointer to the core object used by the federate
Referenced by helics::CloningFilter::CloningFilter(), and helics::Filter::Filter().
getCurrentState()
op_states helics::Federate::getCurrentState () const inline
get the current state of the federate
getCurrentTime()
Time helics::Federate::getCurrentTime () const inline
get the current Time
the most recent granted time of the federate
Referenced by enterExecutionState(), and enterExecutionStateComplete().
getDestFilterId()
filter_id_t helics::Federate::getDestFilterId (const std::string & filterName) const
get the id of a destination filter from the name of the endpoint
Parameters
[in] filterName the publication id
Returns
invalid_filter_id if name is not recognized otherwise returns the filter id
References coreObject, and helics::invalid_id_value.
getFilterEndpoint()
std::string helics::Federate::getFilterEndpoint (filter_id_t id) const
get the name of the endpoint that a filter is associated with
Parameters
[in] id the filter to query
Returns
empty string if an invalid id is passed
References coreObject.
getFilterId()
filter_id_t helics::Federate::getFilterId (const std::string & filterName) const
get the id of a source filter from the name of the endpoint
Parameters
[in] filterName the name of the filter
Returns
invalid_filter_id if name is not recognized otherwise returns the filter id
References coreObject, and helics::invalid_id_value.
getFilterInputType()
std::string helics::Federate::getFilterInputType (filter_id_t id) const
get the input type of a filter from its id
Parameters
[in] id the endpoint to query
Returns
empty string if an invalid id is passed
References coreObject.
getFilterName()
std::string helics::Federate::getFilterName (filter_id_t id) const
get the name of a filter
Parameters
[in] id the filter to query
Returns
empty string if an invalid id is passed
References coreObject.
getFilterObject()
std::shared_ptr< Filter > helics::Federate::getFilterObject (int index)
get a shared pointer to a filter object stored in the federate
filters can be created through the JSON file in which case there is no reference to them elsewhere. They are stored in the federate unless retrieved
Parameters
index the index number of the stored federate
Returns
a shared_ptr to a filter object
References helics::isValidIndex().
getFilterOutputType()
std::string helics::Federate::getFilterOutputType (filter_id_t id) const
get the output type of a filter from its id
Parameters
[in] id the endpoint to query
Returns
empty string if an invalid id is passed
References coreObject.
getID()
auto helics::Federate::getID () const inline noexcept
get the underlying federateID for the core
Referenced by helics::MessageFederate::MessageFederate(), and helics::ValueFederate::ValueFederate().
getName()
const std::string& helics::Federate::getName () const inline
get the federate name
Referenced by helics::MessageFederate::getEndpointId(), helics::ValueFederate::getPublicationId(), query(), helics::MessageFederate::registerEndpoint(), and helics::ValueFederate::registerPublication().
getSourceFilterId()
filter_id_t helics::Federate::getSourceFilterId (const std::string & filterName) const
get the id of a source filter from the name of the filter
Parameters
[in] filterName the publication id
Returns
invalid_filter_id if name is not recognized otherwise returns the filter id
References coreObject, and helics::invalid_id_value.
initializeToExecuteStateTransition()
void helics::Federate::initializeToExecuteStateTransition () protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented in helics::ValueFederate, helics::MessageFederate, and helics::CombinationFederate.
Referenced by enterExecutionState(), and enterExecutionStateComplete().
isAsyncOperationCompleted()
bool helics::Federate::isAsyncOperationCompleted () const
called after one of the async calls and will indicate true if an async operation has completed
only call from the same thread as the one that called the initial async call and will return false if called when no aysnc operation is in flight
References pending_exec, pending_init, pending_iterative_time, pending_time, and state.
isQueryCompleted()
bool helics::Federate::isQueryCompleted (query_id_t queryIndex) const
check if an asynchronous query call has been completed
Returns
true if the results are ready for
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
operator=() [1/2]
Federate & helics::Federate::operator= (Federate && fed) noexcept
default move assignment
References state.
Referenced by helics::MessageFederate::operator=(), and helics::ValueFederate::operator=().
operator=() [2/2]
Federate& helics::Federate::operator= (const Federate & fed) delete
delete copy assignment
query() [1/3]
std::string helics::Federate::query (const std::string & target, const std::string & queryStr)
make a query of the core
this call is blocking until the value is returned which make take some time depending on the size of the federation and the specific string being queried
Parameters
target the target of the query can be "federation", "federate", "broker", "core", or a specific name of a federate, core, or broker
queryStr a string with the query see other documentation for specific properties to query, can be defined by the federate
Returns
a string with the value requested. this is either going to be a vector of strings value or a json string stored in the first element of the vector. The string "#invalid" is returned if the query was not valid
References coreObject.
Referenced by queryAsync(), waitForFed(), and waitForInit().
query() [2/3]
std::string helics::Federate::query (const std::string & target, const std::string & queryStr) inline
make a query of the core
this call is blocking until the value is returned which make take some time depending on the size of the federation and the specific string being queried
Parameters
target the target of the query can be "federation", "federate", "broker", "core", or a specific name of a federate, core, or broker
queryStr a string with the query see other documentation for specific properties to query, can be defined by the federate
Returns
a string with the value requested. this is either going to be a vector of strings value or a json string stored in the first element of the vector. The string "#invalid" is returned if the query was not valid
References helicsCreateQuery(), helicsQueryExecute(), and helicsQueryFree().
query() [3/3]
std::string helics::Federate::query (const std::string & queryStr)
make a query of the core
this call is blocking until the value is returned which make take some time depending on the size of the federation and the specific string being queried
Parameters
queryStr a string with the query see other documentation for specific properties to query, can be defined by the federate if the local federate does not recognize the query it sends it on to the federation
Returns
a string with the value requested. this is either going to be a vector of strings value or a json string stored in the first element of the vector. The string "#invalid" is returned if the query was not valid
References coreObject, and getName().
queryAsync() [1/2]
query_id_t helics::Federate::queryAsync (const std::string & target, const std::string & queryStr)
make a query of the core in an async fashion
this call is blocking until the value is returned which make take some time depending on the size of the federation and the specific string being queried
Parameters
target the target of the query can be "federation", "federate", "broker", "core", or a specific name of a federate, core, or broker
queryStr a string with the query see other documentation for specific properties to query, can be defined by the federate
Returns
a query_id_t to use for returning the result
References coreObject.
queryAsync() [2/2]
query_id_t helics::Federate::queryAsync (const std::string & queryStr)
make a query of the core in an async fashion
this call is blocking until the value is returned which make take some time depending on the size of the federation and the specific string being queried
Parameters
queryStr a string with the query see other documentation for specific properties to query, can be defined by the federate
Returns
a query_id_t used to get the results of the query in the future
References query().
queryComplete()
std::string helics::Federate::queryComplete (query_id_t queryIndex)
get the results of an async query
the call will block until the results are returned inquiry of queryCompleted() to check if the results have been returned or not yet
Parameters
queryIndex the int value returned from the queryAsync call
Returns
a string with the value requested. the format of the string will be either a single string a string vector like "[string1; string2]" or json The string "#invalid" is returned if the query was not valid
References helics::identifier_id_t< BaseType, ID, invalidValue >::value().
registerCloningDestinationFilter() [1/2]
filter_id_t helics::Federate::registerCloningDestinationFilter (const std::string & filterName, const std::string & destEndpoint, const std::string & inputType = std::string (), const std::string & outputType = std::string ())
define a cloning filter interface for a destination
a destination filter will be sent any packets that are going to a particular destination multiple filters are not allowed to specify the same destination
Parameters
[in] the name of the destination endpoint
[in] the inputType which the destination filter can receive
References coreObject.
registerCloningDestinationFilter() [2/2]
filter_id_t helics::Federate::registerCloningDestinationFilter (const std::string & destEndpoint) inline
define a cloning filter interface for a destination
a destination filter will be sent any packets that are going to a particular destination multiple filters are not allowed to specify the same destination
Parameters
[in] the name of the destination endpoint
[in] the inputType which the destination filter can receive
registerCloningFilter()
CloningFilter helics::Federate::registerCloningFilter (const std::string & deliveryEndpoint) inline
create a cloning Filter on the specified federate
cloning filters copy a message and send it to multiple locations source and destination can be added through other functions
Parameters
fed the fed to register through
deliveryEndpoint the specified endpoint to deliver the message
Returns
a helics_filter object
References helicsFederateRegisterCloningFilter().
registerCloningSourceFilter() [1/2]
filter_id_t helics::Federate::registerCloningSourceFilter (const std::string & filterName, const std::string & sourceEndpoint, const std::string & inputType = std::string (), const std::string & outputType = std::string ())
define a cloning filter interface on a source
a source filter will be sent any packets that come from a particular source if multiple filters are defined on the same source, they will be placed in some order defined by the core
Parameters
[in] the name of the endpoint
[in] the inputType which the source filter can receive
References coreObject.
registerCloningSourceFilter() [2/2]
filter_id_t helics::Federate::registerCloningSourceFilter (const std::string & sourceEndpoint) inline
define a cloning filter interface on a source
a source filter will be sent any packets that come from a particular source if multiple filters are defined on the same source, they will be placed in some order defined by the core
Parameters
[in] the name of the endpoint
[in] the inputType which the source filter can receive
registerDestinationFilter() [1/3]
Filter helics::Federate::registerDestinationFilter (helics_filter_type_t type, const std::string & target, const std::string & name = std::string ()) inline
create a destination Filter on the specified federate
filters can be created through a federate or a core , linking through a federate allows a few extra features of name matching to function on the federate interface but otherwise equivalent behavior
Parameters
fed the fed to register through
type the type of filter to create
target the name of endpoint to target
name the name of the filter (can be NULL)
Returns
a helics_filter object
References helicsFederateRegisterDestinationFilter().
registerDestinationFilter() [2/3]
filter_id_t helics::Federate::registerDestinationFilter (const std::string & filterName, const std::string & destEndpoint, const std::string & inputType = std::string (), const std::string & outputType = std::string ())
define a filter interface for a destination
a destination filter will be sent any packets that are going to a particular destination multiple filters are not allowed to specify the same destination
Parameters
[in] the name of the destination endpoint
[in] the inputType which the destination filter can receive
References coreObject.
Referenced by helics::DestinationFilter::DestinationFilter(), and registerFilterInterfaces().
registerDestinationFilter() [3/3]
filter_id_t helics::Federate::registerDestinationFilter (const std::string & destEndpoint) inline
define a filter interface for a destination
a destination filter will be sent any packets that are going to a particular destination multiple filters are not allowed to specify the same destination
Parameters
[in] the name of the destination endpoint
[in] the inputType which the destination filter can receive
registerFilterInterfaces()
void helics::Federate::registerFilterInterfaces (const std::string & jsonString)
register filter interfaces defined in file or string
call is only valid in startup mode
Parameters
[in] jsonString the location of the file or json String to load to generate the interfaces
References loadJsonString(), registerDestinationFilter(), and registerSourceFilter().
Referenced by Federate(), helics::CombinationFederate::registerInterfaces(), helics::MessageFederate::registerInterfaces(), and registerInterfaces().
registerInterfaces()
void helics::Federate::registerInterfaces (const std::string & jsonString) virtual
register a set of interfaces defined in a file
call is only valid in startup mode
Parameters
[in] jsonString the location of the file or json String to load to generate the interfaces
Reimplemented in helics::ValueFederate, helics::MessageFederate, and helics::CombinationFederate.
References registerFilterInterfaces().
Referenced by helics::ValueFederate::registerInterfaces().
registerSourceFilter() [1/2]
filter_id_t helics::Federate::registerSourceFilter (const std::string & filterName, const std::string & sourceEndpoint, const std::string & inputType = std::string (), const std::string & outputType = std::string ())
define a filter interface on a source
a source filter will be sent any packets that come from a particular source if multiple filters are defined on the same source, they will be placed in some order defined by the core
Parameters
[in] the name of the endpoint
[in] the inputType which the source filter can receive
References coreObject.
Referenced by registerFilterInterfaces(), and helics::SourceFilter::SourceFilter().
registerSourceFilter() [2/2]
filter_id_t helics::Federate::registerSourceFilter (const std::string & sourceEndpoint) inline
define a filter interface on a source
a source filter will be sent any packets that come from a particular source if multiple filters are defined on the same source, they will be placed in some order defined by the core
Parameters
[in] the name of the endpoint
[in] the inputType which the source filter can receive
requestTime()
Time helics::Federate::requestTime (Time nextInternalTimeStep)
request a time advancement
Parameters
[in] the next requested time step
Returns
the granted time step
References coreObject, currentTime, error, execution, state, and updateTime().
requestTimeAsync()
void helics::Federate::requestTimeAsync (Time nextInternalTimeStep)
request a time advancement
Parameters
[in] the next requested time step
References coreObject, execution, pending_time, and state.
requestTimeComplete()
Time helics::Federate::requestTimeComplete ()
request a time advancement
Parameters
[in] the next requested time step
Returns
the granted time step
References currentTime, execution, pending_time, state, and updateTime().
Referenced by enterExecutionState(), and finalize().
requestTimeIterative()
iteration_time helics::Federate::requestTimeIterative (Time nextInternalTimeStep, iteration_request iterate)
request a time advancement
Parameters
[in] the next requested time step
[in] iterate a requested iteration mode
Returns
the granted time step in a structure containing a return time and an iteration_result
References coreObject, currentTime, helics::error, error, execution, finalize, helics::halted, helics::iterating, helics::next_step, state, and updateTime().
requestTimeIterativeAsync()
void helics::Federate::requestTimeIterativeAsync (Time nextInternalTimeStep, iteration_request iterate)
request a time advancement
Parameters
[in] the next requested time step
iterate a requested iteration level (none, require, optional)
Returns
the granted time step
request a time advancement
Parameters
[in] the next requested time step
Returns
the granted time step
References coreObject, execution, pending_iterative_time, and state.
requestTimeIterativeComplete()
iteration_time helics::Federate::requestTimeIterativeComplete ()
finalize the time advancement request
Returns
the granted time step in an iteration_time structure which contains a time and iteration result
finalize the time advancement request
Returns
the granted time step
References currentTime, helics::error, error, execution, finalize, helics::halted, helics::iterating, helics::next_step, pending_iterative_time, state, and updateTime().
Referenced by finalize().
setFilterOperator() [1/2]
void helics::Federate::setFilterOperator (filter_id_t filter, std::shared_ptr< FilterOperator > op)
register a operator for the specified filter
for time_agnostic federates only, all other settings would trigger an error The MessageOperator gets called when there is a message to filter, There is no order or state to this messages can come in any order.
Parameters
[in] filter the identifier for the filter to trigger
[in] op A shared_ptr to a message operator
References coreObject.
setFilterOperator() [2/2]
void helics::Federate::setFilterOperator (const std::vector< filter_id_t > & filters, std::shared_ptr< FilterOperator > op)
register a operator for the specified filters
for time_agnostic federates only, all other settings would trigger an error The MessageOperator gets called when there is a message to filter, There is no order or state to this message can come in any order.
Parameters
[in] filters the identifier for the filter to trigger
[in] op A shared_ptr to a message operator
References coreObject.
setFlag()
void helics::Federate::setFlag (int flag, bool flagValue = true) virtual
set a flag for the federate
Parameters
[in] flag an index into the flag /ref flag-definitions.h
[in] flagvalue the value of the flag defaults to true
References coreObject, FedInfo, FORWARD_COMPUTE_FLAG, helics::FederateInfo::forwardCompute, helics::FederateInfo::rollback, and ROLLBACK_FLAG.
setInputDelay()
void helics::Federate::setInputDelay (Time inputDelay)
set the impact Window time
the impact window is the time window around the time request in which other federates cannot affect the federate
Parameters
[in] inputDelay the look ahead time
Exceptions
invalid_value when using a time <0
References coreObject.
setLoggingCallback()
void helics::Federate::setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> & logFunction)
define a logging function to use for logging message and notices from the federation and individual federate
Parameters
logFunction the callback function for doing something with a log message it takes 3 inputs an integer for logLevel 0-4+ 0 -error, 1- warning 2-status, 3-debug 44trace A string indicating the source of the message and another string with the actual message
References coreObject.
setLoggingLevel()
void helics::Federate::setLoggingLevel (int loggingLevel)
set the logging level for the federate @ details debug and trace only do anything if they were enabled in the compilation
Parameters
loggingLevel (-1: none, 0: error_only, 1: warnings, 2: normal, 3: debug, 4: trace)
References coreObject.
setMaxIterations()
void helics::Federate::setMaxIterations (int maxIterations)
set the maximum number of local iterations
Parameters
maxIterations the maximum number of allowed iterations before helics forces a return
References coreObject.
setOutputDelay()
void helics::Federate::setOutputDelay (Time outputDelay)
set the look ahead time or output delay
the look ahead is the propagation time for messages/event to propagate from the Federate to the outside federation
Parameters
[in] outputDelay the value of the time delay (must be >=0)
Exceptions
invalid_value when using a time <0
References coreObject.
setPeriod()
void helics::Federate::setPeriod (Time period, Time offset = timeZero)
set the period and offset of the federate
the federate will on grant time on N*period+offset interval
Parameters
[in] period the length of time between each subsequent grants
[in] offset the shift of the period from 0 offset must be < period
References coreObject.
setTimeDelta()
void helics::Federate::setTimeDelta (Time tdelta)
set the minimum time delta for the federate
Parameters
[in] tdelta the minimum time delta to return from a time request function
References coreObject.
startupToInitializeStateTransition()
void helics::Federate::startupToInitializeStateTransition () protected virtual
function to deal with any operations that need to occur on the transition from startup to initialize
Reimplemented in helics::ValueFederate, helics::MessageFederate, and helics::CombinationFederate.
Referenced by enterExecutionStateAsync(), enterInitializationState(), and enterInitializationStateComplete().
updateTime()
void helics::Federate::updateTime (Time newTime, Time oldTime) protected virtual
function to deal with any operations that need to occur on a time update
Reimplemented in helics::ValueFederate, helics::MessageFederate, and helics::CombinationFederate.
Referenced by enterExecutionState(), enterExecutionStateComplete(), requestTime(), requestTimeComplete(), requestTimeIterative(), and requestTimeIterativeComplete().
The documentation for this class was generated from the following files:
application_api/Federate.hpp
Federate.cpp