helics: helics::apps::Echo Class Reference
helics::apps::Echo Class Reference
#include <Echo.hpp>
Public Member Functions
Echo ()=default
Echo (int argc, char *argv[])
Echo (const FederateInfo &fi)
Echo (const std::shared_ptr< Core > &core, const FederateInfo &fi)
Echo (const std::string &jsonString)
Echo (Echo &&other_echo)=default
Echo & operator= (Echo &&fed)=default
virtual void runTo (Time stopTime_input) override
void addEndpoint (const std::string &endpointName, const std::string &endpointType="")
auto echoCount () const
void setEchoDelay (Time delay)
auto endpointCount () const
Public Member Functions inherited from helics::apps::App
App ()=default
App (const std::string &appName, int argc, char *argv[])
App (const FederateInfo &fi)
App (const std::shared_ptr< Core > &core, const FederateInfo &fi)
App (const std::string &appName, const std::string &jsonString)
App (App &&other_app)=default
App (const App &other_app)=delete
App & operator= (App &&fed)=default
App & operator= (const App &fed)=delete
void loadFile (const std::string &filename)
virtual void initialize ()
virtual void run ()
virtual void finalize ()
bool isActive () const
Additional Inherited Members
Protected Member Functions inherited from helics::apps::App
int loadArguments (boost::program_options::variables_map &vm_map)
void loadJsonFileConfiguration (const std::string &appName, const std::string &jsonString)
virtual void loadTextFile (const std::string &textFile)
Protected Attributes inherited from helics::apps::App
std::shared_ptr< CombinationFederate > fed
the federate created for the Player
Time stopTime = Time::maxVal ()
the time the Player should stop
std::string masterFileName
the name of the master file used to do the construction
bool useLocal = false
bool fileLoaded = false
bool deactivated = false
bool quietMode = false
Detailed Description
class implementing a Echo object, which will generate endpoint interfaces and send a data message back to the source at the with a specified delay
the Echo class is not threadsafe in general, don't try to use it from multiple threads without external protection, that will result in undefined behavior. setEchoDelay is threadsafe
Constructor & Destructor Documentation
Echo() [1/6]
helics::apps::Echo::Echo () default
default constructor
Echo() [2/6]
helics::apps::Echo::Echo (int argc, char * argv[])
construct from command line arguments
Parameters
argc the number of arguments
argv the strings in the input
References helics::argumentParser(), helics::apps::App::loadFile(), and helics::apps::App::masterFileName.
Echo() [3/6]
helics::apps::Echo::Echo (const FederateInfo & fi) explicit
construct from a federate info object
Parameters
fi a pointer info object containing information on the desired federate configuration
Echo() [4/6]
helics::apps::Echo::Echo (const std::shared_ptr< Core > & core, const FederateInfo & fi)
constructor taking a federate information structure and using the given core
Parameters
core a pointer to core object which the federate can join
[in] fi a federate information structure
Echo() [5/6]
helics::apps::Echo::Echo (const std::string & jsonString) explicit
constructor taking a file with the required information
Parameters
[in] jsonString file or json string defining the federate information and other configuration
Echo() [6/6]
helics::apps::Echo::Echo (Echo && other_echo) default
move construction
Member Function Documentation
addEndpoint()
void helics::apps::Echo::addEndpoint (const std::string & endpointName, const std::string & endpointType = "")
add an endpoint to the Player
Parameters
endpointName the name of the endpoint
endpointType the named type of the endpoint
References helics::apps::App::fed.
echoCount()
auto helics::apps::Echo::echoCount () const inline
get the number of points loaded
endpointCount()
auto helics::apps::Echo::endpointCount () const inline
get the number of endpoints
operator=()
Echo& helics::apps::Echo::operator= (Echo && fed) default
move assignment
runTo()
void helics::apps::Echo::runTo (Time stopTime_input) override virtual
run the Echo federate until the specified time
Parameters
stopTime_input the desired stop time
Implements helics::apps::App.
References helics::Federate::execution, helics::apps::App::fed, helics::Federate::finalize, helics::apps::App::initialize(), and helics::Federate::startup.
setEchoDelay()
void helics::apps::Echo::setEchoDelay (Time delay)
set the delay time
The documentation for this class was generated from the following files:
Echo.hpp
Echo.cpp