helics: helics::CommsInterface Class Reference
helics::CommsInterface Class Reference abstract
#include <CommsInterface.hpp>
Public Member Functions
CommsInterface ()=default
CommsInterface (const std::string &localTarget, const std::string &brokerTarget)
CommsInterface (const NetworkBrokerData &netInfo)
virtual ~CommsInterface ()
void transmit (int route_id, const ActionMessage &cmd)
void addRoute (int route_id, const std::string &routeInfo)
bool connect ()
void disconnect ()
bool reconnect ()
void setName (const std::string &name)
void setCallback (std::function< void(ActionMessage &&)> callback)
void setMessageSize (int maxMessageSize, int maxMessageCount)
bool isConnected () const
void setTimeout (int timeout)
Protected Types
enum connection_status : int {
connection_status::startup = -1, connection_status::connected = 0, connection_status::reconnecting = 1, connection_status::terminated = 2,
connection_status::error = 4
}
Protected Attributes
std::atomic< connection_status > rx_status {connection_status::startup}
the status of the receiver thread
std::string name
the name of the object
std::string localTarget_
the base for the receive address
std::string brokerTarget_
the base for the broker address
std::string brokerName_
the identifier for the broker
std::atomic< connection_status > tx_status
the status of the transmitter thread
int connectionTimeout = 4000
int maxMessageSize_ = 16 * 1024
the maximum message size for the queues (if needed)
int maxMessageCount_ = 512
the maximum number of message to buffer (if needed)
std::function< void(ActionMessage &&)> ActionCallback
the callback for what to do with a received message
BlockingPriorityQueue< std::pair< int, ActionMessage > > txQueue
set of messages waiting to be transmitted
std::atomic< bool > disconnecting
flag indicating that the comm system is in the process of disconnecting
Detailed Description
implementation of a generic communications interface
Member Enumeration Documentation
connection_status
enum helics::CommsInterface::connection_status : int strong protected
Enumerator
startup
the connection is in startup mode
connected
we are connected
reconnecting
we are trying reconnect
terminated
the connection has been terminated
error
some error occurred on the connection
Constructor & Destructor Documentation
CommsInterface() [1/3]
helics::CommsInterface::CommsInterface () default
default constructor
CommsInterface() [2/3]
helics::CommsInterface::CommsInterface (const std::string & localTarget, const std::string & brokerTarget)
construct from a localTarget and brokerTarget
Parameters
localTarget the interface or specification that should be set to receive incoming connections
brokerTarget the target of the broker Interface to link to
CommsInterface() [3/3]
helics::CommsInterface::CommsInterface (const NetworkBrokerData & netInfo) explicit
construct from a NetworkBrokerData structure
~CommsInterface()
helics::CommsInterface::~CommsInterface () virtual
destructor
Member Function Documentation
addRoute()
void helics::CommsInterface::addRoute (int route_id, const std::string & routeInfo)
add a new route assigned to the appropriate id
References helics::ActionMessage::dest_id, helics::ActionMessage::index, helics::ActionMessage::payload, and transmit().
connect()
bool helics::CommsInterface::connect ()
connect the commsInterface
Returns
true if the connection was successful false otherwise
References ActionCallback, connected, isConnected(), localTarget_, name, rx_status, startup, and tx_status.
disconnect()
void helics::CommsInterface::disconnect ()
disconnected the comms interface
References connected, tripwire::TripWireDetector::isTripped(), rx_status, terminated, and tx_status.
Referenced by helics::ipc::IpcComms::~IpcComms(), helics::mpi::MpiComms::~MpiComms(), helics::tcp::TcpComms::~TcpComms(), helics::udp::UdpComms::~UdpComms(), and helics::zeromq::ZmqComms::~ZmqComms().
isConnected()
bool helics::CommsInterface::isConnected () const
check if the commInterface is connected
References connected, rx_status, and tx_status.
Referenced by connect().
reconnect()
bool helics::CommsInterface::reconnect ()
try reconnected from a mismatched or disconnection
References connected, reconnecting, rx_status, and tx_status.
setCallback()
void helics::CommsInterface::setCallback (std::function< void(ActionMessage &&)> callback)
set the callback for processing the messages
References ActionCallback.
setMessageSize()
void helics::CommsInterface::setMessageSize (int maxMessageSize, int maxMessageCount)
set the max message size and max Queue size
References maxMessageCount_, and maxMessageSize_.
setName()
void helics::CommsInterface::setName (const std::string & name)
set the name of the communicator
References name.
setTimeout()
void helics::CommsInterface::setTimeout (int timeout) inline
set the timeout for the initial broker connection
Parameters
timeout the value is in milliseconds
transmit()
void helics::CommsInterface::transmit (int route_id, const ActionMessage & cmd)
transmit a message along a particular route
References helics::isPriorityCommand(), and txQueue.
Referenced by addRoute().
Member Data Documentation
disconnecting
std::atomic<bool> helics::CommsInterface::disconnecting protected
Initial value:
{
      false}
flag indicating that the comm system is in the process of disconnecting
tx_status
std::atomic<connection_status> helics::CommsInterface::tx_status protected
Initial value:
{
      connection_status::startup}
the status of the transmitter thread
Referenced by connect(), disconnect(), isConnected(), and reconnect().
The documentation for this class was generated from the following files:
CommsInterface.hpp
CommsInterface.cpp