helics: helics::SourceFilter Class Reference
helics::SourceFilter Class Reference
#include <Filters.hpp>
Public Member Functions
SourceFilter (Federate *fed, const std::string &target, const std::string &name=EMPTY_STRING, const std::string &input_type=EMPTY_STRING, const std::string &output_type=EMPTY_STRING)
SourceFilter (Core *cr, const std::string &target, const std::string &name=EMPTY_STRING, const std::string &input_type=EMPTY_STRING, const std::string &output_type=EMPTY_STRING)
Public Member Functions inherited from helics::Filter
Filter ()=default
Filter (Federate *fed)
Filter (Core *cr)
virtual ~Filter ()=default
void setOperator (std::shared_ptr< FilterOperator > mo)
filter_id_t getID () const
Core::handle_id_t getCoreHandle () const
const std::string & getTarget () const
const std::string & getName () const
const std::string & getInputType () const
const std::string & getOutputType () const
virtual void set (const std::string &property, double val)
virtual void setString (const std::string &property, const std::string &val)
Filter (helics_filter hfilt)
Filter (const Filter &filter)
Filter & operator= (const Filter &filter)
operator helics_filter () const
helics_filter baseObject () const
std::string getTarget () const
std::string getName () const
void set (const std::string &property, double val)
void setString (const std::string &property, const std::string &val)
Additional Inherited Members
Protected Member Functions inherited from helics::Filter
void setFilterOperations (std::shared_ptr< FilterOperations > filterOps)
Protected Attributes inherited from helics::Filter
Core * corePtr = nullptr
the Core to use
Core::handle_id_t id = invalid_handle
the id as generated by the Federate
filter_id_t fid = invalid_id_value
id for interacting with a federate
std::shared_ptr< FilterOperations > filtOp
a class running any specific operation of the Filter
helics_filter filt
the reference to the underlying publication
Detailed Description
class wrapping a source filter
Constructor & Destructor Documentation
SourceFilter() [1/2]
helics::SourceFilter::SourceFilter (Federate * fed, const std::string & target, const std::string & name = EMPTY_STRING, const std::string & input_type = EMPTY_STRING, const std::string & output_type = EMPTY_STRING)
constructor to build an source filter object
Parameters
[in] fed the Federate to use
[in] target the endpoint the filter is targeting
[in] name the name of the filter
[in] input_type the type of data the filter is expecting
[in] output_type the type of data the filter is generating
References helics::Filter::fid, helics::Federate::registerSourceFilter(), and helics::identifier_id_t< BaseType, ID, invalidValue >::value().
SourceFilter() [2/2]
helics::SourceFilter::SourceFilter (Core * cr, const std::string & target, const std::string & name = EMPTY_STRING, const std::string & input_type = EMPTY_STRING, const std::string & output_type = EMPTY_STRING)
constructor to build an source filter object
Parameters
[in] fed the Federate to use
[in] target the endpoint the filter is targeting
[in] name the name of the filter
[in] input_type the type of data the filter is expecting
[in] output_type the type of data the filter is generating
References helics::Filter::corePtr, helics::Filter::fid, helics::Filter::id, and helics::Core::registerSourceFilter().
The documentation for this class was generated from the following files:
Filters.hpp
Filters.cpp