helics: helics::identifier_id_t< BaseType, ID, invalidValue > Class Template Reference
helics::identifier_id_t< BaseType, ID, invalidValue > Class Template Reference
#include <helicsTypes.hpp>
Public Types
using underlyingType = BaseType
Public Member Functions
constexpr identifier_id_t () noexcept
constexpr identifier_id_t (BaseType val) noexcept
constexpr identifier_id_t (const identifier_id_t &id) noexcept
identifier_id_t & operator= (BaseType val) noexcept
identifier_id_t & operator= (const identifier_id_t &id) noexcept
BaseType value () const noexcept
bool operator== (identifier_id_t id) const noexcept
bool operator!= (identifier_id_t id) const noexcept
bool operator< (identifier_id_t id) const noexcept
Static Public Attributes
static const identifiers identity {ID}
the type of the identifier
Detailed Description
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))>
class helics::identifier_id_t< BaseType, ID, invalidValue >
class defining an identifier type
the intent of this class is to limit the operations available on a publication identifier to those that are a actually required and make sense, and make it as low impact as possible. it also acts to limit any mistakes of a publication_id for a subscription_id or other types of interfaces
Constructor & Destructor Documentation
identifier_id_t() [1/3]
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> constexpr helics::identifier_id_t< BaseType, ID, invalidValue >::identifier_id_t () inline noexcept
default constructor
identifier_id_t() [2/3]
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> constexpr helics::identifier_id_t< BaseType, ID, invalidValue >::identifier_id_t (BaseType val) inline noexcept
value based constructor
identifier_id_t() [3/3]
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> constexpr helics::identifier_id_t< BaseType, ID, invalidValue >::identifier_id_t (const identifier_id_t< BaseType, ID, invalidValue > & id) inline noexcept
copy constructor
Member Function Documentation
operator!=()
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> bool helics::identifier_id_t< BaseType, ID, invalidValue >::operator!= (identifier_id_t< BaseType, ID, invalidValue > id) const inline noexcept
inequality operator
operator<()
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> bool helics::identifier_id_t< BaseType, ID, invalidValue >::operator< (identifier_id_t< BaseType, ID, invalidValue > id) const inline noexcept
less than operator for sorting
operator=() [1/2]
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> identifier_id_t& helics::identifier_id_t< BaseType, ID, invalidValue >::operator= (BaseType val) inline noexcept
assignment from number
operator=() [2/2]
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> identifier_id_t& helics::identifier_id_t< BaseType, ID, invalidValue >::operator= (const identifier_id_t< BaseType, ID, invalidValue > & id) inline noexcept
copy assignment
operator==()
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> bool helics::identifier_id_t< BaseType, ID, invalidValue >::operator== (identifier_id_t< BaseType, ID, invalidValue > id) const inline noexcept
equality operator
value()
template<class BaseType, identifiers ID, BaseType invalidValue = (BaseType (-1))> BaseType helics::identifier_id_t< BaseType, ID, invalidValue >::value () const inline noexcept
get the underlying value
Referenced by helics::ValueFederateManager::addSubscriptionShortcut(), helics::DestinationFilter::DestinationFilter(), helics::ValueFederateManager::getPublicationKey(), helics::ValueFederateManager::getPublicationType(), helics::ValueFederateManager::getPublicationUnits(), helics::ValueFederateManager::getSubscriptionKey(), helics::ValueFederateManager::getSubscriptionType(), helics::ValueFederateManager::getSubscriptionUnits(), helics::Federate::isQueryCompleted(), helics::Federate::queryComplete(), helics::ValueFederateManager::queryLastUpdate(), helics::ValueFederateManager::queryUpdate(), helics::MessageFederateManager::registerKnownCommunicationPath(), and helics::SourceFilter::SourceFilter().
The documentation for this class was generated from the following file:
helicsTypes.hpp