helics: helics::ValueConverter< X > Class Template Reference
helics::ValueConverter< X > Class Template Reference
#include <ValueConverter.hpp>
Public Types
using baseType = X
Static Public Member Functions
static data_block convert (const X &val)
static void convert (const X &val, data_block &store)
static void convert (const X *vals, size_t size, data_block &store)
static data_block convert (const X *vals, size_t size)
static X interpret (const data_view &block)
static void interpret (const data_view &block, X &val)
static std::string type ()
Detailed Description
template<class X>
class helics::ValueConverter< X >
converter for a basic value
Member Function Documentation
convert() [1/4]
template<class X > data_block helics::ValueConverter< X >::convert (const X & val) static
convert the value to a block of data
converter for a basic value
convert() [2/4]
template<class X > void helics::ValueConverter< X >::convert (const X & val, data_block & store) static
convert the value and store to a specific block of data
References helics::data_block::reserve().
convert() [3/4]
template<class X > void helics::ValueConverter< X >::convert (const X * vals, size_t size, data_block & store) static
convert a raw vector of objects and store to a specific block
References helics::data_block::reserve().
convert() [4/4]
template<class X > data_block helics::ValueConverter< X >::convert (const X * vals, size_t size) static
convert a raw vector of objects and store to a specific block
interpret() [1/2]
template<class X > X helics::ValueConverter< X >::interpret (const data_view & block) static
interpret a view of the data and convert back to a val
Referenced by helics::ValueFederate::getValue().
interpret() [2/2]
template<class X > void helics::ValueConverter< X >::interpret (const data_view & block, X & val) static
interpret a view of the data block and store to the specified value
References helics::data_view::data(), and helics::data_view::size().
type()
template<class X> static std::string helics::ValueConverter< X >::type () inline static
get the type of the value
The documentation for this class was generated from the following files:
ValueConverter.hpp
ValueConverter_impl.hpp