helics: helics::zeromq::ZmqBroker Class Reference
helics::zeromq::ZmqBroker Class Reference final
Public Member Functions
ZmqBroker (bool rootBroker=false) noexcept
ZmqBroker (const std::string &broker_name)
void initializeFromArgs (int argc, const char *const *argv) override
virtual std::string getAddress () const override
Public Member Functions inherited from helics::CommsBroker< ZmqComms, CoreBroker >
CommsBroker () noexcept
CommsBroker (bool arg) noexcept
CommsBroker (const std::string &obj_name)
~CommsBroker ()
virtual void transmit (int route_id, const ActionMessage &cmd) override
virtual void addRoute (int route_id, const std::string &routeInfo) override
Public Member Functions inherited from helics::CoreBroker
virtual bool connect () override final
virtual void disconnect () override final
void unregister ()
virtual void processDisconnect (bool skipUnregister=false) override final
virtual bool isConnected () const override final
virtual void setAsRoot () override final
virtual bool isRoot () const override final
virtual bool isOpenToNewFederates () const override
virtual void setLoggingCallback (const std::function< void(int, const std::string &, const std::string &)> &logFunction) override final
CoreBroker (bool setAsRootBroker=false) noexcept
CoreBroker (const std::string &broker_name)
virtual ~CoreBroker ()
virtual void initialize (const std::string &initializationString) override final
bool allInitReady () const
bool allDisconnected () const
void setIdentifier (const std::string &name)
virtual const std::string & getIdentifier () const override final
Public Member Functions inherited from helics::Broker
Broker ()=default
virtual ~Broker ()=default
Broker (std::string type, std::string name, std::string initString)
Broker (std::string type, std::string name, int argc, const char **argv)
Broker (const Broker &brk)
Broker & operator= (const Broker &brk)
operator helics_broker ()
helics_broker baseObject () const
bool isConnected () const
void disconnect ()
std::string getIdentifier () const
std::string getAddress () const
Public Member Functions inherited from helics::BrokerBase
BrokerBase (const std::string &broker_name)
virtual void initializeFromCmdArgs (int argc, const char *const *argv)
void addActionMessage (const ActionMessage &m)
void addActionMessage (ActionMessage &&m)
void setLoggerFunction (std::function< void(int, const std::string &, const std::string &)> logFunction)
bool isRunning () const
void setLogLevel (int32_t level)
void setLogLevels (int32_t consoleLevel, int32_t fileLevel)
void joinAllThreads ()
Static Public Member Functions
static void displayHelp (bool local_only=false)
Static Public Member Functions inherited from helics::CoreBroker
static void displayHelp ()
Static Public Member Functions inherited from helics::BrokerBase
static void displayHelp ()
Additional Inherited Members
Protected Types inherited from helics::BrokerBase
enum broker_state_t : int16_t {
created = -5, initialized = -4, connecting = -3, connected = -2,
initializing = -1, operating = 0, terminating = 1, terminated = 3,
errored = 7
}
Protected Member Functions inherited from helics::CoreBroker
virtual void transmit (int32_t route, const ActionMessage &command)=0
Protected Member Functions inherited from helics::BrokerBase
virtual bool sendToLogger (Core::federate_id_t federateID, int logLevel, const std::string &name, const std::string &message) const
void generateNewIdentifier ()
Protected Attributes inherited from helics::CommsBroker< ZmqComms, CoreBroker >
std::atomic< int > disconnectionStage
the stage of disconnection
std::mutex dataMutex
mutex protecting comms data
std::unique_ptr< ZmqComms > comms
the actual comms object
std::atomic< bool > initialized_
atomic protecting local initialization
Protected Attributes inherited from helics::CoreBroker
bool _gateway = false
set to true if this broker should act as a gateway.
Protected Attributes inherited from helics::Broker
helics_broker broker
Protected Attributes inherited from helics::BrokerBase
std::atomic< Core::federate_id_t > global_broker_id
the unique identifier for the broker(core or broker)
Core::federate_id_t higher_broker_id = 0
the id code of the broker 1 level about this broker
std::atomic< int32_t > maxLogLevel {1}
the logging level to use levels >=this will be logged
int32_t consoleLogLevel = 1
the logging level for console display
int32_t fileLogLevel = 1
the logging level for logging to a file
int32_t minFederateCount = 1
the minimum number of federates that must connect before entering init mode
int32_t minBrokerCount = 0
the minimum number of brokers that must connect before entering init mode
int32_t maxIterationCount = 10000
the maximum number of iterative loops that are allowed
int32_t tickTimer = 4000
counter for the length of a keep alive tick in milliseconds
int32_t timeout
timeout to wait to establish a broker connection before giving up in milliseconds
std::string identifier
an identifier for the broker
std::unique_ptr< Logger > loggingObj
default logging object to use if the logging callback is not specified
std::thread _queue_processing_thread
thread for running the broker
std::function< void(int, const std::string &, const std::string &)> loggerFunction
std::atomic< bool > haltOperations {false}
flag indicating that no further message should be processed
std::string logFile
std::unique_ptr< ForwardingTimeCoordinator > timeCoord
object managing the time control
BlockingPriorityQueue< ActionMessage > actionQueue
primary routing queue
std::atomic< broker_state_t > brokerState {created}
bool noAutomaticID = false
bool hasTimeDependency = false
set to true if the broker has Time dependencies
bool enteredExecutionMode = false
flag indicating that the broker has entered execution mode
bool waitingForServerPingReply = false
flag indicating we are waiting for a ping reply
bool hasFilters = false
flag indicating filters come through the broker
Constructor & Destructor Documentation
ZmqBroker()
helics::zeromq::ZmqBroker::ZmqBroker (bool rootBroker = false) noexcept
default constructor
Member Function Documentation
getAddress()
std::string helics::zeromq::ZmqBroker::getAddress () const override virtual
get the connection address for the broker
Implements helics::Broker.
References helics::CommsBroker< ZmqComms, CoreBroker >::comms, helics::CommsBroker< ZmqComms, CoreBroker >::dataMutex, helics::NetworkBrokerData::localInterface, helics::makePortAddress(), and helics::NetworkBrokerData::portNumber.
initializeFromArgs()
void helics::zeromq::ZmqBroker::initializeFromArgs (int argc, const char *const * argv) override virtual
initialize from command line arguments
Reimplemented from helics::CoreBroker.
References helics::BrokerBase::brokerState, helics::NetworkBrokerData::initializeFromArgs(), and helics::CoreBroker::initializeFromArgs().
The documentation for this class was generated from the following files:
ZmqBroker.h
ZmqBroker.cpp