helics: helics::MessageFederateManager Class Reference
helics::MessageFederateManager Class Reference
#include <MessageFederateManager.hpp>
Public Member Functions
MessageFederateManager (Core *coreOb, Core::federate_id_t id)
endpoint_id_t registerEndpoint (const std::string &name, const std::string &type)
void registerKnownCommunicationPath (endpoint_id_t localEndpoint, const std::string &remoteEndpoint)
give the core a hint for known communication paths Specifying a path that is not present will cause the simulation to abort with an error message
void subscribe (endpoint_id_t endpoint, const std::string &name, const std::string &type)
bool hasMessage () const
bool hasMessage (endpoint_id_t id) const
uint64_t receiveCount (endpoint_id_t id) const
uint64_t receiveCount () const
std::unique_ptr< Message > getMessage (endpoint_id_t endpoint)
std::unique_ptr< Message > getMessage ()
void sendMessage (endpoint_id_t source, const std::string &dest, data_view message)
void sendMessage (endpoint_id_t source, const std::string &dest, data_view message, Time sendTime)
void sendMessage (endpoint_id_t source, std::unique_ptr< Message > message)
void updateTime (Time newTime, Time oldTime)
void startupToInitializeStateTransition ()
void initializeToExecuteStateTransition ()
std::string getEndpointName (endpoint_id_t id) const
endpoint_id_t getEndpointId (const std::string &name) const
std::string getEndpointType (endpoint_id_t id) const
void registerCallback (const std::function< void(endpoint_id_t, Time)> &callback)
void registerCallback (endpoint_id_t id, const std::function< void(endpoint_id_t, Time)> &callback)
void registerCallback (const std::vector< endpoint_id_t > &ids, const std::function< void(endpoint_id_t, Time)> &callback)
void disconnect ()
int getEndpointCount () const
Detailed Description
class handling the implementation details of a value Federate
the functions will parallel those in message Federate and contain the actual implementation details
Constructor & Destructor Documentation
MessageFederateManager()
helics::MessageFederateManager::MessageFederateManager (Core * coreOb, Core::federate_id_t id)
construct from a pointer to a core and a specified federate id
Member Function Documentation
disconnect()
void helics::MessageFederateManager::disconnect ()
disconnect from the coreObject
getEndpointCount()
int helics::MessageFederateManager::getEndpointCount () const
get the number of registered endpoints
getEndpointId()
endpoint_id_t helics::MessageFederateManager::getEndpointId (const std::string & name) const
get the id of a registered publication from its id
Parameters
[in] name the publication id
Returns
ivalid_publication_id if name is not recognized otherwise returns the publication_id
getEndpointName()
std::string helics::MessageFederateManager::getEndpointName (endpoint_id_t id) const
get the name of an endpoint from its id
Parameters
[in] id the endpoint to query
Returns
empty string if an invalid id is passed
getEndpointType()
std::string helics::MessageFederateManager::getEndpointType (endpoint_id_t id) const
get the type of an endpoint from its id
Parameters
[in] id the endpoint to query
Returns
empty string if an invalid id is passed or no type was specified
getMessage()
std::unique_ptr< Message > helics::MessageFederateManager::getMessage (endpoint_id_t endpoint)
receive a packet from a particular endpoint
Parameters
[in] endpoint the identifier for the endpoint
Returns
a message object
hasMessage()
bool helics::MessageFederateManager::hasMessage () const
check if the federate has any outstanding messages
initializeToExecuteStateTransition()
void helics::MessageFederateManager::initializeToExecuteStateTransition ()
transition from initialize to execution State
receiveCount() [1/2]
uint64_t helics::MessageFederateManager::receiveCount (endpoint_id_t id) const
Returns the number of pending receives for the specified destination endpoint.
receiveCount() [2/2]
uint64_t helics::MessageFederateManager::receiveCount () const
Returns the number of pending receives for the specified destination endpoint.
Returns the number of pending receives for the specified destination endpoint.
this function is not preferred in multi-threaded contexts due to the required locking prefer to just use getMessage until it returns an invalid Message.
registerCallback() [1/3]
void helics::MessageFederateManager::registerCallback (const std::function< void(endpoint_id_t, Time)> & callback)
register a callback function to call when any endpoint receives a message
there can only be one generic callback
Parameters
[in] callback the function to call
registerCallback() [2/3]
void helics::MessageFederateManager::registerCallback (endpoint_id_t id, const std::function< void(endpoint_id_t, Time)> & callback)
register a callback function to call when the specified endpoint receives a message
Parameters
[in] id the endpoint id to register the callback for
[in] callback the function to call
registerCallback() [3/3]
void helics::MessageFederateManager::registerCallback (const std::vector< endpoint_id_t > & ids, const std::function< void(endpoint_id_t, Time)> & callback)
register a callback function to call when one of the specified endpoint ids receives a message
Parameters
[in] ids the set of ids to register the callback for
[in] callback the function to call
registerEndpoint()
endpoint_id_t helics::MessageFederateManager::registerEndpoint (const std::string & name, const std::string & type)
register an endpoint
call is only valid in startup mode
Parameters
[in] name the name of the endpoint
[in] type the defined type of the interface for endpoint checking if requested
References helics::Core::registerEndpoint().
registerKnownCommunicationPath()
void helics::MessageFederateManager::registerKnownCommunicationPath (endpoint_id_t localEndpoint, const std::string & remoteEndpoint)
give the core a hint for known communication paths Specifying a path that is not present will cause the simulation to abort with an error message
Parameters
[in] localEndpoint the local endpoint of a known communication pair
[in] remoteEndpoint of a communication pair
References helics::Core::registerFrequentCommunicationsPair(), and helics::identifier_id_t< BaseType, ID, invalidValue >::value().
startupToInitializeStateTransition()
void helics::MessageFederateManager::startupToInitializeStateTransition ()
transition from Startup To the Initialize State
subscribe()
void helics::MessageFederateManager::subscribe (endpoint_id_t endpoint, const std::string & name, const std::string & type)
subscribe to valueFederate publication to be delivered as Messages to the given endpoint
Parameters
[in] endpoint the specified endpoint to deliver the values
[in] name the name of the publication to subscribe
[in] type the type of publication
updateTime()
void helics::MessageFederateManager::updateTime (Time newTime, Time oldTime)
update the time from oldTime to newTime
Parameters
[in] newTime the newTime of the federate
[in] oldTime the oldTime of the federate
find the id
References helics::Core::getValue(), helics::Core::getValueUpdates(), helics::Core::receiveAny(), and helics::Core::receiveCountAny().
The documentation for this class was generated from the following files:
MessageFederateManager.hpp
MessageFederateManager.cpp