helics: helics::LoggerManager Class Reference
helics::LoggerManager Class Reference
#include <logger.h>
Public Member Functions
const std::string & getName () const
Static Public Member Functions
static std::shared_ptr< LoggerManager > getLoggerManager (const std::string &loggerName="")
static std::shared_ptr< LoggingCore > getLoggerCore (const std::string &loggerName="")
static void closeLogger (const std::string &loggerName="")
static void logMessage (const std::string &message)
Detailed Description
class defining a singleton manager for all logging use
Member Function Documentation
closeLogger()
void helics::LoggerManager::closeLogger (const std::string & loggerName = "") static
close the named Logger
prevents the Logger from being retrieved through this class but does not necessarily destroy the Logger
Referenced by helicsCloseLibrary().
getLoggerCore()
std::shared_ptr< LoggingCore > helics::LoggerManager::getLoggerCore (const std::string & loggerName = "") static
get a pointer to a logging core
References getLoggerManager().
Referenced by helics::Logger::Logger().
getLoggerManager()
std::shared_ptr< LoggerManager > helics::LoggerManager::getLoggerManager (const std::string & loggerName = "") static
get a pointer to a logging manager so it cannot go out of scope
Referenced by getLoggerCore().
getName()
const std::string& helics::LoggerManager::getName () const inline
get the name of the logger
logMessage()
void helics::LoggerManager::logMessage (const std::string & message) static
sends a message to the default Logger
The documentation for this class was generated from the following files:
logger.h
logger.cpp