helics: BlockingQueue< T > Class Template Reference
BlockingQueue< T > Class Template Reference
#include <BlockingQueue.hpp>
Public Member Functions
BlockingQueue ()=default
BlockingQueue (size_t capacity)
BlockingQueue (BlockingQueue &&bq) noexcept
BlockingQueue & operator= (BlockingQueue &&sq) noexcept
BlockingQueue (const BlockingQueue &)=delete
BlockingQueue & operator= (const BlockingQueue &)=delete
void clear ()
void reserve (size_t capacity)
template<class Z >
void push (Z &&val)
template<class... Args>
void emplace (Args &&... args)
template<typename = std::enable_if<std::is_copy_assignable<T>::value>>
stx::optional< T > try_peek () const
stx::optional< T > try_pop ()
T pop ()
template<typename Functor >
T pop (Functor callOnWaitFunction)
bool empty () const
size_t size () const
Detailed Description
template<typename T>
class BlockingQueue< T >
NOTES:: PT Went with unlocking after signaling on the basis of this page http://www.domaigne.com/blog/computing/condvars-signal-with-mutex-locked-or-not/ will check performance at a later time class implementing a blocking queue
this class uses locks one for push and pull it can exhibit longer blocking times if the internal operations require a swap, however in high contention the two locks will reduce contention in most cases.
Constructor & Destructor Documentation
BlockingQueue() [1/4]
template<typename T> BlockingQueue< T >::BlockingQueue () default
default constructor
BlockingQueue() [2/4]
template<typename T> BlockingQueue< T >::BlockingQueue (size_t capacity) inline explicit
constructor with the capacity numbers
there are two internal vectors that alternate so the actual reserve is 2x the capacity numbers in two different vectors
Parameters
capacity the initial reserve capacity for the arrays
BlockingQueue() [3/4]
template<typename T> BlockingQueue< T >::BlockingQueue (BlockingQueue< T > && bq) inline noexcept
enable the move constructor not the copy constructor
BlockingQueue() [4/4]
template<typename T> BlockingQueue< T >::BlockingQueue (const BlockingQueue< T > &) delete
DISABLE_COPY_AND_ASSIGN
Member Function Documentation
clear()
template<typename T> void BlockingQueue< T >::clear () inline
clear the queue
emplace()
template<typename T> template<class... Args> void BlockingQueue< T >::emplace (Args &&... args) inline
construct on object in place on the queue
Referenced by helics::LoggingCore::addMessage(), and helics::LoggingCore::~LoggingCore().
empty()
template<typename T > bool BlockingQueue< T >::empty () const
check whether there are any elements in the queue because this is meant for multi-threaded applications this may or may not have any meaning depending on the number of consumers
operator=()
template<typename T> BlockingQueue& BlockingQueue< T >::operator= (BlockingQueue< T > && sq) inline noexcept
enable the move assignment not the copy assignment
pop() [1/2]
template<typename T> T BlockingQueue< T >::pop () inline
blocking call to wait on an object from the stack
pop() [2/2]
template<typename T> template<typename Functor > T BlockingQueue< T >::pop (Functor callOnWaitFunction) inline
blocking call that will call the specified functor if the queue is empty
Parameters
callOnWaitFunction an nullary functor that will be called if the initial query does not return a value
after calling the function the call will check again and if still empty will block and wait.
push()
template<typename T> template<class Z > void BlockingQueue< T >::push (Z && val) inline
push an element onto the queue val the value to push on the queue
reserve()
template<typename T> void BlockingQueue< T >::reserve (size_t capacity) inline
set the capacity of the queue actually double the requested the size will be reserved due to the use of two vectors internally
Parameters
[in] capacity the capacity to reserve
size()
template<typename T > size_t BlockingQueue< T >::size () const
get the current size of the queue
this may or may not have much meaning depending on the number of consumers
try_peek()
template<typename T> template<typename = std::enable_if<std::is_copy_assignable<T>::value>> stx::optional<T> BlockingQueue< T >::try_peek () const inline
try to peek at an object without popping it from the stack
only available for copy assignable objects
Returns
an optional object with an object of type T if available
try_pop()
template<typename T > stx::optional< T > BlockingQueue< T >::try_pop ()
try to pop an object from the queue
Returns
an optional containing the value if successful the optional will be empty if there is no element in the queue
Referenced by BlockingQueue< std::pair< int32_t, std::string > >::pop().
The documentation for this class was generated from the following file:
BlockingQueue.hpp