helics: helics::SubscriptionBase Class Reference
helics::SubscriptionBase Class Reference
#include <Subscriptions.hpp>
Public Member Functions
template<class FedPtr >
SubscriptionBase (FedPtr valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
template<class FedPtr >
SubscriptionBase (interface_availability required, FedPtr valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
SubscriptionBase (ValueFederate *valueFed, int subIndex)
SubscriptionBase (SubscriptionBase &&base)=default
SubscriptionBase & operator= (SubscriptionBase &&base)=default
Time getLastUpdate () const
virtual bool isUpdated () const
subscription_id_t getID () const
void registerCallback (std::function< void(Time)> callback)
const std::string & getKey () const
const std::string & getName () const
std::string getType () const
const std::string & getUnits () const
Protected Attributes
ValueFederate * fed = nullptr
reference to the value federate
std::string key_
the name of the subscription
std::string type_
the requested type of the subscription
std::string units_
the defined units of the subscription
subscription_id_t id
the id of the federate
Detailed Description
base class for a subscription object
Member Function Documentation
getKey()
const std::string& helics::SubscriptionBase::getKey () const inline
get the key for the subscription
References key_.
getLastUpdate()
Time helics::SubscriptionBase::getLastUpdate () const inline
get the time of the last update
Returns
the time of the last update
References fed, and helics::ValueFederate::getLastUpdateTime().
getName()
const std::string& helics::SubscriptionBase::getName () const inline
get the key for the subscription
References key_.
getType()
std::string helics::SubscriptionBase::getType () const inline
get the key for the subscription
References fed, and helics::ValueFederate::getPublicationType().
getUnits()
const std::string& helics::SubscriptionBase::getUnits () const inline
get the units associated with a subscription
References units_.
isUpdated()
virtual bool helics::SubscriptionBase::isUpdated () const inline virtual
check if the value has subscription has been updated
Reimplemented in helics::Subscription, and helics::Subscription.
References fed, and helics::ValueFederate::isUpdated().
Referenced by helics::Subscription::isUpdated().
registerCallback()
void helics::SubscriptionBase::registerCallback (std::function< void(Time)> callback) inline
register a callback for an update notification
the callback is called in the just before the time request function returns
Parameters
[in] callback a function with signature void(Time time) time is the time the value was updated This callback is a notification callback and doesn't return the value
References fed, and helics::ValueFederate::registerSubscriptionNotificationCallback().
The documentation for this class was generated from the following files:
Subscriptions.hpp
Subscriptions.cpp