helics: helics::SubscriptionT< X > Class Template Reference
helics::SubscriptionT< X > Class Template Reference
#include <Subscriptions.hpp>
Public Member Functions
template<class FedPtr >
SubscriptionT (FedPtr valueFed, const std::string &name, const std::string &units=std::string())
template<class FedPtr >
SubscriptionT (interface_availability required, FedPtr valueFed, const std::string &name, const std::string &units="")
X getValue () const
void getValue (X &out) const
void registerCallback (std::function< void(X, Time)> callback)
void setDefault (const X &val)
void setMinimumChange (double deltaV)
void enableChangeDetection (bool enabled=true)
void registerCallback (std::function< void(Time)> callback)
Public Member Functions inherited from helics::SubscriptionBase
template<class FedPtr >
SubscriptionBase (FedPtr valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
template<class FedPtr >
SubscriptionBase (interface_availability required, FedPtr valueFed, const std::string &key, const std::string &type="def", const std::string &units=std::string())
SubscriptionBase (ValueFederate *valueFed, int subIndex)
SubscriptionBase (SubscriptionBase &&base)=default
SubscriptionBase & operator= (SubscriptionBase &&base)=default
Time getLastUpdate () const
virtual bool isUpdated () const
subscription_id_t getID () const
void registerCallback (std::function< void(Time)> callback)
const std::string & getKey () const
const std::string & getName () const
std::string getType () const
const std::string & getUnits () const
Additional Inherited Members
Protected Attributes inherited from helics::SubscriptionBase
ValueFederate * fed = nullptr
reference to the value federate
std::string key_
the name of the subscription
std::string type_
the requested type of the subscription
std::string units_
the defined units of the subscription
subscription_id_t id
the id of the federate
Detailed Description
template<class X>
class helics::SubscriptionT< X >
class to handle a subscription
Template Parameters
X the class of the value associated with a subscription
Constructor & Destructor Documentation
SubscriptionT() [1/2]
template<class X > template<class FedPtr > helics::SubscriptionT< X >::SubscriptionT (FedPtr valueFed, const std::string & name, const std::string & units = std::string ()) inline
constructor to build a subscription object
Parameters
[in] valueFed the ValueFederate to use
[in] name the name of the subscription
[in] units the units associated with a Federate
SubscriptionT() [2/2]
template<class X > template<class FedPtr > helics::SubscriptionT< X >::SubscriptionT (interface_availability required, FedPtr valueFed, const std::string & name, const std::string & units = "") inline
constructor to build a subscription object
Parameters
[in] required a flag indicating that the subscription is required to have a matching publication
[in] valueFed the ValueFederate to use
[in] name the name of the subscription
[in] units the units associated with a Federate
Member Function Documentation
getValue() [1/2]
template<class X > X helics::SubscriptionT< X >::getValue () const inline
get the most recent value
Returns
the value
References helics::SubscriptionBase::fed, helics::ValueFederate::getValue(), and helics::SubscriptionBase::id.
getValue() [2/2]
template<class X > void helics::SubscriptionT< X >::getValue (X & out) const inline
store the value in the given variable
Parameters
[out] out the location to store the value
References helics::SubscriptionBase::fed, and helics::ValueFederate::getValue().
registerCallback() [1/2]
template<class X > void helics::SubscriptionBase::registerCallback inline
register a callback for an update notification
the callback is called in the just before the time request function returns
Parameters
[in] callback a function with signature void(Time time) time is the time the value was updated This callback is a notification callback and doesn't return the value
registerCallback() [2/2]
template<class X > void helics::SubscriptionT< X >::registerCallback (std::function< void(X, Time)> callback) inline
register a callback for the update
the callback is called in the just before the time request function returns
Parameters
[in] callback a function with signature void(X val, Time time) val is the new value and time is the time the value was updated
References helics::SubscriptionBase::fed, and helics::ValueFederate::registerSubscriptionNotificationCallback().
setDefault()
template<class X > void helics::SubscriptionT< X >::setDefault (const X & val) inline
set a default value
Parameters
val the value to set as the default
References helics::SubscriptionBase::fed, and helics::ValueFederate::setDefaultValue().
setMinimumChange()
template<class X > void helics::SubscriptionT< X >::setMinimumChange (double deltaV) inline
set a minimum change value
The documentation for this class was generated from the following file:
Subscriptions.hpp