helics: JsonProcessingFunctions.hpp File Reference
JsonProcessingFunctions.hpp File Reference
#include "json/json.h"
#include "../core/helics-time.hpp"
Functions
Json_helics::Value loadJsonString (const std::string &jsonString)
helics::Time loadJsonTime (const Json_helics::Value &timeElement, timeUnits defaultUnits=timeUnits::sec)
std::string getKey (const Json_helics::Value &Element)
Detailed Description
functions related to loading and evaluating JSON files and helper functions for reading them using the jsoncpp library
Function Documentation
getKey()
std::string getKey (const Json_helics::Value & Element)
get a name or key from the element
Referenced by helics::MessageFederate::registerMessageInterfaces(), and helics::ValueFederate::registerValueInterfaces().
loadJsonString()
Json_helics::Value loadJsonString (const std::string & jsonString)
load a JSON string or filename that points to a JSON file and return a json::Value to the root object
Referenced by helics::loadFederateInfo(), helics::apps::App::loadJsonFileConfiguration(), helics::Federate::registerFilterInterfaces(), helics::MessageFederate::registerMessageInterfaces(), and helics::ValueFederate::registerValueInterfaces().
loadJsonTime()
helics::Time loadJsonTime (const Json_helics::Value & timeElement, timeUnits defaultUnits)
read a time from a JSON value element
References TimeRepresentation< Tconv >::minVal(), and helics::timeUnitsFromString().
Referenced by helics::loadFederateInfo().