helics: MessageFilters.h File Reference
MessageFilters.h File Reference
functions related the message filters for the C api
#include "helics.h"
Functions
HELICS_Export helics_filter helicsFederateRegisterSourceFilter (helics_federate fed, helics_filter_type_t type, const char *target, const char *name)
HELICS_Export helics_filter helicsFederateRegisterDestinationFilter (helics_federate fed, helics_filter_type_t type, const char *target, const char *name)
HELICS_Export helics_filter helicsFederateRegisterCloningFilter (helics_federate fed, const char *deliveryEndpoint)
HELICS_Export helics_filter helicsCoreRegisterSourceFilter (helics_core core, helics_filter_type_t type, const char *target, const char *name)
HELICS_Export helics_filter helicsCoreRegisterDestinationFilter (helics_core core, helics_filter_type_t type, const char *target, const char *name)
HELICS_Export helics_filter helicsCoreRegisterCloningFilter (helics_core core, const char *deliveryEndpoint)
HELICS_Export helics_status helicsFilterGetTarget (helics_filter filt, char *outputString, int maxlen)
HELICS_Export helics_status helicsFilterGetName (helics_filter filt, char *outputString, int maxlen)
HELICS_Export helics_status helicsFilterSet (helics_filter filt, const char *property, double val)
HELICS_Export helics_status helicsFilterSetString (helics_filter filt, const char *property, const char *val)
HELICS_Export helics_status helicsFilterAddDestinationTarget (helics_filter filt, const char *dest)
HELICS_Export helics_status helicsFilterAddSourceTarget (helics_filter filt, const char *source)
HELICS_Export helics_status helicsFilterAddDeliveryEndpoint (helics_filter filt, const char *deliveryEndpoint)
HELICS_Export helics_status helicsFilterRemoveDestinationTarget (helics_filter filt, const char *dest)
HELICS_Export helics_status helicsFilterRemoveSourceTarget (helics_filter filt, const char *source)
HELICS_Export helics_status helicsFilterRemoveDeliveryEndpoint (helics_filter filt, const char *deliveryEndpoint)
Detailed Description
functions related the message filters for the C api
Function Documentation
helicsCoreRegisterCloningFilter()
HELICS_Export helics_filter helicsCoreRegisterCloningFilter (helics_core core, const char * deliveryEndpoint)
create a cloning Filter on the specified core
cloning filters copy a message and send it to multiple locations source and destination can be added through other functions
Parameters
core the core to register through
deliveryEndpoint the specified endpoint to deliver the message
Returns
a helics_filter object
Referenced by helics::Core::registerCloningFilter().
helicsCoreRegisterDestinationFilter()
HELICS_Export helics_filter helicsCoreRegisterDestinationFilter (helics_core core, helics_filter_type_t type, const char * target, const char * name)
create a destination Filter on the specified core
filters can be created through a federate or a core , linking through a federate allows a few extra features of name matching to function on the federate interface but otherwise equivalent behavior
Parameters
core the core to register the filter through
type the type of filter to create
target the name of endpoint to target
name the name of the filter (can be NULL)
Returns
a helics_filter object
Referenced by helics::Core::registerDestinationFilter().
helicsCoreRegisterSourceFilter()
HELICS_Export helics_filter helicsCoreRegisterSourceFilter (helics_core core, helics_filter_type_t type, const char * target, const char * name)
create a source Filter on the specified core
filters can be created through a federate or a core , linking through a federate allows a few extra features of name matching to function on the federate interface but otherwise equivalent behavior
Parameters
core the core to register through
type the type of filter to create
target the name of endpoint to target
name the name of the filter (can be NULL)
Returns
a helics_filter object
helicsFederateRegisterCloningFilter()
HELICS_Export helics_filter helicsFederateRegisterCloningFilter (helics_federate fed, const char * deliveryEndpoint)
create a cloning Filter on the specified federate
cloning filters copy a message and send it to multiple locations source and destination can be added through other functions
Parameters
fed the fed to register through
deliveryEndpoint the specified endpoint to deliver the message
Returns
a helics_filter object
Referenced by helics::Federate::registerCloningFilter().
helicsFederateRegisterDestinationFilter()
HELICS_Export helics_filter helicsFederateRegisterDestinationFilter (helics_federate fed, helics_filter_type_t type, const char * target, const char * name)
create a destination Filter on the specified federate
filters can be created through a federate or a core , linking through a federate allows a few extra features of name matching to function on the federate interface but otherwise equivalent behavior
Parameters
fed the fed to register through
type the type of filter to create
target the name of endpoint to target
name the name of the filter (can be NULL)
Returns
a helics_filter object
Referenced by helics::Federate::registerDestinationFilter().
helicsFederateRegisterSourceFilter()
HELICS_Export helics_filter helicsFederateRegisterSourceFilter (helics_federate fed, helics_filter_type_t type, const char * target, const char * name)
create a source Filter on the specified federate
filters can be created through a federate or a core , linking through a federate allows a few extra features of name matching to function on the federate interface but otherwise equivalent behavior
Parameters
fed the fed to register through
type the type of filter to create
target the name of endpoint to target
name the name of the filter (can be NULL)
Returns
a helics_filter object
helicsFilterGetName()
HELICS_Export helics_status helicsFilterGetName (helics_filter filt, char * outputString, int maxlen)
get the name of the filter and store in the given string
Parameters
filt the given filter
[out] outputString storage for the name of the target
maxlen the maximum length of string that str can store
Returns
a helics_status enumeration helics_ok if everything worked
get the name of the filter
helicsFilterGetTarget()
HELICS_Export helics_status helicsFilterGetTarget (helics_filter filt, char * outputString, int maxlen)
get the target of the filter and store in the given string
Parameters
filt the given filter
[out] outputString storage for the name of the target
maxlen the maximum length of string that str can store
Returns
a helics_status enumeration helics_ok if everything worked
get the target of the filter
helicsFilterSet()
HELICS_Export helics_status helicsFilterSet (helics_filter filt, const char * property, double val)
set a property on a filter
Parameters
filt the filter to modify
property a string containing the property to set
val a numerical value of the property
helicsFilterSetString()
HELICS_Export helics_status helicsFilterSetString (helics_filter filt, const char * property, const char * val)
set a string property on a filter
Parameters
filt the filter to modify
property a string containing the property to set
val a string containing the new value