helics: MessageFederate.h File Reference
MessageFederate.h File Reference
functions related the message federates for the C api
#include "helics.h"
Functions
HELICS_Export helics_endpoint helicsFederateRegisterEndpoint (helics_federate fed, const char *name, const char *type)
HELICS_Export helics_endpoint helicsFederateRegisterGlobalEndpoint (helics_federate fed, const char *name, const char *type)
HELICS_Export helics_status helicsEndpointSetDefaultDestination (helics_endpoint endpoint, const char *dest)
HELICS_Export helics_status helicsEndpointSendMessageRaw (helics_endpoint endpoint, const char *dest, const void *data, int inputDataLength)
HELICS_Export helics_status helicsEndpointSendEventRaw (helics_endpoint endpoint, const char *dest, const void *data, int inputDataLength, helics_time_t time)
HELICS_Export helics_status helicsEndpointSendMessage (helics_endpoint endpoint, message_t *message)
HELICS_Export helics_status helicsEndpointSubscribe (helics_endpoint endpoint, const char *key, const char *type)
HELICS_Export helics_bool_t helicsFederateHasMessage (helics_federate fed)
HELICS_Export helics_bool_t helicsEndpointHasMessage (helics_endpoint endpoint)
HELICS_Export int helicsFederateReceiveCount (helics_federate fed)
HELICS_Export int helicsEndpointReceiveCount (helics_endpoint endpoint)
HELICS_Export message_t helicsEndpointGetMessage (helics_endpoint endpoint)
HELICS_Export message_t helicsFederateGetMessage (helics_federate fed)
HELICS_Export helics_status helicsEndpointGetType (helics_endpoint endpoint, char *outputString, int maxlen)
HELICS_Export helics_status helicsEndpointGetName (helics_endpoint endpoint, char *outputString, int maxlen)
HELICS_Export int helicsFederateGetEndpointCount (helics_federate fed)
Detailed Description
functions related the message federates for the C api
Function Documentation
helicsEndpointGetMessage()
HELICS_Export message_t helicsEndpointGetMessage (helics_endpoint endpoint)
receive a packet from a particular endpoint
Parameters
[in] endpoint the identifier for the endpoint
Returns
a message object
References message_t::data.
Referenced by Endpoint::getMessage().
helicsEndpointGetName()
HELICS_Export helics_status helicsEndpointGetName (helics_endpoint endpoint, char * outputString, int maxlen)
get the name of an endpoint
Parameters
endpoint the endpoint object in question
[out] outputString the location where the string is stored
[in] maxlen the maximum string length that can be stored in str
Returns
a status variable
References helics_invalid_argument, helics_invalid_object, and helics_ok.
helicsEndpointGetType()
HELICS_Export helics_status helicsEndpointGetType (helics_endpoint endpoint, char * outputString, int maxlen)
get the type specified for an endpoint
Parameters
endpoint the endpoint object in question
[out] outputString the location where the string is stored
[in] maxlen the maximum string length that can be stored in str
Returns
a status variable
References helics_invalid_argument, helics_invalid_object, and helics_ok.
helicsEndpointHasMessage()
HELICS_Export helics_bool_t helicsEndpointHasMessage (helics_endpoint endpoint)
check if a given endpoint has any unread messages
Parameters
endpoint the endpoint to check
Returns
helics_true if the endpoint has a message, false otherwise
helicsEndpointReceiveCount()
HELICS_Export int helicsEndpointReceiveCount (helics_endpoint endpoint)
Returns the number of pending receives for all endpoints of particular federate.
Parameters
endpoint the endpoint to query
Referenced by Endpoint::receiveCount().
helicsEndpointSendEventRaw()
HELICS_Export helics_status helicsEndpointSendEventRaw (helics_endpoint endpoint, const char * dest, const void * data, int inputDataLength, helics_time_t time)
send a message at a specific time to the specified destination
Parameters
endpoint the endpoint to send the data from
dest the target destination (nullptr to use the default destination
data the data to send
len the length of the data to send
time the time the message should be sent
Returns
helics_ok if everything worked
References helics_invalid_object, and helics_ok.
helicsEndpointSendMessage()
HELICS_Export helics_status helicsEndpointSendMessage (helics_endpoint endpoint, message_t * message)
send a message object from a specific endpoint
Parameters
endpoint the endpoint to send the data from
message the actual message to send
Returns
helics_ok if everything worked
References message_t::data, message_t::dest, helics_invalid_argument, helics_invalid_object, helics_ok, message_t::length, and message_t::time.
helicsEndpointSendMessageRaw()
HELICS_Export helics_status helicsEndpointSendMessageRaw (helics_endpoint endpoint, const char * dest, const void * data, int inputDataLength)
send a message to the specified destination
Parameters
endpoint the endpoint to send the data from
dest the target destination (nullptr to use the default destination
data the data to send
len the length of the data to send
Returns
helics_ok if everything worked
References helics_invalid_object, and helics_ok.
Referenced by Endpoint::sendMessage().
helicsEndpointSetDefaultDestination()
HELICS_Export helics_status helicsEndpointSetDefaultDestination (helics_endpoint endpoint, const char * dest)
set the default destination for an endpoint if no other endpoint is given
Parameters
endpoint the endpoint to set the destination for
dest a string naming the desired default endpoint
References helics_invalid_object, and helics_ok.
helicsEndpointSubscribe()
HELICS_Export helics_status helicsEndpointSubscribe (helics_endpoint endpoint, const char * key, const char * type)
subscribe an endpoint to a publication
Parameters
endpoint the endpoint to use
key the name of the publication
type the type of the publication that is expected (nullptr or "" for DON'T CARE)
References helics_error, and helics_ok.
helicsFederateGetEndpointCount()
HELICS_Export int helicsFederateGetEndpointCount (helics_federate fed)
get the number of endpoints in a federate
Returns
(-1) if fed was not a valid federate otherwise returns the number of subscriptions
helicsFederateGetMessage()
HELICS_Export message_t helicsFederateGetMessage (helics_federate fed)
receive a communication message for any endpoint in the federate
the return order will be in order of endpoint creation then order of arrival all messages for the first endpoint, then all for the second, and so on within a single endpoint the messages are ordered by time, then source_id, then order of arrival
Returns
a unique_ptr to a Message object containing the message data
References message_t::data.
Referenced by helics::MessageFederate::getMessage().
helicsFederateHasMessage()
HELICS_Export helics_bool_t helicsFederateHasMessage (helics_federate fed)
check if the federate has any outstanding messages
Parameters
fed the federate to check if it has
Returns
helics_true if the federate has a message waiting false otherwise
Referenced by helics::MessageFederate::hasMessage().
helicsFederateReceiveCount()
HELICS_Export int helicsFederateReceiveCount (helics_federate fed)
Returns the number of pending receives for the specified destination endpoint.
Parameters
fed the federate to get the number of waiting messages
Referenced by helics::MessageFederate::receiveCount().
helicsFederateRegisterEndpoint()
HELICS_Export helics_endpoint helicsFederateRegisterEndpoint (helics_federate fed, const char * name, const char * type)
create an endpoint
the endpoint becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for endpoints
Parameters
fed the federate object in which to create an endpoint must have been create with helicsCreateMessageFederate or helicsCreateCombinationFederate
name the identifier for the endpoint, this will be prepended with the federate name for the global identifier
type a string describing the expected type of the publication may be NULL
Returns
an object containing the endpoint, nullptr on failure
Referenced by helics::MessageFederate::registerEndpoint().
helicsFederateRegisterGlobalEndpoint()
HELICS_Export helics_endpoint helicsFederateRegisterGlobalEndpoint (helics_federate fed, const char * name, const char * type)
create an endpoint
the endpoint becomes part of the federate and is destroyed when the federate is freed so there are no separate free functions for endpoints
Parameters
fed the federate object in which to create an endpoint must have been create with helicsCreateMessageFederate or helicsCreateCombinationFederate
name the identifier for the endpoint, the given name is the global identifier
type a string describing the expected type of the publication may be NULL
Returns
an object containing the endpoint, nullptr on failure