helics: helics::CoreFactory Namespace Reference
helics::CoreFactory Namespace Reference
Functions
std::shared_ptr< Core > create (core_type type, const std::string &initializationString)
std::shared_ptr< Core > create (core_type type, const std::string &core_name, std::string &initializationString)
std::shared_ptr< Core > create (int argc, const char *const *argv)
std::shared_ptr< Core > create (core_type type, int argc, const char *const *argv)
std::shared_ptr< Core > create (core_type type, const std::string &core_name, int argc, const char *const *argv)
std::shared_ptr< Core > FindOrCreate (core_type type, const std::string &core_name, const std::string &initializationString)
std::shared_ptr< Core > FindOrCreate (core_type type, const std::string &core_name, int argc, const char *const *argv)
std::shared_ptr< Core > findCore (const std::string &name)
bool isJoinableCoreOfType (core_type type, const std::shared_ptr< CommonCore > &ptr)
std::shared_ptr< Core > findJoinableCoreOfType (core_type type)
bool registerCore (std::shared_ptr< Core > core)
size_t cleanUpCores ()
size_t cleanUpCores (int delay)
void copyCoreIdentifier (const std::string &copyFromName, const std::string &copyToName)
void unregisterCore (const std::string &name)
Detailed Description
Factory for building Core API instances.available core types
Function Documentation
cleanUpCores() [1/2]
size_t helics::CoreFactory::cleanUpCores ()
clean up unused cores
when Cores are unregistered they get put in a holding area that gets cleaned up when a new Core is registered or when the clean up function is called this prevents some odd threading issues
Returns
the number of cores still operating
Referenced by helics::cleanupHelicsLibrary(), helics::Federate::Federate(), helicsCloseLibrary(), helicsCoreFree(), helicsFederateFree(), and registerCore().
cleanUpCores() [2/2]
size_t helics::CoreFactory::cleanUpCores (int delay)
clean up unused cores
when Cores are unregistered they get put in a holding area that gets cleaned up when a new Core is registered or when the clean up function is called this prevents some odd threading issues
Parameters
delay the delay time in milliseconds to wait for the cores to finish before destroying
Returns
the number of cores still operating
copyCoreIdentifier()
void helics::CoreFactory::copyCoreIdentifier (const std::string & copyFromName, const std::string & copyToName)
make a copy of the broker pointer to allow access to the new name
create() [1/5]
std::shared_ptr< Core > helics::CoreFactory::create (core_type type, const std::string & initializationString)
Creates a Core API object of the specified type.
Invokes initialize() on the instantiated Core object.
References registerCore().
Referenced by create(), and helics::Federate::Federate().
create() [2/5]
std::shared_ptr< Core > helics::CoreFactory::create (core_type type, const std::string & core_name, std::string & initializationString)
create a core from a type, name, and initializationString
Parameters
type the type of core to create
core_name the name for the core
initializationString a string containing arguments for the core
References registerCore().
create() [3/5]
std::shared_ptr< Core > helics::CoreFactory::create (int argc, const char *const * argv)
create a core from arguments
an argument of '–coretype' must be specified to define the type, otherwise the default type is used
Parameters
argc the number of arguments
argv the actual argument parameters
Returns
a pointer to the created core
References helics::coreTypeFromString(), create(), and helics::DEFAULT.
create() [4/5]
std::shared_ptr< Core > helics::CoreFactory::create (core_type type, int argc, const char *const * argv)
create a core from a type and command line arguments
Parameters
type the type of core to create
argc the number of command line arguments
argv the actual string parameters for the command line
References registerCore().
create() [5/5]
std::shared_ptr< Core > helics::CoreFactory::create (core_type type, const std::string & core_name, int argc, const char *const * argv)
create a core from a type, name, and arguments
Parameters
type the type of core to create
core_name the name for the core
argc the number of arguments
argv the actual argument parameters
Returns
a pointer to the created core
References registerCore().
findCore()
std::shared_ptr< Core > helics::CoreFactory::findCore (const std::string & name)
locate a registered Core by name
Parameters
name the name of the core to find
Returns
a shared_ptr to the testCore
Referenced by helics::testcore::TestBroker::addRoute(), helics::testcore::TestCore::addRoute(), FindOrCreate(), and helics::CommonCore::unregister().
findJoinableCoreOfType()
std::shared_ptr< Core > helics::CoreFactory::findJoinableCoreOfType (core_type type)
try to find a joinable core of a specific type
Referenced by helics::Federate::Federate().
FindOrCreate() [1/2]
std::shared_ptr< Core > helics::CoreFactory::FindOrCreate (core_type type, const std::string & coreName, const std::string & initializationString)
tries to find a named core if it fails it creates a new one
References findCore(), and registerCore().
Referenced by helics::Federate::Federate(), helicsCreateCore(), and helicsCreateCoreFromArgs().
FindOrCreate() [2/2]
std::shared_ptr< Core > helics::CoreFactory::FindOrCreate (core_type type, const std::string & coreName, int argc, const char *const * argv)
tries to find a named core if it fails it creates a new one
References findCore(), and registerCore().
registerCore()
bool helics::CoreFactory::registerCore (std::shared_ptr< Core > core)
register a testCore so it can be found by others
also cleans up any leftover bCoresrokers that were previously unregistered this can be controlled by calling cleanUpBrokers earlier if desired
Parameters
core a pointer to a testCore object that should be found globally
Returns
true if the registration was successful false otherwise
References cleanUpCores().
Referenced by create(), and FindOrCreate().
unregisterCore()
void helics::CoreFactory::unregisterCore (const std::string & name)
remove a Core from the registry
Parameters
name the name of the Core to unregister
Referenced by helics::CommonCore::unregister().