helics: helics::BrokerFactory Namespace Reference
helics::BrokerFactory Namespace Reference
Functions
std::shared_ptr< Broker > create (core_type type, const std::string &initializationString)
std::shared_ptr< Broker > create (core_type type, const std::string &broker_name, const std::string &initializationString)
std::shared_ptr< Broker > create (core_type type, int argc, const char *const *argv)
std::shared_ptr< Broker > create (core_type type, const std::string &broker_name, int argc, const char *const *argv)
std::shared_ptr< Broker > findBroker (const std::string &brokerName)
bool registerBroker (std::shared_ptr< Broker > broker)
size_t cleanUpBrokers ()
size_t cleanUpBrokers (int delay)
void copyBrokerIdentifier (const std::string &copyFromName, const std::string &copyToName)
void unregisterBroker (const std::string &name)
void displayHelp (core_type type)
Detailed Description
Factory for building Core API instances.
Function Documentation
cleanUpBrokers() [1/2]
size_t helics::BrokerFactory::cleanUpBrokers ()
clean up unused brokers
when brokers are unregistered they get put in a holding area that gets cleaned up when a new broker is registered or when the clean up function is called this prevents some odd threading issues
Returns
the number of brokers still operating
Referenced by helics::testcore::TestBroker::brokerConnect(), helics::cleanupHelicsLibrary(), helicsBrokerFree(), helicsCloseLibrary(), and registerBroker().
cleanUpBrokers() [2/2]
size_t helics::BrokerFactory::cleanUpBrokers (int delay)
clean up unused brokers
when brokers are unregistered they get put in a holding area that gets cleaned up when a new broker is registered or when the clean up function is called this prevents some odd threading issues
Parameters
delay the number of milliseconds to wait to ensure stuff is cleaned up
Returns
the number of brokers still operating
copyBrokerIdentifier()
void helics::BrokerFactory::copyBrokerIdentifier (const std::string & copyFromName, const std::string & copyToName)
make a copy of the broker pointer to allow access to the new name
create()
std::shared_ptr< Broker > helics::BrokerFactory::create (core_type type, const std::string & initializationString)
Creates a Broker object of the specified type.
Invokes initialize() on the instantiated Core object.
References registerBroker().
Referenced by helics::testcore::TestBroker::brokerConnect(), helicsCreateBroker(), and helicsCreateBrokerFromArgs().
displayHelp()
void helics::BrokerFactory::displayHelp (core_type type = core_type::UNRECOGNIZED)
display the help listing for a particular core_type
References helics::CoreBroker::displayHelp(), helics::INTERPROCESS, helics::IPC, helics::MPI, helics::TCP, helics::TEST, helics::UDP, and helics::ZMQ.
findBroker()
std::shared_ptr< Broker > helics::BrokerFactory::findBroker (const std::string & brokerName)
locate a coreBroker by name
Parameters
name the name of the broker
Returns
a shared_ptr to the Broker
Referenced by helics::testcore::TestBroker::addRoute(), helics::testcore::TestCore::addRoute(), helics::testcore::TestBroker::brokerConnect(), helics::testcore::TestBroker::tryReconnect(), and helics::CoreBroker::unregister().
registerBroker()
bool helics::BrokerFactory::registerBroker (std::shared_ptr< Broker > broker)
register a coreBroker so it can be found by others
also cleans up any leftover brokers that were previously unregistered this can be controlled by calling cleanUpBrokers earlier if desired
Parameters
broker a pointer to a Broker object that should be able to be found globally
Returns
true if the registration was successful false otherwise
References cleanUpBrokers().
Referenced by create().
unregisterBroker()
void helics::BrokerFactory::unregisterBroker (const std::string & name)
remove a broker from the registry
Parameters
name the name of the broker to unregister
Referenced by helics::CoreBroker::unregister().