helics: helics Namespace Reference
helics Namespace Reference
Namespaces
action_message_def
BrokerFactory
CoreFactory
Classes
class ActionMessage
class ArgDescriptor
class AsyncFedCallInfo
class Barrier
class BasicBrokerInfo
class BasicFedInfo
class BasicHandleInfo
class Broker
class BrokerBase
class BrokerObject
class changeOnDestroy
class CloneFilterOperation
class CloneOperator
class CloningFilter
class CombinationFederate
class CommonCore
class CommsBroker
class CommsInterface
class conditionalChangeOnDestroy
class ConnectionFailure
class Core
class CoreBroker
class CoreFederateInfo
class CoreObject
class data_block
class data_view
class DelayFilterOperation
class DependencyInfo
class DestinationFilter
class Endpoint
class endpoint_info
class EndpointInfo
class EndpointObject
class Federate
class FederateInfo
class FederateState
class FedObject
class Filter
class FilterCoordinator
class FilterInfo
class FilterObject
class FilterOperations
class FilterOperator
class ForwardingTimeCoordinator
class FunctionExecutionFailure
class HandleManager
class HandlePointerManager
struct helics_iteration_time
class HelicsException
class HelicsTerminated
class identifier_id_t
class InvalidFunctionCall
class InvalidIdentifier
class InvalidParameter
class InvalidParameterValue
class InvalidStateTransition
struct is_iterable
struct is_iterable< T, typename std::enable_if_t< std::is_same< decltype(std::begin(T()) !=std::end(T()), void(), void(*std::begin(T())), std::true_type{}), std::true_type >::value > >
struct is_vector
struct is_vector< T, typename std::enable_if_t< std::is_same< T, std::vector< typename T::value_type, typename T::allocator_type > >::value > >
struct iteration_time
class Logger
class LoggerManager
class LoggerNoThread
class LoggingCore
class Message
class MessageConditionalOperator
class MessageDataOperator
class MessageDestOperator
class MessageFederate
class MessageFederateManager
class MessageTimeOperator
class NetworkBrokerData
class NullFilterOperator
class Publication
struct publication_info
class PublicationBase
class PublicationInfo
class PublicationObject
class PublicationOnChange
class PublicationT
class queryObject
class RandomDelayFilterOperation
class RandomDropFilterOperation
class RegistrationFailure
class RerouteFilterOperation
class SourceFilter
class Subscription
struct subscription_info
class SubscriptionBase
class SubscriptionInfo
class SubscriptionObject
class SubscriptionT
class TimeCoordinator
class TimeDependencies
class ValueConverter
class ValueConverter< std::string >
class ValueFederate
class ValueFederateManager
class VectorSubscription
class VectorSubscription2d
Typedefs
using defV = mpark::variant< double, int64_t, std::string, std::complex< double >, std::vector< double >, std::vector< std::complex< double > >, named_point >
using identifier_type = uint32_t
using publication_id_t = identifier_id_t< identifier_type, identifiers::publication, invalid_id_value >
using subscription_id_t = identifier_id_t< identifier_type, identifiers::subscription, invalid_id_value >
using endpoint_id_t = identifier_id_t< identifier_type, identifiers::endpoint, invalid_id_value >
using filter_id_t = identifier_id_t< identifier_type, identifiers::filter, invalid_id_value >
using query_id_t = identifier_id_t< identifier_type, identifiers::query, invalid_id_value >
using named_point = std::pair< std::string, double >
using ArgDescriptors = std::vector< ArgDescriptor >
using variable_map = boost::program_options::variables_map
using archiver = cereal::PortableBinaryOutputArchive
using retriever = cereal::PortableBinaryInputArchive
using actionPair = std::pair< action_message_def::action_t, const char * >
using errorPair = std::pair< int, const char * >
using activeProtector = libguarded::guarded< std::pair< bool, bool > >
using federate_id_t = Core::federate_id_t
using handle_id_t = Core::handle_id_t
using Time = TimeRepresentation< count_time< 9 > >
Enumerations
enum random_dists_t : int {
constant, uniform, bernoulli, binomial,
geometric, poisson, exponential, gamma,
weibull, extreme_value, normal, lognormal,
chi_squared, cauchy, fisher_f, student_t
}
enum defined_filter_types {
custom = 0, delay = 1, randomDelay = 2, randomDrop = 3,
reroute = 4, clone = 5, unrecognized = 6
}
enum type_location {
doubleLoc = 0, intLoc = 1, stringLoc = 2, complexLoc = 3,
vectorLoc = 4, complexVectorLoc = 5, namedPointLoc = 6
}
enum identifiers : char {
publication, subscription, filter, endpoint,
query
}
enum interface_visibility { local, global }
enum interface_availability { interface_availability::required, interface_availability::optional }
enum helics_type_t : int {
helicsString = 0, helicsDouble = 1, helicsInt = 2, helicsComplex = 3,
helicsVector = 4, helicsComplexVector = 5, helicsNamedPoint = 6, helicsBool = 7,
helicsInvalid = 23425, helicsAny = 247652
}
enum action_message_flags : uint16_t {
iteration_requested_flag = 0, processing_complete_flag = 1, required_flag = 2, error_flag = 4,
indicator_flag = 5, extra_flag1 = 7, forwarding_coordinator = 8, clone_flag = 9,
destination_processing_flag = 11, broker_min_time_flag = 12
}
enum handle_type_t : char {
unknown, handle_type_t::publication, handle_type_t::subscription, handle_type_t::endpoint,
handle_type_t::source_filter, handle_type_t::destination_filter, handle_type_t::cloning_filter
}
enum federate_state_t {
HELICS_CREATED, HELICS_INITIALIZING, HELICS_EXECUTING, HELICS_ERROR,
HELICS_FINISHED, HELICS_NONE
}
enum core_type : int {
core_type::DEFAULT = 0, core_type::ZMQ = 1, core_type::MPI = 2, core_type::TEST = 3,
core_type::INTERPROCESS = 4, core_type::IPC = 5, core_type::TCP = 6, core_type::UDP = 7,
core_type::UNRECOGNIZED = 8
}
enum iteration_state : signed char {
iteration_state::error = -5, iteration_state::continue_processing = -1, iteration_state::next_step = 0, iteration_state::iterating = 2,
iteration_state::halted = 3
}
enum iteration_result : signed char { iteration_result::error = -5, iteration_result::next_step = 0, iteration_result::iterating = 2, iteration_result::halted = 3 }
enum iteration_request : signed char { iteration_request::no_iterations = 0, iteration_request::force_iteration = 1, iteration_request::iterate_if_needed = 2 }
enum handle_check_mode : char { handle_check_mode::required = 0, handle_check_mode::optional = 1 }
enum message_process_result { message_process_result::no_effect = 0, message_process_result::processed, message_process_result::delay_processing }
enum PubSubTypes {
STRING_TYPE = HELICS_DATA_TYPE_STRING, DOUBLE_TYPE = HELICS_DATA_TYPE_DOUBLE, INT_TYPE = HELICS_DATA_TYPE_INT, COMPLEX_TYPE = HELICS_DATA_TYPE_COMPLEX,
VECTOR_TYPE = HELICS_DATA_TYPE_VECTOR, RAW_TYPE = HELICS_DATA_TYPE_RAW
}
enum vtype : int { genericFed, valueFed, messageFed, combinationFed }
enum ftype { source, dest, clone }
Functions
template<>
std::string typeNameString< std::vector< data_block > > ()
void cleanupHelicsLibrary ()
FederateInfo loadFederateInfo (const std::string &jsonString)
FederateInfo loadFederateInfo (const std::string &name, const std::string &jsonString)
double randDouble (random_dists_t dist, double p1, double p2)
std::string newDestGeneration (const std::string &src, const std::string &dest, const std::string &formula)
defined_filter_types filterTypeFromString (const std::string &filterType) noexcept
void addOperations (Filter *filt, defined_filter_types type, Core *cptr)
std::unique_ptr< DestinationFilter > make_destination_filter (defined_filter_types type, Federate *mFed, const std::string &target, const std::string &name)
std::unique_ptr< SourceFilter > make_source_filter (defined_filter_types type, Core *cr, const std::string &target, const std::string &name)
std::unique_ptr< DestinationFilter > make_destination_filter (defined_filter_types type, Core *cr, const std::string &target, const std::string &name)
std::unique_ptr< SourceFilter > make_source_filter (defined_filter_types type, Federate *fed, const std::string &target, const std::string &name)
bool changeDetected (const defV &prevValue, const std::string &val, double)
bool changeDetected (const defV &prevValue, bool val, double)
bool changeDetected (const defV &prevValue, const std::vector< double > &val, double deltaV)
bool changeDetected (const defV &prevValue, const std::vector< std::complex< double >> &val, double deltaV)
bool changeDetected (const defV &prevValue, const double *vals, size_t size, double deltaV)
bool changeDetected (const defV &prevValue, const std::complex< double > &val, double deltaV)
bool changeDetected (const defV &prevValue, double val, double deltaV)
bool changeDetected (const defV &prevValue, int64_t val, double deltaV)
bool changeDetected (const defV &prevValue, named_point val, double deltaV)
void valueExtract (const defV &dv, std::string &val)
void valueExtract (const defV &dv, std::complex< double > &val)
void valueExtract (const defV &dv, std::vector< double > &val)
void valueExtract (const defV &dv, std::vector< std::complex< double >> &val)
void valueExtract (const defV &dv, named_point &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::string &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::vector< double > &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::vector< std::complex< double >> &val)
void valueExtract (const data_view &dv, helics_type_t baseType, std::complex< double > &val)
void valueExtract (const data_view &dv, helics_type_t baseType, named_point &val)
template<class X >
std::enable_if_t< std::is_arithmetic< X >::value > valueExtract (const defV &dv, X &val)
template<class X >
std::enable_if_t< std::is_arithmetic< X >::value > valueExtract (const data_view &dv, helics_type_t baseType, X &val)
const std::string & typeNameStringRef (helics_type_t type)
std::string helicsComplexString (double real, double imag)
std::string helicsComplexString (std::complex< double > val)
helics_type_t getTypeFromString (const std::string &typeName)
const std::regex creg (R"(([+-]?(\(\+)?|\+)([eE][+-]?\)?)\([+-]\(\(\+)?|\+)([eE][+-]?\)?)[ji]*)")
std::complex< double > helicsGetComplex (const std::string &val)
std::string helicsVectorString (const std::vector< double > &val)
std::string helicsVectorString (const double *vals, size_t size)
std::string helicsComplexVectorString (const std::vector< std::complex< double >> &val)
std::string helicsNamedPointString (const named_point &point)
std::string helicsNamedPointString (const std::string &pointName, double val)
std::string helicsNamedPointString (const char *pointName, double val)
std::vector< double > helicsGetVector (const std::string &val)
std::vector< std::complex< double > > helicsGetComplexVector (const std::string &val)
named_point helicsGetNamedPoint (const std::string &val)
void helicsGetVector (const std::string &val, std::vector< double > &data)
void helicsGetComplexVector (const std::string &val, std::vector< std::complex< double >> &data)
data_block emptyBlock (helics_type_t outputType, helics_type_t inputType=helics_type_t::helicsAny)
data_block typeConvert (helics_type_t type, double val)
data_block typeConvert (helics_type_t type, int64_t val)
data_block typeConvert (helics_type_t type, const char *val)
data_block typeConvert (helics_type_t type, const std::string &val)
data_block typeConvert (helics_type_t type, const named_point &point)
data_block typeConvert (helics_type_t type, const std::vector< double > &val)
data_block typeConvert (helics_type_t type, const double *vals, size_t size)
data_block typeConvert (helics_type_t type, const std::vector< std::complex< double >> &val)
data_block typeConvert (helics_type_t type, const std::complex< double > &val)
data_block typeConvert (helics_type_t type, named_point &val)
data_block typeConvert (helics_type_t type, const char *str, double val)
data_block typeConvert (helics_type_t type, bool val)
data_block typeConvert (helics_type_t type, const std::string &str, double val)
template<class X >
std::string typeNameString ()
template<>
std::string typeNameString< std::vector< std::string > > ()
template<>
std::string typeNameString< std::vector< double > > ()
template<>
std::string typeNameString< std::vector< std::complex< double > > > ()
template<>
std::string typeNameString< double > ()
template<>
std::string typeNameString< float > ()
template<>
std::string typeNameString< bool > ()
template<>
std::string typeNameString< char > ()
template<>
std::string typeNameString< unsigned char > ()
template<>
std::string typeNameString< std::int32_t > ()
template<>
std::string typeNameString< std::uint32_t > ()
template<>
std::string typeNameString< int64_t > ()
template<>
std::string typeNameString< std::uint64_t > ()
template<>
std::string typeNameString< std::complex< float > > ()
template<>
std::string typeNameString< std::complex< double > > ()
template<>
std::string typeNameString< std::string > ()
template<>
std::string typeNameString< named_point > ()
template<class X >
constexpr helics_type_t helicsType ()
template<>
constexpr helics_type_t helicsType< int64_t > ()
template<>
constexpr helics_type_t helicsType< bool > ()
template<>
constexpr helics_type_t helicsType< std::string > ()
template<>
constexpr helics_type_t helicsType< named_point > ()
template<>
constexpr helics_type_t helicsType< double > ()
template<>
constexpr helics_type_t helicsType< std::complex< double > > ()
template<>
constexpr helics_type_t helicsType< std::vector< double > > ()
template<>
constexpr helics_type_t helicsType< std::vector< std::complex< double > > > ()
template<class X >
constexpr bool isConvertableType ()
template<>
constexpr bool isConvertableType< float > ()
template<>
constexpr bool isConvertableType< long double > ()
template<>
constexpr bool isConvertableType< int > ()
template<>
constexpr bool isConvertableType< short > ()
template<>
constexpr bool isConvertableType< unsigned short > ()
template<>
constexpr bool isConvertableType< unsigned int > ()
template<>
constexpr bool isConvertableType< char > ()
template<>
constexpr bool isConvertableType< uint64_t > ()
template<class X >
X invalidValue ()
template<>
constexpr double invalidValue< double > ()
template<>
constexpr uint64_t invalidValue< uint64_t > ()
template<>
constexpr std::complex< double > invalidValue< std::complex< double > > ()
data_block typeConvert (helics_type_t type, const defV &val)
template<class X , class FedPtr >
std::enable_if_t< helicsType< X >) !=helics_type_t::helicsInvalid, std::unique_ptr< Publication > > make_publication (FedPtr valueFed, const std::string &key, const std::string &units=std::string())
template<class X , class FedPtr >
std::enable_if_t< helicsType< X >) !=helics_type_t::helicsInvalid, std::unique_ptr< Publication > > make_publication (interface_visibility locality, FedPtr valueFed, const std::string &key, const std::string &units=std::string())
template<class Archive >
void save (Archive &ar, const data_block &db)
template<class Archive >
void load (Archive &ar, data_block &db)
template<class Archive >
void save (Archive &ar, const data_view &db)
template<class Archive >
void load (Archive &ar, data_view &db)
template<class X >
constexpr std::enable_if_t<!is_iterable< X >::value &&!std::is_convertible< X, std::string >::value, size_t > getMinSize ()
template<class X >
constexpr std::enable_if_t< is_iterable< X >::value &&!std::is_convertible< X, std::string >::value, size_t > getMinSize ()
template<class X >
constexpr std::enable_if_t< std::is_convertible< X, std::string >::value, size_t > getMinSize ()
template<class... Us>
void publish (std::shared_ptr< ValueFederate > &fed, const std::string &pubKey, Us... pargs)
template<class... Us>
void publish (ValueFederate &fed, const std::string &pubKey, Us... pargs)
template<class X >
X getValue (std::shared_ptr< ValueFederate > &fed, const std::string &Key)
template<class X >
void getValue (std::shared_ptr< ValueFederate > &fed, const std::string &Key, X &obj)
template<class X >
X getValue (ValueFederate &fed, const std::string &Key)
template<class X >
void getValue (ValueFederate &fed, const std::string &Key, X &obj)
int getTypeSize (const std::string &type)
bool isBlockSizeValid (int size, const publication_info &pubI)
int argumentParser (int argc, const char *const *argv, variable_map &vm_map, const ArgDescriptors &argDefinitions, const std::string &posName)
constexpr int helpReturn (-1)
constexpr int versionReturn (-2)
std::unique_ptr< Message > createMessageFromCommand (const ActionMessage &cmd)
std::unique_ptr< Message > createMessageFromCommand (ActionMessage &&cmd)
const char * actionMessageType (action_message_def::action_t action)
const char * commandErrorString (int errorcode)
std::string prettyPrintString (const ActionMessage &command)
std::ostream & operator<< (std::ostream &os, const ActionMessage &command)
template<class FlagContainer , class FlagIndex >
void setActionFlag (FlagContainer &M, FlagIndex flag)
template<class FlagContainer , class FlagIndex >
bool checkActionFlag (const FlagContainer &M, FlagIndex flag)
template<class FlagContainer , class FlagIndex >
void clearActionFlag (FlagContainer &M, FlagIndex flag)
bool isProtocolCommand (const ActionMessage &command) noexcept
bool isPriorityCommand (const ActionMessage &command) noexcept
bool isTimingCommand (const ActionMessage &command) noexcept
bool isDependencyCommand (const ActionMessage &command) noexcept
bool isDisconnectCommand (const ActionMessage &command) noexcept
bool isValidCommand (const ActionMessage &command) noexcept
bool hasInfo (action_message_def::action_t action)
std::shared_ptr< Broker > makeBroker (core_type type, const std::string &name)
bool matchingTypes (const std::string &type1, const std::string &type2)
bool operator!= (const data_block &db1, const data_block &db2)
template<class sizeType , class SizedDataType >
bool isValidIndex (sizeType testSize, const SizedDataType &vec)
std::string to_string (core_type type)
core_type coreTypeFromString (std::string type)
bool isCoreTypeAvailable (core_type type) noexcept
std::shared_ptr< Core > makeCore (core_type type, const std::string &name)
timeUnits timeUnitsFromString (const std::string &unitString)
helics::Time loadTimeFromString (const std::string &timeString)
helics::Time loadTimeFromString (const std::string &timeString, timeUnits defUnits)
constexpr Time operator"" _t (long double val)
std::string makePortAddress (const std::string &networkInterface, int portNumber)
std::pair< std::string, int > extractInterfaceandPort (const std::string &address)
std::pair< std::string, std::string > extractInterfaceandPortString (const std::string &address)
std::string getLocalExternalAddressV4 ()
std::string getLocalExternalAddressV4 (const std::string &)
std::string getHelicsVersionString ()
Variables
constexpr identifier_type invalid_id_value = static_cast<identifier_type> (-1)
defining an invalid id value
constexpr interface_visibility GLOBAL = interface_visibility::global
constexpr interface_visibility LOCAL = interface_visibility::local
constexpr interface_availability OPTIONAL = interface_availability::optional
constexpr interface_availability REQUIRED = interface_availability::required
const ActionMessage::AdditionalInfo emptyAddInfo
constexpr auto LEADING_CHAR = '\xF3'
constexpr auto TAIL_CHAR1 = '\xFA'
constexpr auto TAIL_CHAR2 = '\xFC'
constexpr std::pair< action_message_def::action_t, const char * > actionStrings []
constexpr size_t actEnd = sizeof (actionStrings) / sizeof (actionPair)
constexpr std::pair< int, const char * > errorStrings []
constexpr size_t errEnd = sizeof (errorStrings) / sizeof (errorPair)
constexpr int32_t cmd_info_basis = 65536
constexpr Core::federate_id_t invalid_fed_id = -2'000'000'000
constexpr Core::handle_id_t invalid_handle = -2'000'000'000
constexpr Core::handle_id_t direct_send_handle
this special handle can be used to directly send a message in a core
constexpr Core::federate_id_t global_federate_id_shift = 0x0001'0000
constexpr Core::federate_id_t global_broker_id_shift = 0x7000'0000
const std::vector< Core::handle_id_t > emptyHandles
constexpr Time startupTime = Time::minVal ()
constexpr Time initialTime {-1000000.0}
const std::map< std::string, timeUnits > timeUnitStrings
constexpr Time timeZero = Time::zeroVal ()
constexpr Time timeEpsilon = Time::epsilon ()
constexpr Time negEpsilon = -Time::epsilon ()
constexpr auto versionString = HELICS_VERSION_STRING
constexpr int versionMajor = HELICS_VERSION_MAJOR
constexpr int versionMinor = HELICS_VERSION_MINOR
constexpr int versionPatch = HELICS_VERSION_PATCH
auto recordComparison
Detailed Description
HELICS Application API
@ file different signal generators for the source app
HELICS Core API
HELICS C++98 Interface
Typedef Documentation
ArgDescriptors
using helics::ArgDescriptors = typedef std::vector<ArgDescriptor>
convenience alias
defV
using helics::defV = typedef mpark::variant<double, int64_t, std::string, std::complex<double>, std::vector<double>, std::vector<std::complex<double> >, named_point>
define a variant with the different types
Time
using helics::Time = typedef TimeRepresentation<count_time<9> >
Simulation virtual time.
Class represents time in the core.
Enumeration Type Documentation
action_message_flags
enum helics::action_message_flags : uint16_t
flag definitions for the action Message Flag field
Enumerator
iteration_requested_flag
indicator that an iteration has been requested
processing_complete_flag
indicator that processing has been completed
required_flag
flag indicating that an action or match is required
error_flag
flag indicating an error condition associated with the command
indicator_flag
flag used for setting values
extra_flag1
extra flag
forwarding_coordinator
flag indicating that a dependency is a forwarding coordinator
clone_flag
flag indicating the filter is a clone filter
destination_processing_flag
flag indicating the message is for destination processing
broker_min_time_flag
flag indicating that a broker the time constraint
core_type
enum helics::core_type : int strong
the type of the cores that are available
Enumerator
DEFAULT
pick a core type depending on compile configuration usually either ZMQ if available or UDP
ZMQ
use the Zero MQ networking protocol
MPI
use MPI for operation on a parallel cluster
TEST
use the Test core if all federates are in the same process
INTERPROCESS
interprocess uses memory mapped files to transfer data (for use when all federates are on the same machine
IPC
same as INTERPROCESS
TCP
use a generic TCP protocol message stream to send messages
UDP
use UDP packets to send the data
UNRECOGNIZED
unknown
defined_filter_types
enum helics::defined_filter_types strong
a set of common defined filters
federate_state_t
enum helics::federate_state_t
enumeration of the possible federate states
Enumerator
HELICS_INITIALIZING
the federation has entered initialization state and initial values can be published
state upon creation, all registration calls are allowed
HELICS_EXECUTING
the federation has entered execution state and it now advancing in time
HELICS_ERROR
the federation has encountered an error
HELICS_FINISHED
the federation has finished its execution
HELICS_NONE
unknown state
ftype
enum helics::ftype strong
enumeration of possible filter object types
handle_check_mode
enum helics::handle_check_mode : char strong
defining some check modes for dealing with required or optional components
Enumerator
required
indicator that the publication or endpoint is required to be there
optional
indicator that the publication or endpoint is optional
handle_type_t
enum helics::handle_type_t : char strong
define the type of the handle
Enumerator
publication
handle to publish interface
subscription
handle to a subscribe interface
endpoint
handle to an endpoint
source_filter
handle to a source filter
destination_filter
handle to a destination filter
cloning_filter
handle for a cloning filter
helics_type_t
enum helics::helics_type_t : int strong
the base types for helics
identifiers
enum helics::identifiers : char strong
the known types of identifiers
interface_availability
enum helics::interface_availability strong
enumeration of a whether a publication is required or is optional
Enumerator
required
the matching interface is required to exist
optional
the matching interface is NOT required
interface_visibility
enum helics::interface_visibility strong
enumeration of locality namespaces
iteration_request
enum helics::iteration_request : signed char strong
enumeration of the possible iteration requests by a federate
Enumerator
no_iterations
indicator that the iterations have completed
force_iteration
force an iteration whether it is needed or not
iterate_if_needed
indicator that the iterations need to continue
iteration_result
enum helics::iteration_result : signed char strong
enumeration of the possible states of iteration
Enumerator
error
indicator that an error has occurred
next_step
indicator that the iterations have completed and the federate has moved to the next step
iterating
indicator that the iterations need to continue
halted
indicator that the simulation has been halted
iteration_state
enum helics::iteration_state : signed char strong
enumeration of the possible states of convergence
Enumerator
error
indicator that an error has occurred
continue_processing
the current loop should continue
next_step
indicator that the iterations have completed
iterating
indicator that the iterations need to continue
halted
indicator that the simulation has been halted
message_process_result
enum helics::message_process_result strong
enumeration of possible processing results
Enumerator
no_effect
the message did not result in an update
processed
the message was used to update the current state
delay_processing
the message should be delayed and reprocessed later
random_dists_t
enum helics::random_dists_t : int strong
enumeration of possible random number generator distributions
type_location
enum helics::type_location
enumeration of the order inside the variant so the Which function returns match the enumeration
vtype
enum helics::vtype : int strong
type code embedded in the objects so the library knows how to cast them appropriately
Function Documentation
actionMessageType()
const char * helics::actionMessageType (action_message_def::action_t action)
return the name of the action
Parameters
action The action to get the name for
Returns
a pointer to string with the name
Referenced by prettyPrintString().
argumentParser()
int helics::argumentParser (int argc, const char *const * argv, variable_map & vm_map, const ArgDescriptors & argDefinitions, const std::string & posName = std::string())
using boost argument_parser to process a set of command line arguments
Parameters
[in] argc the number of arguments
[in] argv the actual strings in the argument
[out] vm_map the variable_map of all the arguments
[in] argDefinitions the definition targets used for the processing
[in] posName,(optional) the name of a positional argument
Returns
helpReturn(-1) if the help argument was called and displayed, versionReturn(-2) if version argument was used 0 otherwise
References helpReturn(), and versionReturn().
Referenced by helics::apps::App::App(), helics::testcore::TestBroker::displayHelp(), helics::NetworkBrokerData::displayHelp(), helics::BrokerBase::displayHelp(), helics::CoreBroker::displayHelp(), helics::apps::Echo::Echo(), helics::mpi::MpiBroker::initializeFromArgs(), helics::mpi::MpiCore::initializeFromArgs(), helics::ipc::IpcBroker::initializeFromArgs(), helics::ipc::IpcCore::initializeFromArgs(), helics::testcore::TestBroker::initializeFromArgs(), helics::testcore::TestCore::initializeFromArgs(), helics::NetworkBrokerData::initializeFromArgs(), helics::CoreBroker::initializeFromArgs(), helics::BrokerBase::initializeFromCmdArgs(), helics::FederateInfo::loadInfoFromArgs(), helics::apps::Player::Player(), helics::apps::Recorder::Recorder(), helics::apps::Source::Source(), and helics::apps::Tracer::Tracer().
changeDetected()
bool helics::changeDetected (const defV & prevValue, const std::string & val, double deltaV)
detect a change from the previous values
Referenced by helics::Publication::publish().
checkActionFlag()
template<class FlagContainer , class FlagIndex > bool helics::checkActionFlag (const FlagContainer & M, FlagIndex flag) inline
template function to check a flag in an object containing a flags field
Referenced by prettyPrintString(), helics::TimeCoordinator::processConfigUpdateMessage(), helics::CommonCore::processFilterInfo(), and helics::DependencyInfo::ProcessMessage().
cleanupHelicsLibrary()
void helics::cleanupHelicsLibrary ()
function to do some housekeeping work
this runs some cleanup routines and tries to close out any residual thread that haven't been shutdown yet
References helics::BrokerFactory::cleanUpBrokers(), and helics::CoreFactory::cleanUpCores().
Referenced by helicsCleanupHelicsLibrary().
clearActionFlag()
template<class FlagContainer , class FlagIndex > void helics::clearActionFlag (FlagContainer & M, FlagIndex flag) inline
template function to clear a flag in an object containing a flags field
commandErrorString()
const char * helics::commandErrorString (int errorcode)
return a string associated with a particular error code
Parameters
errorcode The error to get the string for
Returns
a pointer to string with the name
coreTypeFromString()
core_type helics::coreTypeFromString (std::string type)
generate a core type value from a std::string
Parameters
a string describing the desired core type
Returns
a value of the helics_core_type enumeration
Exceptions
invalid_argument if the string is not recognized
References DEFAULT, INTERPROCESS, MPI, TCP, TEST, UDP, UNRECOGNIZED, and ZMQ.
Referenced by helics::CoreFactory::create(), helicsCreateBroker(), helicsCreateBrokerFromArgs(), helicsCreateCore(), helicsCreateCoreFromArgs(), helicsFederateInfoSetCoreTypeFromString(), loadFederateInfo(), and helics::FederateInfo::loadInfoFromArgs().
createMessageFromCommand() [1/2]
std::unique_ptr< Message > helics::createMessageFromCommand (const ActionMessage & cmd)
create a new message object that copies all the information from the ActionMessage into newly allocated memory for the message
References helics::ActionMessage::actionTime, helics::ActionMessage::info(), helics::ActionMessage::AdditionalInfo::orig_source, helics::ActionMessage::AdditionalInfo::original_dest, helics::ActionMessage::payload, helics::ActionMessage::AdditionalInfo::source, and helics::ActionMessage::AdditionalInfo::target.
Referenced by helics::CommonCore::deliverMessage(), and helics::CommonCore::processMessage().
createMessageFromCommand() [2/2]
std::unique_ptr< Message > helics::createMessageFromCommand (ActionMessage && cmd)
create a new message object that moves all the information from the ActionMessage into newly allocated memory for the message
extractInterfaceandPort()
std::pair< std::string, int > helics::extractInterfaceandPort (const std::string & address)
extract a port number and interface string from an address number
, if there is no port number it default to -1 this is true if none was listed or the interface doesn't use port numbers
Parameters
[in] address a string with an network location description i.e 127.0.0.1:34
Returns
a pair with a string and int with the interface name and port number
References extractInterfaceandPort().
Referenced by extractInterfaceandPort(), and helics::NetworkBrokerData::initializeFromArgs().
extractInterfaceandPortString()
std::pair< std::string, std::string > helics::extractInterfaceandPortString (const std::string & address)
extract a port number string and interface string from an address number
, if there is no port number it default to empty string this is true if none was listed or the interface doesn't use port numbers
Parameters
[in] address a string with an network location description i.e 127.0.0.1:34
Returns
a pair with 2 strings with the interface name and port number
References extractInterfaceandPortString().
Referenced by extractInterfaceandPortString().
filterTypeFromString()
defined_filter_types helics::filterTypeFromString (const std::string & filterType) noexcept
get the filter type from a string
getHelicsVersionString()
std::string helics::getHelicsVersionString ()
get a string with the helics version info
References helicsGetVersion().
getLocalExternalAddressV4() [1/2]
std::string helics::getLocalExternalAddressV4 ()
get the external ipv4 address of the current computer
References getLocalExternalAddressV4().
Referenced by getLocalExternalAddressV4().
getLocalExternalAddressV4() [2/2]
std::string helics::getLocalExternalAddressV4 (const std::string & server)
get the external ipv4 Ethernet address of the current computer that best matches the listed server
References getLocalExternalAddressV4().
getTypeFromString()
helics_type_t helics::getTypeFromString (const std::string & typeName)
convert a string to a type
Referenced by helicsFederateRegisterGlobalPublication(), helicsFederateRegisterOptionalSubscription(), helicsFederateRegisterPublication(), and helicsFederateRegisterSubscription().
getValue() [1/4]
template<class X > X helics::getValue (std::shared_ptr< ValueFederate > & fed, const std::string & Key)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a shared pointer to a valueFederate
key the name of the publication
getValue() [2/4]
template<class X > void helics::getValue (std::shared_ptr< ValueFederate > & fed, const std::string & Key, X & obj)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a shared pointer to a valueFederate
key the name of the publication
obj the obj to store the retrieved value
getValue() [3/4]
template<class X > X helics::getValue (ValueFederate & fed, const std::string & Key)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a reference to a valueFederate
key the name of the publication
References helics::ValueFederate::getSubscriptionId(), and helics::ValueFederate::getValue().
getValue() [4/4]
template<class X > void helics::getValue (ValueFederate & fed, const std::string & Key, X & obj)
get a value directly from the subscription key name
this is a convenience function to get a value directly from the subscription key name this function should not be used as the primary means of retrieving value as it does involve an additional map find operation vs the member getValue calls
Parameters
fed a reference to a valueFederate
key the name of the publication
obj the obj to store the retrieved value
References helics::ValueFederate::getSubscriptionId(), and helics::ValueFederate::getValue().
hasInfo()
bool helics::hasInfo (action_message_def::action_t action) inline
check if the action has an info structure associated with it
References helics::action_message_def::null_info_command, and helics::action_message_def::priority_null_info_command.
Referenced by helics::ActionMessage::ActionMessage(), and helics::ActionMessage::setAction().
helicsGetComplex()
std::complex< double > helics::helicsGetComplex (const std::string & val)
convert a string to a complex number
Referenced by helics::apps::PhasorGenerator::setString().
helicsGetComplexVector()
std::vector< std::complex< double > > helics::helicsGetComplexVector (const std::string & val)
convert a string to a complex vector
helicsGetVector()
std::vector< double > helics::helicsGetVector (const std::string & val)
convert a string to a vector
helicsType()
template<class X > constexpr helics_type_t helics::helicsType ()
template class for generating a known name of a type
helpReturn()
constexpr int helics::helpReturn (- 1)
return value if the help argument is called
Referenced by helics::apps::App::App(), and argumentParser().
invalidValue()
template<class X > X helics::invalidValue ()
generate an invalid value for the various types
isBlockSizeValid()
bool helics::isBlockSizeValid (int size, const publication_info & pubI) inline
function to check if the size is valid for the given type
References isBlockSizeValid(), and helics::publication_info::size.
Referenced by isBlockSizeValid(), and helics::ValueFederateManager::publish().
isCoreTypeAvailable()
bool helics::isCoreTypeAvailable (core_type type) noexcept
Returns true if core/broker type specified is available in current compilation.
References DEFAULT, INTERPROCESS, IPC, MPI, TCP, TEST, UDP, and ZMQ.
isDisconnectCommand()
bool helics::isDisconnectCommand (const ActionMessage & command) inline noexcept
check if a command is a disconnect command
isPriorityCommand()
bool helics::isPriorityCommand (const ActionMessage & command) inline noexcept
check if a command is a priority command
References helics::action_message_def::cmd_ignore.
Referenced by helics::BrokerBase::addActionMessage(), and helics::CommsInterface::transmit().
isProtocolCommand()
bool helics::isProtocolCommand (const ActionMessage & command) inline noexcept
check if a command is a protocol command
isValidCommand()
bool helics::isValidCommand (const ActionMessage & command) inline noexcept
check if a command is a valid command
References helics::action_message_def::cmd_invalid.
isValidIndex()
template<class sizeType , class SizedDataType > bool helics::isValidIndex (sizeType testSize, const SizedDataType & vec) inline
helper template to check whether an index is actually valid for a particular vector
Template Parameters
SizedDataType a vector like data type that must have a size function
Parameters
testSize an index to test
vec a reference to a vector like object that has a size method
Returns
true if it is a valid index false otherwise
Referenced by helics::Federate::getFilterObject(), helics::HandleManager::getHandleInfo(), helics::apps::Recorder::getMessage(), and helics::apps::Recorder::getValue().
loadFederateInfo() [1/2]
FederateInfo helics::loadFederateInfo (const std::string & jsonString)
generate a FederateInfo object from a JSON file
loadFederateInfo() [2/2]
FederateInfo helics::loadFederateInfo (const std::string & name, const std::string & jsonString)
generate a FederateInfo object from a JSON file
References helics::FederateInfo::coreInitString, helics::FederateInfo::coreName, helics::FederateInfo::coreType, coreTypeFromString(), helics::FederateInfo::forwardCompute, helics::CoreFederateInfo::inputDelay, loadJsonString(), loadJsonTime(), helics::CoreFederateInfo::maxIterations, helics::FederateInfo::name, helics::CoreFederateInfo::observer, helics::CoreFederateInfo::offset, helics::CoreFederateInfo::only_transmit_on_change, helics::CoreFederateInfo::only_update_on_change, helics::CoreFederateInfo::outputDelay, helics::CoreFederateInfo::period, helics::FederateInfo::rollback, helics::FederateInfo::separator, helics::CoreFederateInfo::source_only, and helics::CoreFederateInfo::uninterruptible.
make_destination_filter() [1/2]
std::unique_ptr< DestinationFilter > helics::make_destination_filter (defined_filter_types type, Federate * fed, const std::string & target, const std::string & name = EMPTY_STRING)
create a destination filter
Parameters
type the type of filter to create
fed the federate to create the filter through
target the target endpoint all message with the specified target as a destination will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a destination Filter object, note destroying the object does not deactivate the filter
make_destination_filter() [2/2]
std::unique_ptr< DestinationFilter > helics::make_destination_filter (defined_filter_types type, Core * cr, const std::string & target, const std::string & name = EMPTY_STRING)
create a destination filter
Parameters
type the type of filter to create
cr the core to create the federate through
target the target endpoint all message with the specified target as a destination will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a destination Filter object, note destroying the object does not deactivate the filter
make_publication() [1/2]
template<class X , class FedPtr > std::enable_if_t<helicsType<X>) != helics_type_t::helicsInvalid, std::unique_ptr<Publication> > helics::make_publication (FedPtr valueFed, const std::string & key, const std::string & units = std::string ())
create a pointer to a publication
Template Parameters
X is the type of the publication
FedPtr a pointer a value Federate
Parameters
valueFed pointer to a valid federate
key the identifier for the publication
units optional units for the publication
make_publication() [2/2]
template<class X , class FedPtr > std::enable_if_t<helicsType<X>) != helics_type_t::helicsInvalid, std::unique_ptr<Publication> > helics::make_publication (interface_visibility locality, FedPtr valueFed, const std::string & key, const std::string & units = std::string ())
create a pointer to a publication
Template Parameters
X is the type of the publication
FedPtr a pointer a value Federate
Parameters
locality either LOCAL or GLOBAL defining whether the federate name is prepended or not
valueFed pointer to a valid federate
key the identifier for the publication
units optional units for the publication
make_source_filter() [1/2]
std::unique_ptr< SourceFilter > helics::make_source_filter (defined_filter_types type, Core * cr, const std::string & target, const std::string & name = EMPTY_STRING)
create a source filter
Parameters
type the type of filter to create
cr the core to create the filter through
target the target endpoint all message coming from the specified source will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a source Filter object, note destroying the object does not deactivate the filter
make_source_filter() [2/2]
std::unique_ptr< SourceFilter > helics::make_source_filter (defined_filter_types type, Federate * fed, const std::string & target, const std::string & name = EMPTY_STRING)
create a source filter
Parameters
type the type of filter to create
fed the federate to create the filter through
target the target endpoint all message coming from the specified source will route through the filter
name the name of the filter (optional)
Returns
a unique pointer to a source Filter object, note destroying the object does not deactivate the filter
makePortAddress()
std::string helics::makePortAddress (const std::string & networkInterface, int portNumber)
generate a string with a full address based on an interface string and port number
, how things get merged depend on what interface is used some use port number some do not
Parameters
[in] interface a string with an interface description i.e 127.0.0.1
portNumber the number of the port to use
Returns
a string with the merged address
References makePortAddress().
Referenced by helics::udp::UdpCore::getAddress(), helics::tcp::TcpCore::getAddress(), helics::udp::UdpBroker::getAddress(), helics::tcp::TcpBroker::getAddress(), helics::zeromq::ZmqBroker::getAddress(), helics::zeromq::ZmqCore::getAddress(), and makePortAddress().
operator<<()
std::ostream & helics::operator<< (std::ostream & os, const ActionMessage & command)
stream operator for a command
References prettyPrintString().
prettyPrintString()
std::string helics::prettyPrintString (const ActionMessage & command)
generate a human readable string with information about a command
Parameters
command the command to generate the string for
Returns
a string representing information about the command
References helics::ActionMessage::action(), actionMessageType(), helics::ActionMessage::actionTime, checkActionFlag(), helics::ActionMessage::dest_handle, helics::ActionMessage::dest_id, error_flag, helics::ActionMessage::info(), helics::ActionMessage::name, helics::ActionMessage::AdditionalInfo::orig_source, helics::ActionMessage::payload, helics::ActionMessage::source_handle, helics::ActionMessage::source_id, helics::ActionMessage::AdditionalInfo::target, helics::ActionMessage::Tdemin, and helics::ActionMessage::Te.
Referenced by operator<<().
publish() [1/2]
template<class... Us> void helics::publish (std::shared_ptr< ValueFederate > & fed, const std::string & pubKey, Us... pargs)
publish directly from the publication key name
this is a convenience function to publish directly from the publication key
Parameters
fed a shared_ptr to a value federate
pubKey the name of the publication
Template Parameters
pargs any combination of arguments that go into the other publish commands
publish() [2/2]
template<class... Us> void helics::publish (ValueFederate & fed, const std::string & pubKey, Us... pargs)
publish directly from the publication key name
this is a convenience function to publish directly from the publication key this function should not be used as the primary means of publications as it does involve an additional map find operation vs the member publish calls
Parameters
fed a reference to a valueFederate
pubKey the name of the publication
Template Parameters
pargs any combination of arguments that go into the other publish commands
References helics::ValueFederate::getPublicationId(), and helics::ValueFederate::publish().
setActionFlag()
template<class FlagContainer , class FlagIndex > void helics::setActionFlag (FlagContainer & M, FlagIndex flag) inline
template function to set a flag in an object containing a flags field
Referenced by helics::TimeCoordinator::checkExecEntry(), helics::FederateState::enterExecutingState(), helics::TimeCoordinator::enteringExecMode(), helics::CommonCore::processMessage(), and helics::CommonCore::setFlag().
timeUnitsFromString()
timeUnits helics::timeUnitsFromString (const std::string & unitString)
generate a time related unit,
Returns
a timeUnits enumeration value
Exceptions
Referenced by loadJsonTime().
to_string()
std::string helics::to_string (core_type type)
generate a string based on the core type
References INTERPROCESS, IPC, MPI, TCP, TEST, UDP, and ZMQ.
typeConvert()
data_block helics::typeConvert (helics_type_t type, double val)
convert a value to a data block to be interpreted using the specified type
Parameters
type the type used for the data conversion
val a double to convert
Referenced by helics::Publication::publish().
typeNameString()
template<class X > std::string helics::typeNameString () inline
template class for generating a known name of a type
typeNameString< bool >()
template<> std::string helics::typeNameString< bool > () inline
for boolean
typeNameString< char >()
template<> std::string helics::typeNameString< char > () inline
for character
typeNameString< double >()
template<> std::string helics::typeNameString< double > () inline
for float
typeNameString< float >()
template<> std::string helics::typeNameString< float > () inline
for float
typeNameString< int64_t >()
template<> std::string helics::typeNameString< int64_t > () inline
for 64 bit unsigned integer
typeNameString< std::complex< double > >()
template<> std::string helics::typeNameString< std::complex< double > > () inline
for complex double
typeNameString< std::complex< float > >()
template<> std::string helics::typeNameString< std::complex< float > > () inline
for complex double
typeNameString< std::int32_t >()
template<> std::string helics::typeNameString< std::int32_t > () inline
for integer
typeNameString< std::uint32_t >()
template<> std::string helics::typeNameString< std::uint32_t > () inline
for unsigned integer
typeNameString< std::uint64_t >()
template<> std::string helics::typeNameString< std::uint64_t > () inline
for 64 bit unsigned integer
typeNameString< unsigned char >()
template<> std::string helics::typeNameString< unsigned char > () inline
for unsigned character
typeNameStringRef()
const std::string & helics::typeNameStringRef (helics_type_t type)
sometime we just need a ref to a string for the basic types
valueExtract() [1/2]
template<class X > std::enable_if_t<std::is_arithmetic<X>::value> helics::valueExtract (const defV & dv, X & val)
for numeric types
valueExtract() [2/2]
template<class X > std::enable_if_t<std::is_arithmetic<X>::value> helics::valueExtract (const data_view & dv, helics_type_t baseType, X & val)
assume it is some numeric type (int or double)
versionReturn()
constexpr int helics::versionReturn (- 2)
return argument if a version argument was detected
Referenced by helics::apps::App::App(), argumentParser(), and helics::FederateInfo::loadInfoFromArgs().
Variable Documentation
direct_send_handle
constexpr Core::handle_id_t helics::direct_send_handle
Initial value:
=
  -1'745'234
this special handle can be used to directly send a message in a core
Referenced by helics::CommonCore::sendMessage().
errorStrings
constexpr std::pair<int, const char *> helics::errorStrings[]
Initial value:
= {
  {5, "already in initialization mode"},
  {6, "duplicate federate name detected"}}
global_broker_id_shift
constexpr Core::federate_id_t helics::global_broker_id_shift = 0x7000'0000
a shift in the global id index to discriminate between global ids of brokers vs federates
Referenced by helics::TimeDependencies::hasActiveTimeDependencies().
global_federate_id_shift
constexpr Core::federate_id_t helics::global_federate_id_shift = 0x0001'0000
a shift in the global federate id numbers to allow discrimination between local ids and global ones this value allows 65535 federates to be available in each core 1,878,982,656 allowable federates in the system and 268,435,455 brokers allowed if we need more than that this program has been phenomenally successful beyond all wildest imaginations and we can probably afford to change these to 64 bit numbers to accommodate
Referenced by helics::TimeDependencies::hasActiveTimeDependencies().
recordComparison
auto helics::recordComparison
Initial value:
= [](const SubscriptionInfo::dataRecord &rec1, const SubscriptionInfo::dataRecord &rec2) {
    return (rec1.time < rec2.time) ? true : ((rec1.time == rec2.time) ? (rec1.index < rec2.index) : false);
}
timeUnitStrings
const std::map<std::string, timeUnits> helics::timeUnitStrings
Initial value:
{
  {"ps", timeUnits::ps},
  {"ns", timeUnits::ns},
  {"us", timeUnits::us},
  {"ms", timeUnits::ms},
  {"s", timeUnits::s},
  {"sec", timeUnits::sec},
  {"", timeUnits::sec},
  {"seconds", timeUnits::sec},
  {"second", timeUnits::sec},
  {"min", timeUnits::minutes},
  {"minute", timeUnits::minutes},
  {"minutes", timeUnits::minutes},
  {"hr", timeUnits::hr},
  {"hour", timeUnits::hr},
  {"hours", timeUnits::hr},
  {"day", timeUnits::day},
  {"week", timeUnits::week},
  {"wk", timeUnits::week}}
versionMajor
constexpr int helics::versionMajor = HELICS_VERSION_MAJOR
get the Major version number
versionMinor
constexpr int helics::versionMinor = HELICS_VERSION_MINOR
get the Minor version number
versionPatch
constexpr int helics::versionPatch = HELICS_VERSION_PATCH
get the patch number
versionString
constexpr auto helics::versionString = HELICS_VERSION_STRING
Returns
a string containing version information
Referenced by helics::apps::App::App(), helicsGetVersion(), and helics::FederateInfo::loadInfoFromArgs().