helics: queryFunctions.hpp File Reference
queryFunctions.hpp File Reference
#include <string>
#include <vector>
Namespaces
helics
Functions
std::vector< std::string > vectorizeQueryResult (std::string &&queryres)
std::vector< std::string > vectorizeQueryResult (const std::string &queryres)
std::vector< std::string > vectorizeAndSortQueryResult (std::string &&queryres)
std::vector< std::string > vectorizeAndSortQueryResult (const std::string &queryres)
bool waitForInit (helics::Federate *fed, const std::string &fedName, int timeout=10000)
bool waitForFed (helics::Federate *fed, const std::string &fedName, int timeout=10000)
Detailed Description
functions for dealing with query results
Function Documentation
vectorizeAndSortQueryResult() [1/2]
std::vector<std::string> vectorizeAndSortQueryResult (std::string && queryres)
function takes a query result, vectorizes and sorts it if the query is a vector result, if not the results go into the first element of the vector
References vectorizeQueryResult().
vectorizeAndSortQueryResult() [2/2]
std::vector<std::string> vectorizeAndSortQueryResult (const std::string & queryres)
function takes a query result, vectorizes and sorts it if the query is a vector result, if not the results go into the first element of the vector
References vectorizeQueryResult().
vectorizeQueryResult() [1/2]
std::vector<std::string> vectorizeQueryResult (std::string && queryres)
function takes a query result and vectorizes it if the query is a vector result, if not the results go into the first element of the vector
Referenced by vectorizeAndSortQueryResult().
vectorizeQueryResult() [2/2]
std::vector<std::string> vectorizeQueryResult (const std::string & queryres)
function takes a query result and vectorizes it if the query is a vector result, if not the results go into the first element of the vector
waitForFed()
bool waitForFed (helics::Federate * fed, const std::string & fedName, int timeout = 10000)
helper function to wait for a particular federate to be created
this is useful if some reason we need to make sure a federate is created before proceeding
Parameters
[in] fed a pointer to the federate
[in] fedName the name of the federate we are querying
[in] timeout the amount of time in ms to wait before returning false
Returns
true if the federate exists, false if the timeout occurred
References helics::Federate::query().
waitForInit()
bool waitForInit (helics::Federate * fed, const std::string & fedName, int timeout = 10000)
helper function to wait for a particular federate has requested initialization mode
this is useful for querying information and being reasonably certain the federate is done adding to its interface
Parameters
[in] fed a pointer to the federate
[in] fedName the name of the federate we are querying
Returns
true if the federate is now trying to enter initialization false if the timeout was reached
References helics::Federate::query().